// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

cpp_quote("#define MIDISRV_LRPC_PROTOCOL  L\"ncalrpc\"")
cpp_quote("#define MIDISRV_ENDPOINT L\"MidiSrvClientRpc\"")

typedef [system_handle(sh_section)] HANDLE CP_MMAP_HANDLE;
typedef [system_handle(sh_event, 0x001F0003L)] HANDLE CP_EVENT_HANDLE;

// this is used for auto-cleanup of connections and other resources
typedef [context_handle] void * PMIDISRV_CONTEXT_HANDLE;

// temporary test RPC data, to be removed
typedef enum
{
    RequestEntry0 = 0,
    RequestEntry1,
    RequestEntry2,
} RequestEnum;

typedef struct REQUESTED_SETTINGS
{
    GUID Identifier;
    BOOL Flag;
    RequestEnum Request;
} REQUESTED_SETTINGS, *PREQUESTED_SETTINGS;

typedef struct ALLOCATED_SETTINGS
{
    GUID Identifier;
    BOOL Flag;
    RequestEnum Request;
} ALLOCATED_SETTINGS, *PALLOCATED_SETTINGS;
// end temporary test RPC data, to be removed

typedef ULONGLONG MidiClientHandle;

typedef struct MIDISRV_CLIENTCREATION_PARAMS
{
    MidiDataFormats DataFormat;
    MidiFlow     Flow;
    ULONG        BufferSize;
} MIDISRV_CLIENTCREATION_PARAMS, *PMIDISRV_CLIENTCREATION_PARAMS;

typedef struct MIDISRV_CLIENT
{
    CP_EVENT_HANDLE MidiInWriteEvent;
    CP_EVENT_HANDLE MidiInReadEvent;
    CP_EVENT_HANDLE MidiOutWriteEvent;
    CP_EVENT_HANDLE MidiOutReadEvent;

    CP_MMAP_HANDLE MidiInDataFileMapping;
    CP_MMAP_HANDLE MidiInRegisterFileMapping;

    CP_MMAP_HANDLE MidiOutDataFileMapping;
    CP_MMAP_HANDLE MidiOutRegisterFileMapping;

    ULONG MidiInBufferSize;
    ULONG MidiOutBufferSize;

    MidiClientHandle ClientHandle;
    MidiDataFormats DataFormat;
} MIDISRV_CLIENT, *PMIDISRV_CLIENT;

[
    uuid(64839251-9daf-4e79-aa4e-9771c86ffbc1),
    version(1.0),
    pointer_default(unique)
]
interface MidiSrvRPC
{
    HRESULT MidiSrvCreateClient(
        [in] handle_t bindingHandle, 
        [in, string] LPCWSTR midiDevice, 
        [in] PMIDISRV_CLIENTCREATION_PARAMS creationParams, 
        [in] GUID sessionId, 
        [out] PMIDISRV_CLIENT *client);

    HRESULT MidiSrvDestroyClient(
        [in] handle_t bindingHandle, 
        [in] MidiClientHandle clientHandle);


    // API-driven configuration

    HRESULT MidiSrvUpdateConfiguration(
        [in] handle_t bindingHandle, 
        [in, string] LPCWSTR configurationJson, 
        [out, string] LPWSTR* response);


    // Session Management and reporting

    HRESULT MidiSrvRegisterSession(
        [in] handle_t bindingHandle, 
        [in] GUID sessionId,
        [in, string] LPCWSTR sessionName,
        [in,out] PMIDISRV_CONTEXT_HANDLE *contextHandle
    );

    HRESULT MidiSrvUpdateSessionName(
        [in] handle_t bindingHandle,
        [in] PMIDISRV_CONTEXT_HANDLE contextHandle,
        [in] GUID sessionId,
        [in, string] LPCWSTR sessionName
    );

    HRESULT MidiSrvDeregisterSession(
        [in] handle_t bindingHandle, 
        [in] PMIDISRV_CONTEXT_HANDLE contextHandle,
        [in] GUID sessionId
    );


    HRESULT MidiSrvGetSessionList(
        [in] handle_t bindingHandle, 
        [out, string] LPWSTR* sessionListJson);


    // Abstractions and Transforms metadata reporting only

    HRESULT MidiSrvGetTransportList(
        [in] handle_t bindingHandle,
        [out, string] LPWSTR* transportListJson);

    HRESULT MidiSrvGetTransformList(
        [in] handle_t bindingHandle,
        [out, string] LPWSTR* transformListJson);

    // required for clients to be able to enumerate devices without creating a session
    BOOL MidiSrvVerifyConnectivity(
        [in] handle_t bindingHandle);

}
