// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "IMidiServiceTransportPluginConfig.idl";
import "MidiNetworkAuthenticationTypeEnum.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkHostCreationConfig", UUID_IMidiNetworkHostCreationConfig)]
    [constructor_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkHostCreationConfigFactory", UUID_IMidiNetworkHostCreationConfigFactory)]
    [static_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkHostCreationConfigStatics", UUID_IMidiNetworkHostCreationConfigStatics)]
    runtimeclass MidiNetworkHostCreationConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiNetworkHostCreationConfig();

        [noexcept] static MidiNetworkHostCreationConfig CreateDefault();

        [noexcept] static String EnsureCompliantServiceInstanceName(String serviceInstanceName);

        [noexcept] Guid HostId { get; };

        [noexcept] String Name;
        [noexcept] String ServiceInstanceName;
        [noexcept] String ProductInstanceId;

        [noexcept] Boolean CreateOnlyUmpEndpoints;

        [noexcept] Boolean UseAutomaticPortAllocation;
        [noexcept] String ManuallyAssignedPort;

        [noexcept] Boolean Advertise;

        [noexcept] MidiNetworkAuthenticationType AuthenticationType;

        // todo: password key etc.


    }
}
