// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


// TODO: Now that this is a runtimeclass, change the fields into fixed-size arrays


namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiDeclaredDeviceIdentity", UUID_IMidiDeclaredDeviceIdentity)]
    [constructor_name("Windows.Devices.Midi2.Enumeration.IMidiDeclaredDeviceIdentityFactory", UUID_IMidiDeclaredDeviceIdentityFactory)]
    runtimeclass MidiDeclaredDeviceIdentity
    {
        MidiDeclaredDeviceIdentity();
        MidiDeclaredDeviceIdentity(
            UInt8 sysexIdByte1, UInt8 sysexIdByte2, UInt8 sysexIdByte3,
            UInt8 deviceFamilyLsb, UInt8 deviceFamilyMsb,
            UInt8 deviceFamilyModelNumberLsb, UInt8 deviceFamilyModelNumberMsb,
            UInt8 softwareRevisionLevelByte1, UInt8 softwareRevisionLevelByte2, UInt8 softwareRevisionLevelByte3, UInt8 softwareRevisionLevelByte4);


        [noexcept] Boolean IsReadOnly { get; };

        [noexcept] UInt8[] SystemExclusiveId{ get; };
        [noexcept] void SetSystemExclusiveId(UInt8 byte1, UInt8 byte2, UInt8 byte3);

        [noexcept] UInt8 DeviceFamilyLsb{ get; };
        [noexcept] UInt8 DeviceFamilyMsb{ get; };
        [noexcept] void SetDeviceFamily(UInt8 deviceFamilyLsb, UInt8 deviceFamilyMsb);

        [noexcept] UInt8 DeviceFamilyModelNumberLsb{ get; };
        [noexcept] UInt8 DeviceFamilyModelNumberMsb{ get; };
        [noexcept] void SetDeviceFamilyModelNumber(UInt8 deviceFamilyModelNumberLsb, UInt8 deviceFamilyModelNumberMsb);

        [noexcept] UInt8[] SoftwareRevisionLevel{ get; };
        [noexcept] void SetSoftwareRevisionLevel(UInt8 byte1, UInt8 byte2, UInt8 byte3, UInt8 byte4);
    }
}
