// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiEndpointNativeDataFormatEnum.idl";

namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointTransportSuppliedInfo", UUID_IMidiEndpointTransportSuppliedInfo)]
    [constructor_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointTransportSuppliedInfoFactory", UUID_IMidiEndpointTransportSuppliedInfoFactory)]
    runtimeclass MidiEndpointTransportSuppliedInfo
    {
        MidiEndpointTransportSuppliedInfo();
        MidiEndpointTransportSuppliedInfo(
            String name,
            String description,
            String serialNumber,
            UInt16 vendorId,
            UInt16 productId,
            String manufacturerName,
            Boolean supportsMultiClient,
            MidiEndpointNativeDataFormat nativeDataFormat,
            Guid transportId,
            String transportCode,
            String driverDeviceInterfaceId
        );

        Boolean IsReadOnly { get; };

        String Name;
        String Description;

        String SerialNumber;

        UInt16 VendorId;
        UInt16 ProductId;

        String ManufacturerName;

        Boolean SupportsMultiClient;

        MidiEndpointNativeDataFormat NativeDataFormat;

        Guid TransportId;
        String TransportCode;

        String DriverDeviceInterfaceId;

    };
}