// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiMessageTypeEnum.idl";
import "IMidiEndpointMessageProcessingPlugin.idl";
import "IMidiMessageReceivedEventSource.idl";


namespace Windows.Devices.Midi2.ClientPlugins
{
    [contract(MidiClientPluginsApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.ClientPlugins.IMidiMessageTypeEndpointListener", UUID_IMidiMessageTypeEndpointListener)]
    [constructor_name("Windows.Devices.Midi2.ClientPlugins.IMidiMessageTypeEndpointListenerFactory", UUID_IMidiMessageTypeEndpointListenerFactory)]
    runtimeclass MidiMessageTypeEndpointListener : Windows.Devices.Midi2.IMidiEndpointMessageProcessingPlugin,
                                                   Windows.Devices.Midi2.IMidiMessageReceivedEventSource
    {
        MidiMessageTypeEndpointListener();

        IVector<Windows.Devices.Midi2.MidiMessageType> IncludedMessageTypes{ get; };

        Boolean PreventCallingFurtherListeners;
        Boolean PreventFiringMainMessageReceivedEvent;
    }
}