// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"


import "MidiApiContracts.idl";

import "MidiEndpointConnection.idl";
import "MidiEndpointConnectionSettings.idl";


namespace Windows.Devices.Midi2
{
    [contract(MidiCoreApiContract,1)]
    
    [interface_name("Windows.Devices.Midi2.IMidiSession", UUID_IMidiSession)]
    [static_name("Windows.Devices.Midi2.IMidiSessionStatics", UUID_IMidiSessionStatics)]
    runtimeclass MidiSession : Windows.Foundation.IClosable, Windows.Foundation.IStringable
    {
        [noexcept] Guid SessionId { get; };
        [noexcept] String Name{ get; };

        [noexcept] static MidiSession Create(String sessionName);

        [noexcept] Boolean IsOpen { get; };

        [noexcept] IMapView<Guid, MidiEndpointConnection> Connections{ get; };

        [noexcept] MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId
        );

        [noexcept] MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId,
            MidiEndpointConnectionSettings settings
        );

        [noexcept] void DisconnectEndpointConnection(Guid endpointConnectionId);

        [noexcept] Boolean UpdateName(String newName);
    }
}
