// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "IMidiServiceTransportPluginConfig.idl";
import "MidiServiceConfigResponse.idl";
import "MidiServiceTransportCommand.idl";

namespace Windows.Devices.Midi2.ServiceConfig
{
    [contract(MidiServiceConfigApiContract, 1)]
    [static_name("Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfigManagerStatics", UUID_IMidiServiceTransportPluginConfigManagerStatics)]
    static runtimeclass MidiServiceTransportPluginConfigManager
    {
        static MidiServiceConfigResponse SendUpdate(
            IMidiServiceTransportPluginConfig configUpdate);

        static MidiServiceConfigResponse SendUpdate(
            Guid transportId,
            Windows.Data.Json.JsonObject fullConfigObject);

        static MidiServiceConfigResponse SendCommand(
            MidiServiceTransportCommand command);
    }
}

