// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "MidiServiceSessionConnectionInfo.idl";

namespace Windows.Devices.Midi2.Reporting
{
    [contract(MidiReportingApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Reporting.IMidiServiceSessionInfo", UUID_IMidiServiceSessionInfo)]
    runtimeclass MidiServiceSessionInfo
    {
        [noexcept] Guid SessionId{ get; };

        [noexcept] UInt64 ProcessId{ get; };
        [noexcept] String ProcessName{ get; };
        [noexcept] String SessionName{ get; };

        [noexcept] Windows.Foundation.DateTime StartTime{ get; };


        [noexcept] IVectorView<MidiServiceSessionConnectionInfo> Connections{ get; };
    }
}
