// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


namespace Windows.Devices.Midi2.Utilities.SysExTransfer
{
    [contract(MidiSysExTransferUtilityApiContract,1)]
    [interface_name("Windows.Devices.Midi2.Utilities.SysExTransfer.IMidiSystemExclusiveSendProgress", UUID_IMidiSystemExclusiveSendProgress)]
    runtimeclass MidiSystemExclusiveSendProgress
    {
        UInt64 CountBytesRead{ get; };
        UInt64 CountMessagesSent{ get; };

   //     Boolean HasError{ get; };
   //     String LastErrorMessage{ get; };
    };
}
