// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "MidiNetworkAdvertisedHostAddedEventArgs.idl";
import "MidiNetworkAdvertisedHostRemovedEventArgs.idl";
import "MidiNetworkAdvertisedHostUpdatedEventArgs.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkAdvertisedHostWatcher", UUID_IMidiNetworkAdvertisedHostWatcher)]
    [static_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkAdvertisedHostWatcherStatics", UUID_IMidiNetworkAdvertisedHostWatcherStatics)]
    runtimeclass MidiNetworkAdvertisedHostWatcher
    {
        [noexcept] static MidiNetworkAdvertisedHostWatcher Create();

        [noexcept] void Start();
        [noexcept] void Stop();

        [noexcept] Windows.Foundation.Collections.IMapView<String, MidiNetworkAdvertisedHost> EnumeratedHosts{ get; };

        [noexcept] Windows.Devices.Enumeration.DeviceWatcherStatus Status{ get; };

        event Windows.Foundation.TypedEventHandler<MidiNetworkAdvertisedHostWatcher, MidiNetworkAdvertisedHostAddedEventArgs> Added;
        event Windows.Foundation.TypedEventHandler<MidiNetworkAdvertisedHostWatcher, MidiNetworkAdvertisedHostRemovedEventArgs> Removed;
        event Windows.Foundation.TypedEventHandler<MidiNetworkAdvertisedHostWatcher, MidiNetworkAdvertisedHostUpdatedEventArgs> Updated;

        event Windows.Foundation.TypedEventHandler<MidiNetworkAdvertisedHostWatcher, IInspectable> EnumerationCompleted;
        event Windows.Foundation.TypedEventHandler<MidiNetworkAdvertisedHostWatcher, IInspectable> Stopped;
    }
}

