// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "Midi1PortFlowEnum.idl";
import "MidiEndpointNativeDataFormatEnum.idl";
import "MidiParentDeviceInformation.idl";


namespace Windows.Devices.Midi2.Enumeration.Legacy
{
    [contract(MidiEnumerationLegacyApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.Legacy.IMidiLegacyPortDeviceInformation", UUID_IMidiLegacyPortDeviceInformation )]
    runtimeclass MidiLegacyPortDeviceInformation : Windows.Foundation.IStringable
    {
        [noexcept] static MidiLegacyPortDeviceInformation CreateFromPortDeviceId(String portDeviceId);

        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAll();
        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAll(Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);
        //static IVectorView<MidiLegacyPortDeviceInformation> FindAllForParentDevice(String parentDeviceInstanceId);
        //static IVectorView<MidiLegacyPortDeviceInformation> FindAllForParentDevice(String parentDeviceInstanceId, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);
        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAllForAssociatedEndpoint(String endpointDeviceId);
        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAllForAssociatedEndpoint(String endpointDeviceId, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);
        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAllForName(String portName);
        [noexcept] static IVectorView<MidiLegacyPortDeviceInformation> FindAllForContainer(Guid containerId);


        [noexcept] static IVectorView<String> GetAdditionalPropertiesList();

        [noexcept] static Guid Midi1SourcePortInterfaceClass { get; };
        [noexcept] static Guid Midi1DestinationPortInterfaceClass { get; };

        [noexcept] String PortDeviceId{ get; };                    // device id in our tree (also used directly in WinRT MIDI 1.0)
        [noexcept] String PortDeviceInstanceId{ get; };            // device instance id 
        [noexcept] String Name{ get; };                            // friendly name (this is the current WinMM port name). Get other names from the parent 

        [noexcept] Guid ContainerId{ get; };                       // container this exists in. It will be the same as the parent endpoint's. Here for convenience.
        [noexcept] String AssociatedEndpointDeviceId{ get; };      // device id of the owning Windows MIDI Services endpoint

        [noexcept] String ParentDeviceInstanceId{ get; };          // device instance id of the (resolved) parent device
        [noexcept] Windows.Devices.Midi2.Enumeration.MidiParentDeviceInformation GetParentDeviceInformation();

        [noexcept] String DriverDeviceInterfaceId{ get; };         // the device interface id that the WinMM API exposes via DRV_QUERYDEVICEINTERFACE
        [noexcept] Windows.Devices.Midi2.MidiGroup Group{ get; };  // the single group this MIDI 1.0 port is associated with

        [noexcept] Windows.Devices.Midi2.Enumeration.Midi1PortFlow Flow{ get; };                 // source (midi input) or destination (midi output)

        [noexcept] UInt32 Number{ get; };                          // current winmm port number (0..n). This can change if devices are added/removed.

        [noexcept] Windows.Devices.Midi2.Enumeration.MidiEndpointNativeDataFormat NativeDataFormat{ get; };   // the native data format of the port, which is needed to know in order to use the port with WinMM APIs. This is the same as the parent endpoint's native data format. Here for convenience.

        [noexcept] Windows.Foundation.Collections.IMapView<String, IInspectable> Properties{ get; };
    }
}
