// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "IMidiServiceTransportPluginConfig.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkRemoteClientApprovalConfig")]
    [constructor_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkRemoteClientApprovalConfigFactory")]
    runtimeclass MidiNetworkRemoteClientApprovalConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiNetworkRemoteClientApprovalConfig();

        MidiNetworkRemoteClientApprovalConfig(
            Guid hostId, 
            String remoteClientName,
            String remoteClientProductInstanceId,
            Boolean approve, 
            Boolean restrictScopeToThisRequestOnly);


        Guid HostId{ get; set; };

        String RemoteClientName{ get; set; };
        String RemoteClientProductInstanceId{ get; set; };
        Boolean Approve{ get; set; };
        Boolean ScopeIsThisRequestOnly{ get; set; };

    }
}
