// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiFunctionBlockDirectionEnum.idl";
import "MidiFunctionBlockUIHintEnum.idl";
import "MidiFunctionBlockRepresentsMidi10ConnectionEnum.idl";
import "MidiGroup.idl";


namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiFunctionBlock", UUID_IMidiFunctionBlock)]
    [static_name("Windows.Devices.Midi2.Enumeration.IMidiFunctionBlockStatics", UUID_IMidiFunctionBlockStatics)]
    [constructor_name("Windows.Devices.Midi2.Enumeration.IMidiFunctionBlockFactory", UUID_IMidiFunctionBlockFactory)]
    runtimeclass MidiFunctionBlock : Windows.Foundation.IStringable
    {
        MidiFunctionBlock();

        [noexcept] static String ShortLabel{ get; };
        [noexcept] static String ShortLabelPlural{ get; };
        [noexcept] static String LongLabel{ get; };
        [noexcept] static String LongLabelPlural{ get; };

        [noexcept] Boolean IsReadOnly { get; };

        [noexcept] UInt8 Number;
        [noexcept] String Name;


        [noexcept] Boolean IsActive;

        [noexcept] MidiFunctionBlockDirection Direction;
        [noexcept] MidiFunctionBlockUIHint UIHint;

        [noexcept] MidiFunctionBlockRepresentsMidi10Connection RepresentsMidi10Connection;

        [noexcept] Windows.Devices.Midi2.MidiGroup FirstGroup;
        //UInt8 FirstGroupIndex;
        [noexcept] UInt8 GroupCount;

        [noexcept] Boolean IncludesGroup(Windows.Devices.Midi2.MidiGroup group);

        [noexcept] UInt8 MidiCIMessageVersionFormat;

        [noexcept] UInt8 MaxSystemExclusive8Streams;
    }
}
