// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiLoopbackCreationResponse.idl";
import "MidiLoopbackRemovalResponse.idl";
import "MidiLoopbackUpdateResponse.idl";

import "MidiLoopbackCreationConfig.idl";
import "MidiLoopbackRemovalConfig.idl";

import "MidiEndpointDeviceInformation.idl";

namespace Windows.Devices.Midi2.Transports.Loopback
{
    [contract(MidiTransportsLoopbackApiContract, 1)]
    
    [static_name("Windows.Devices.Midi2.Transports.Loopback.IMidiLoopbackManagerStatics", UUID_IMidiLoopbackManagerStatics)]
    static runtimeclass MidiLoopbackManager
    {
        [noexcept] static Boolean IsTransportAvailable{ get; };

        [noexcept] static Guid TransportId{ get; };

        [noexcept] static MidiLoopbackCreationResponse CreateTransientLoopback(
            MidiLoopbackCreationConfig creationConfig);

        [noexcept] static MidiLoopbackRemovalResponse RemoveTransientLoopback(
            MidiLoopbackRemovalConfig removalConfig);

        [noexcept] static Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpointForId(
            String loopbackEndpointId);

        [noexcept] static Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpoint(
            Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation loopbackEndpoint,
            IIterable<Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation> endpointsToSearch);

        [noexcept] static Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpoint(
            Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation loopbackEndpoint);

        [noexcept] static Boolean DoesLoopbackAExist(String uniqueIdentifier);
        [noexcept] static Boolean DoesLoopbackBExist(String uniqueIdentifier);

        [noexcept] static Guid GetAssociationId(Windows.Devices.Midi2.Enumeration.MidiEndpointDeviceInformation loopbackEndpoint);

        [noexcept] static MidiLoopbackUpdateResponse MuteLoopback(Guid associationId);
        [noexcept] static MidiLoopbackUpdateResponse UnmuteLoopback(Guid associationId);


        [noexcept] static IVectorView<MidiLoopbackEntry> GetActiveLoopbackEntries();

    }
}

