// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


namespace Windows.Devices.Midi2.Reporting
{
    [contract(MidiReportingApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Reporting.IMidiServiceTransportPluginInfo", UUID_IMidiServiceTransportPluginInfo)]
    runtimeclass MidiServiceTransportPluginInfo
    {
        [noexcept] Guid TransportId{ get; };

        [noexcept] String Name{ get; };
        [noexcept] String TransportCode{ get; };
        [noexcept] String Description{ get; };

        [noexcept] String ImageFileName{ get; };

        [noexcept] String Author{ get; };

        [noexcept] String Version{ get; };

        [noexcept] Boolean IsRuntimeCreatableByApps{ get; };
        [noexcept] Boolean IsRuntimeCreatableBySettings{ get; };

        [noexcept] Boolean IsSystemManaged{ get; };
        [noexcept] Boolean CanConfigure{ get; };

    };
}
