// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiLegacyPortDeviceInformation.idl";

import "MidiLegacyPortDeviceInformationAddedEventArgs.idl";
import "MidiLegacyPortDeviceInformationUpdatedEventArgs.idl";
import "MidiLegacyPortDeviceInformationRemovedEventArgs.idl";

import "MidiGroup.idl";

import "Midi1PortFlowEnum.idl";

namespace Windows.Devices.Midi2.Enumeration.Legacy
{
    [contract(MidiEnumerationLegacyApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.Legacy.IMidiLegacyPortDeviceWatcher", UUID_IMidiLegacyPortDeviceWatcher)]
    [static_name("Windows.Devices.Midi2.Enumeration.Legacy.IMidiLegacyPortDeviceWatcherStatics", UUID_IMidiLegacyPortDeviceWatcherStatics)]
    runtimeclass MidiLegacyPortDeviceWatcher
    {
        [noexcept] static MidiLegacyPortDeviceWatcher Create();
        [noexcept] static MidiLegacyPortDeviceWatcher CreateForFlow(Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] void Start();
        [noexcept] void Stop();

        // Cached list of ports
        [noexcept] Windows.Foundation.Collections.IMapView<String, MidiLegacyPortDeviceInformation> EnumeratedPorts{ get; };

        [noexcept] Windows.Devices.Enumeration.DeviceWatcherStatus Status{ get; };

        event Windows.Foundation.TypedEventHandler<MidiLegacyPortDeviceWatcher, MidiLegacyPortDeviceInformationAddedEventArgs> Added;
        event Windows.Foundation.TypedEventHandler<MidiLegacyPortDeviceWatcher, MidiLegacyPortDeviceInformationUpdatedEventArgs> Updated;
        event Windows.Foundation.TypedEventHandler<MidiLegacyPortDeviceWatcher, MidiLegacyPortDeviceInformationRemovedEventArgs> Removed;

        event Windows.Foundation.TypedEventHandler<MidiLegacyPortDeviceWatcher, IInspectable> EnumerationCompleted;
        event Windows.Foundation.TypedEventHandler<MidiLegacyPortDeviceWatcher, IInspectable> Stopped;

        // these all operate on the collection of enumerated ports and are a snapshot in time.They do not re-query

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForFlow(Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] MidiLegacyPortDeviceInformation GetEnumeratedPortForNumber(UInt32 portNumber, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForParent(String parentDeviceInstanceId);
        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForParent(String parentDeviceInstanceId, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForAssociatedEndpoint(String endpointDeviceId);
        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForAssociatedEndpoint(String endpointDeviceId, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForAssociatedEndpointAndGroup(String endpointDeviceId, Windows.Devices.Midi2.MidiGroup group);
        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForAssociatedEndpointAndGroup(String endpointDeviceId, Windows.Devices.Midi2.MidiGroup group, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForName(String portName);
        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForName(String portName, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForDriverDeviceInterfaceId(String driverDeviceInterfaceId);
        [noexcept] IVectorView<MidiLegacyPortDeviceInformation> GetEnumeratedPortsForDriverDeviceInterfaceId(String driverDeviceInterfaceId, Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);

        [noexcept] UInt32 CountSourcePorts { get;};
        [noexcept] UInt32 CountDestinationPorts { get;};

    }
}
