// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkAdvertisedHost", UUID_IMidiNetworkAdvertisedHost)]
    runtimeclass MidiNetworkAdvertisedHost
    {
        // from Windows props
        [noexcept] String DeviceId { get; };
        [noexcept] String DeviceName{ get; };

        // from SRV record
        [noexcept] String FullName{ get; };
        [noexcept] String ServiceInstanceName{ get; };
        [noexcept] String ServiceType{ get; };
        [noexcept] String HostName{ get; };
        [noexcept] UInt16 Port{ get; };
        [noexcept] String Domain{ get; };

        // from TXT record
        [noexcept] String UmpEndpointName{ get; };
        [noexcept] String ProductInstanceId{ get; };

        [noexcept] IVectorView<String> IPAddresses{ get; };
    };
}

