// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";


namespace Windows.Devices.Midi2
{
    [contract(MidiCoreApiContract,1)]
    
    [interface_name("Windows.Devices.Midi2.IMidiEndpointConnectionSettings", UUID_IMidiEndpointConnectionSettings)]
    [constructor_name("Windows.Devices.Midi2.IMidiEndpointConnectionSettingsFactory", UUID_IMidiEndpointConnectionSettingsFactory)]
    runtimeclass MidiEndpointConnectionSettings
    {
        MidiEndpointConnectionSettings();
        MidiEndpointConnectionSettings(Boolean waitForEndpointReceiptOnSend);
        MidiEndpointConnectionSettings(Boolean waitForEndpointReceiptOnSend, Boolean autoReconnect);

        [noexcept] Boolean WaitForEndpointReceiptOnSend{ get; };
        [noexcept] Boolean AutoReconnect{ get; };

    }
}
