// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "MidiNetworkHostCreationResponse.idl";
import "MidiNetworkHostCreationConfig.idl";
import "MidiNetworkHostRemovalResponse.idl";
import "MidiNetworkHostRemovalConfig.idl";
import "MidiNetworkHostUpdateResponse.idl";


import "MidiNetworkClientConnectResponse.idl";
import "MidiNetworkClientConnectConfig.idl";

import "MidiNetworkClientDisconnectResponse.idl";
import "MidiNetworkClientDisconnectConfig.idl";

import "MidiNetworkAdvertisedHost.idl";

import "MidiNetworkConfiguredHost.idl";
import "MidiNetworkConfiguredClient.idl";

import "MidiNetworkRemoteClientApprovalConfig.idl";
import "MidiNetworkRemoteClientApprovalResponse.idl";
import "MidiNetworkPendingRemoteClient.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [static_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkTransportManagerStatics")]
    static runtimeclass MidiNetworkTransportManager
    {
        static Boolean IsTransportAvailable{ get; };
        static Guid TransportId{ get; };


        static Windows.Foundation.IAsyncOperation<MidiNetworkHostCreationResponse> CreateNetworkHostAsync(
            MidiNetworkHostCreationConfig creationConfig);

        static Windows.Foundation.IAsyncOperation<MidiNetworkHostRemovalResponse> RemoveNetworkHostAsync(
            MidiNetworkHostRemovalConfig removalConfig);

        // keeps the host entry in memory, but closes all connections
        // stops advertising, and refuses any new connections
        static Windows.Foundation.IAsyncOperation<MidiNetworkHostUpdateResponse> StopNetworkHostAsync(Guid hostId);
        static Windows.Foundation.IAsyncOperation<MidiNetworkHostUpdateResponse> StartNetworkHostAsync(Guid hostId);


        // Sends new client info to the service
        static Windows.Foundation.IAsyncOperation<MidiNetworkClientConnectResponse> ConnectNetworkClientAsync(
            MidiNetworkClientConnectConfig connectConfig);

        // Closes the connection and removes the entry in the service
        static Windows.Foundation.IAsyncOperation<MidiNetworkClientDisconnectResponse> DisconnectNetworkClientAsync(
            MidiNetworkClientDisconnectConfig disconnectConfig);

        // Approves or denies a pending client connection request. 
        static Windows.Foundation.IAsyncOperation<MidiNetworkRemoteClientApprovalResponse> ApproveOrDenyRemoteClientConnectRequestAsync(
            MidiNetworkRemoteClientApprovalConfig approvalConfig);



        // returns info about what is configured inside the service
        static Windows.Foundation.Collections.IVectorView<MidiNetworkConfiguredHost> GetConfiguredHosts();
        static Windows.Foundation.Collections.IVectorView<MidiNetworkConfiguredClient> GetConfiguredClients();

        static Windows.Foundation.Collections.IVectorView<MidiNetworkPendingRemoteClient> GetPendingRemoteClients();


        // list the external hosts currently visible to this PC
        static Windows.Foundation.Collections.IVectorView<MidiNetworkAdvertisedHost> GetAdvertisedHosts();


        static String MidiNetworkUdpDnsServiceType{ get; };
        static String MidiNetworkUdpDnsSdQueryString{ get; };
        static String MidiNetworkUdpDnsDomain { get; };
        static Windows.Devices.Enumeration.DeviceInformationKind MidiNetworkUdpDnsSdDeviceInformationKind{ get; };

        static IVector<String> MidiNetworkUdpDnsSdQueryAdditionalProperties { get; };

    }
}
