// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiBasicLoopbackErrorCodeEnum.idl";

namespace Windows.Devices.Midi2.Transports.BasicLoopback
{
    [contract(MidiTransportsBasicLoopbackApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Transports.BasicLoopback.IMidiBasicLoopbackUpdateResponse", UUID_IMidiBasicLoopbackUpdateResponse)]
    runtimeclass MidiBasicLoopbackUpdateResponse
    {
        [noexcept] Boolean Success { get; };

        [noexcept] MidiBasicLoopbackErrorCode ErrorCode{ get; };
        [noexcept] String ErrorMessage{ get; };
    };
}
