// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

// error codes shared with service
#include "..\..\..\..\Transport\UdpNetworkMidi2Transport\network_transport_error_codes.h"

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    enum MidiNetworkHostCreationErrorCode
    {
        NoErrorInformationAvailable =           NETWORK_ERROR_CODE_UNKNOWN_ERROR,
        UnrecognizedCommand =                   NETWORK_ERROR_CODE_UNRECOGNIZED_COMMAND,

        InvalidJson =                           NETWORK_ERROR_CODE_INVALID_JSON,

        HostCreationFailed =                    NETWORK_ERROR_CODE_HOST_CREATION_FAILED,

        InvalidOrMissingEntryIdentifier =       NETWORK_ERROR_CODE_MISSING_ENTRY_IDENTIFIER,
        MalformedEntryIdentifier =              NETWORK_ERROR_CODE_INVALID_ENTRY_IDENTIFIER,

        InvalidOrMissingEndpointName =          NETWORK_ERROR_CODE_MISSING_ENDPOINT_NAME,
        EndpointNameTooLong =                   NETWORK_ERROR_CODE_ENDPOINT_NAME_TOO_LONG,
        InvalidOrMissingProductInstanceId =     NETWORK_ERROR_CODE_MISSING_PRODUCT_INSTANCE_ID,
        ProductInstanceIdTooLong =              NETWORK_ERROR_CODE_PRODUCT_INSTANCE_ID_TOO_LONG,
        ServiceInstanceNameInUse =              NETWORK_ERROR_CODE_SERVICE_INSTANCE_NAME_IN_USE,
        ServiceInstanceNameTooLong =            NETWORK_ERROR_CODE_SERVICE_INSTANCE_NAME_TOO_LONG,
        InvalidNetworkProtocol =                NETWORK_ERROR_CODE_INVALID_NETWORK_PROTOCOL,
        InvalidNetworkPort =                    NETWORK_ERROR_CODE_INVALID_HOST_PORT,
        NetworkPortInUse =                      NETWORK_ERROR_CODE_HOST_PORT_IN_USE,

        InvalidOrMissingCredentialIdentifier =  NETWORK_ERROR_CODE_MISSING_CREDENTIAL_IDENTIFIER,
        MalformedCredentialIdentifier =         NETWORK_ERROR_CODE_INVALID_CREDENTIAL_IDENTIFIER,
        AuthenticationNotImplemented =          NETWORK_ERROR_CODE_AUTHENTICATION_NOT_IMPLEMENTED,

        InvalidArgument =                       NETWORK_ERROR_CODE_CLIENT_API_INVALID_ARGUMENT,
        ClientApiException =                    NETWORK_ERROR_CODE_CLIENT_API_EXCEPTION,

        // the service accepted the definition, but the host did not come up in time
        TimedOutWaitingForHostToStart =         NETWORK_ERROR_CODE_CLIENT_API_TIMEOUT,
    };
}