// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


// TODO: Change to runtimeclass

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkConfiguredHost", UUID_IMidiNetworkConfiguredHost)]
    runtimeclass MidiNetworkConfiguredHost
    {
        [noexcept] Guid HostId{ get;} ;  // internal id we use to match up in config file

        [noexcept] Boolean IsEnabled{ get; };                  // true if this is allows to connect. Mostly for pre-configured connections
        [noexcept] Boolean HasStarted{ get; };                 // true if this has started

        [noexcept] String ActualPort{ get; };                  // string because DatagramSocket.LocalPort returns a string
        [noexcept] String ActualAddress{ get; };

        [noexcept] String UmpEndpointName{ get; };
        [noexcept] String ProductInstanceId{ get; };

        [noexcept] String ServiceInstanceName{ get; };

        [noexcept] Boolean CreateMidi1Ports{ get; };
    };
}

