// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


// TODO: Change to runtimeclass

namespace Windows.Devices.Midi2.Transports.Network
{
    [experimental]
    [contract(MidiTransportsNetworkApiContract, 1)]
    runtimeclass MidiNetworkConfiguredHost
    {
        Guid HostId{ get;} ;  // internal id we use to match up in config file

        Boolean IsEnabled{ get; };                  // true if this is allows to connect. Mostly for pre-configured connections
        Boolean HasStarted{ get; };                 // true if this has started

        String ActualPort{ get; };                  // string because DatagramSocket.LocalPort returns a string
        String ActualAddress{ get; };

        String UmpEndpointName{ get; };
        String ProductInstanceId{ get; };

        String ServiceInstanceName{ get; };

        Boolean CreateMidi1Ports{ get; };
    };
}

