// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiProtocolEnum.idl";

namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiDeclaredStreamConfiguration", UUID_IMidiDeclaredStreamConfiguration)]
    [constructor_name("Windows.Devices.Midi2.Enumeration.IMidiDeclaredStreamConfigurationFactory", UUID_IMidiDeclaredStreamConfigurationFactory)]
    runtimeclass MidiDeclaredStreamConfiguration
    {
        MidiDeclaredStreamConfiguration();
        MidiDeclaredStreamConfiguration(
            MidiProtocol protocol,
            Boolean receiveJitterReductionTimestamps,
            Boolean sendJitterReductionTimestamps
        );

        Boolean IsReadOnly { get; };

        MidiProtocol Protocol;
        Boolean ReceiveJitterReductionTimestamps;
        Boolean SendJitterReductionTimestamps;
    };
}