// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiLoopbackErrorCodeEnum.idl";
import "MidiLoopbackEntry.idl";

namespace Windows.Devices.Midi2.Transports.Loopback
{
    [contract(MidiTransportsLoopbackApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Loopback.IMidiLoopbackCreationResult", UUID_IMidiLoopbackCreationResult)]
    runtimeclass MidiLoopbackCreationResult
    {
        Boolean Success{ get; };

        MidiLoopbackErrorCode ErrorCode{ get; };
        String ErrorMessage{ get; };

        MidiLoopbackEntry CreatedLoopbackEntry{ get; };
    };
}