// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiGroupTerminalBlock.idl";
import "MidiProtocolEnum.idl";
import "MidiEndpointNativeDataFormatEnum.idl";
import "MidiEndpointDevicePurposeEnum.idl";
import "MidiFunctionBlock.idl";
import "MidiDeclaredDeviceIdentity.idl";
import "MidiDeclaredEndpointInfo.idl";
import "MidiDeclaredStreamConfiguration.idl";
import "MidiEndpointTransportSuppliedInfo.idl";
import "MidiEndpointUserSuppliedInfo.idl";
import "Midi1PortNamingApproachEnum.idl";

import "MidiEndpointDeviceInformationSortOrderEnum.idl";
import "MidiEndpointDeviceInformationFiltersEnum.idl";

import "MidiLegacyPortDeviceInformation.idl";

import "Midi1PortFlowEnum.idl";
import "Midi1PortNameTableEntry.idl";
import "MidiParentDeviceInformation.idl";


namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointDeviceInformation", UUID_IMidiEndpointDeviceInformation)]
    [static_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointDeviceInformationStatics", UUID_IMidiEndpointDeviceInformationStatics)]
    runtimeclass MidiEndpointDeviceInformation : Windows.Foundation.IStringable
    {
        [noexcept] static MidiEndpointDeviceInformation CreateFromEndpointDeviceId(String endpointDeviceId);

        [noexcept] static IVectorView<MidiEndpointDeviceInformation> FindAll();
        [noexcept] static IVectorView<MidiEndpointDeviceInformation> FindAll(MidiEndpointDeviceInformationSortOrder sortOrder);
        [noexcept] static IVectorView<MidiEndpointDeviceInformation> FindAll(MidiEndpointDeviceInformationSortOrder sortOrder, MidiEndpointDeviceInformationFilters endpointTypesToInclude);

        [noexcept] static IVectorView<MidiEndpointDeviceInformation> FindAllForContainer(Guid containerId);

        [noexcept] static Guid EndpointInterfaceClass{ get; };

        [noexcept] static IVectorView<String> GetAdditionalPropertiesList();

        [noexcept] static Boolean DeviceMatchesFilter(MidiEndpointDeviceInformation deviceInformation, MidiEndpointDeviceInformationFilters endpointTypesToInclude);



        [noexcept] String EndpointDeviceId { get; };

        [noexcept] String Name{ get; };

        [noexcept] Guid ContainerId{ get; };
        [noexcept] String DeviceInstanceId{ get; };

        [noexcept] MidiEndpointDevicePurpose EndpointPurpose{ get; };


        [noexcept] MidiDeclaredEndpointInfo GetDeclaredEndpointInfo();
        [noexcept] Windows.Foundation.DateTime DeclaredEndpointInfoLastUpdateTime{ get; };

        [noexcept] MidiDeclaredDeviceIdentity GetDeclaredDeviceIdentity();
        [noexcept] Windows.Foundation.DateTime DeclaredDeviceIdentityLastUpdateTime{ get; };

        [noexcept] MidiDeclaredStreamConfiguration GetDeclaredStreamConfiguration();
        [noexcept] Windows.Foundation.DateTime DeclaredStreamConfigurationLastUpdateTime{ get; };

        [noexcept] IVectorView<MidiFunctionBlock> GetDeclaredFunctionBlocks();
        [noexcept] Windows.Foundation.DateTime DeclaredFunctionBlocksLastUpdateTime{ get; };

        [noexcept] IVectorView<MidiGroupTerminalBlock> GetGroupTerminalBlocks();

        [noexcept] MidiEndpointUserSuppliedInfo GetUserSuppliedInfo();

        [noexcept] MidiEndpointTransportSuppliedInfo GetTransportSuppliedInfo();

        [noexcept] String ParentDeviceInstanceId{ get; };          // device instance id of the parent device

        [noexcept] MidiParentDeviceInformation GetParentDeviceInformation();
        [noexcept] Windows.Devices.Enumeration.DeviceInformation GetContainerDeviceInformation();

        [noexcept] Windows.Foundation.Collections.IMapView<String, IInspectable> Properties{ get; };

        [noexcept] IVectorView<Midi1PortNameTableEntry> GetNameTable();

        [noexcept] Midi1PortNamingApproach Midi1PortNamingApproach{ get; };


        [noexcept] Boolean IsMidi1PortCreationEnabled{ get; };
        [noexcept] Boolean IsMuted{ get; };


    }
}
