// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"

// Every Midi2 IDL imports this file, so it carries the external WinRT
// declarations the API surface depends on.
import "inspectable.idl";
import "windows.foundation.idl";
import "robytestream.idl";
import "windows.data.json.idl";
import "windows.devices.enumeration.idl";
import "windows.devices.midi.idl";

namespace Windows.Devices.Midi2
{
    [contractversion(1)]
    apicontract MidiCoreApiContract { };

    namespace CapabilityInquiry
    {
        [contractversion(1)]
        apicontract MidiCapabilityInquiryApiContract { };
    }

    namespace ClientPlugins
    {
        [contractversion(1)]
        apicontract MidiClientPluginsApiContract { };
    }

    namespace Diagnostics
    {
        [contractversion(1)]
        apicontract MidiDiagnosticsApiContract { };
    }


    namespace Enumeration
    {
        [contractversion(1)]
        apicontract MidiEnumerationApiContract { };

        namespace Legacy
        {
            [contractversion(1)]
            apicontract MidiEnumerationLegacyApiContract { };
        }
    }

    namespace Reporting
    {
        [contractversion(1)]
        apicontract MidiReportingApiContract { };
    }

    namespace ServiceConfig
    {
        [contractversion(1)]
        apicontract MidiServiceConfigApiContract { };
    }


    namespace Transports
    {

        namespace Loopback
        {
            [contractversion(1)]
            apicontract MidiTransportsLoopbackApiContract { };
        }

        namespace BasicLoopback
        {
            [contractversion(1)]
            apicontract MidiTransportsBasicLoopbackApiContract { };
        }

        namespace Virtual
        {
            [contractversion(1)]
            apicontract MidiTransportsVirtualApiContract { };
        }

        namespace Network
        {
            [contractversion(1)]
            apicontract MidiTransportsNetworkApiContract { };
        }

    }


    namespace Utilities
    {

        namespace Messages
        {
            [contractversion(1)]
            apicontract MidiMessageUtilityApiContract { };
        }

        namespace SysExTransfer
        {
            [contractversion(1)]
            apicontract MidiSysExTransferUtilityApiContract { };
        }

    }

}
