// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#define IDS_MIDI2_CLIENT 100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif



// Common MIDI Strings

#define IDS_MIDI_COMMON_LABEL_GROUP_FULL							50100
#define IDS_MIDI_COMMON_LABEL_GROUP_SHORT							50101
#define IDS_MIDI_COMMON_LABEL_GROUP_FULL_PLURAL						50102
#define IDS_MIDI_COMMON_LABEL_GROUP_SHORT_PLURAL					50103

#define IDS_MIDI_COMMON_LABEL_CHANNEL_FULL							50110
#define IDS_MIDI_COMMON_LABEL_CHANNEL_SHORT							50111
#define IDS_MIDI_COMMON_LABEL_CHANNEL_FULL_PLURAL					50112
#define IDS_MIDI_COMMON_LABEL_CHANNEL_SHORT_PLURAL					50113

#define IDS_MIDI_COMMON_LABEL_MUID_FULL								50120
#define IDS_MIDI_COMMON_LABEL_MUID_SHORT							50121
#define IDS_MIDI_COMMON_LABEL_MUID_FULL_PLURAL						50122
#define IDS_MIDI_COMMON_LABEL_MUID_SHORT_PLURAL						50123

#define IDS_MIDI_COMMON_LABEL_FUNCTION_BLOCK_FULL					50130
#define IDS_MIDI_COMMON_LABEL_FUNCTION_BLOCK_SHORT					50131
#define IDS_MIDI_COMMON_LABEL_FUNCTION_BLOCK_FULL_PLURAL			50132
#define IDS_MIDI_COMMON_LABEL_FUNCTION_BLOCK_SHORT_PLURAL			50133

#define IDS_MIDI_COMMON_LABEL_GROUP_TERMINAL_BLOCK_FULL				50140
#define IDS_MIDI_COMMON_LABEL_GROUP_TERMINAL_BLOCK_SHORT			50141
#define IDS_MIDI_COMMON_LABEL_GROUP_TERMINAL_BLOCK_FULL_PLURAL		50142
#define IDS_MIDI_COMMON_LABEL_GROUP_TERMINAL_BLOCK_SHORT_PLURAL		50143

#define IDS_MIDI_COMMON_LABEL_SYSEX_CHANNEL_FULL				    50150
#define IDS_MIDI_COMMON_LABEL_SYSEX_CHANNEL_SHORT			        50151
#define IDS_MIDI_COMMON_LABEL_SYSEX_CHANNEL_FULL_PLURAL		        50152
#define IDS_MIDI_COMMON_LABEL_SYSEX_CHANNEL_SHORT_PLURAL		    50153


// Note index info

#define IDS_NOTE_INVALID                                            50199



// Message type descriptions. These are optionally displayed by apps using the API


// Message Type ?

#define IDS_MESSAGE_DESC_MT_UNKNOWN									50200


// Message Type 0 - Utility

#define IDS_MESSAGE_DESC_MT0_NOOP									50201
#define IDS_MESSAGE_DESC_MT0_JR_CLOCK								50202
#define IDS_MESSAGE_DESC_MT0_JR_TS									50203
#define IDS_MESSAGE_DESC_MT0_TICKS_PQN								50204
#define IDS_MESSAGE_DESC_MT0_DELTA_TICKS							50205
#define IDS_MESSAGE_DESC_MT0_UNKNOWN								50206

// Message Type 1 - System Common

#define IDS_MESSAGE_DESC_MT1_F0_RESERVED							50300
#define IDS_MESSAGE_DESC_MT1_F1_TIME_CODE							50301
#define IDS_MESSAGE_DESC_MT1_F2_SONG_POSITION						50302
#define IDS_MESSAGE_DESC_MT1_F3_SONG_SELECT							50303
#define IDS_MESSAGE_DESC_MT1_F4_RESERVED							50304
#define IDS_MESSAGE_DESC_MT1_F5_RESERVED							50305
#define IDS_MESSAGE_DESC_MT1_F6_TUNE_REQUEST						50306
#define IDS_MESSAGE_DESC_MT1_F7_RESERVED							50307
#define IDS_MESSAGE_DESC_MT1_F8_TIMING_CLOCK						50308
#define IDS_MESSAGE_DESC_MT1_F9_RESERVED							50309
#define IDS_MESSAGE_DESC_MT1_FA_START								50310
#define IDS_MESSAGE_DESC_MT1_FB_CONTINUE							50311
#define IDS_MESSAGE_DESC_MT1_FC_STOP								50312
#define IDS_MESSAGE_DESC_MT1_FD_RESERVED							50313
#define IDS_MESSAGE_DESC_MT1_FE_ACTIVE_SENSE						50314
#define IDS_MESSAGE_DESC_MT1_FF_RESET								50315
#define IDS_MESSAGE_DESC_MT1_UNKNOWN								50316

// Message Type 2 - MIDI 1.0 Channel Voice

#define IDS_MESSAGE_DESC_MT2_8_NOTE_OFF								50400
#define IDS_MESSAGE_DESC_MT2_9_NOTE_ON								50401
#define IDS_MESSAGE_DESC_MT2_A_POLY_PRESSURE						50402
#define IDS_MESSAGE_DESC_MT2_B_CONTROL_CHANGE						50403
#define IDS_MESSAGE_DESC_MT2_C_PROGRAM_CHANGE						50404
#define IDS_MESSAGE_DESC_MT2_D_CHANNEL_PRESSURE						50405
#define IDS_MESSAGE_DESC_MT2_E_PITCH_BEND							50406
#define IDS_MESSAGE_DESC_MT2_UNKNOWN								50407

// Message Type 3 - Data Messages

#define IDS_MESSAGE_DESC_MT3_0_SYSEX7_COMPLETE						50500
#define IDS_MESSAGE_DESC_MT3_1_SYSEX7_START							50501
#define IDS_MESSAGE_DESC_MT3_2_SYSEX7_CONTINUE						50502
#define IDS_MESSAGE_DESC_MT3_3_SYSEX7_END							50503
#define IDS_MESSAGE_DESC_MT3_DATA64_UNKNOWN							50504

// Message Type 4 - MIDI 2.0 Channel Voice

#define IDS_MESSAGE_DESC_MT4_0_RPNC									50600
#define IDS_MESSAGE_DESC_MT4_1_APNC									50601
#define IDS_MESSAGE_DESC_MT4_2_RC									50602
#define IDS_MESSAGE_DESC_MT4_3_AC									50603
#define IDS_MESSAGE_DESC_MT4_4_REL_RC								50604
#define IDS_MESSAGE_DESC_MT4_5_REL_AC								50605
#define IDS_MESSAGE_DESC_MT4_6_PER_NOTE_BEND						50606
#define IDS_MESSAGE_DESC_MT4_8_NOTE_OFF								50607
#define IDS_MESSAGE_DESC_MT4_9_NOTE_ON								50608
#define IDS_MESSAGE_DESC_MT4_A_POLY_PRESSURE						50609
#define IDS_MESSAGE_DESC_MT4_B_CONTROL_CHANGE						50610
#define IDS_MESSAGE_DESC_MT4_C_PROGRAM_CHANGE						50611
#define IDS_MESSAGE_DESC_MT4_D_CHANNEL_PRESSURE						50612
#define IDS_MESSAGE_DESC_MT4_E_PITCH_BEND							50613
#define IDS_MESSAGE_DESC_MT4_MIDI2_CV_UNKNOWN						50614

// Message Type 5 - Data Messages

#define IDS_MESSAGE_DESC_MT5_0_SYSEX8_COMPLETE						50700
#define IDS_MESSAGE_DESC_MT5_1_SYSEX8_START							50701
#define IDS_MESSAGE_DESC_MT5_2_SYSEX8_CONTINUE						50702
#define IDS_MESSAGE_DESC_MT5_3_SYSEX8_END							50703
#define IDS_MESSAGE_DESC_MT5_8_MIXED_DATA_HEADER					50704
#define IDS_MESSAGE_DESC_MT5_9_MIXED_DATA_PAYLOAD					50705
#define IDS_MESSAGE_DESC_MT5_UNKNOWN								50706

// Message Type 6 - Unallocated

#define IDS_MESSAGE_DESC_MT6_RESERVED								50800

// Message Type 7 - Unallocated

#define IDS_MESSAGE_DESC_MT7_RESERVED								50900

// Message Type 8 - Unallocated

#define IDS_MESSAGE_DESC_MT8_RESERVED								51000

// Message Type 9 - Unallocated

#define IDS_MESSAGE_DESC_MT9_RESERVED								51100

// Message Type A - Unallocated

#define IDS_MESSAGE_DESC_MTA_RESERVED								51200

// Message Type B - Unallocated

#define IDS_MESSAGE_DESC_MTB_RESERVED								51300

// Message Type C - Unallocated

#define IDS_MESSAGE_DESC_MTC_RESERVED								51400

// Message Type D - Flex Data

#define IDS_MESSAGE_DESC_MTD_00_00_SET_TEMPO						51450
#define IDS_MESSAGE_DESC_MTD_00_01_SET_TIME_SIGNATURE				51451
#define IDS_MESSAGE_DESC_MTD_00_02_SET_METRONOME					51452
#define IDS_MESSAGE_DESC_MTD_00_05_SET_KEY_SIGNATURE				51453
#define IDS_MESSAGE_DESC_MTD_00_06_SET_CHORD_NAME					51454
#define IDS_MESSAGE_DESC_MTD_00_UNKNOWN								51455

#define IDS_MESSAGE_DESC_MTD_01_00_METADATA_TEXT					51500
#define IDS_MESSAGE_DESC_MTD_01_01_PROJECT_NAME						51501
#define IDS_MESSAGE_DESC_MTD_01_02_SONG_NAME						51502
#define IDS_MESSAGE_DESC_MTD_01_03_CLIP_NAME						51503
#define IDS_MESSAGE_DESC_MTD_01_04_COPYRIGHT						51504
#define IDS_MESSAGE_DESC_MTD_01_05_COMPOSER_NAME					51505
#define IDS_MESSAGE_DESC_MTD_01_06_LYRICIST_NAME					51506
#define IDS_MESSAGE_DESC_MTD_01_07_ARRANGER_NAME					51507
#define IDS_MESSAGE_DESC_MTD_01_08_PUBLISHER_NAME					51508
#define IDS_MESSAGE_DESC_MTD_01_09_PRIMARY_PERFORMER_NAME			51509
#define IDS_MESSAGE_DESC_MTD_01_0A_ACCOMPANY_PERFORMER_NAME			51510
#define IDS_MESSAGE_DESC_MTD_01_0B_RECORDING_DATE					51511
#define IDS_MESSAGE_DESC_MTD_01_0C_RECORDING_LOCATION				51512
#define IDS_MESSAGE_DESC_MTD_01_UNKNOWN								51513

#define IDS_MESSAGE_DESC_MTD_02_00_PERF_TEXT_EVENT					51600
#define IDS_MESSAGE_DESC_MTD_02_01_LYRICS							51601
#define IDS_MESSAGE_DESC_MTD_02_02_LYRICS_LANGUAGE					51602
#define IDS_MESSAGE_DESC_MTD_02_03_RUBY								51603
#define IDS_MESSAGE_DESC_MTD_02_04_RUBY_LANGUAGE					51604
#define IDS_MESSAGE_DESC_MTD_02_UNKNOWN								51605

#define IDS_MESSAGE_DESC_MTD_UNKNOWN								51700

// Message Type E - Unallocated

#define IDS_MESSAGE_DESC_MTE_RESERVED								51800

// Message Type F - Stream Messages

#define IDS_MESSAGE_DESC_MTF_00_DISCOVERY							51900
#define IDS_MESSAGE_DESC_MTF_01_ENDPOINT_INFO						51901
#define IDS_MESSAGE_DESC_MTF_02_DEVICE_IDENTITY						51902
#define IDS_MESSAGE_DESC_MTF_03_ENDPOINT_NAME						51903
#define IDS_MESSAGE_DESC_MTF_04_PRODUCT_INSTANCE_ID					51904
#define IDS_MESSAGE_DESC_MTF_05_CONFIG_REQUEST						51905
#define IDS_MESSAGE_DESC_MTF_06_CONFIG_NOTIFICATION					51906
#define IDS_MESSAGE_DESC_MTF_10_FUNCTION_BLOCK_DISCOVERY            51910
#define IDS_MESSAGE_DESC_MTF_11_FUNCTION_BLOCK_INFO					51911
#define IDS_MESSAGE_DESC_MTF_12_FUNCTION_BLOCK_NAME					51912
#define IDS_MESSAGE_DESC_MTF_UNKNOWN								51999


// Display strings used when building names for presentation to the user

#define IDS_DISPLAY_IDS_BASE_INDEX                                  52000

#define IDS_DISPLAY_UNNAMED_ENDPOINT                                IDS_DISPLAY_IDS_BASE_INDEX + 0
#define IDS_DISPLAY_UNNAMED_FUNCTION_BLOCK                          IDS_DISPLAY_IDS_BASE_INDEX + 1
#define IDS_DISPLAY_UNNAMED_GROUP_TERMINAL_BLOCK                    IDS_DISPLAY_IDS_BASE_INDEX + 2
#define IDS_DISPLAY_UNNAMED_PARENT_DEVICE                           IDS_DISPLAY_IDS_BASE_INDEX + 3

#define IDS_DISPLAY_VIRTUAL_DEVICE_NAME_PREFIX                      IDS_DISPLAY_IDS_BASE_INDEX + 10


// CC Mode messages
// these are the base index + the CC number

#define IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX                         60000
#define IDS_MESSAGE_DESC_CC_MODE_ALL_SOUNDS_OFF                     IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 120
#define IDS_MESSAGE_DESC_CC_MODE_RESET_CONTROLLERS                  IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 121
#define IDS_MESSAGE_DESC_CC_MODE_LOCAL_CONTROL                      IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 122
#define IDS_MESSAGE_DESC_CC_MODE_ALL_NOTES_OFF                      IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 123
#define IDS_MESSAGE_DESC_CC_MODE_OMNI_OFF                           IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 124
#define IDS_MESSAGE_DESC_CC_MODE_OMNI_ON                            IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 125
#define IDS_MESSAGE_DESC_CC_MODE_MONO_ON                            IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 126
#define IDS_MESSAGE_DESC_CC_MODE_POLY_ON                            IDS_MESSAGE_DESC_CC_MODE_BASE_INDEX + 127

// Errors

#define IDS_VALIDATION_ERROR_IDS_BASE_INDEX                         61000

#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_NAME         IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 0
#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_UNIQUEID     IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 1

#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_NAME_A       IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 20
#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_UNIQUEID_A   IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 21

#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_NAME_B       IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 40
#define IDS_VALIDATION_ERROR_LOOPBACK_MISSING_ENDPOINT_UNIQUEID_B   IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 41

#define IDS_ERROR_UNKNOWN                                           IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 50
#define IDS_ERROR_GENERAL_EXCEPTION                                 IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 51
#define IDS_ERROR_SERVICE_CALL_FAILED_NO_MESSAGE                    IDS_VALIDATION_ERROR_IDS_BASE_INDEX + 52


// Loopback and Basic Loopback transport errors

#define IDS_LOOPBACK_ERROR_IDS_BASE_INDEX                           61100

#define IDS_LOOPBACK_ERROR_MUTE_NOT_SUPPORTED                       IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 0
#define IDS_LOOPBACK_ERROR_UNMUTE_NOT_SUPPORTED                     IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 1

#define IDS_LOOPBACK_ERROR_NULL_CREATION_CONFIG                     IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 10
#define IDS_LOOPBACK_ERROR_NULL_ENDPOINT_DEFINITION_A               IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 11
#define IDS_LOOPBACK_ERROR_NULL_ENDPOINT_DEFINITION_B               IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 12

#define IDS_LOOPBACK_ERROR_ENTRY_ALLOCATION_FAILED                  IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 20
#define IDS_LOOPBACK_ERROR_ENDPOINT_ENTRY_ALLOCATION_FAILED         IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 21

#define IDS_LOOPBACK_ERROR_EMPTY_RETURNED_DEVICE_ID                 IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 30
#define IDS_LOOPBACK_ERROR_EMPTY_RETURNED_DEVICE_IDS                IDS_LOOPBACK_ERROR_IDS_BASE_INDEX + 31


// Diagnostics / service ping errors

#define IDS_PING_ERROR_IDS_BASE_INDEX                               61200

#define IDS_PING_ERROR_ZERO_PING_COUNT                              IDS_PING_ERROR_IDS_BASE_INDEX + 0
#define IDS_PING_ERROR_ZERO_TIMEOUT                                 IDS_PING_ERROR_IDS_BASE_INDEX + 1
#define IDS_PING_ERROR_SESSION_CREATION_FAILED                      IDS_PING_ERROR_IDS_BASE_INDEX + 2
#define IDS_PING_ERROR_ENDPOINT_CREATION_FAILED                     IDS_PING_ERROR_IDS_BASE_INDEX + 3
#define IDS_PING_ERROR_ENDPOINT_OPEN_FAILED                         IDS_PING_ERROR_IDS_BASE_INDEX + 4
#define IDS_PING_ERROR_SEND_MESSAGE_FAILED                          IDS_PING_ERROR_IDS_BASE_INDEX + 5
#define IDS_PING_ERROR_RESPONSE_TIMEOUT                             IDS_PING_ERROR_IDS_BASE_INDEX + 6
#define IDS_PING_ERROR_EXCEPTION                                    IDS_PING_ERROR_IDS_BASE_INDEX + 7

// Network MIDI 2.0 transport errors

#define IDS_NETWORK_ERROR_IDS_BASE_INDEX                            61300

#define IDS_NETWORK_ERROR_NULL_CREATION_CONFIG                      IDS_NETWORK_ERROR_IDS_BASE_INDEX + 0
#define IDS_NETWORK_ERROR_NULL_REMOVAL_CONFIG                       IDS_NETWORK_ERROR_IDS_BASE_INDEX + 1
#define IDS_NETWORK_ERROR_NULL_CONNECT_CONFIG                       IDS_NETWORK_ERROR_IDS_BASE_INDEX + 2
#define IDS_NETWORK_ERROR_NULL_DISCONNECT_CONFIG                    IDS_NETWORK_ERROR_IDS_BASE_INDEX + 3
#define IDS_NETWORK_ERROR_NULL_APPROVAL_CONFIG                      IDS_NETWORK_ERROR_IDS_BASE_INDEX + 4

#define IDS_NETWORK_ERROR_MISSING_MATCH_CRITERIA                    IDS_NETWORK_ERROR_IDS_BASE_INDEX + 10
#define IDS_NETWORK_ERROR_MISSING_REMOTE_CLIENT_IDENTITY            IDS_NETWORK_ERROR_IDS_BASE_INDEX + 11

#define IDS_NETWORK_ERROR_HOST_START_TIMEOUT                        IDS_NETWORK_ERROR_IDS_BASE_INDEX + 20

// SysEx Transfer Errors

#define IDS_SYSEX_ERROR_IDS_BASE_INDEX                                      62000

#define IDS_SYSEX_TRANSFER_ERROR_MISSING_STATE_ARGUMENT                     IDS_SYSEX_ERROR_IDS_BASE_INDEX + 0
#define IDS_SYSEX_TRANSFER_ERROR_MISSING_DATA_SOURCE_ARGUMENT               IDS_SYSEX_ERROR_IDS_BASE_INDEX + 1
#define IDS_SYSEX_TRANSFER_ERROR_MISSING_DESTINATION_GROUP_ARGUMENT         IDS_SYSEX_ERROR_IDS_BASE_INDEX + 2
#define IDS_SYSEX_TRANSFER_ERROR_MISSING_DESTINATION_CONNECTION_ARGUMENT    IDS_SYSEX_ERROR_IDS_BASE_INDEX + 3

#define IDS_SYSEX_TRANSFER_ERROR_CLOSED_DESTINATION_CONNECTION_ARGUMENT     IDS_SYSEX_ERROR_IDS_BASE_INDEX + 10
#define IDS_SYSEX_TRANSFER_ERROR_UNEXPECTED_MESSAGE_IN_DATA                 IDS_SYSEX_ERROR_IDS_BASE_INDEX + 11
#define IDS_SYSEX_TRANSFER_ERROR_SEND_MESSAGE_FAILED                        IDS_SYSEX_ERROR_IDS_BASE_INDEX + 12


// Configuration file save errors

#define IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX                                62100

#define IDS_CONFIG_SAVE_ERROR_NOT_PERSISTABLE                               IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 0
#define IDS_CONFIG_SAVE_ERROR_JSON_NULL_OR_EMPTY                            IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 1
#define IDS_CONFIG_SAVE_ERROR_PROCESSING_JSON                               IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 2
#define IDS_CONFIG_SAVE_ERROR_NO_CONFIG_FILE_REGISTERED                     IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 3
#define IDS_CONFIG_SAVE_ERROR_FILE_NOT_VALID_JSON                           IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 4
#define IDS_CONFIG_SAVE_ERROR_ACCESS_DENIED                                 IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 5
#define IDS_CONFIG_SAVE_ERROR_FILE_BUSY                                     IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 6
#define IDS_CONFIG_SAVE_ERROR_WRITING_FILE                                  IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 7
#define IDS_CONFIG_SAVE_ERROR_VERIFICATION_FAILED                           IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 8
#define IDS_CONFIG_SAVE_ERROR_UNEXPECTED                                    IDS_CONFIG_SAVE_ERROR_IDS_BASE_INDEX + 9


#define IDS_BLUETOOTH_ERROR_IDS_BASE_INDEX                                  62200

#define IDS_BLUETOOTH_ERROR_NO_SERVICE_RESPONSE                             IDS_BLUETOOTH_ERROR_IDS_BASE_INDEX + 0
#define IDS_BLUETOOTH_ERROR_MISSING_DEVICE_ID                               IDS_BLUETOOTH_ERROR_IDS_BASE_INDEX + 1
#define IDS_BLUETOOTH_ERROR_PERIPHERAL_PROTOCOL_REQUIRED                    IDS_BLUETOOTH_ERROR_IDS_BASE_INDEX + 2
