// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

typedef enum
{
    MidiDataFormat_Invalid = 0,
    MidiDataFormat_ByteStream = 0x1,
    MidiDataFormat_UMP = 0x2,
    MidiDataFormat_Any = 0x3
} MidiDataFormat;
