// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "unknwn.idl";

import "MidiFlow.idl";
import "MidiDataFormat.idl";

// If you change these, you should also update
// the WinRT MidiEndpointDevicePurpose enum, which is projected through the API
typedef enum
{
    NormalMessageEndpoint = 0,
    VirtualDeviceResponder = 100,
    InBoxGeneralMidiSynth = 400,
    DiagnosticLoopback = 500,
    DiagnosticPing = 510,
} MidiEndpointDevicePurposePropertyValue;


// This is used when creating a device endpoint from an abstraction
typedef struct
{
    GUID AbstractionLayerGuid;
    MidiEndpointDevicePurposePropertyValue EndpointPurpose;

    LPCWSTR FriendlyName;

    LPCWSTR TransportMnemonic;
    LPCWSTR TransportSuppliedEndpointName;
    LPCWSTR TransportSuppliedEndpointDescription;

    LPCWSTR UserSuppliedEndpointName;
    LPCWSTR UserSuppliedEndpointDescription;

    LPCWSTR UniqueIdentifier;

    MidiDataFormat SupportedDataFormats;
    BYTE NativeDataFormat;

    BOOL SupportsMultiClient;
    BOOL RequiresMetadataHandler;
    BOOL GenerateIncomingTimestamps;
} MIDIENDPOINTCOMMONPROPERTIES, *PMIDIENDPOINTCOMMONPROPERTIES;


[
    object,
    local,
    uuid(A04374D3-4514-44E1-A2F9-7D8B907AEF1F),
    pointer_default(unique)
]
interface IMidiDeviceManagerInterface : IUnknown
{

    HRESULT ActivateVirtualParentDevice(
        [in] ULONG DevPropertyCount,
        [in, annotation("_In_opt_")] PVOID DevProperties,
        [in, annotation("_In_")] PVOID CreateInfo,
        [out, annotation("_Out_writes_opt_z_(CreatedSwDeviceIdCharCount)")] LPWSTR CreatedSwDeviceId,
        [in] ULONG CreatedSwDeviceIdCharCount
    );


    HRESULT ActivateEndpoint(
        [in] LPCWSTR ParentInstanceId,
        [in] BOOL UMPOnly,
        [in] MidiFlow MidiFlow,
        [in] PMIDIENDPOINTCOMMONPROPERTIES CommonProperties,
        [in] ULONG IntPropertyCount,
        [in] ULONG DevPropertyCount,
        [in, annotation("_In_opt_")] PVOID InterfaceDevProperties,
        [in, annotation("_In_opt_")] PVOID DeviceDevProperties,
        [in, annotation("_In_opt_")] PVOID CreateInfo,
        [out, annotation("_Out_writes_opt_z_(CreatedSwDeviceInterfaceIdWCharCount)")] LPWSTR CreatedSwDeviceInterfaceId,
        [in] ULONG CreatedSwDeviceInterfaceIdWCharCount
    );

    HRESULT UpdateEndpointProperties(
        [in] LPCWSTR DeviceInterfaceId,
        [in] ULONG IntPropertyCount,
        [in, annotation("_In_")] PVOID InterfaceDevProperties
    );

    HRESULT DeleteEndpointProperties(
        [in] LPCWSTR DeviceInterfaceId,
        [in] ULONG IntPropertyCount,
        [in, annotation("_In_")] PVOID DevPropKeys
    );

    HRESULT DeleteAllEndpointInProtocolDiscoveredProperties(
        [in] LPCWSTR DeviceInterfaceId
    );

    HRESULT DeactivateEndpoint(
        [in] LPCWSTR InstanceId
    );

    HRESULT RemoveEndpoint(
        [in] LPCWSTR InstanceId
    );


    // Update the configuration for an abstraction or endpoints managed by that abstraction
    HRESULT UpdateAbstractionConfiguration(
        [in] GUID AbstractionId,
        [in] LPCWSTR ConfigurationJson,
        [in] BOOL IsFromConfigurationFile,
        [out] BSTR* Response
    );


};
