// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiGroupTerminalBlockDirectionEnum.idl";
import "MidiGroupTerminalBlockProtocolEnum.idl";
import "MidiFunctionBlock.idl";

namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiGroupTerminalBlock", UUID_IMidiGroupTerminalBlock)]
    [static_name("Windows.Devices.Midi2.Enumeration.IMidiGroupTerminalBlockStatics", UUID_IMidiGroupTerminalBlockStatics)]
    runtimeclass MidiGroupTerminalBlock : Windows.Foundation.IStringable
    {
        static String ShortLabel{ get; };
        static String ShortLabelPlural{ get; };
        static String LongLabel{ get; };
        static String LongLabelPlural{ get; };

        UInt8 Number{ get; };

        String Name{ get; };

        MidiGroupTerminalBlockDirection Direction { get; };
        MidiGroupTerminalBlockProtocol Protocol { get; };

        Windows.Devices.Midi2.MidiGroup FirstGroup{ get; };
        UInt8 GroupCount{ get; };

        Boolean IncludesGroup(Windows.Devices.Midi2.MidiGroup group);

        UInt16 MaxDeviceInputBandwidthIn4KBitsPerSecondUnits{ get; };
        UInt16 MaxDeviceOutputBandwidthIn4KBitsPerSecondUnits{ get; };

        UInt32 CalculatedMaxDeviceInputBandwidthBitsPerSecond{ get; };
        UInt32 CalculatedMaxDeviceOutputBandwidthBitsPerSecond{ get; };

        MidiFunctionBlock AsEquivalentFunctionBlock();
    }
}