// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

//#include "..\shared\midi_sdk_idl_defs.h"
//import "MidiApiContracts.idl";
//
//
//
//import "MidiEndpointDeviceInformation.idl";
//import "MidiServiceTransportPluginInfo.idl";
//
//namespace Windows.Devices.Midi2.Utilities.Metadata
//{
//    [experimental]
//    static runtimeclass MidiImageAssetHelper
//    {
//        static String GetImageFullPathForTransport(Windows.Devices.Midi2.Reporting.MidiServiceTransportPluginInfo transportPluginInfo);
//        static String GetDefaultImageFullPathForTransport(Windows.Devices.Midi2.Reporting.MidiServiceTransportPluginInfo transportPluginInfo);
//
//        static String GetImageFullPathForEndpoint(Windows.Devices.Midi2.MidiEndpointDeviceInformation endpointDeviceInformation);
//        static String GetDefaultImageFullPathForEndpoint(Windows.Devices.Midi2.MidiEndpointDeviceInformation endpointDeviceInformation);
//
//        static Boolean EndpointHasValidCustomImageAsset(Windows.Devices.Midi2.MidiEndpointDeviceInformation endpointDeviceInformation);
//        static String GetFullCustomImageAssetPathForEndpointImage(Windows.Devices.Midi2.MidiEndpointDeviceInformation endpointDeviceInformation);
//    }
//}