// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiGroupTerminalBlock.idl";
import "MidiProtocolEnum.idl";
import "MidiEndpointNativeDataFormatEnum.idl";
import "MidiEndpointDevicePurposeEnum.idl";
import "MidiFunctionBlock.idl";
import "MidiDeclaredDeviceIdentity.idl";
import "MidiDeclaredEndpointInfo.idl";
import "MidiDeclaredStreamConfiguration.idl";
import "MidiEndpointTransportSuppliedInfo.idl";
import "MidiEndpointUserSuppliedInfo.idl";
import "Midi1PortNamingApproachEnum.idl";

import "MidiEndpointDeviceInformationSortOrderEnum.idl";
import "MidiEndpointDeviceInformationFiltersEnum.idl";

import "MidiLegacyPortDeviceInformation.idl";

import "Midi1PortFlowEnum.idl";
import "Midi1PortNameTableEntry.idl";
import "MidiParentDeviceInformation.idl";


namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointDeviceInformation", UUID_IMidiEndpointDeviceInformation)]
    [static_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointDeviceInformationStatics", UUID_IMidiEndpointDeviceInformationStatics)]
    runtimeclass MidiEndpointDeviceInformation : Windows.Foundation.IStringable
    {
        static MidiEndpointDeviceInformation CreateFromEndpointDeviceId(String endpointDeviceId);

        static IVectorView<MidiEndpointDeviceInformation> FindAll();
        static IVectorView<MidiEndpointDeviceInformation> FindAll(MidiEndpointDeviceInformationSortOrder sortOrder);
        static IVectorView<MidiEndpointDeviceInformation> FindAll(MidiEndpointDeviceInformationSortOrder sortOrder, MidiEndpointDeviceInformationFilters endpointTypesToInclude);

        static IVectorView<MidiEndpointDeviceInformation> FindAllForContainer(Guid containerId);

        static Guid EndpointInterfaceClass{ get; };

        static IVectorView<String> GetAdditionalPropertiesList();

        static Boolean DeviceMatchesFilter(MidiEndpointDeviceInformation deviceInformation, MidiEndpointDeviceInformationFilters endpointTypesToInclude);



        String EndpointDeviceId { get; };

        String Name{ get; };

        Guid ContainerId{ get; };
        String DeviceInstanceId{ get; };

        MidiEndpointDevicePurpose EndpointPurpose{ get; };


        MidiDeclaredEndpointInfo GetDeclaredEndpointInfo();
        Windows.Foundation.DateTime DeclaredEndpointInfoLastUpdateTime{ get; };

        MidiDeclaredDeviceIdentity GetDeclaredDeviceIdentity();
        Windows.Foundation.DateTime DeclaredDeviceIdentityLastUpdateTime{ get; };

        MidiDeclaredStreamConfiguration GetDeclaredStreamConfiguration();
        Windows.Foundation.DateTime DeclaredStreamConfigurationLastUpdateTime{ get; };

        IVectorView<MidiFunctionBlock> GetDeclaredFunctionBlocks();
        Windows.Foundation.DateTime DeclaredFunctionBlocksLastUpdateTime{ get; };

        IVectorView<MidiGroupTerminalBlock> GetGroupTerminalBlocks();

        MidiEndpointUserSuppliedInfo GetUserSuppliedInfo();

        MidiEndpointTransportSuppliedInfo GetTransportSuppliedInfo();

        String ParentDeviceInstanceId{ get; };          // device instance id of the parent device

        MidiParentDeviceInformation GetParentDeviceInformation();
        Windows.Devices.Enumeration.DeviceInformation GetContainerDeviceInformation();

        Windows.Foundation.Collections.IMapView<String, IInspectable> Properties{ get; };

        IVectorView<Midi1PortNameTableEntry> GetNameTable();

        Midi1PortNamingApproach Midi1PortNamingApproach{ get; };


        Boolean IsMidi1PortCreationEnabled{ get; };
        Boolean IsMuted{ get; };


    }
}