// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"


namespace Windows.Devices.Midi2
{
    namespace Enumeration
    {
        [contractversion(1)]
        apicontract MidiEnumerationApiContract{ };
    }

    namespace Enumeration.Legacy
    {
        [contractversion(1)]
        apicontract MidiEnumerationLegacyApiContract{ };
    }

}
