// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiEndpointDeviceInformation.idl";


namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiParentDeviceInformation", UUID_IMidiParentDeviceInformation)]
    [static_name("Windows.Devices.Midi2.Enumeration.IMidiParentDeviceInformationStatics", UUID_IMidiParentDeviceInformationStatics)]
    runtimeclass MidiParentDeviceInformation : Windows.Foundation.IStringable
    {
        static MidiParentDeviceInformation CreateFromId(String deviceInstanceId);
        static IVectorView<MidiParentDeviceInformation> FindAllForContainer(Guid containerId);

        static IVectorView<String> GetAdditionalPropertiesList();

        String Id { get; };
        String Name{ get; };
        Guid ContainerId{ get; };
        String DeviceInstanceId{ get; };

        String ParentDeviceInstanceId{ get; };

        String RelatedParentDeviceMediaInstanceId{ get; };

        //String ModelName{ get; };
        //String Manufacturer{ get; };

        String DriverInfPath{ get; };           // DEVPKEY_Device_DriverInfPath
        String DriverKey{ get; };               // DEVPKEY_Device_Driver
        String DriverProvider{ get; };          // DEVPKEY_Device_DriverProvider
        String ServiceName{ get; };             // DEVPKEY_Device_Service
        String DriverVersion{ get; };           // DEVPKEY_Device_DriverVersion
        String EnumeratorName{ get; };          // DEVPKEY_Device_EnumeratorName

        UInt16 UsbVendorId{ get; };             // parsed from device instance id
        UInt16 UsbProductId{ get; };            // parsed from device instance id
        String UsbSerialNumber{ get; };         // parsed from device instance id

        Windows.Foundation.Collections.IMapView<String, IInspectable> Properties{ get; };
    }
}