// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "Midi1PortFlowEnum.idl";
import "MidiEndpointNativeDataFormatEnum.idl";


namespace Windows.Devices.Midi2.Enumeration.Legacy
{
    [contract(MidiEnumerationLegacyApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Enumeration.Legacy.IMidiLegacyPortDeviceInformation", UUID_IMidiLegacyPortDeviceInformation )]
    runtimeclass MidiLegacyPortDeviceInformation : Windows.Foundation.IStringable
    {
        static MidiLegacyPortDeviceInformation CreateFromPortDeviceId(String portDeviceId);

        static IVectorView<MidiLegacyPortDeviceInformation> FindAll();
        static IVectorView<MidiLegacyPortDeviceInformation> FindAll(Windows.Devices.Midi2.Enumeration.Midi1PortFlow flow);
        static IVectorView<MidiLegacyPortDeviceInformation> FindAllForEndpoint(String endpointDeviceId);

        static IVectorView<String> GetAdditionalPropertiesList();

        static Guid Midi1SourcePortClassGuid { get; };
        static Guid Midi1DestinationPortClassGuid { get; };

        Windows.Devices.Enumeration.DeviceInformation DeviceInformation{ get; };    // the base WinRT Device Information object for this port

        String PortDeviceId{ get; };                    // device id in our tree (also used directly in WinRT MIDI 1.0)
        String Name{ get; };                            // friendly name (this is the current WinMM port name). Get other names from the parent 

        Guid ContainerId{ get; };                       // container this exists in. It will be the same as the parent endpoint's. Here for convenience.
        String EndpointDeviceId{ get; };                // device id of the owning Windows MIDI Services endpoint

        String DriverDeviceInterfaceId{ get; };         // the device interface id that the WinMM API exposes via DRV_QUERYDEVICEINTERFACE
        Windows.Devices.Midi2.MidiGroup Group{ get; };  // the single group this MIDI 1.0 port is associated with

        Windows.Devices.Midi2.Enumeration.Midi1PortFlow PortFlow{ get; };                 // source (midi input) or destination (midi output)

        UInt32 WinMMPortNumber{ get; };                 // current winmm port number (0..n). This can change if devices are added/removed.

        Windows.Devices.Midi2.Enumeration.MidiEndpointNativeDataFormat NativeDataFormat{ get; };   // the native data format of the port, which is needed to know in order to use the port with WinMM APIs. This is the same as the parent endpoint's native data format. Here for convenience.
     //   Guid TransportId;
     //   String TransportCode;


    }
}
