// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiMessageReceivedEventArgs.idl";
import "IMidiEndpointConnectionSource.idl";


namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiSessionAndConnectionApiContract, 1)]
    [uuid("198d5ef2-313f-41af-9259-a42997e060f0"), version(1.0)]
    interface IMidiEndpointMessageProcessingPlugin
    {
        Guid PluginId { get; };            

        String PluginName;
        IInspectable PluginTag;

        Boolean IsEnabled;

        void Initialize(IMidiEndpointConnectionSource endpointConnection);

        void OnEndpointConnectionOpened();

        void ProcessIncomingMessage(
            MidiMessageReceivedEventArgs args,
            out Boolean skipFurtherListeners,
            out Boolean skipMainMessageReceivedEvent);

        void Cleanup();
    }
}