// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2.ServiceConfig
{
    [contract(MidiServiceConfigApiContract, 1)]
    [uuid("8087b303-0519-31d1-c0de-ff0000000070"), version(1.0)]
    interface IMidiServiceTransportPluginConfig
    {
        Guid TransportId { get; };
        //Boolean IsFromCurrentConfigFile{ get; };

        String GetConfigJson();
    }
}