// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiLoopbackEndpointCreationResult.idl";
import "MidiLoopbackEndpointCreationConfig.idl";
import "MidiLoopbackEndpointRemovalConfig.idl";

import "MidiEndpointDeviceInformation.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Loopback
{
    [contract(MidiEndpointsLoopbackApiContract, 1)]
    static runtimeclass MidiLoopbackEndpointManager
    {
        static Boolean IsTransportAvailable{ get; };

        static Guid TransportId{ get; };

        static MidiLoopbackEndpointCreationResult CreateTransientLoopbackEndpoints(
            MidiLoopbackEndpointCreationConfig creationConfig);

        static Boolean RemoveTransientLoopbackEndpoints(
            MidiLoopbackEndpointRemovalConfig removalConfig);

        static Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpointForId(
            String loopbackEndpointId);

        static Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpoint(
            Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation loopbackEndpoint,
            IIterable<Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation> endpointsToSearch);

        static Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation GetAssociatedLoopbackEndpoint(
            Microsoft.Windows.Devices.Midi2.MidiEndpointDeviceInformation loopbackEndpoint);
    }
}

