// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiGroup.idl";

import "IMidiEndpointMessageProcessingPlugin.idl";
import "IMidiMessageReceivedEventSource.idl";

import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2.ClientPlugins
{
    [contract(MidiClientPluginsApiContract, 1)]
    [interface_name("IMidiGroupEndpointListener", 8087b303-0519-31d1-c0de-dd0000003000)]
    runtimeclass MidiGroupEndpointListener : Microsoft.Windows.Devices.Midi2.IMidiEndpointMessageProcessingPlugin,
                                             Microsoft.Windows.Devices.Midi2.IMidiMessageReceivedEventSource
    {
        MidiGroupEndpointListener();

        IVector<Microsoft.Windows.Devices.Midi2.MidiGroup> IncludedGroups{ get; };
        
        Boolean PreventCallingFurtherListeners;
        Boolean PreventFiringMainMessageReceivedEvent;
    }
}