// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiServiceSessionConnectionInfo.idl";

namespace Microsoft.Windows.Devices.Midi2.Reporting
{
    [contract(MidiReportingApiContract, 1)]
    [version(1)]
    [default_interface]
    runtimeclass MidiServiceSessionInfo
    {
        Guid SessionId{ get; };

        UInt64 ProcessId{ get; };
        String ProcessName{ get; };
        String SessionName{ get; };

        Windows.Foundation.DateTime StartTime{ get; };


        IVectorView<MidiServiceSessionConnectionInfo> Connections{ get; };
    }
}