// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("IMidiEndpointDeviceInformationRemovedEventArgs", 8087b303-0519-31d1-c0de-dd000000c000)]
    runtimeclass MidiEndpointDeviceInformationRemovedEventArgs
    {
        String EndpointDeviceId { get; };

        Windows.Devices.Enumeration.DeviceInformationUpdate DeviceInformationUpdate{ get; };
    }
}

