// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2.Utilities.RuntimeInformation
{
    [contract(MidiRuntimeInformationApiContract, 1)]
    [flags]
    enum MidiRuntimeReleaseTypes
    {
        Unknown =   0x00000000,
        Stable =    0x00000001,
        Preview =   0x00000002,
    };


}
