// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "IMidiServiceTransportPluginConfig.idl";

import "MidiVirtualPatchBaySourceDefinition.idl";
import "MidiVirtualPatchBayDestinationDefinition.idl";
import "MidiVirtualPatchBayRouteDestinationTransform.idl";

namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    // this type is needed for listing existing routes as well as creating/updating routes

    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBayRouteDefinition")]
    runtimeclass MidiVirtualPatchBayRouteDefinition
    {
        MidiVirtualPatchBayRouteDefinition();

        // we generate the id internally
        Guid RouteId{ get; };

        String Name;
        Boolean IsEnabled;

        IVector<MidiVirtualPatchBaySourceDefinition> Sources;
        IVector<MidiVirtualPatchBayDestinationDefinition> Destinations;

        static MidiVirtualPatchBayRouteDefinition CreateFromConfigJson(String jsonSection);
        Windows.Data.Json.JsonObject GetConfigJson();
    }
}
