// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";

import "MidiNetworkHostEndpointCreationResult.idl";
import "MidiNetworkHostEndpointCreationConfig.idl";

import "MidiNetworkHostEndpointRemovalResult.idl";
import "MidiNetworkHostEndpointRemovalConfig.idl";

import "MidiNetworkClientEndpointCreationResult.idl";
import "MidiNetworkClientEndpointCreationConfig.idl";

import "MidiNetworkClientEndpointRemovalResult.idl";
import "MidiNetworkClientEndpointRemovalConfig.idl";

import "MidiNetworkAdvertisedHost.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [static_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkEndpointManagerStatics")]
    static runtimeclass MidiNetworkEndpointManager
    {
        static Boolean IsTransportAvailable{ get; };
        static Guid TransportId{ get; };

        static MidiNetworkHostEndpointCreationResult CreateNetworkHost(
            MidiNetworkHostEndpointCreationConfig creationConfig);

        static MidiNetworkHostEndpointRemovalResult RemoveNetworkHost(
            MidiNetworkHostEndpointRemovalConfig removalConfig);


        static MidiNetworkClientEndpointCreationResult CreateNetworkClient(
            MidiNetworkClientEndpointCreationConfig creationConfig);

        static MidiNetworkClientEndpointRemovalResult RemoveNetworkClient(
            MidiNetworkClientEndpointRemovalConfig removalConfig);

        // list the hosts currently visible to this PC
        static Windows.Foundation.Collections.IVector<MidiNetworkAdvertisedHost> GetAdvertisedHosts();
        static String MidiNetworkUdpDnsServiceType{ get; };
        static String MidiNetworkUdpDnsSdQueryString{ get; };

    }
}
