// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";
import "MidiBasicLoopbackEndpointCreationResultErrorCodeEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.BasicLoopback
{
    [contract(MidiEndpointsBasicLoopbackApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.Endpoints.BasicLoopback.IMidiBasicLoopbackEndpointCreationResult", UUID_IMidiBasicLoopbackEndpointCreationResult)]
    runtimeclass MidiBasicLoopbackEndpointCreationResult
    {
        Boolean Success { get; };

        MidiBasicLoopbackEndpointCreationResultErrorCode ErrorCode{ get; };
        String ErrorInformation{ get; };

        Guid AssociationId{ get; };

        String EndpointDeviceId{ get; };
    };
}