// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiServicePingResponseSummary.idl";

namespace Microsoft.Windows.Devices.Midi2.Diagnostics
{
    static runtimeclass MidiDiagnostics
    {
        static String DiagnosticsLoopbackAEndpointDeviceId{ get; };
        static String DiagnosticsLoopbackBEndpointDeviceId{ get; };

        static MidiServicePingResponseSummary PingService(UInt8 pingCount);
        static MidiServicePingResponseSummary PingService(UInt8 pingCount, UInt32 timeoutMilliseconds);
    }
}









