// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiGroup.idl";
import "MidiMessageTypeEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBaySourceDefinition")]
    runtimeclass MidiVirtualPatchBaySourceDefinition
    {
        MidiVirtualPatchBaySourceDefinition();

        Boolean IsEnabled;

        String EndpointDeviceId;            // TODO: May want to have fuzzy match here

        // message types to include. If empty, all types are included.
        IVector<Microsoft.Windows.Devices.Midi2.MidiMessageType> IncludedMessageTypes{ get; };

        // only for messages with groups. If this is empty, all groups are included.
        IVector<Microsoft.Windows.Devices.Midi2.MidiGroup> IncludedGroups{ get; };
    }
}