// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";


import "MidiGroup.idl";
import "MidiChannel.idl";

import "MidiMessage32.idl";
import "MidiMessage64.idl";
import "MidiMessage96.idl";
import "MidiMessage128.idl";

import "MidiSystemExclusive8StatusEnum.idl";

import "Midi1ChannelVoiceMessageStatusEnum.idl";
import "Midi2ChannelVoiceMessageStatusEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Messages
{
    [contract(MidiMessageUtilitiesApiContract, 1)]
    [version(1)]
    static runtimeclass MidiMessageBuilder
    {
        static Microsoft.Windows.Devices.Midi2.MidiMessage32 BuildUtilityMessage(
            UInt64 timestamp, 
            UInt8 status, 
            UInt32 dataOrReserved);

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 BuildSystemMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 status, 
            UInt8 midi1Byte2, 
            UInt8 midi1Byte3);

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 BuildMidi1ChannelVoiceMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Midi1ChannelVoiceMessageStatus status,
            Microsoft.Windows.Devices.Midi2.MidiChannel channel,
            UInt8 byte3, 
            UInt8 byte4);

        [default_overload]
        static Microsoft.Windows.Devices.Midi2.MidiMessage64 BuildSystemExclusive7Message(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 status,
            UInt8 numberOfBytes, 
            UInt8 dataByte0, 
            UInt8 dataByte1, 
            UInt8 dataByte2, 
            UInt8 dataByte3, 
            UInt8 dataByte4, 
            UInt8 dataByte5);

        static Microsoft.Windows.Devices.Midi2.MidiMessage64 BuildMidi2ChannelVoiceMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Midi2ChannelVoiceMessageStatus status,
            Microsoft.Windows.Devices.Midi2.MidiChannel channel,
            UInt16 index,
            UInt32 data);

        static Microsoft.Windows.Devices.Midi2.MidiMessage128 BuildSystemExclusive8Message(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            MidiSystemExclusive8Status status,
            UInt8 numberOfValidDataBytesThisMessage, 
            UInt8 streamId, 
            UInt8 dataByte00, 
            UInt8 dataByte01, 
            UInt8 dataByte02, 
            UInt8 dataByte03, 
            UInt8 dataByte04, 
            UInt8 dataByte05, 
            UInt8 dataByte06, 
            UInt8 dataByte07, 
            UInt8 dataByte08, 
            UInt8 dataByte09, 
            UInt8 dataByte10, 
            UInt8 dataByte11, 
            UInt8 dataByte12);

        static Microsoft.Windows.Devices.Midi2.MidiMessage128 BuildMixedDataSetChunkHeaderMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 mdsId,
            UInt16 numberValidDataBytesInThisChunk, 
            UInt16 numberChunksInMixedDataSet, 
            UInt16 numberOfThisChunk, 
            UInt16 manufacturerId, 
            UInt16 deviceId, 
            UInt16 subId1, 
            UInt16 subId2);

        static Microsoft.Windows.Devices.Midi2.MidiMessage128 BuildMixedDataSetChunkDataMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 mdsId,
            UInt8 dataByte00, 
            UInt8 dataByte01, 
            UInt8 dataByte02, 
            UInt8 dataByte03, 
            UInt8 dataByte04, 
            UInt8 dataByte05, 
            UInt8 dataByte06, 
            UInt8 dataByte07, 
            UInt8 dataByte08, 
            UInt8 dataByte09, 
            UInt8 dataByte10, 
            UInt8 dataByte11, 
            UInt8 dataByte12, 
            UInt8 dataByte13);

        static Microsoft.Windows.Devices.Midi2.MidiMessage128 BuildFlexDataMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 form,
            UInt8 address, 
            Microsoft.Windows.Devices.Midi2.MidiChannel channel,
            UInt8 statusBank, 
            UInt8 status, 
            UInt32 word1Data, 
            UInt32 word2Data, 
            UInt32 word3Data);

        static Microsoft.Windows.Devices.Midi2.MidiMessage128 BuildStreamMessage(
            UInt64 timestamp,
            UInt8 form,
            UInt16 status, 
            UInt16 word0RemainingData, 
            UInt32 word1Data, 
            UInt32 word2Data, 
            UInt32 word3Data);
    };
}