// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiEndpointDeviceInformation.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    [default_interface]
    runtimeclass MidiEndpointDeviceInformationAddedEventArgs
    {
        MidiEndpointDeviceInformation AddedDevice{ get; };
    }
}

