// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiVirtualPatchBayRouteCreationResult.idl";
import "MidiVirtualPatchBayRouteUpdateResult.idl";

import "MidiVirtualPatchBayRouteCreationConfig.idl";
import "MidiVirtualPatchBayRouteRemovalConfig.idl";
import "MidiVirtualPatchBayRouteUpdateConfig.idl";

import "MidiVirtualPatchBayRouteDefinition.idl";

namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    [default_interface]
    static runtimeclass MidiVirtualPatchBayManager
    {
        static Boolean IsTransportAvailable{ get; };
        static Guid AbstractionId{ get; };

        static IVectorView<MidiVirtualPatchBayRouteDefinition> GetRoutes();
        static MidiVirtualPatchBayRouteDefinition GetRoute(Guid routeId);


        static MidiVirtualPatchBayRouteCreationResult CreateRoute(
            MidiVirtualPatchBayRouteCreationConfig creationConfig);

        static MidiVirtualPatchBayRouteUpdateResult UpdateRoute(
            MidiVirtualPatchBayRouteUpdateConfig updateConfig);

        static Boolean RemoveRoute(
            MidiVirtualPatchBayRouteRemovalConfig removalConfig);

    }
}

