// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiCoreApiContract,1)]
    [interface_name("IMidiChannel", 8087b303-0519-31d1-c0de-dd0000005000)]
    [static_name("IMidiChannelStatics", 8087b303-0519-31d1-c0de-ee0000005000)]
    runtimeclass MidiChannel : Windows.Foundation.IStringable
    {
        MidiChannel();
        MidiChannel(UInt8 index);

        static String ShortLabel{ get; };
        static String ShortLabelPlural{ get; };
        static String LongLabel{ get; };
        static String LongLabelPlural{ get; };

        UInt8 Index;
        UInt8 DisplayValue{ get; };

        static Boolean IsValidIndex(UInt8 index);
    }
}