// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiGroupTerminalBlockDirectionEnum.idl";
import "MidiGroupTerminalBlockProtocolEnum.idl";
import "MidiGroup.idl";

import "MidiFunctionBlock.idl";
import "MidiGroup.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("IMidiGroupTerminalBlock", 8087b303-0519-31d1-c0de-dd0000010000)]
    [static_name("IMidiGroupTerminalBlockStatics", 8087b303-0519-31d1-c0de-ee0000010000)]
    runtimeclass MidiGroupTerminalBlock : Windows.Foundation.IStringable
    {
        static String ShortLabel{ get; };
        static String ShortLabelPlural{ get; };
        static String LongLabel{ get; };
        static String LongLabelPlural{ get; };

        UInt8 Number{ get; };

        String Name{ get; };

        MidiGroupTerminalBlockDirection Direction { get; };
        MidiGroupTerminalBlockProtocol Protocol { get; };

        MidiGroup FirstGroup{ get; };
        UInt8 GroupCount{ get; };

        Boolean IncludesGroup(MidiGroup group);

        UInt16 MaxDeviceInputBandwidthIn4KBitsPerSecondUnits{ get; };
        UInt16 MaxDeviceOutputBandwidthIn4KBitsPerSecondUnits{ get; };

        UInt32 CalculatedMaxDeviceInputBandwidthBitsPerSecond{ get; };
        UInt32 CalculatedMaxDeviceOutputBandwidthBitsPerSecond{ get; };

        MidiFunctionBlock AsEquivalentFunctionBlock();
    }
}