// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";
import "Midi1PortFlowEnum.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    // this needs to be kept in sync with Midi1PortNameEntry in service

    [contract(MidiEnumerationApiContract, 1)]
    struct Midi1PortNameTableEntry
    {
        UInt8 GroupIndex;               // can't use MidiGroup here unless we're going to make a runtimeclass of this
        Midi1PortFlow Flow;

        String CustomName;              // user-supplied name. Blank if not provided.
        String LegacyCompatibleName;    // WinMM MIDI 1.0 compatible port name
        String NewStyleName;            // New-style port name
    };
}