// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [contract(MidiEndpointsNetworkApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkAdvertisedHost")]
    runtimeclass MidiNetworkAdvertisedHost
    {
        // from Windows props
        String DeviceId {get; };
        String DeviceName{ get; };
         
        // from SRV record 
        String FullName{ get; };
        String ServiceInstanceName{ get; };
        String ServiceType{ get; };
        String HostName{ get; };
        UInt16 Port{ get; };
        String Domain{ get; };

        // from TXT record
        String UmpEndpointName{ get; };
        String ProductInstanceId{ get; };

        IVectorView<String> IPAddresses{ get; };
    };
}

