// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "IMidiServiceTransportPluginConfig.idl";

import "MidiLoopbackEndpointDefinition.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Loopback
{
    [default_interface]
    runtimeclass MidiLoopbackEndpointCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiLoopbackEndpointCreationConfig();
        MidiLoopbackEndpointCreationConfig(
            Guid associationId, 
            MidiLoopbackEndpointDefinition endpointDefinitionA, 
            MidiLoopbackEndpointDefinition endpointDefinitionB
        );


        Guid AssociationId;

        MidiLoopbackEndpointDefinition EndpointDefinitionA;
        MidiLoopbackEndpointDefinition EndpointDefinitionB;
    }
}

