// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiGroup.idl";
import "MidiChannel.idl";
import "MidiMessageTypeEnum.idl";
import "MidiServiceConfigEndpointMatchCriteria.idl";

import "Midi1ChannelVoiceMessageStatusEnum.idl";
import "Midi2ChannelVoiceMessageStatusEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    // "source" is currently limited to MIDI Sources (a MIDI input)

    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBaySourceDefinition")]
    runtimeclass MidiVirtualPatchBaySourceDefinition
    {
        MidiVirtualPatchBaySourceDefinition();

        MidiVirtualPatchBaySourceDefinition(
            Microsoft.Windows.Devices.Midi2.ServiceConfig.MidiServiceConfigEndpointMatchCriteria matchCriteria,
            IVector<Microsoft.Windows.Devices.Midi2.MidiMessageType> includedMessageTypes,
            IVector<Microsoft.Windows.Devices.Midi2.MidiGroup> includedGroups,
            IVector<Microsoft.Windows.Devices.Midi2.MidiChannel> includedChannels
        );

        Boolean IsEnabled;

        Microsoft.Windows.Devices.Midi2.ServiceConfig.MidiServiceConfigEndpointMatchCriteria EndpointMatchCriteria;

        // These criteria all work together. If you want separate criteria for different
        // groups or channels, or message types, you need to create separate routes
        IVector<Microsoft.Windows.Devices.Midi2.MidiMessageType> IncludedMessageTypes{ get; };
        IVector<Microsoft.Windows.Devices.Midi2.MidiGroup> IncludedGroups{ get; };
        IVector<Microsoft.Windows.Devices.Midi2.MidiChannel> IncludedChannels{ get; };

        // if a MIDI 2 channel voice message
        IVector<Microsoft.Windows.Devices.Midi2.Messages.Midi2ChannelVoiceMessageStatus> IncludedMidi2ChannelVoiceMessageStatuses{ get; };

        // if a MIDI 1 channel voice message
        IVector<Microsoft.Windows.Devices.Midi2.Messages.Midi1ChannelVoiceMessageStatus> IncludedMidi1ChannelVoiceMessageStatuses{ get; };


        static MidiVirtualPatchBaySourceDefinition CreateFromConfigJson(String jsonSection);
        Windows.Data.Json.JsonObject GetConfigJson();

    }
}