// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiSystemTimerSettings.idl";

import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiCoreApiContract,1)]
    [static_name("Microsoft.Windows.Devices.Midi2.IMidiClockStatics", 8087b303-0519-31d1-c0de-ee0000006000)]
    static runtimeclass MidiClock
    {
        static UInt64 Now{ get; };

        static UInt64 TimestampConstantSendImmediately{ get; };

        static UInt64 TimestampFrequency{ get; };

        static Double ConvertTimestampTicksToNanoseconds(UInt64 timestampValue);
        static Double ConvertTimestampTicksToMicroseconds(UInt64 timestampValue);
        static Double ConvertTimestampTicksToMilliseconds(UInt64 timestampValue);
        static Double ConvertTimestampTicksToSeconds(UInt64 timestampValue);

        static UInt64 OffsetTimestampByTicks(UInt64 timestampValue, Int64 offsetTicks);

        static UInt64 OffsetTimestampByMicroseconds(UInt64 timestampValue, Int64 offsetMicroseconds);
        static UInt64 OffsetTimestampByMilliseconds(UInt64 timestampValue, Int64 offsetMilliseconds);
        static UInt64 OffsetTimestampBySeconds(UInt64 timestampValue, Int64 offsetSeconds);



        static MidiSystemTimerSettings GetCurrentSystemTimerInfo();

        static Boolean BeginLowLatencySystemTimerPeriod();
        static Boolean EndLowLatencySystemTimerPeriod();
}
}

