// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";

import "MidiRuntimeRelease.idl";
import "MidiRuntimeReleaseTypesEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Utilities.Update
{
    [contract(MidiRuntimeUpdateUtilityApiContract, 1)]
    [static_name("Microsoft.Windows.Devices.Midi2.Utilities.Update.IMidiRuntimeUpdateUtilityStatics", 8087b303-0519-31d1-c0de-ee0001000000)]
    static runtimeclass MidiRuntimeUpdateUtility
    {
        static IVectorView<Microsoft.Windows.Devices.Midi2.Utilities.Update.MidiRuntimeRelease> GetAllAvailableReleases();

        static MidiRuntimeRelease GetHighestAvailableRelease();

        static MidiRuntimeRelease GetHighestAvailableRelease(
            Microsoft.Windows.Devices.Midi2.Utilities.RuntimeInformation.MidiRuntimeReleaseTypes inScopeReleaseTypes);

        static MidiRuntimeRelease GetHighestAvailableRelease(
            UInt16 specificMajorVersion, 
            Microsoft.Windows.Devices.Midi2.Utilities.RuntimeInformation.MidiRuntimeReleaseTypes inScopeReleaseTypes);

        static Boolean IsReleaseNewerThanInstalled(
            Microsoft.Windows.Devices.Midi2.Utilities.Update.MidiRuntimeRelease release);

    }

}