// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiEndpointConnection.idl";
import "MidiClockDestination.idl";

namespace Microsoft.Windows.Devices.Midi2.Utilities.Sequencing
{
    [experimental]
    runtimeclass MidiClockGenerator
    {
        MidiClockGenerator(IVector<MidiClockDestination> destinations, Double bpm, UInt16 pulsesPerQuarterNote);

        void UpdateRunningClock(Double bpm);
        void UpdateRunningClock(Double bpm, UInt16 pulsesPerQuarterNote);

        IVectorView<MidiClockDestination> Destinations{ get; };

        Boolean Start(Boolean sendMidiStartMessage);   // start the clock
        Boolean Stop(Boolean sendMidiStopMessage);     // stop the clock
    }
}