// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


namespace Microsoft.Windows.Devices.Midi2.Reporting
{
    struct MidiServiceMessageProcessingPluginInfo
    {
        Guid Id;

        String Name;
        String Description;
        String Author;

        String SmallImagePath;

        String Version;

        Boolean SupportsMultipleInstancesPerDevice;

        Boolean IsSystemManaged;
        Boolean IsClientConfigurable;

        //String ClientConfigurationAssemblyName;

    };
}