// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";


import "MidiProtocolEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [contract(MidiEndpointsVirtualApiContract, 1)]
    [interface_name("IMidiStreamConfigRequestReceivedEventArgs", 8087b303-0519-31d1-c0de-dd00000e0000)]
    runtimeclass MidiStreamConfigRequestReceivedEventArgs
    {
        UInt64 Timestamp{ get; };

        Microsoft.Windows.Devices.Midi2.MidiProtocol PreferredMidiProtocol{ get; };

        Boolean RequestEndpointTransmitJitterReductionTimestamps{ get; };
        Boolean RequestEndpointReceiveJitterReductionTimestamps{ get; };
    }
}