// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2.Messages
{
    [contract(MidiMessageUtilitiesApiContract, 1)]
    [version(1)]
    enum Midi1ChannelVoiceMessageStatus
    {
        NoteOff =           0x8,
        NoteOn =            0x9,
        PolyPressure =      0xA,
        ControlChange =     0xB,
        ProgramChange =     0xC,
        ChannelPressure =   0xD,
        PitchBend =         0xE,
    };
}