// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";
import "MidiNetworkClientMatchCriteria.idl";
import "IMidiServiceTransportPluginConfig.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkClientEndpointCreationConfig")]
    runtimeclass MidiNetworkClientEndpointCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiNetworkClientEndpointCreationConfig();

		Guid ClientId;				// GUID we use in the config file and for subsequent edits/deletes
		Boolean CreateMidi1Ports;	// todo: this will also need a table of port names
		Boolean AutoReconnect;		// true if we reconnect after any disconnects. Otherwise, we connect only once.

		// sets the criteria we look for when creating the endpoint. mDNS is generally preferred.
		MidiNetworkClientMatchCriteria MatchCriteria{ get; set; };

		// TODO: authentication information from vault


		//TODO: do we need to specify protocol here?


    }
}

