// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";


import "MidiProtocolEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [contract(MidiEndpointsVirtualApiContract, 1)]
    [version(1)]
    struct MidiStreamConfigRequestedSettings
    {
        UInt8 SpecificationVersionMajor;
        UInt8 SpecificationVersionMinor;

        Microsoft.Windows.Devices.Midi2.MidiProtocol PreferredMidiProtocol;

        Boolean RequestEndpointTransmitJitterReductionTimestamps;
        Boolean RequestEndpointReceiveJitterReductionTimestamps;
   };
}