// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiServicePingResponse.idl";

namespace Microsoft.Windows.Devices.Midi2.Diagnostics
{
    [contract(MidiDiagnosticsApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.Diagnostics.IMidiServicePingResponseSummary", 8087b303-0519-31d1-c0de-dd0000500000)]
    runtimeclass MidiServicePingResponseSummary
    {
        Boolean Success { get; };
        String FailureReason{ get; };

        UInt64 TotalPingRoundTripMidiClock { get; };
        UInt64 AveragePingRoundTripMidiClock{ get; };

        IVectorView<MidiServicePingResponse> Responses { get; };
    }
}
