// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "MidiServiceTransportPluginInfo.idl";
import "MidiServiceMessageProcessingPluginInfo.idl";
import "MidiServiceSessionInfo.idl";

namespace Microsoft.Windows.Devices.Midi2.Reporting
{
    [contract(MidiReportingApiContract, 1)]
    [static_name("IMidiReportingStatics", 8087b303-0519-31d1-c0de-ee0000b00000)]
    static runtimeclass MidiReporting
    {
        static IVector<MidiServiceTransportPluginInfo> GetInstalledTransportPlugins();
        //static IVector<MidiServiceMessageProcessingPluginInfo> GetInstalledMessageProcessingPlugins();

        static IVector<MidiServiceSessionInfo> GetActiveSessions();
    }
}

