// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiSessionAndConnectionApiContract, 1)]
    [flags]
    enum MidiSendMessageResults
    {
        Succeeded =                         0x80000000,
        Failed =                            0x10000000,

        BufferFull =                        0x00010000,
        EndpointConnectionClosedOrInvalid = 0x00040000,

        InvalidMessageTypeForWordCount =    0x00100000,
        InvalidMessageOther =               0x00200000,
        DataIndexOutOfRange =               0x00400000,
        TimestampOutOfRange =               0x00800000,

        MessageListPartiallyProcessed =     0x00F00000,

        /*Other = 0x01000000,*/
    };
}