// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


namespace Microsoft.Windows.Devices.Midi2.CapabilityInquiry
{
    [default_interface]
    runtimeclass MidiUniqueId : Windows.Foundation.IStringable
    {
        MidiUniqueId();
        MidiUniqueId(UInt32 combined28BitValue);
        MidiUniqueId(UInt8 sevenBitByte1, UInt8 sevenBitByte2, UInt8 sevenBitByte3, UInt8 sevenBitByte4);

        static String ShortLabel{ get; };
        static String ShortLabelPlural{ get; };
        static String LongLabel{ get; };
        static String LongLabelPlural{ get; };

        static MidiUniqueId CreateBroadcast();
        static MidiUniqueId CreateRandom();

        UInt8 Byte1;
        UInt8 Byte2;
        UInt8 Byte3;
        UInt8 Byte4;

        UInt32 AsCombined28BitValue{ get; };

        Boolean IsBroadcast{ get; };
        Boolean IsReserved{ get; };
    };



}