// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";


import "IMidiServiceTransportPluginConfig.idl";
import "MidiDeclaredEndpointInfo.idl";
import "MidiDeclaredDeviceIdentity.idl";
import "MidiEndpointUserSuppliedInfo.idl";

import "MidiDeclaredDeviceIdentity.idl";
import "MidiDeclaredEndpointInfo.idl";
import "MidiEndpointUserSuppliedInfo.idl";
import "MidiFunctionBlock.idl";



namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [contract(MidiEndpointsVirtualApiContract, 1)]
    [version(1)]
    [default_interface]
    runtimeclass MidiVirtualDeviceCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiVirtualDeviceCreationConfig(
            String name,
            String description,
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo
        );

        MidiVirtualDeviceCreationConfig(
            String name,
            String description, 
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity declaredDeviceIdentity
        );

        MidiVirtualDeviceCreationConfig(
            String name,
            String description,
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity declaredDeviceIdentity,
            Microsoft.Windows.Devices.Midi2.MidiEndpointUserSuppliedInfo userSuppliedInfo
        );


        // maps to transport-supplied values. We don't make the rest of the
        // MidiEndpointTransportSuppliedInfo settings available because some, like 
        // transport id and data format, need to be set service-side. Also, all 
        // app-to-app MIDI devices are multi-client
        String Name;
        String Description;
        String Manufacturer;

        Boolean CreateOnlyUmpEndpoints;

        Guid AssociationId{ get; };

        Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity DeclaredDeviceIdentity;
        Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo DeclaredEndpointInfo;
        Microsoft.Windows.Devices.Midi2.MidiEndpointUserSuppliedInfo UserSuppliedInfo;

        IVector<Microsoft.Windows.Devices.Midi2.MidiFunctionBlock> FunctionBlocks{ get; };
    }
}