// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";
import "MidiProtocolEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [contract(MidiEndpointsVirtualApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.Endpoints.Virtual.IMidiStreamConfigRequestReceivedEventArgs", UUID_IMidiStreamConfigRequestReceivedEventArgs)]
    runtimeclass MidiStreamConfigRequestReceivedEventArgs
    {
        UInt64 Timestamp{ get; };

        Microsoft.Windows.Devices.Midi2.MidiProtocol PreferredMidiProtocol{ get; };

        Boolean RequestEndpointTransmitJitterReductionTimestamps{ get; };
        Boolean RequestEndpointReceiveJitterReductionTimestamps{ get; };
    }
}