// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    [static_name("Microsoft.Windows.Devices.Midi2.IMidiEndpointDeviceIdHelperStatics", 8087b303-0519-31d1-c0de-ee0000009000)]
    static runtimeclass MidiEndpointDeviceIdHelper
    {
        // returns a short version of the midisrv-enumerated id
        // from:    \\?\swd#midisrv#midiu_ksa_9447707571394916916#{e7cce071-3c03-423f-88d3-f1045d02552b}
        // to       ksa_9447707571394916916
        static String GetShortIdFromFullId(String fullEndpointDeviceId);

        // returns the full id for a midisrv-enumerated shortId
        static String GetFullIdFromShortId(String shortEndpointDeviceId);

        // returns true if this is a midisrv-enumerated id, even if not present
        static Boolean IsWindowsMidiServicesEndpointDeviceId(String fullEndpointDeviceId);

        // puts the full id in the correct case. Wrapper around the internal function which
        // does that for all endpoint ids we expose. Useful when doing comparisons.
        static String NormalizeFullId(String fullEndpointDeviceId);
    }
}