// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "IMidiServiceTransportPluginConfig.idl";
import "MidiNetworkAuthenticationTypeEnum.idl";


namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [default_interface]
    [experimental]
    runtimeclass MidiNetworkHostEndpointCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiNetworkHostEndpointCreationConfig();

        Guid Identifier;

        String Name;
        String HostInstanceName;
        String ProductInstanceId;

        Boolean UmpOnly;

        Boolean UseAutomaticPortAllocation;
        String ManuallyAssignedPort;
        
        Boolean Advertise;

        // todo: network adapter/interface

        // todo: connection rules
        IVector<String> AllowedClientConnectionList{ get; };



        MidiNetworkAuthenticationType AuthenticationType;

        // todo: password key etc.


    }
}