// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";

import "MidiNetworkHostCreationResult.idl";
import "MidiNetworkHostCreationConfig.idl";

import "MidiNetworkHostRemovalResult.idl";
import "MidiNetworkHostRemovalConfig.idl";

import "MidiNetworkClientEndpointCreationResult.idl";
import "MidiNetworkClientEndpointCreationConfig.idl";

import "MidiNetworkClientEndpointRemovalResult.idl";
import "MidiNetworkClientEndpointRemovalConfig.idl";

import "MidiNetworkAdvertisedHost.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [static_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkEndpointManagerStatics")]
    static runtimeclass MidiNetworkEndpointManager
    {
        static Boolean IsTransportAvailable{ get; };
        static Guid TransportId{ get; };

        static MidiNetworkHostCreationResult CreateNetworkHost(
            MidiNetworkHostCreationConfig creationConfig);

        static MidiNetworkHostRemovalResult RemoveNetworkHost(
            MidiNetworkHostRemovalConfig removalConfig);


        static MidiNetworkClientEndpointCreationResult CreateNetworkClient(
            MidiNetworkClientEndpointCreationConfig creationConfig);

        static MidiNetworkClientEndpointRemovalResult RemoveNetworkClient(
            MidiNetworkClientEndpointRemovalConfig removalConfig);


        // list the hosts currently visible to this PC
        static Windows.Foundation.Collections.IVector<MidiNetworkAdvertisedHost> GetAdvertisedHosts();

        static String MidiNetworkUdpDnsServiceType{ get; };
        static String MidiNetworkUdpDnsSdQueryString{ get; };
        static String MidiNetworkUdpDnsDomain { get; };
        static Windows.Devices.Enumeration.DeviceInformationKind MidiNetworkUdpDnsSdDeviceInformationKind{ get; };

        static IVector<String> MidiNetworkUdpDnsSdQueryAdditionalProperties { get; };
    }
}
