// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [contract(MidiEndpointsNetworkApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkAdvertisedHostRemovedEventArgs")]
    runtimeclass MidiNetworkAdvertisedHostRemovedEventArgs
    {
        String HostId { get; };

        Windows.Devices.Enumeration.DeviceInformationUpdate DeviceInformationUpdate{ get; };
    }
}

