// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiVirtualPatchBayRouteDefinition.idl";
import "IMidiServiceTransportPluginConfig.idl";


namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBayRouteUpdateConfig")]
    runtimeclass MidiVirtualPatchBayRouteUpdateConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiVirtualPatchBayRouteUpdateConfig();

        MidiVirtualPatchBayRouteUpdateConfig(
            Guid routeId
        );

        Guid RouteId;
    }
}