// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


import "IMidiServiceTransportPluginConfig.idl";

import "MidiLoopbackEndpointDefinition.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Loopback
{
    [contract(MidiEndpointsLoopbackApiContract, 1)]
    [interface_name("IMidiLoopbackEndpointCreationConfig", 8087b303-0519-31d1-c0de-dd00000b0000)]
    runtimeclass MidiLoopbackEndpointCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiLoopbackEndpointCreationConfig();
        MidiLoopbackEndpointCreationConfig(
            Guid associationId, 
            MidiLoopbackEndpointDefinition endpointDefinitionA, 
            MidiLoopbackEndpointDefinition endpointDefinitionB
        );


        Guid AssociationId;

        MidiLoopbackEndpointDefinition EndpointDefinitionA;
        MidiLoopbackEndpointDefinition EndpointDefinitionB;
    }
}

