// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    static runtimeclass MidiEndpointDeviceIdHelper
    {
        // returns a short version of the midisrv-enumerated id
        static String GetShortIdFromFullId(String fullEndpointDeviceId);

        // returns the full id for a midisrv-enumerated shortId
        static String GetFullIdFromShortId(String shortEndpointDeviceId);

        // returns just the trailing GUID from the id
        static Guid GetInterfaceIdFromFullId(String fullEndpointDeviceId);

        // returns true if this is a midisrv-enumerated id, even if not present
        static Boolean IsWindowsMidiServicesDeviceId(String fullEndpointDeviceId);
    }
}