// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiApiContracts.idl";


namespace Microsoft.Windows.Devices.Midi2.Utilities.Update
{
    [contract(MidiRuntimeUpdateUtilityApiContract, 1)]
    [flags]
    enum MidiRuntimeUpdateReleaseTypes
    {
        Stable =    0x00000001,
        Preview =   0x00000002,
    };


}
