// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiFunctionBlockDirectionEnum.idl";
import "MidiFunctionBlockUIHintEnum.idl";
import "MidiFunctionBlockRepresentsMidi10ConnectionEnum.idl";
import "MidiGroup.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [contract(MidiEnumerationApiContract, 1)]
    [interface_name("Microsoft.Windows.Devices.Midi2.IMidiFunctionBlock", UUID_IMidiFunctionBlock)]
    [static_name("Microsoft.Windows.Devices.Midi2.IMidiFunctionBlockStatics", UUID_IMidiFunctionBlockStatics)]
    runtimeclass MidiFunctionBlock : Windows.Foundation.IStringable
    {
        MidiFunctionBlock();

        static String ShortLabel{ get; };
        static String ShortLabelPlural{ get; };
        static String LongLabel{ get; };
        static String LongLabelPlural{ get; };

        Boolean IsReadOnly { get; };

        UInt8 Number;
        String Name;

        Boolean IsActive;

        MidiFunctionBlockDirection Direction;
        MidiFunctionBlockUIHint UIHint;

        MidiFunctionBlockRepresentsMidi10Connection RepresentsMidi10Connection;

        MidiGroup FirstGroup;
        //UInt8 FirstGroupIndex;
        UInt8 GroupCount;

        Boolean IncludesGroup(MidiGroup group);

        UInt8 MidiCIMessageVersionFormat;

        UInt8 MaxSystemExclusive8Streams;
    }
}