// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiApiContracts.idl";
import "MidiRuntimeVersion.idl";
import "MidiRuntimeArchitectureEnum.idl";
import "MidiRuntimeReleaseTypesEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.Utilities.RuntimeInformation
{
    [contract(MidiRuntimeInformationApiContract, 1)]
    [static_name("Microsoft.Windows.Devices.Midi2.Utilities.RuntimeInformation.IMidiRuntimeInformationStatics", 8087b303-0519-31d1-c0de-ee0001500000)]
    static runtimeclass MidiRuntimeInformation
    {
        static MidiRuntimeVersion GetInstalledVersion();

        static MidiRuntimeArchitecture GetInstalledArchitecture();

        static MidiRuntimeReleaseTypes GetInstalledReleaseType();
    }
}