// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiNetworkHostCreationResult.idl";
import "MidiNetworkHostCreationConfig.idl";
import "MidiNetworkHostRemovalResult.idl";
import "MidiNetworkHostRemovalConfig.idl";
import "MidiNetworkHostUpdateResult.idl";


import "MidiNetworkClientConnectionResult.idl";
import "MidiNetworkClientConnectConfig.idl";
import "MidiNetworkClientDisconnectConfig.idl";

import "MidiNetworkAdvertisedHost.idl";

import "MidiNetworkConfiguredHost.idl";
import "MidiNetworkConfiguredClient.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [contract(MidiEndpointsNetworkApiContract, 1)]
    [static_name("Microsoft.Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkTransportManagerStatics")]
    static runtimeclass MidiNetworkTransportManager
    {
        static Boolean IsTransportAvailable{ get; };
        static Guid TransportId{ get; };


        static Windows.Foundation.IAsyncOperation<MidiNetworkHostCreationResult> CreateNetworkHostAsync(
            MidiNetworkHostCreationConfig creationConfig);

        static Windows.Foundation.IAsyncOperation<MidiNetworkHostRemovalResult> RemoveNetworkHostAsync(
            MidiNetworkHostRemovalConfig removalConfig);

        // keeps the host entry in memory, but closes all connections
        // stops advertising, and refuses any new connections
        static Windows.Foundation.IAsyncOperation<MidiNetworkHostUpdateResult> StopNetworkHostAsync(String hostId);

        static Windows.Foundation.IAsyncOperation<MidiNetworkHostUpdateResult> StartNetworkHostAsync(String hostId);


        // Sends new client info to the service
        static Windows.Foundation.IAsyncOperation<MidiNetworkClientConnectionResult> ConnectNetworkClientAsync(
            MidiNetworkClientConnectConfig connectConfig);

        //// Closes the connection and removes the entry in the service
        static Windows.Foundation.IAsyncOperation<MidiNetworkClientConnectionResult> DisconnectNetworkClientAsync(
            MidiNetworkClientDisconnectConfig disconnectConfig);


        // returns info about what is configured inside the service
        static Windows.Foundation.Collections.IVectorView<MidiNetworkConfiguredHost> GetConfiguredHosts();
        static Windows.Foundation.Collections.IVectorView<MidiNetworkConfiguredClient> GetConfiguredClients();


        // list the external hosts currently visible to this PC
        static Windows.Foundation.Collections.IVectorView<MidiNetworkAdvertisedHost> GetAdvertisedHosts();


        static String MidiNetworkUdpDnsServiceType{ get; };
        static String MidiNetworkUdpDnsSdQueryString{ get; };
        static String MidiNetworkUdpDnsDomain { get; };
        static Windows.Devices.Enumeration.DeviceInformationKind MidiNetworkUdpDnsSdDeviceInformationKind{ get; };

        static IVector<String> MidiNetworkUdpDnsSdQueryAdditionalProperties { get; };

    }
}
