// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "midi_sdk_idl_defs.h"

import "MidiApiContracts.idl";

import "MidiGroup.idl";
import "MidiChannel.idl";
import "MidiMessageTypeEnum.idl";
import "MidiServiceConfigEndpointMatchCriteria.idl";

import "Midi1ChannelVoiceMessageStatusEnum.idl";
import "Midi2ChannelVoiceMessageStatusEnum.idl";

namespace Microsoft.Windows.Devices.Midi2.VirtualPatchBay
{
    // "source" is currently limited to MIDI Sources (a MIDI input)

    [experimental]
    [interface_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBaySourceDefinition")]
    [static_name("Microsoft.Windows.Devices.Midi2.VirtualPatchBay.IMidiVirtualPatchBaySourceDefinitionStatics")]
    runtimeclass MidiVirtualPatchBaySourceDefinition
    {
        MidiVirtualPatchBaySourceDefinition();

        MidiVirtualPatchBaySourceDefinition(
            Microsoft.Windows.Devices.Midi2.ServiceConfig.MidiServiceConfigEndpointMatchCriteria matchCriteria
        );

        Boolean IsEnabled;

        Microsoft.Windows.Devices.Midi2.ServiceConfig.MidiServiceConfigEndpointMatchCriteria EndpointMatchCriteria;


        // TODO: Chain of source transform/filter definitions


        static MidiVirtualPatchBaySourceDefinition CreateFromConfigJson(String jsonSection);
        Windows.Data.Json.JsonObject GetConfigJson();

    }
}