// Current level: Prototype

// TODO consider making this a built-in stream type
// THis is a TEMPORARY interface and is not based on Gary's MIDI buffer work

namespace Windows.Devices.Midi2
{
	[default_interface]
	runtimeclass MidiMessageReadBuffer
	{
		MidiMessageReadBuffer();

		Boolean HasData{ get; };
		UInt32 CountMidiWords{ get; };

		UInt32 GetNextWord();

		// TODO

	}
}