// Current level: Prototype

import "MidiMessageReadBuffer.idl";
import "MidiMessageWriteBuffer.idl";


// TODO: Break these out into IInputMidiUmpEndpoint, IOutputMidiUmpEndpoint 
// and then have Input, Output, and Bidirectional implementation classes
namespace Windows.Devices.Midi2
{
	[default_interface]
	runtimeclass MidiUmpEndpoint
	{
		MidiUmpEndpoint();


		Windows.Devices.Midi2.MidiMessageReadBuffer IncomingMessages { get; };
		Windows.Devices.Midi2.MidiMessageWriteBuffer OutcomingMessages { get; };

	}
}
