// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

namespace Windows.Devices.Midi2.ClientPlugins
{
    [contract(MidiClientPluginsApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.ClientPlugins.IMidiGroupEndpointListener", UUID_IMidiGroupEndpointListener)]
    runtimeclass MidiGroupEndpointListener : Windows.Devices.Midi2.IMidiEndpointMessageProcessingPlugin,
                                             Windows.Devices.Midi2.IMidiMessageReceivedEventSource
    {
        MidiGroupEndpointListener();

        IVector<Windows.Devices.Midi2.MidiGroup> IncludedGroups{ get; };
        
        Boolean PreventCallingFurtherListeners;
        Boolean PreventFiringMainMessageReceivedEvent;
    }
}