// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiLoopbackEndpointDefinition.idl";

namespace Microsoft.Devices.Midi2.Endpoints.Loopback
{
    [default_interface]
    runtimeclass MidiLoopbackEndpointCreationConfiguration : Microsoft.Devices.Midi2.IMidiServiceTransportPluginConfiguration
    {
        MidiLoopbackEndpointCreationConfiguration();
        MidiLoopbackEndpointCreationConfiguration(
            Guid associationId, 
            MidiLoopbackEndpointDefinition endpointDefinitionA, 
            MidiLoopbackEndpointDefinition endpointDefinitionB
        );


        Guid AssociationId;

        MidiLoopbackEndpointDefinition EndpointDefinitionA;
        MidiLoopbackEndpointDefinition EndpointDefinitionB;
    }
}

