// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

namespace Windows.Devices.Midi2.Utilities.Messages
{
    [contract(MidiMessageUtilityApiContract,1)]
    [static_name("IMidiUniversalSystemExclusive7MessageBuilderStatics", UUID_IMidiUniversalSystemExclusive7MessageBuilderStatics)]
    static runtimeclass MidiUniversalSystemExclusive7MessageBuilder
    {
        static Windows.Devices.Midi2.MidiMessage64 BuildIdentityRequest(
            UInt64 timestamp,
            Windows.Devices.Midi2.MidiUniversalSystemExclusiveChannel systemExclusiveChannel
            );

        static Windows.Foundation.Collections.IVector<Windows.Devices.Midi2.MidiMessage64> BuildIdentityRequestReply(
            UInt64 timestamp,
            Windows.Devices.Midi2.Enumeration.MidiDeclaredDeviceIdentity identity
            );

        static Windows.Devices.Midi2.MidiMessage64 BuildWait(
            UInt64 timestamp
            );

        static Windows.Devices.Midi2.MidiMessage64 BuildCancel(
            UInt64 timestamp
            );

        static Windows.Devices.Midi2.MidiMessage64 BuildNAK(
            UInt64 timestamp
            );

        static Windows.Devices.Midi2.MidiMessage64 BuildACK(
            UInt64 timestamp
            );

    }
}
