//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Midi.Settings.Strings.en_us {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Midi.Settings.Strings.en_us.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management, settings, and utility app for Windows MIDI Services. Features in the prototype do not necessarily represent committed features..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Settings DEVELOPER PREVIEW.
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string AppSessionName {
            get {
                return ResourceManager.GetString("AppSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows MIDI Services Dashboard.
        /// </summary>
        internal static string HomePage_Description_Text {
            get {
                return ResourceManager.GetString("HomePage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a list of all MIDI devices as seen by the legacy MIDI 1.0 APIs, and the apps which use them..
        /// </summary>
        internal static string Midi1DevicesPage_Description_Text {
            get {
                return ResourceManager.GetString("Midi1DevicesPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page lists the full set of transport plugins installed and recognized by Windows MIDI Services on this PC. For information on the endpoint devices enumerated by these transport plugins, see the Devices page..
        /// </summary>
        internal static string PluginsTransportPage_Description_Text {
            get {
                return ResourceManager.GetString("PluginsTransportPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management, settings, and utility app for Windows MIDI Services. Features in the prototype do not necessarily represent committed features..
        /// </summary>
        internal static string Settings_AboutDescription_Header {
            get {
                return ResourceManager.GetString("Settings_AboutDescription.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non-developers, or anyone wishing to discuss Windows MIDI Services, we host a Discord server..
        /// </summary>
        internal static string Settings_AboutDescriptionMidiDiscordLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiDiscordLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows MIDI Services is an open source project hosted on GitHub. We encourage bug reports and pull requests..
        /// </summary>
        internal static string Settings_AboutDescriptionMidiRepoLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiRepoLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important..
        /// </summary>
        internal static string Settings_AboutDescriptionPrivacyLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionPrivacyLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI® and the MIDI® Logo are registered trademarks of the MIDI® Association. Used with permission. Microsoft is an active MIDI® Association corporate member. AMEI is the Japanese partner of the MIDI® Association and the author, in partnership with AmeNote, of the USB MIDI 2.0 driver on Windows..
        /// </summary>
        internal static string Settings_AboutMidiDescription_Header {
            get {
                return ResourceManager.GetString("Settings_AboutMidiDescription.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        internal static string Settings_AppThemeExpander_Description {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string Settings_AppThemeExpander_Header {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show developer options for MIDI.
        /// </summary>
        internal static string Settings_ShowDeveloperOptions_Header {
            get {
                return ResourceManager.GetString("Settings_ShowDeveloperOptions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system setting.
        /// </summary>
        internal static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 Microsoft. All rights reserved..
        /// </summary>
        internal static string SettingsPage_AboutCard_Description {
            get {
                return ResourceManager.GetString("SettingsPage_AboutCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Settings.
        /// </summary>
        internal static string SettingsPage_AboutCard_Header {
            get {
                return ResourceManager.GetString("SettingsPage_AboutCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMEI.
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.amei.or.jp/.
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally off. Non-developer MIDI users do not need to use developer options as they may adversely impact the stability, capability, or performance of MIDI on your computer. Developer options require that the PC be placed into Developer Mode in Windows settings..
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show developer options for MIDI.
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Mode is not enabled. Enable developer mode in Windows Settings..
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsDisabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsDisabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Mode is currently enabled on this PC. To turn it off, use Windows Settings..
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsEnabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsEnabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Settings &quot;For developers&quot; page.
        /// </summary>
        internal static string SettingsPage_DeveloperModeLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows MIDI Services on Discord.
        /// </summary>
        internal static string SettingsPage_DiscordLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://aka.ms/mididiscord.
        /// </summary>
        internal static string SettingsPage_DiscordLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIDI Association.
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://midi.org.
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows MIDI Services on Github.
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://aka.ms/midirepo.
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Privacy Statement.
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://privacy.microsoft.com/privacystatement.
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        internal static string SettingsPage_SendFeedbackButton_Content {
            get {
                return ResourceManager.GetString("SettingsPage_SendFeedbackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        internal static string Shell_ContentGrid_Content {
            get {
                return ResourceManager.GetString("Shell_ContentGrid.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Shell_Devices_Content {
            get {
                return ResourceManager.GetString("Shell_Devices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Developers.
        /// </summary>
        internal static string Shell_ForDevelopers_Content {
            get {
                return ResourceManager.GetString("Shell_ForDevelopers.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Shell_Home_Content {
            get {
                return ResourceManager.GetString("Shell_Home.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Shell_ManagementNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sessions.
        /// </summary>
        internal static string Shell_ManagementSessions_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementSessions.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Shell_Midi1ApiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_Midi1ApiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy MIDI 1.0 API.
        /// </summary>
        internal static string Shell_Midi1ApiNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_Midi1ApiNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows MIDI Services.
        /// </summary>
        internal static string Shell_MidiServicesNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MidiServicesNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Shell_MoreNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MoreNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Shell_PluginsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &amp; Filtering.
        /// </summary>
        internal static string Shell_PluginsProcessing_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsProcessing.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transports.
        /// </summary>
        internal static string Shell_PluginsTransport_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsTransport.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        internal static string Shell_Routes_Content {
            get {
                return ResourceManager.GetString("Shell_Routes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setups.
        /// </summary>
        internal static string Shell_Setup_Content {
            get {
                return ResourceManager.GetString("Shell_Setup.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices &amp; Setups.
        /// </summary>
        internal static string Shell_SetupNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_SetupNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string Shell_SystemInfo_Content {
            get {
                return ResourceManager.GetString("Shell_SystemInfo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Shell_ToolsConsole_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsConsole.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Monitor.
        /// </summary>
        internal static string Shell_ToolsMonitor_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsMonitor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Shell_ToolsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysEx Transfer.
        /// </summary>
        internal static string Shell_ToolsSysEx_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsSysEx.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Test.
        /// </summary>
        internal static string Shell_ToolsTest_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsTest.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        internal static string Shell_Troubleshooting_Content {
            get {
                return ResourceManager.GetString("Shell_Troubleshooting.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a setting.
        /// </summary>
        internal static string ShellPage_SettingsSearchBox_PlaceholderText {
            get {
                return ResourceManager.GetString("ShellPage_SettingsSearchBox.PlaceholderText", resourceCulture);
            }
        }
    }
}
