//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Midi.Settings.Strings.en_us {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Midi.Settings.Strings.en_us.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Management, settings, and utility app for Windows MIDI Services. 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI and Musician Settings PREVIEW 的本地化字符串。
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Settings 的本地化字符串。
        /// </summary>
        internal static string AppSessionName {
            get {
                return ResourceManager.GetString("AppSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        internal static string Button_Monitor_Content {
            get {
                return ResourceManager.GetString("Button_Monitor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panic 的本地化字符串。
        /// </summary>
        internal static string Button_Panic_Content {
            get {
                return ResourceManager.GetString("Button_Panic.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart Now 的本地化字符串。
        /// </summary>
        internal static string Button_Reboot_Content {
            get {
                return ResourceManager.GetString("Button_Reboot.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart MIDI Service 的本地化字符串。
        /// </summary>
        internal static string Button_RestartMidiService_Content {
            get {
                return ResourceManager.GetString("Button_RestartMidiService.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a USB MIDI 1.0 device to use the new fast UMP MIDI 2.0 driver (requires Administrator account) 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_AssignMidi1DeviceToNewDriver_Text {
            get {
                return ResourceManager.GetString("CommonTasks_AssignMidi1DeviceToNewDriver.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture MIDI Diagnostics information to a text file for use with technical support 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_CaptureMidiDiag_Text {
            get {
                return ResourceManager.GetString("CommonTasks_CaptureMidiDiag.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a loopback endpoint so two or more applications can communicate using MIDI messages 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_CreateLoopbackEndpoints_Text {
            get {
                return ResourceManager.GetString("CommonTasks_CreateLoopbackEndpoints.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Windows MIDI Services Console 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_OpenConsole_Text {
            get {
                return ResourceManager.GetString("CommonTasks_OpenConsole.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send a file of System Exclusive data (patches, firmware, etc.) to an endpoint 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SendSysExFile_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SendSysExFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set MIDI Service to auto-start at boot (requires Administrator account) 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SetServiceAutoStart_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SetServiceAutoStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up Network MIDI 2.0 to enable MIDI messages to be sent to other devices on your local network. 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SetUpNetworkMidi2_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SetUpNetworkMidi2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Endpoints 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_Endpoints_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_Endpoints.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_Other_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_Other.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service and Drivers 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_ServiceAndDrivers_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_ServiceAndDrivers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configured Protocol 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredProtocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredProtocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configured to receive Jitter Reduction Timestamps 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredReceiveJR_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredReceiveJR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configured to send Jitter Reduction Timestamps 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredSendJR_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredSendJR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Description_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Flow_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Flow.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapped Group 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_MappedGroup_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_MappedGroup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Name_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SerialNumber_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SerialNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports MIDI 1.0 Protocol 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SupportsMidi1Protocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SupportsMidi1Protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports MIDI 2.0 Protocol 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SupportsMidi2Protocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SupportsMidi2Protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport Code 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_TransportCode_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_TransportCode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport Id 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_TransportId_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_TransportId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinMM Port Number 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_WinMMPortNumber_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_WinMMPortNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinRT Port Id 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_WinRTPortId_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_WinRTPortId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Loopback Endpoints 的本地化字符串。
        /// </summary>
        internal static string CreateLoopbackEndpointsWindowTitle {
            get {
                return ResourceManager.GetString("CreateLoopbackEndpointsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default basic MIDI 1.0 loopback endpoint for use by applications. 的本地化字符串。
        /// </summary>
        internal static string DefaultBasicLoopbackDescription {
            get {
                return ResourceManager.GetString("DefaultBasicLoopbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Basic App Loopback 的本地化字符串。
        /// </summary>
        internal static string DefaultBasicLoopbackName {
            get {
                return ResourceManager.GetString("DefaultBasicLoopbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default loopback endpoint for use by applications. This is the A-side of the loopback pair. 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackADescription {
            get {
                return ResourceManager.GetString("DefaultLoopbackADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default App Loopback (A) 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackAName {
            get {
                return ResourceManager.GetString("DefaultLoopbackAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default loopback endpoint for use by applications. This is the B-side of the loopback pair. 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackBDescription {
            get {
                return ResourceManager.GetString("DefaultLoopbackBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default App Loopback (B) 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackBName {
            get {
                return ResourceManager.GetString("DefaultLoopbackBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalize 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Button_Customize_Content {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Button_Customize.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Endpoint Device Id: 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_EndpointDeviceIdLabel_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_EndpointDeviceIdLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For a MIDI 2.0 device, function blocks indicate the active groups and their valid directions. 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_FunctionBlocksExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_FunctionBlocksExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Blocks 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_FunctionBlocksExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_FunctionBlocksExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For USB MIDI 2.0 devices, Group Terminal Blocks are the fallback when no Function Blocks are available. They indicate active groups and their direction. For MIDI 1.0 devices, we generate Group Terminal Blocks for each MIDI jack (formerly &quot;Port&quot;). 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_GroupTerminalBlocksExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_GroupTerminalBlocksExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Terminal Blocks 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_GroupTerminalBlocksExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_GroupTerminalBlocksExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination/Output Ports 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_HeaderDestinationOutputPorts_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_HeaderDestinationOutputPorts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source/Input Ports 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_HeaderSourceInputPorts_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_HeaderSourceInputPorts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ManufacturerLabel_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ManufacturerLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIDI 2.0 protocol includes device discovery. The information here is obtained from that source. 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Midi2ProtocolExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Midi2ProtocolExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 In-protocol Discovered Information 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Midi2ProtocolExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Midi2ProtocolExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native Data Format 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_NativeDataFormat_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_NativeDataFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices may have more than one MIDI Endpoint. This is the parent device for this endpoint. 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ParentDeviceExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ParentDeviceExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent Device 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ParentDeviceExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ParentDeviceExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some settings for devices, like the name and description, can be customized by you. Applications may use this information when displaying device information. 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_PersonalizationExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_PersonalizationExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Instance Id 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ProductInstanceId_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ProductInstanceId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Associated MIDI 1.0 API Ports 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Section_AssociatedMidi1Ports_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Section_AssociatedMidi1Ports.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_SerialNumber_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_SerialNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change image 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Tooltip_ChangeImage_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Tooltip_ChangeImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename endpoint, update description and other properties 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Tooltip_Customize_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Tooltip_Customize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport Code 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportCode_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportCode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIDI Service transport plugin obtains device information from the underlying transport (USB, Network, BLE, etc.) 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport-Supplied Information 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB VID/PID 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_UsbVidPid_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_UsbVidPid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This MIDI device does not report a serial number or unique identifier. As a result, the customizations may not stay applied if you change how the device is connected to this PC (different USB port, or hub, for example). If you have more than one of these devices, and connect them at different times, Windows may not know which one to apply the personalization to. 的本地化字符串。
        /// </summary>
        internal static string EndpointPersonalizationUniqueIdInfoBar_Message {
            get {
                return ResourceManager.GetString("EndpointPersonalizationUniqueIdInfoBar.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization may not be permanent 的本地化字符串。
        /// </summary>
        internal static string EndpointPersonalizationUniqueIdInfoBar_Title {
            get {
                return ResourceManager.GetString("EndpointPersonalizationUniqueIdInfoBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to initialize Windows MIDI Services Runtime. An exception was thrown:  的本地化字符串。
        /// </summary>
        internal static string Error_ExceptionThrownDuringSdkInitialization {
            get {
                return ResourceManager.GetString("Error_ExceptionThrownDuringSdkInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Windows MIDI Services feature does not appear to be enabled on this PC. Enablement for supported versions of Windows will come through Windows Update.
        ///
        ///If the feature has been previously activated, it&apos;s possible a driver uninstaller or registry reordering tool has broken Windows MIDI Services. 
        ///
        ///If that is the case, open an Administrator command prompt, type midifixreg, and then walk through the steps. When it has completed, reboot your PC. 的本地化字符串。
        /// </summary>
        internal static string Error_MidiServicesFeatureNotEnabled {
            get {
                return ResourceManager.GetString("Error_MidiServicesFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIDI Settings app could not automatically close and restart. Please close the application and then relaunch it. 的本地化字符串。
        /// </summary>
        internal static string Error_SettingsAppCouldNotAutomaticallyRestart {
            get {
                return ResourceManager.GetString("Error_SettingsAppCouldNotAutomaticallyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Starting MIDI Settings App 的本地化字符串。
        /// </summary>
        internal static string Error_StartupMessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_StartupMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to initialize the Windows MIDI Services Runtime. Is it installed? 的本地化字符串。
        /// </summary>
        internal static string Error_UnableToInitializeMidiRuntime {
            get {
                return ResourceManager.GetString("Error_UnableToInitializeMidiRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to start the MIDI Service. If this persists, please terminate the midisrv.exe process or reboot your PC. 的本地化字符串。
        /// </summary>
        internal static string Error_UnableToStartMidiService {
            get {
                return ResourceManager.GetString("Error_UnableToStartMidiService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services is not Enabled 的本地化字符串。
        /// </summary>
        internal static string Error_WindowsMIDIServicesNotEnabledMessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_WindowsMIDIServicesNotEnabledMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Many MIDI customizations are stored in a portable configuration file. These include customized endpoint properties like the name, definitions for persistent loopback endpoints, and your Network MIDI host and client reconnections. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_ConfigFileDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_ConfigFileDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create default configuration file if it doesn&apos;t already exist. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_CreateDefaultConfigFileSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_CreateDefaultConfigFileSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create default loopback endpoints if they don&apos;t already exist. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_CreateDefaultLoopbacksSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_CreateDefaultLoopbacksSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some applications and utilities, especially those on the web, rely on having a known loopback endpoint available. This requires a configuration file to store the loopback endpoint information. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_DefaultLoopbacksDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_DefaultLoopbacksDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By default, the MIDI Service is set to start only when the first MIDI connection is made by an app. This ensures Windows startup time is not impacted for those who do not use MIDI. But the first time a MIDI connection is made, it can take several seconds. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_MidiServiceStartupDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_MidiServiceStartupDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you use MIDI frequently, we recommend changing the service to start automatically with Windows, so you never have to wait when making a connection. This requires Administrator permissions to set. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_MidiServiceStartupDescription2_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_MidiServiceStartupDescription2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apps using the older MIDI 1.0 API (WinMM) used port names as the identifier in many apps and files. By default, we use names that are compatible with those older names. However, if you want better port names by default, select the option below. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_PortNamesDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_PortNamesDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set MIDI Service to auto-start with Windows 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_SetServiceAutoStartSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_SetServiceAutoStartSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up Windows MIDI Services 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_Title_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use new-style MIDI 1 port names. 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_UseNewPortNamesSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_UseNewPortNamesSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save to Registry 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_CommitDiscoveryTimeoutButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_CommitDiscoveryTimeoutButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These settings are for advanced users or development and prototyping purposes only. Changing the settings here may cause unexpected or undesirable behavior in applications and devices using Windows MIDI Services. These settings may be reset with a Windows upgrade. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Description_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normally on. By default, the MIDI Service performs MIDI 2.0 discovery and protocol negotiation for any natively UMP device. If you are testing a device which breaks when those messages are sent, disable the process here. Requires a MIDI Service restart. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Discovery_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_Discovery.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovery and Protocol Negotiation 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Discovery_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_Discovery.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovery Timeout (milliseconds) 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryTimeoutSlider_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryTimeoutSlider.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service-based MIDI 2.0 discovery and protocol negotiation is currently disabled. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryToggle_OffContent {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryToggle.OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service-based MIDI 2.0 discovery and protocol negotiation is currently enabled. This is the recommended choice. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryToggle_OnContent {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryToggle.OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In order to install previews of the service or service components/plugins, you must first take ownership of the registry entries which are used for component registration. If you do not do this first, the install will appear to work, but the components used will not be the ones you expect.
        ///
        ///This step requires Administrator rights, and must be repeated after any new Windows upgrade (not update, but full OS upgrade). 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableDeveloperInstallationExpander_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableDeveloperInstallationExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Installation of Developer Releases 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableDeveloperInstallationExpander_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableDeveloperInstallationExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normally off. MMCSS threads are a limited resource in Windows, and are often used for audio processing threads in DAW applications. If this feature is enabled, Windows MIDI Services will use MMCSS threads for handling incoming messages. This reduces the number of MMCSS threads available to the client process, and may cause applications to fail to work properly. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcss_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcss.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable MMCSS for the Incoming Message Queue 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcss_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcss.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services will not use MMCSS threads in the client process. This is the recommended choice. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcssToggle_OffContent {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcssToggle.OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services will use MMCSS threads in the client process. This may cause some applications to malfunction. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcssToggle_OnContent {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcssToggle.OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install Developer / Preview Releases 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_InstallPreviewSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_InstallPreviewSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 Features 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Midi2FeaturesSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_Midi2FeaturesSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prepare for Preview/Developer Install 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_PrepareForDeveloperInstallButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_PrepareForDeveloperInstallButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes made require that you restart your PC before they can take effect. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_RebootRequired_Message {
            get {
                return ResourceManager.GetString("ForDevelopers_RebootRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Related Support 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_RelatedSupportSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_RelatedSupportSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace wdmaud2.drv with Developer Version 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_ReplaceWdmaud2DrvButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_ReplaceWdmaud2DrvButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Windows MIDI Service (midisrv.exe) must be restarted for changes to take effect. 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_ServiceRestartRequired_Message {
            get {
                return ResourceManager.GetString("ForDevelopers_ServiceRestartRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Settings 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_SystemSettingsSectionHeader {
            get {
                return ResourceManager.GetString("ForDevelopers_SystemSettingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The option chosen here will be the default approach for naming MIDI 1.0 API ports using classic MIDI 1.0 in-box or vendor drivers. The default naming approach can be overridden on a per-device basis if desired.
        ///
        ///If you have many existing projects using your MIDI 1.0 devices and need to keep naming compatibility so the devices are automatically discovered by your DAW or other app, we recommend using the classic port names. Otherwise, the new style names are usually more informative.
        ///
        ///This change will req [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultNamingExpander_Description {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultNamingExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default MIDI 1.0 Port Naming 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultNamingExpander_Header {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultNamingExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use names compatible with previous versions of Windows MIDI APIs, and preserve compatibility with saved MIDI projects in applications. 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultUseClassicMidi1PortNames_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultUseClassicMidi1PortNames.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use newer-style port names preferred by MIDI device manufacturers. (For USB devices, these names use the iJack name when available). 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultUseNewStyleMidi1PortNames_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultUseNewStyleMidi1PortNames.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set MIDI Service to Auto-Start 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_SetMidiServiceToAutoStartButton_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_SetMidiServiceToAutoStartButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the Windows MIDI Service (midisrv.exe) to auto-start with Windows, to reduce delays when apps call MIDI APIs for the first time after a reboot. 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_SetMidiServiceToAutoStartCard_Header {
            get {
                return ResourceManager.GetString("GlobalSettings_SetMidiServiceToAutoStartCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services Dashboard 的本地化字符串。
        /// </summary>
        internal static string HomePage_Description_Text {
            get {
                return ResourceManager.GetString("HomePage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 and 2.0 Specifications at the MIDI Association 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_MidiSpecifications_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_MidiSpecifications.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://midi.org/specs 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_MidiSpecifications_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_MidiSpecifications.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI and ASIO Discord Server 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDiscord_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDiscord.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/mididiscord 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDiscord_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDiscord.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services Documentation 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDocumentation_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDocumentation.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midi 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDocumentation_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDocumentation.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services GitHub Repo 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesGitHub_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesGitHub.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midirepo 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesGitHub_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesGitHub.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app needs to restart to apply the language change. Restart now? 的本地化字符串。
        /// </summary>
        internal static string Message_RestartAppForLanguageChange {
            get {
                return ResourceManager.GetString("Message_RestartAppForLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIDI Settings app will now restart. 的本地化字符串。
        /// </summary>
        internal static string Message_SettingsAppWillNowRestart {
            get {
                return ResourceManager.GetString("Message_SettingsAppWillNowRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Below is a list of all MIDI devices as seen by the legacy MIDI 1.0 APIs, and the apps which use them. 的本地化字符串。
        /// </summary>
        internal static string Midi1DevicesPage_Description_Text {
            get {
                return ResourceManager.GetString("Midi1DevicesPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Classic API Compatible 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseClassicAPICompatible {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseClassicAPICompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Global Default 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseGlobalDefault {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseGlobalDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use New-Style 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseNewStyle {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseNewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This page lists the full set of transport plugins installed and recognized by Windows MIDI Services on this PC. For information on the endpoint devices enumerated by these transport plugins, see the Devices page. 的本地化字符串。
        /// </summary>
        internal static string PluginsTransportPage_Description_Text {
            get {
                return ResourceManager.GetString("PluginsTransportPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For anyone wishing to discuss Windows MIDI Services, we host a Discord server. 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionMidiDiscordLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiDiscordLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services is an open source project hosted on GitHub. We encourage bug reports and pull requests. 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionMidiRepoLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiRepoLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your privacy is important. 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionPrivacyLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionPrivacyLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI® and the MIDI® Logo are registered trademarks of the MIDI® Association. Used with permission. Microsoft is an active MIDI® Association corporate member. AMEI is the Japanese partner of the MIDI® Association and the author, in partnership with AmeNote, of the USB MIDI 2.0 driver on Windows. 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutMidiDescription_Header {
            get {
                return ResourceManager.GetString("Settings_AboutMidiDescription.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select which app theme to display 的本地化字符串。
        /// </summary>
        internal static string Settings_AppThemeExpander_Description {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App theme 的本地化字符串。
        /// </summary>
        internal static string Settings_AppThemeExpander_Header {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 (简体) 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_ChineseSimplified_Content {
            get {
                return ResourceManager.GetString("Settings_Language_ChineseSimplified.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select your preferred language. Requires restarting the app. 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (United States) 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_English_Content {
            get {
                return ResourceManager.GetString("Settings_Language_English.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_Header {
            get {
                return ResourceManager.GetString("Settings_Language.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use system default 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_SystemDefault_Content {
            get {
                return ResourceManager.GetString("Settings_Language_SystemDefault.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization 的本地化字符串。
        /// </summary>
        internal static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show developer options for MIDI 的本地化字符串。
        /// </summary>
        internal static string Settings_ShowDeveloperOptions_Header {
            get {
                return ResourceManager.GetString("Settings_ShowDeveloperOptions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use system setting 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 © 2025 Microsoft. All rights reserved. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AboutCard_Description {
            get {
                return ResourceManager.GetString("SettingsPage_AboutCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AMEI 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.amei.or.jp/ 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically check for new releases of the MIDI SDK Runtime and Tools when starting the MIDI Settings app.  的本地化字符串。
        /// </summary>
        internal static string SettingsPage_CheckForUpdatesExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_CheckForUpdatesExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for MIDI SDK Runtime Updates 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_CheckForUpdatesExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_CheckForUpdatesExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer options are generally intended for developers, and those working with developers to test pre-release components. Non-developer MIDI users do not need to use developer options as they may adversely impact the stability, capability, or performance of MIDI on your computer. Developer options require that the PC be placed into Developer Mode in Windows settings. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer options for MIDI 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer Mode is not enabled. Enable developer mode in Windows Settings if you want to be able to install in-development and unsigned third-party service plugins. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsDisabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsDisabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer Mode is currently enabled on this PC, enabling you to install in-development and third-party unsigned service plugins. To turn it off, use Windows Settings. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsEnabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsEnabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Windows Settings &quot;For developers&quot; page 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services on Discord 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DiscordLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/mididiscord 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DiscordLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MIDI Association 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://midi.org 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services on Github 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midirepo 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Privacy Statement 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://privacy.microsoft.com/privacystatement 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable preview versions of the SDK runtime, including unstable features which may have bugs. Recommended only for technical users or developers. Once enabled, this can only be changed by uninstalling the SDK Runtime and Tools, removing the settings configuration file, and then reinstalling the SDK Runtime and Tools. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SdkChannelExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_SdkChannelExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Preview MIDI SDK Runtime and Tools Channel 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SdkChannelExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_SdkChannelExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send feedback 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SendFeedbackButton_Content {
            get {
                return ResourceManager.GetString("SettingsPage_SendFeedbackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable preview tools like the System Exclusive message sender. These tools are not yet stable and may have bugs or incomplete functionality. Requires restarting this app to see the changes. 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_ShowPreviewToolsExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_ShowPreviewToolsExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Preview Tools 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_ShowPreviewToolsExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_ShowPreviewToolsExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced USB Settings 的本地化字符串。
        /// </summary>
        internal static string Shell_AdvancedUsbSettings_Text {
            get {
                return ResourceManager.GetString("Shell_AdvancedUsbSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Devices and Endpoints 的本地化字符串。
        /// </summary>
        internal static string Shell_AllMidiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_AllMidiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configurations 的本地化字符串。
        /// </summary>
        internal static string Shell_Configurations_Content {
            get {
                return ResourceManager.GetString("Shell_Configurations.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport Configuration 的本地化字符串。
        /// </summary>
        internal static string Shell_ConfigureTransportsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ConfigureTransportsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentGrid 的本地化字符串。
        /// </summary>
        internal static string Shell_ContentGrid_Content {
            get {
                return ResourceManager.GetString("Shell_ContentGrid.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsAll_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsAll.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Device Apps 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsApp_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsApp.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 Loopback Endpoints 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsBasicLoop_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsBasicLoop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bluetooth MIDI 1.0 (Preview) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsBle10_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsBle10.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnostic 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsDiagnostic_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsDiagnostic.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 UMP Drivers (USB) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsKS_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsKS.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 Drivers (USB, etc.) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsKsa_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsKsa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 Loopback Endpoints 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsLoop_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsLoop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network MIDI 2.0 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsNet2Udp_Text {
            get {
                return ResourceManager.GetString("Shell_EndpointsNet2Udp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developers 的本地化字符串。
        /// </summary>
        internal static string Shell_ForDevelopers_Content {
            get {
                return ResourceManager.GetString("Shell_ForDevelopers.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global MIDI Settings 的本地化字符串。
        /// </summary>
        internal static string Shell_GlobalMidiSettings_Text {
            get {
                return ResourceManager.GetString("Shell_GlobalMidiSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Shell_Home_Content {
            get {
                return ResourceManager.GetString("Shell_Home.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Live Performance Mode 的本地化字符串。
        /// </summary>
        internal static string Shell_LivePerformanceMode_Text {
            get {
                return ResourceManager.GetString("Shell_LivePerformanceMode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        internal static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Management 的本地化字符串。
        /// </summary>
        internal static string Shell_ManagementNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Sessions 的本地化字符串。
        /// </summary>
        internal static string Shell_ManagementSessions_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementSessions.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 API Ports 的本地化字符串。
        /// </summary>
        internal static string Shell_Midi1ApiNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_Midi1ApiNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Setup 的本地化字符串。
        /// </summary>
        internal static string Shell_MidiNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MidiNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services UMP Endpoints 的本地化字符串。
        /// </summary>
        internal static string Shell_MidiServicesNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MidiServicesNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        internal static string Shell_MoreNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MoreNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing &amp; Filtering 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsProcessing_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsProcessing.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transports 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsTransport_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsTransport.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routing 的本地化字符串。
        /// </summary>
        internal static string Shell_Routes_Content {
            get {
                return ResourceManager.GetString("Shell_Routes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices &amp; Configurations 的本地化字符串。
        /// </summary>
        internal static string Shell_SetupNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_SetupNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Information 的本地化字符串。
        /// </summary>
        internal static string Shell_SystemInfo_Content {
            get {
                return ResourceManager.GetString("Shell_SystemInfo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Console 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsConsole_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsConsole.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traffic Monitor 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsMonitor_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsMonitor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysEx Transfer 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsSysEx_Text {
            get {
                return ResourceManager.GetString("Shell_ToolsSysEx.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Test 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsTest_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsTest.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Troubleshooting 的本地化字符串。
        /// </summary>
        internal static string Shell_Troubleshooting_Text {
            get {
                return ResourceManager.GetString("Shell_Troubleshooting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimizations for Musicians 的本地化字符串。
        /// </summary>
        internal static string Shell_WindowsSettings_Text {
            get {
                return ResourceManager.GetString("Shell_WindowsSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinMM MIDI 1.0 Ports 的本地化字符串。
        /// </summary>
        internal static string Shell_WinMMMidi1ApiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_WinMMMidi1ApiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinRT MIDI 1.0 Ports 的本地化字符串。
        /// </summary>
        internal static string Shell_WinRTMidi1ApiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_WinRTMidi1ApiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        internal static string ShellPage_AdministratorIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_AdministratorIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer Mode Enabled 的本地化字符串。
        /// </summary>
        internal static string ShellPage_DeveloperModeIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_DeveloperModeIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No MIDI Service 的本地化字符串。
        /// </summary>
        internal static string ShellPage_ServiceUnavailableIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_ServiceUnavailableIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find a setting 的本地化字符串。
        /// </summary>
        internal static string ShellPage_SettingsSearchBox_PlaceholderText {
            get {
                return ResourceManager.GetString("ShellPage_SettingsSearchBox.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send a System Exclusive (SysEx) binary 7-bit file (a typical MIDI 1.0 SysEx File) to an endpoint of your choice. Older devices or devices with very small data buffers may work better if you increase the transfer delay by 10-50 milliseconds. This is especially true when sending large patch banks or firmware upgrades over SysEx. 的本地化字符串。
        /// </summary>
        internal static string ToolsSysExPageDescription_Text {
            get {
                return ResourceManager.GetString("ToolsSysExPageDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can exclude specific trusted processes and file locations from Windows Defender scanning. This will significantly speed up reading/writing in those locations, but you must be careful to only put trusted content and plugins there. 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude DAW Process from Defender Scanning 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludeDawProcessButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludeDawProcessButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude DAW Projects Folder 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludeDawProjectsFolderButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludeDawProjectsFolderButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude Plugin Data Folders 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludePluginDataFoldersButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludePluginDataFoldersButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defender Settings 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When working with low-latency audio, setting the Windows power mode to Best Performance can help increase processor speed and reduce glitching. 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Mode 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Windows Settings 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_LaunchButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard_LaunchButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Spotlight 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_DesktopSpotlightCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_DesktopSpotlightCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game DVR 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_GameDvrCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_GameDvrCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeoLocation 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_GeoLocationCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_GeoLocationCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock Screen Tips 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_LockscreenTipsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_LockscreenTipsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_NewsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_NewsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solitaire and Casual Games 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_SolitaireAndGamesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_SolitaireAndGamesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommended Apps in Start 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StartMenuRecommendedAppsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StartMenuRecommendedAppsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Search in Start 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StartMenuWebSearchCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StartMenuWebSearchCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sticky Keys 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StickyKeysCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StickyKeysCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WeatherCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WeatherCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Widgets 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WidgetsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WidgetsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Suggestions 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WindowsSuggestionsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WindowsSuggestionsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xbox App 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_XboxCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_XboxCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-installed Windows features are great for many users, but may sometimes interfere with the creative process. You may easily remove or disable them here. Once uninstalled, they cannot be reinstalled. 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeaturesCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeaturesCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Installed Windows Features 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeaturesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeaturesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These features can be easily turned on or off, but are located here for convenience. 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableRecoverableFeaturesCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableRecoverableFeaturesCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configurable Windows Features 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableRecoverableFeaturesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableRecoverableFeaturesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Although staying up to date is important for security, features, and bug fixes, you may pause Windows updates for a duration of time while working on a project.  的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Updates 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Updates for X Days 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_PauseUpdatesButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard_PauseUpdatesButton.Content", resourceCulture);
            }
        }
    }
}
