// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "MidiUmpMessageTypeEnum.idl";
import "MidiUmpWithTimestamp.idl";

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass DummyTestClass
    {
        DummyTestClass();

        static MidiUmpMessageType GetSomeStaticValue();

        UInt32 SomeProperty{ get; set; };

        UInt32 SomeReadOnlyProperty{ get; };


        void LoadDummyUmps(UInt32 count);

        IVector<MidiUmpWithTimestamp> Umps{ get; };

    }
}