// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessageTypeEnum.idl";
import "MidiUmpWithTimestamp.idl";
import "MidiUmpWithTimestampList.idl";


// TODO: Consider thread synchronization for this class. Right now, assumes single-threaded access

namespace Microsoft.Devices.Midi2
{
    // WinRT doesn't let you return null values so we need to consider the
    // the circumstances where the caller didn't check for the end but
    // kept reading, or the caller is multi-threaded and another thread
    // drained the queue while they were looping
    enum MidiMessageReaderNoMoreDataBehavior
    {
        ThrowException = 0,
        WaitAndBlockCallingThread
    };

    [default_interface]
    runtimeclass MidiMessageReader // not IClosable because this needs to keep the lifetime of the EndpointConnection
    {
        //MidiMessageReader();

        MidiMessageReaderNoMoreDataBehavior NoMoreDataBehavior{ get; set; };

        // EOF for MIDI messages.
        Boolean EndOfMessages{ get; };

        // look at the timestamp in the buffer. This is always the first 64 bits at the read pointer
        UInt64 PeekNextTimestamp();

        // look at the next message's type without moving the read pointer (skips over the timestamp to do this)
        MidiMessageType PeekNextMessageType();

        // look at the next message without moving the read pointer
        MidiUmpWithTimestamp PeekNextMessage();
        
        // copies all pending messages into a List
        //IVector<UmpWithTimestamp> ReadToEnd();
        MidiUmpWithTimestampList ReadToEnd();           // All IVector<T> were replaced with strongly typed list classes to better support Delphi apps

        // reads a single message
        MidiUmpWithTimestamp ReadNextMessage();

        // TODO: Consider a method to read next messages into a pre-allocated app buffer
        // This would require a COM interface because WinRT doesn't do pointers.


    }
}