// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// The various list implementations are here because some languages (like Delphi/Pascal)
// have no automatic projection support, and can't reasonably handle any class with
// templates / generics.
// The IDL is a placeholder for now
// Ref: https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/collections

// TODO: This needs to have in here, or a separate COM interface, some reasonable way
// to convert to/from std::vector. Normally the IVector projection would do that for you
// for C++


namespace Microsoft.Devices.Midi2
{
    [default_interface]
    unsealed runtimeclass MidiListBase
    {
        
    }
}