// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// TODO: Consider changing to a struct

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiChannel
    {
        MidiChannel();

        UInt8 Index{ get; };                 // 0-15, the number used in the UMPs
        UInt8 NumberForDisplay{ get; };      // 1-16, the number displayed to users

        Boolean IsActive{ get; };                   // from channel information
        String Name{ get; };                        // from channel information
    }
}