// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// some helper methods for folks having to build their own projections for languages
// like Delphi. 

import "MidiUmpWithTimestamp.idl";

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiInteropHelper
    {
        static IVector<MidiUmpWithTimestamp> CreateEmptyUmpWithTimestampList();

   }
}