// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiEndpointDisplayFormatter
    {
        //MidiEndpointDisplayFormatter();

        // TODO: Need to create a version of this for group blocks? Likely, but how do we advise apps about which one to use?
        // we should be opinionated here. Maybe just have one call which takes both Function and Group blocks
        // and then makes the right decisions?
        static String FormatGroupWithFunctionBlocks(
            Windows.Devices.Midi2.MidiGroup group, 
            IVector<Windows.Devices.Midi2.MidiFunctionBlock> blocks,
            Boolean abbreviatedVersion);

        // returns the "All Groups (FB name, FB name, FB name)" string
        static String FormatAllGroupOptionWithFunctionBlocks(
            IVector<Windows.Devices.Midi2.MidiFunctionBlock> blocks,
            Boolean abbreviatedVersion);


        // includes the channel name if provided
        static String FormatChannel(
            Windows.Devices.Midi2.MidiChannel channel,
            Boolean abbreviatedVersion);

    }
}