// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Windows.Devices.Midi2.ServiceConfig
{
    [uuid("2ebcfa13-585a-4376-8fe1-635784fa7fd4"), version(1.0)]
    interface IMidiServiceMessageProcessingPluginConfig
    {
        String EndpointDeviceId { get; };

        Guid MessageProcessingPluginId { get; };

        Guid PluginInstanceId{ get; };

        Boolean IsFromCurrentConfigFile{ get; };

        String GetConfigJson();
    }
}