// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "oaidl.idl";
import "ocidl.idl";

import "MidiAbstraction.idl";

[
    uuid(001776b2-f6ad-4faa-8610-0aab74ad3957),
    version(1.0),
]
library Midi2SchedulerAbstractionLib
{
    importlib("stdole2.tlb");

    [uuid(0a306359-1ea1-48c0-b1ab-d344ceccc147), version(1.0)]
    coclass Midi2SchedulerAbstraction
    {
        [default] interface IMidiAbstraction;
    }
};

