// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

[
    uuid(2ac669ca-18ca-4e7d-951e-b6cc511c96fc),
    version(1.0),
]
library Midi2SchedulerTransformLib
{
    importlib("stdole2.tlb");

    [uuid(a42cde44-7fa9-4597-a8ee-b40b96bcddb1), version(1.0)]
    coclass Midi2SchedulerTransform
    {
        [default] interface IMidiDataTransform;
    }
};

