// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "Ump128.idl";

namespace Microsoft.Devices.Midi2.Messages
{
	runtimeclass Midi2SysEx8Message : Microsoft.Devices.Midi2.Messages.Ump128
	{
		void ThisIsHereJustToAllowCppWinRTGenAndCompilation();
	};
}
