// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessage.idl";
import "Midi1ChannelVoiceMessage.idl";

namespace Microsoft.Devices.Midi2.Messages
{
    runtimeclass Midi1NoteOnMessage : Midi1ChannelVoiceMessage
    {
        UInt8 NoteNumber{ get; };
        UInt8 Velocity{ get; };
    };
}



