// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessage.idl";
import "Midi2ChannelVoiceMessage.idl";

namespace Microsoft.Devices.Midi2.Messages
{
    runtimeclass Midi2PerNoteManagementMessage : Midi2ChannelVoiceMessage
    {
        UInt8 NoteNumber{ get; };
        Boolean DetachPerNoteControllers{ get; };
        Boolean ResetPerNoteControllers{ get; };
    };
}


