// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "Midi2FlexDataMessage.idl";

namespace Microsoft.Devices.Midi2.Messages
{
	runtimeclass Midi2TimeSignatureMessage : Midi2FlexDataMessage
	{
		void ThisIsHereJustToAllowCppWinRTGenAndCompilation();
	};
}
