// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Microsoft.Devices.Midi2.ClientPlugins
{
    [default_interface]
    runtimeclass MidiChannelEndpointListener : Microsoft.Devices.Midi2.IMidiEndpointMessageProcessingPlugin, 
                                               Microsoft.Devices.Midi2.IMidiMessageReceivedEventSource
    {
        MidiChannelEndpointListener();

        Microsoft.Devices.Midi2.MidiGroup IncludedGroup;

        IVector<Microsoft.Devices.Midi2.MidiChannel> IncludedChannels{ get; };

        Boolean PreventCallingFurtherListeners;
        Boolean PreventFiringMainMessageReceivedEvent;
    }
}