// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "oaidl.idl";
import "ocidl.idl";
import "unknwn.idl";

import "WindowsMidiServices.idl";


[
    uuid(945588ac-b364-4795-abc4-58cdf9009ed9),
    version(1.0),
]
library Midi2LoopbackMidiTransportLib
{
    importlib("stdole2.tlb");

    [uuid(942BF02D-93C0-4EA8-B03E-D51156CA75E1), version(1.0)]
    coclass Midi2LoopbackMidiTransport
    {
        [default] interface IMidiTransport;
    }
};

