// TODO: Figure out if we should split this to plug into the existing Windows.Devices.Enumeration 
// and the underlying device enumerator / device tree code. 

// TODO: Refer to the UMP lib

namespace MidiEnumeration
{
    runtimeclass MidiTransportDefinition
    {
        string Type;                                // identifier of the type of transport. BLE, USB, etc.
        string IconPath;                            // path to the icon which represents this type of transport
        string Description;                         // description of the type of transport like "RTP MIDI 1.0"


    };

    interface IMidiDeviceAdapter
    {

        // TODO


    };
}



