// Copyright (c) Microsoft Corporation. All rights reserved.

import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

[
    uuid(658B88EB-B2A9-437C-9558-284B1EFFAC5B),
    version(1.0),
]
library Midi2UMP2BSTransformLib
{
    importlib("stdole2.tlb");

    [uuid(96121591-8D68-479F-9B48-2BF0B90113F7), version(1.0)]
    coclass Midi2UMP2BSTransform
    {
        [default] interface IMidiDataTransform;
    }
};

