// Copyright (c) Microsoft Corporation. All rights reserved.

#define IDS_PROJNAME                    100
#define IDR_MIDI2NETWORKMIDITRANSPORT   101

#define IDS_PLUGIN_METADATA_VERSION     500
#define IDS_PLUGIN_METADATA_NAME        501
#define IDS_PLUGIN_METADATA_DESCRIPTION 502
#define IDS_PLUGIN_METADATA_AUTHOR      503




#define IDS_ERROR_PARSING_JSON                          2000
#define IDS_ERROR_MISSING_NAME                          2001
#define IDS_ERROR_MISSING_ENTRY_IDENTIFIER              2002
#define IDS_ERROR_CREATION_FAILED                       2003
#define IDS_ERROR_UNRECOGNIZED_COMMAND                  2004
#define IDS_ERROR_MISSING_PRODUCT_INSTANCE_ID           2005
#define IDS_ERROR_MISSING_CREDENTIAL_IDENTIFIER         2008
#define IDS_ERROR_INVALID_CREDENTIAL_IDENTIFIER         2009
#define IDS_ERROR_AUTHENTICATION_NOT_IMPLEMENTED        2010
#define IDS_ERROR_HOST_NOT_FOUND                        2011
#define IDS_ERROR_UNABLE_TO_STOP_HOST                   2012
#define IDS_ERROR_UNABLE_TO_START_HOST                  2013
#define IDS_ERROR_MISSING_REMOTE_ADDRESS                2014
#define IDS_ERROR_MISSING_REMOTE_PORT                   2015
#define IDS_ERROR_INVALID_REMOTE_PORT                   2016
#define IDS_ERROR_MISSING_COMMAND                       2017
#define IDS_ERROR_FEC_PACKET_COUNT_OUT_OF_RANGE         2018
#define IDS_ERROR_RETRANSMIT_BUFFER_SIZE_OUT_OF_RANGE   2019
#define IDS_ERROR_PING_INTERVAL_OUT_OF_RANGE            2020
#define IDS_ERROR_MAX_HOST_CONNECTIONS_OUT_OF_RANGE     2021
#define IDS_ERROR_INVALID_NETWORK_PROTOCOL              2022
#define IDS_ERROR_MISSING_MATCH_ENTRY                   2023
#define IDS_ERROR_NO_REPLY_TO_INVITATION                2024
#define IDS_ERROR_INVITATION_NOT_APPROVED               2025
#define IDS_ERROR_INVITATION_PENDING_TIMEOUT_OUT_OF_RANGE 2026
#define IDS_ERROR_DIRECT_CONNECTION_SCAN_INTERVAL_OUT_OF_RANGE 2027
#define IDS_ERROR_MISSING_REMOTE_CLIENT_IDENTITY        2006
#define IDS_ERROR_SERVICE_INSTANCE_NAME_IN_USE          2007
#define IDS_ERROR_INVALID_ENTRY_IDENTIFIER              2028
#define IDS_ERROR_ENDPOINT_NAME_TOO_LONG                2029
#define IDS_ERROR_PRODUCT_INSTANCE_ID_TOO_LONG          2030
#define IDS_ERROR_CLIENT_NOT_FOUND                      2031
#define IDS_ERROR_INVALID_PRODUCT_INSTANCE_ID           2032
#define IDS_ERROR_MISSING_MATCH_ID                      2033
#define IDS_ERROR_REMOTE_CLIENT_NOT_FOUND               2034
#define IDS_ERROR_INVALID_HOST_PORT                     2035
#define IDS_ERROR_HOST_PORT_IN_USE                      2036

#define IDS_MESSAGE_CONNECTION_ENDED                    2100
#define IDS_MESSAGE_USER_DISCONNECTED                   2101
#define IDS_MESSAGE_INVITATION_DENIED                   2102
#define IDS_MESSAGE_SESSION_TIMED_OUT                   2103
#define IDS_MESSAGE_UNEXPECTED_INVITATION_ACCEPT        2104
#define IDS_MESSAGE_HOST_CANNOT_ACCEPT_INVITATIONS      2105
#define IDS_MESSAGE_UNEXPECTED_INVITATION               2106
#define IDS_MESSAGE_ENDPOINT_CREATION_FAILED            2107
#define IDS_MESSAGE_DEVICE_ALREADY_CONNECTED            2108
#define IDS_MESSAGE_AUTHENTICATION_NOT_SUPPORTED        2109
#define IDS_MESSAGE_NO_SESSION_ESTABLISHED              2110
#define IDS_MESSAGE_COMMAND_NOT_SUPPORTED               2111
#define IDS_MESSAGE_RETRANSMIT_DISABLED                 2112
#define IDS_MESSAGE_MAX_SESSIONS_REACHED                2113


#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
