// Copyright (c) Microsoft Corporation. All rights reserved.

#define IDS_PROJNAME                    100
#define IDR_MIDI2NETWORKMIDITRANSPORT   101

#define IDS_PLUGIN_METADATA_VERSION     500
#define IDS_PLUGIN_METADATA_NAME        501
#define IDS_PLUGIN_METADATA_DESCRIPTION 502
#define IDS_PLUGIN_METADATA_AUTHOR      503




#define IDS_ERROR_PARSING_JSON              2000
#define IDS_ERROR_MISSING_NAME              2001
#define IDS_ERROR_MISSING_ENTRY_IDENTIFIER  2002
#define IDS_ERROR_CREATION_FAILED           2003
#define IDS_ERROR_UNRECOGNIZED_COMMAND      2004


#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
