// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiNetworkClientConnectResultErrorCodeEnum.idl";

namespace Windows.Devices.Midi2.Endpoints.Network
{
    [experimental]
    [contract(MidiEndpointsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Endpoints.Network.IMidiNetworkClientConnectResult")]
    runtimeclass MidiNetworkClientConnectResult
    {
        Guid ClientId{ get; };

		Boolean Success{ get; };

        MidiNetworkClientConnectResultErrorCode ErrorCode{ get; };

        String ErrorInformation{ get; };

		// we won't have the endpoint device id yet, so cannot return it here


    }
}

