// Copyright (c) Microsoft Corporation. All rights reserved.

import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

[
    uuid(15C88C78-4CB3-49B5-97D4-01E60C8E6B9D),
    version(1.0),
]
library Midi2MidiSrvTransportLib
{
    importlib("stdole2.tlb");

    [uuid(2BA15E4E-5417-4A66-85B8-2B2260EFBC84), version(1.0)]
    coclass Midi2MidiSrvTransport
    {
        [default] interface IMidiTransport;
    }
};

