// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Microsoft.Devices.Midi2.VirtualkEndpoints
{
    [default_interface]
    runtimeclass MidiVirtualEndpointSettingsUI
    {
        void CreateNewEndpoint();
        void ModifyExistingEndpoint(String settingsJson);

        // need to think this through. The settings to/from the service are just json that the API knows nothing about

        // would be good to have flexibility to create multiple endpoints in one UI (loopback, for example). 


    }
}