// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiEndpointConnectOptions
    {
        MidiEndpointConnectOptions();

        Boolean DisableProcessingFunctionBlockInformationMessages { get; set; };
        Boolean DisableProcessingEndpointInformationMessages { get; set; };


    }
}