// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


// class that wraps the DeviceInformation class and provides better access to properties

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    unsealed runtimeclass MidiDeviceInformation
    {
        static MidiDeviceInformation FromDeviceInformation(Windows.Devices.Enumeration.DeviceInformation deviceInformation);

        // TODO:
        // Device names
        // Manufacturer information
        // Driver information if present
        // Transport information
        // Other device metadata
        //
        

    }
}