namespace Microsoft.Devices.Midi2.Endpoints
{
    // this is the direction as specified in the spec, so it is 
    // from the POV of the function block, not from the OS. IOW, 
    // Input here means the device FB *receives* messages that
    // are sent through Windows
    enum MidiEndpointType
    {
        EndpointTypeNativeUmp,
        EndpointTypeConvertedMidi10ByteStream
    }
}