// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2
{
    enum MidiFunctionBlockUIHint
    {
        FunctionBlockUIHintUnknown = 0x0,
        FunctionBlockUIHintReceiver = 0x1,
        FunctionBlockUIHintSender = 0x2,
        FunctionBlockUIHintBidirectional = 0x3
    };
}