// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessageType.idl";

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    unsealed runtimeclass Ump
    {
        Ump();


        // TODO: Need to ensure unknown message types can still work for prototyping etc.
        MidiMessageType MessageType { get; set; };

    }
}