namespace Microsoft.Devices.Midi2.Messages
{
    [default_interface]
    unsealed runtimeclass Ump
    {
        Ump();


        // TODO: Need to ensure unknown message types can still work for prototyping etc.
        MidiMessageType MessageType { get; set; };

        
        UInt8[] ToMidi1Bytes();



    }
}