// These are WinRT because that's closer to COM than what I started with
// To be plugins to the service, these will need to change to COM DLLs
// so they can be discovered and dynamically loaded. WinRT can't be
// loaded in the same way.

namespace Windows.Devices.Midi.NetworkMidiTransportPlugin
{
    [default_interface]
    runtimeclass MidiMessageBuffer
    {
        MidiMessageBuffer();

        Boolean IsFull();
        Boolean HasData();

        UInt32 ReadWord();
        void WriteWord(UInt32 word);

        void Clear();
    }
}