// Current level: Prototype

import "MidiUmpEndpoint.idl";

namespace Windows.Devices.Midi2
{
	[default_interface]
	runtimeclass MidiSession
	{
		MidiSession();

		String Id{ get; };

		static Windows.Devices.Midi2.MidiSession CreateSession(String sessionName);

		Windows.Devices.Midi2.MidiUmpEndpoint ConnectToEndpoint(String id);

	}
}