name: "🐞 Device, Endpoint, or Port Naming Issue"
description: Report an issue with a MIDI Device, Endpoint, or Port name
type: Bug
title: "[NAME_BUG]: "
labels:
  - "bug :lady_beetle:"
  - "needs triage :ambulance:"
assignees: ["Psychlist1972"]
projects: microsoft/339

body:
- type: markdown
  attributes:
    value: Thank you for filing a naming bug report for Windows MIDI Services. Please be sure to [search for existing issues](https://github.com/microsoft/MIDI/labels/bug%20%3Alady_beetle%3A) before filing a new bug.

- type: checkboxes
  id: steps-completed
  attributes:
    label: Report pre-requisites
    description: These steps must be completed before filing a bug report
    options:
    - label: I have searched this repo for existing issues to confirm this is not a duplicate
      required: true
    - label: I agree to follow this project's Code of Conduct
      required: true

- type: checkboxes
  id: clarity-and-disclosure
  attributes:
    label: Clarity and Disclosure
    description: These steps must be completed before filing a bug report
    options:
    - label: I confirm that any AI analysis included in this report is clearly called out / tagged as AI-generated with "AI Generated Content". Reports with suspected AI content may be closed if not disclosed.
      required: true
    - label: I confirm that I will quickly follow-up to questions or requests for additional detail, otherwise the issue may be closed
      required: true

- type: input
  id: windows-version
  attributes:
    label: Windows Version
    description: In Windows Settings > System > About. For Insider builds, this is at the bottom right of the screen. Example 27788.rs_prerelease
  validations:
    required: true

- type: input
  id: device-model
  attributes:
    label: Device Make and Model
    description: If a hardware device, what is the device you are reporting an issue with? Actual physical device name if appropriate.
  validations:
    required: true
  

- type: input
  id: name-shown
  attributes:
    label: Name(s) you saw
    description: The name displayed in the tool or application
  validations:
    required: true

- type: input
  id: name-expected
  attributes:
    label: Name(s) you expected
    description: The name(s) you expected to see
  validations:
    required: true
    
- type: textarea
  id: midi-ks-info-output
  attributes:
    label: MIDI KS Info Output
    description: If a USB or other kernel streaming device, please paste the output (text or screenshot) from running `midiksinfo.exe` from the SDK
  validations:
    required: true

- type: textarea
  id: mididiag-output
  attributes:
    label: Output from the MIDI Diagnostics Tool
    description: Use the MIDI settings app from https://aka.ms/midi, open the MIDI Settings app, and go to the troubleshooting page. Capture the resulting MIDI system information and paste the entire text here.
    placeholder: mididiag output
  validations:
    required: true
  
- type: textarea
  id: additional-notes
  attributes:
    label: Additional notes
    description: Any additional notes or information which may be relevant
    placeholder: Any additional notes or information
  validations:
    required: false
