// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"

// Every IDL in this component imports this file, so it carries the external WinRT
// declarations the API surface depends on.
import "inspectable.idl";
import "windows.foundation.idl";
import "robytestream.idl";
import "windows.data.json.idl";
import "windows.devices.enumeration.idl";
import "windows.devices.midi.idl";

namespace Windows.Devices.Midi2
{
    [contractversion(1)]
    apicontract MidiCoreApiContract { };
}
