// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

[
    uuid(4568a471-6f32-4015-b4db-9087bfb60a0b),
    version(1.0),
]
library Midi2NetworkMidiTransportLib
{
    importlib("stdole2.tlb");

    [uuid(c95dcd1f-cde3-4c2d-913c-528cb8a4cbe6), version(1.0)]
    coclass Midi2NetworkMidiTransport
    {
        [default] interface IMidiTransport;
    }
};

