- title: Overview
  icon: /assets/images/service-icon2.png
  description: Overview of Windows MIDI Services features
  button_label: Learn More
  url: /overview/
  
- title: Tools
  icon: /assets/images/service-icon.png
  description: MIDI Settings, MIDI Console, monitoring, troubleshooting, and setup tools
  button_label: See Tools
  url: /tools/
  
- title: Developer Docs
  icon: /assets/images/service-icon3.png
  description:  Developer WinRT API reference and how-to documentation
  button_label: Read Docs
  url: /sdk-overview/
  