//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Midi.Settings.Strings.zh_cn {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Midi.Settings.Strings.zh_cn.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 的管理、设置和工具应用。 的本地化字符串。
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI 和音乐人设置 预览版 的本地化字符串。
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 设置 的本地化字符串。
        /// </summary>
        internal static string AppSessionName {
            get {
                return ResourceManager.GetString("AppSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        internal static string Button_Monitor_Content {
            get {
                return ResourceManager.GetString("Button_Monitor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧急停止 的本地化字符串。
        /// </summary>
        internal static string Button_Panic_Content {
            get {
                return ResourceManager.GetString("Button_Panic.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即重启 的本地化字符串。
        /// </summary>
        internal static string Button_Reboot_Content {
            get {
                return ResourceManager.GetString("Button_Reboot.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 MIDI 服务 的本地化字符串。
        /// </summary>
        internal static string Button_RestartMidiService_Content {
            get {
                return ResourceManager.GetString("Button_RestartMidiService.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 USB MIDI 1.0 设备使用新的快速 UMP MIDI 2.0 驱动程序（需要管理员账户） 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_AssignMidi1DeviceToNewDriver_Text {
            get {
                return ResourceManager.GetString("CommonTasks_AssignMidi1DeviceToNewDriver.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将 MIDI 诊断信息捕获到文本文件，用于技术支持 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_CaptureMidiDiag_Text {
            get {
                return ResourceManager.GetString("CommonTasks_CaptureMidiDiag.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建环回端点，以便两个或更多应用可以使用 MIDI 消息进行通信 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_CreateLoopbackEndpoints_Text {
            get {
                return ResourceManager.GetString("CommonTasks_CreateLoopbackEndpoints.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 Windows MIDI Services 控制台 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_OpenConsole_Text {
            get {
                return ResourceManager.GetString("CommonTasks_OpenConsole.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向端点发送系统独占数据文件（音色、固件等） 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SendSysExFile_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SendSysExFile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 MIDI 服务在启动时自动启动（需要管理员账户） 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SetServiceAutoStart_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SetServiceAutoStart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置网络 MIDI 2.0 以启用 MIDI 消息发送到本地网络上的其他设备。 的本地化字符串。
        /// </summary>
        internal static string CommonTasks_SetUpNetworkMidi2_Text {
            get {
                return ResourceManager.GetString("CommonTasks_SetUpNetworkMidi2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端点 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_Endpoints_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_Endpoints.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_Other_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_Other.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务和驱动程序 的本地化字符串。
        /// </summary>
        internal static string CommonTasksGroup_ServiceAndDrivers_Text {
            get {
                return ResourceManager.GetString("CommonTasksGroup_ServiceAndDrivers.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置的协议 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredProtocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredProtocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置为接收抖动减少时间戳 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredReceiveJR_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredReceiveJR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置为发送抖动减少时间戳 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_ConfiguredSendJR_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_ConfiguredSendJR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Description_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Flow_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Flow.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射组 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_MappedGroup_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_MappedGroup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_Name_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_Name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SerialNumber_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SerialNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持 MIDI 1.0 协议 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SupportsMidi1Protocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SupportsMidi1Protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持 MIDI 2.0 协议 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_SupportsMidi2Protocol_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_SupportsMidi2Protocol.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输代码 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_TransportCode_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_TransportCode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输 ID 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_TransportId_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_TransportId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinMM 端口号 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_WinMMPortNumber_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_WinMMPortNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinRT 端口 ID 的本地化字符串。
        /// </summary>
        internal static string CommonTextBlockLabel_WinRTPortId_Text {
            get {
                return ResourceManager.GetString("CommonTextBlockLabel_WinRTPortId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建环回端点 的本地化字符串。
        /// </summary>
        internal static string CreateLoopbackEndpointsWindowTitle {
            get {
                return ResourceManager.GetString("CreateLoopbackEndpointsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用使用的默认基本 MIDI 1.0 环回端点。 的本地化字符串。
        /// </summary>
        internal static string DefaultBasicLoopbackDescription {
            get {
                return ResourceManager.GetString("DefaultBasicLoopbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认基本应用环回 的本地化字符串。
        /// </summary>
        internal static string DefaultBasicLoopbackName {
            get {
                return ResourceManager.GetString("DefaultBasicLoopbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用使用的默认环回端点。这是环回对的 A 端。 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackADescription {
            get {
                return ResourceManager.GetString("DefaultLoopbackADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认应用环回 (A) 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackAName {
            get {
                return ResourceManager.GetString("DefaultLoopbackAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用使用的默认环回端点。这是环回对的 B 端。 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackBDescription {
            get {
                return ResourceManager.GetString("DefaultLoopbackBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认应用环回 (B) 的本地化字符串。
        /// </summary>
        internal static string DefaultLoopbackBName {
            get {
                return ResourceManager.GetString("DefaultLoopbackBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Button_Customize_Content {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Button_Customize.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端点设备 ID： 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_EndpointDeviceIdLabel_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_EndpointDeviceIdLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于 MIDI 2.0 设备，功能块指示活动组及其有效方向。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_FunctionBlocksExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_FunctionBlocksExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能块 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_FunctionBlocksExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_FunctionBlocksExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于 USB MIDI 2.0 设备，当没有功能块可用时，组终端块是后备选项。它们指示活动组及其方向。对于 MIDI 1.0 设备，我们为每个 MIDI 插孔（以前称为&quot;端口&quot;）生成组终端块。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_GroupTerminalBlocksExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_GroupTerminalBlocksExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组终端块 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_GroupTerminalBlocksExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_GroupTerminalBlocksExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标/输出端口 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_HeaderDestinationOutputPorts_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_HeaderDestinationOutputPorts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源/输入端口 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_HeaderSourceInputPorts_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_HeaderSourceInputPorts.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造商 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ManufacturerLabel_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ManufacturerLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 协议包括设备发现。此处的信息即从此来源获取。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Midi2ProtocolExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Midi2ProtocolExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 协议内发现的信息 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Midi2ProtocolExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Midi2ProtocolExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原生数据格式 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_NativeDataFormat_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_NativeDataFormat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备可能有多个 MIDI 端点。这是此端点的父设备。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ParentDeviceExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ParentDeviceExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父设备 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ParentDeviceExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ParentDeviceExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您可以自定义设备的某些设置，如名称和描述。应用可以使用此信息来显示设备信息。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_PersonalizationExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_PersonalizationExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品实例 ID 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_ProductInstanceId_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_ProductInstanceId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联的 MIDI 1.0 API 端口 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Section_AssociatedMidi1Ports_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Section_AssociatedMidi1Ports.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_SerialNumber_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_SerialNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改图像 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Tooltip_ChangeImage_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Tooltip_ChangeImage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名端点、更新描述和其他属性 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_Tooltip_Customize_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_Tooltip_Customize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输代码 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportCode_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportCode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Service 传输插件从底层传输（USB、网络、BLE 等）获取设备信息。 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportExpander_Description {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输提供的信息 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_TransportExpander_Header {
            get {
                return ResourceManager.GetString("DeviceDetailPage_TransportExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB VID/PID 的本地化字符串。
        /// </summary>
        internal static string DeviceDetailPage_UsbVidPid_Text {
            get {
                return ResourceManager.GetString("DeviceDetailPage_UsbVidPid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此 MIDI 设备不报告序列号或唯一标识符。因此，如果您更改设备与此 PC 的连接方式（例如不同的 USB 端口或集线器），自定义设置可能不会保持应用。如果您有多个此类设备，并在不同时间连接它们，Windows 可能不知道将个性化设置应用于哪个设备。 的本地化字符串。
        /// </summary>
        internal static string EndpointPersonalizationUniqueIdInfoBar_Message {
            get {
                return ResourceManager.GetString("EndpointPersonalizationUniqueIdInfoBar.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化可能不是永久的 的本地化字符串。
        /// </summary>
        internal static string EndpointPersonalizationUniqueIdInfoBar_Title {
            get {
                return ResourceManager.GetString("EndpointPersonalizationUniqueIdInfoBar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法初始化 Windows MIDI Services 运行时。抛出异常： 的本地化字符串。
        /// </summary>
        internal static string Error_ExceptionThrownDuringSdkInitialization {
            get {
                return ResourceManager.GetString("Error_ExceptionThrownDuringSdkInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此 PC 上似乎未启用 Windows MIDI Services 功能。受支持的 Windows 版本将通过 Windows 更新启用。
        ///
        ///如果之前已激活该功能，可能是驱动程序卸载程序或注册表重新排序工具破坏了 Windows MIDI Services。
        ///
        ///如果是这种情况，请以管理员身份打开命令提示符，输入 midifixreg，然后按照步骤操作。完成后，重启您的 PC。 的本地化字符串。
        /// </summary>
        internal static string Error_MidiServicesFeatureNotEnabled {
            get {
                return ResourceManager.GetString("Error_MidiServicesFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 设置应用无法自动关闭并重启。请关闭应用程序，然后重新启动它。 的本地化字符串。
        /// </summary>
        internal static string Error_SettingsAppCouldNotAutomaticallyRestart {
            get {
                return ResourceManager.GetString("Error_SettingsAppCouldNotAutomaticallyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 MIDI 设置应用时出错 的本地化字符串。
        /// </summary>
        internal static string Error_StartupMessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_StartupMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法初始化 Windows MIDI Services 运行时。是否已安装？ 的本地化字符串。
        /// </summary>
        internal static string Error_UnableToInitializeMidiRuntime {
            get {
                return ResourceManager.GetString("Error_UnableToInitializeMidiRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动 MIDI 服务。如果此问题持续存在，请终止 midisrv.exe 进程或重启您的 PC。 的本地化字符串。
        /// </summary>
        internal static string Error_UnableToStartMidiService {
            get {
                return ResourceManager.GetString("Error_UnableToStartMidiService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 未启用 的本地化字符串。
        /// </summary>
        internal static string Error_WindowsMIDIServicesNotEnabledMessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_WindowsMIDIServicesNotEnabledMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许多 MIDI 自定义设置存储在可移植配置文件中。这些包括自定义端点属性（如名称）、持久环回端点定义以及网络 MIDI 主机和客户端重新连接。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_ConfigFileDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_ConfigFileDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果不存在则创建默认配置文件。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_CreateDefaultConfigFileSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_CreateDefaultConfigFileSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果不存在则创建默认环回端点。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_CreateDefaultLoopbacksSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_CreateDefaultLoopbacksSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 某些应用和工具（尤其是基于 Web 的应用和工具）依赖于已知的环回端点可用。这需要配置文件来存储环回端点信息。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_DefaultLoopbacksDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_DefaultLoopbacksDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认情况下，MIDI 服务设置为仅在应用进行第一个 MIDI 连接时启动。这确保不使用 MIDI 的用户不会影响 Windows 启动时间。但首次进行 MIDI 连接时，可能需要几秒钟。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_MidiServiceStartupDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_MidiServiceStartupDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您经常使用 MIDI，我们建议将服务设置为与 Windows 一起自动启动，这样您在建立连接时就无需等待。这需要管理员权限才能设置。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_MidiServiceStartupDescription2_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_MidiServiceStartupDescription2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用旧版 MIDI 1.0 API (WinMM) 的应用在许多应用和文件中使用端口名称作为标识符。默认情况下，我们使用与这些旧名称兼容的名称。但是，如果您想要更好的默认端口名称，请选择下面的选项。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_PortNamesDescription_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_PortNamesDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 MIDI 服务与 Windows 一起自动启动 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_SetServiceAutoStartSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_SetServiceAutoStartSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 Windows MIDI Services 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_Title_Text {
            get {
                return ResourceManager.GetString("FirstRunSetup_Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用新式 MIDI 1 端口名称。 的本地化字符串。
        /// </summary>
        internal static string FirstRunSetup_UseNewPortNamesSwitch_Header {
            get {
                return ResourceManager.GetString("FirstRunSetup_UseNewPortNamesSwitch.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存到注册表 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_CommitDiscoveryTimeoutButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_CommitDiscoveryTimeoutButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这些设置仅供高级用户或开发和原型设计使用。更改此处的设置可能会导致使用 Windows MIDI Services 的应用和设备出现意外或不理想的行为。这些设置可能会在 Windows 升级时被重置。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Description_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通常开启。默认情况下，MIDI 服务为任何原生 UMP 设备执行 MIDI 2.0 发现和协议协商。如果您测试的设备在发送这些消息时会出错，请禁用此过程。需要重启 MIDI 服务。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Discovery_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_Discovery.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现和协议协商 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Discovery_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_Discovery.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现超时（毫秒） 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryTimeoutSlider_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryTimeoutSlider.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已禁用基于服务的 MIDI 2.0 发现和协议协商。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryToggle_OffContent {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryToggle.OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已启用基于服务的 MIDI 2.0 发现和协议协商。这是推荐的选择。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_DiscoveryToggle_OnContent {
            get {
                return ResourceManager.GetString("ForDevelopers_DiscoveryToggle.OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为了安装服务或服务组件/插件的预览版，您必须首先获取用于组件注册的注册表项的所有权。如果您不先执行此操作，安装将显示成功，但使用的组件将不是您期望的组件。
        ///
        ///此步骤需要管理员权限，并且必须在任何新的 Windows 升级（不是更新，而是完整操作系统升级）后重复执行。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableDeveloperInstallationExpander_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableDeveloperInstallationExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用开发者版本安装 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableDeveloperInstallationExpander_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableDeveloperInstallationExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通常关闭。MMCSS 线程是 Windows 中的有限资源，通常用于 DAW 应用中的音频处理线程。如果启用此功能，Windows MIDI Services 将使用 MMCSS 线程处理传入消息。这会减少客户端进程可用的 MMCSS 线程数量，并可能导致应用无法正常工作。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcss_Description {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcss.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为传入消息队列启用 MMCSS 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcss_Header {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcss.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 将不会在客户端进程中使用 MMCSS 线程。这是推荐的选择。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcssToggle_OffContent {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcssToggle.OffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 将在客户端进程中使用 MMCSS 线程。这可能导致某些应用出现故障。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_EnableMmcssToggle_OnContent {
            get {
                return ResourceManager.GetString("ForDevelopers_EnableMmcssToggle.OnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装开发者/预览版本 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_InstallPreviewSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_InstallPreviewSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 功能 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_Midi2FeaturesSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_Midi2FeaturesSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备预览/开发者安装 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_PrepareForDeveloperInstallButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_PrepareForDeveloperInstallButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所做的更改需要重启 PC 才能生效。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_RebootRequired_Message {
            get {
                return ResourceManager.GetString("ForDevelopers_RebootRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关支持 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_RelatedSupportSectionHeader_Text {
            get {
                return ResourceManager.GetString("ForDevelopers_RelatedSupportSectionHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将 wdmaud2.drv 替换为开发者版本 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_ReplaceWdmaud2DrvButton_Content {
            get {
                return ResourceManager.GetString("ForDevelopers_ReplaceWdmaud2DrvButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须重启 Windows MIDI Service (midisrv.exe) 才能使更改生效。 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_ServiceRestartRequired_Message {
            get {
                return ResourceManager.GetString("ForDevelopers_ServiceRestartRequired.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string ForDevelopers_SystemSettingsSectionHeader {
            get {
                return ResourceManager.GetString("ForDevelopers_SystemSettingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此处选择的选项将是使用经典 MIDI 1.0 内置或供应商驱动程序命名 MIDI 1.0 API 端口的默认方法。如果需要，可以按设备覆盖默认命名方法。
        ///
        ///如果您有许多使用 MIDI 1.0 设备的现有项目，并且需要保持命名兼容性以便 DAW 或其他应用自动发现设备，我们建议使用经典端口名称。否则，新式名称通常信息量更大。
        ///
        ///此更改需要重启 MIDI 服务才能生效。 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultNamingExpander_Description {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultNamingExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 MIDI 1.0 端口命名 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultNamingExpander_Header {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultNamingExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用与之前版本的 Windows MIDI API 兼容的名称，并保持与应用中保存的 MIDI 项目的兼容性。 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultUseClassicMidi1PortNames_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultUseClassicMidi1PortNames.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 MIDI 设备制造商推荐的新式端口名称。（对于 USB 设备，这些名称在可用时使用 iJack 名称）。 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_DefaultUseNewStyleMidi1PortNames_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_DefaultUseNewStyleMidi1PortNames.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 MIDI 服务为自动启动 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_SetMidiServiceToAutoStartButton_Content {
            get {
                return ResourceManager.GetString("GlobalSettings_SetMidiServiceToAutoStartButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 Windows MIDI Service (midisrv.exe) 与 Windows 一起自动启动，以减少应用在重启后首次调用 MIDI API 时的延迟。 的本地化字符串。
        /// </summary>
        internal static string GlobalSettings_SetMidiServiceToAutoStartCard_Header {
            get {
                return ResourceManager.GetString("GlobalSettings_SetMidiServiceToAutoStartCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 仪表板 的本地化字符串。
        /// </summary>
        internal static string HomePage_Description_Text {
            get {
                return ResourceManager.GetString("HomePage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 协会上的 MIDI 1.0 和 2.0 规范 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_MidiSpecifications_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_MidiSpecifications.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://midi.org/specs 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_MidiSpecifications_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_MidiSpecifications.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI 和 ASIO Discord 服务器 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDiscord_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDiscord.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/mididiscord 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDiscord_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDiscord.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 文档 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDocumentation_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDocumentation.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midi 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesDocumentation_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesDocumentation.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services GitHub 仓库 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesGitHub_Content {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesGitHub.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midirepo 的本地化字符串。
        /// </summary>
        internal static string HyperlinkButton_WindowsMidiServicesGitHub_NavigateUri {
            get {
                return ResourceManager.GetString("HyperlinkButton_WindowsMidiServicesGitHub.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用需要重启以应用语言更改。立即重启？ 的本地化字符串。
        /// </summary>
        internal static string Message_RestartAppForLanguageChange {
            get {
                return ResourceManager.GetString("Message_RestartAppForLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 设置应用现在将重启。 的本地化字符串。
        /// </summary>
        internal static string Message_SettingsAppWillNowRestart {
            get {
                return ResourceManager.GetString("Message_SettingsAppWillNowRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下是传统 MIDI 1.0 API 看到的所有 MIDI 设备列表，以及使用它们的应用。 的本地化字符串。
        /// </summary>
        internal static string Midi1DevicesPage_Description_Text {
            get {
                return ResourceManager.GetString("Midi1DevicesPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用经典 API 兼容 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseClassicAPICompatible {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseClassicAPICompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用全局默认 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseGlobalDefault {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseGlobalDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用新式 的本地化字符串。
        /// </summary>
        internal static string Midi1PortNamingValue_UseNewStyle {
            get {
                return ResourceManager.GetString("Midi1PortNamingValue_UseNewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此页面列出了此 PC 上安装并被 Windows MIDI Services 识别的所有传输插件。有关这些传输插件枚举的端点设备信息，请参阅设备页面。 的本地化字符串。
        /// </summary>
        internal static string PluginsTransportPage_Description_Text {
            get {
                return ResourceManager.GetString("PluginsTransportPage_Description.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string Settings_About_Text {
            get {
                return ResourceManager.GetString("Settings_About.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您想讨论 Windows MIDI Services，我们托管了一个 Discord 服务器。 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionMidiDiscordLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiDiscordLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services 是托管在 GitHub 上的开源项目。我们鼓励提交错误报告和拉取请求。 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionMidiRepoLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionMidiRepoLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的隐私很重要。 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutDescriptionPrivacyLinkCard_Description {
            get {
                return ResourceManager.GetString("Settings_AboutDescriptionPrivacyLinkCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI® 和 MIDI® 标志是 MIDI® 协会的注册商标。经许可使用。Microsoft 是 MIDI® 协会的企业会员。AMEI 是 MIDI® 协会的日本合作伙伴，也是 Windows 上 USB MIDI 2.0 驱动程序的作者（与 AmeNote 合作开发）。 的本地化字符串。
        /// </summary>
        internal static string Settings_AboutMidiDescription_Header {
            get {
                return ResourceManager.GetString("Settings_AboutMidiDescription.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要显示的应用主题 的本地化字符串。
        /// </summary>
        internal static string Settings_AppThemeExpander_Description {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用主题 的本地化字符串。
        /// </summary>
        internal static string Settings_AppThemeExpander_Header {
            get {
                return ResourceManager.GetString("Settings_AppThemeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 (简体) 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_ChineseSimplified_Content {
            get {
                return ResourceManager.GetString("Settings_Language_ChineseSimplified.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择您的首选语言。需要重启应用。 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (United States) 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_English_Content {
            get {
                return ResourceManager.GetString("Settings_Language_English.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_Header {
            get {
                return ResourceManager.GetString("Settings_Language.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用系统默认 的本地化字符串。
        /// </summary>
        internal static string Settings_Language_SystemDefault_Content {
            get {
                return ResourceManager.GetString("Settings_Language_SystemDefault.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        internal static string Settings_Personalization_Text {
            get {
                return ResourceManager.GetString("Settings_Personalization.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 MIDI 开发者选项 的本地化字符串。
        /// </summary>
        internal static string Settings_ShowDeveloperOptions_Header {
            get {
                return ResourceManager.GetString("Settings_ShowDeveloperOptions.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用系统设置 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 © 2025 Microsoft。保留所有权利。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AboutCard_Description {
            get {
                return ResourceManager.GetString("SettingsPage_AboutCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AMEI 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.amei.or.jp/ 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_AmeiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_AmeiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 MIDI 设置应用时自动检查 MIDI SDK 运行时和工具的新版本。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_CheckForUpdatesExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_CheckForUpdatesExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 MIDI SDK 运行时更新 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_CheckForUpdatesExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_CheckForUpdatesExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者选项通常适用于开发者以及与开发者合作测试预发布组件的用户。非开发者 MIDI 用户无需使用开发者选项，因为它们可能会对计算机上 MIDI 的稳定性、功能或性能产生不利影响。开发者选项要求将 PC 设置为开发者模式。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 开发者选项 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者模式未启用。如果您想安装开发中和未签名的第三方服务插件，请在 Windows 设置中启用开发者模式。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsDisabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsDisabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前此 PC 已启用开发者模式，允许您安装开发中和第三方未签名服务插件。要关闭它，请使用 Windows 设置。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeIsEnabledInfo_Text {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeIsEnabledInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 Windows 设置&quot;开发者&quot;页面 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DeveloperModeLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DeveloperModeLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord 上的 Windows MIDI Services 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DiscordLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/mididiscord 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_DiscordLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_DiscordLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 协会 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://midi.org 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiOrgLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiOrgLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub 上的 Windows MIDI Services 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://aka.ms/midirepo 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_MidiRepoLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_MidiRepoLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft 隐私声明 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_Content {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://privacy.microsoft.com/privacystatement 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_PrivacyTermsLink_NavigateUri {
            get {
                return ResourceManager.GetString("SettingsPage_PrivacyTermsLink.NavigateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用预览版本的 SDK 运行时，包括可能具有错误的稳定功能。仅推荐技术用户或开发者使用。启用后，这只能通过卸载 SDK 运行时和工具、删除设置配置文件，然后重新安装 SDK 运行时和工具来更改。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SdkChannelExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_SdkChannelExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用预览 MIDI SDK 运行时和工具通道 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SdkChannelExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_SdkChannelExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送反馈 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_SendFeedbackButton_Content {
            get {
                return ResourceManager.GetString("SettingsPage_SendFeedbackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用系统独占消息发送器等预览工具。这些工具尚不稳定，可能具有错误或不完整的功能。需要重启此应用才能看到更改。 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_ShowPreviewToolsExpander_Description {
            get {
                return ResourceManager.GetString("SettingsPage_ShowPreviewToolsExpander.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用预览工具 的本地化字符串。
        /// </summary>
        internal static string SettingsPage_ShowPreviewToolsExpander_Header {
            get {
                return ResourceManager.GetString("SettingsPage_ShowPreviewToolsExpander.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级 USB 设置 的本地化字符串。
        /// </summary>
        internal static string Shell_AdvancedUsbSettings_Text {
            get {
                return ResourceManager.GetString("Shell_AdvancedUsbSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 设备和端点 的本地化字符串。
        /// </summary>
        internal static string Shell_AllMidiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_AllMidiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string Shell_Configurations_Content {
            get {
                return ResourceManager.GetString("Shell_Configurations.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输配置 的本地化字符串。
        /// </summary>
        internal static string Shell_ConfigureTransportsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ConfigureTransportsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容网格 的本地化字符串。
        /// </summary>
        internal static string Shell_ContentGrid_Content {
            get {
                return ResourceManager.GetString("Shell_ContentGrid.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsAll_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsAll.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚拟设备应用 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsApp_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsApp.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 环回端点 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsBasicLoop_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsBasicLoop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝牙 MIDI 1.0 (预览) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsBle10_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsBle10.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsDiagnostic_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsDiagnostic.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 UMP 驱动程序 (USB) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsKS_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsKS.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 驱动程序 (USB 等) 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsKsa_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsKsa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 2.0 环回端点 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsLoop_Content {
            get {
                return ResourceManager.GetString("Shell_EndpointsLoop.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 MIDI 2.0 的本地化字符串。
        /// </summary>
        internal static string Shell_EndpointsNet2Udp_Text {
            get {
                return ResourceManager.GetString("Shell_EndpointsNet2Udp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者 的本地化字符串。
        /// </summary>
        internal static string Shell_ForDevelopers_Content {
            get {
                return ResourceManager.GetString("Shell_ForDevelopers.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局 MIDI 设置 的本地化字符串。
        /// </summary>
        internal static string Shell_GlobalMidiSettings_Text {
            get {
                return ResourceManager.GetString("Shell_GlobalMidiSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Shell_Home_Content {
            get {
                return ResourceManager.GetString("Shell_Home.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现场表演模式 的本地化字符串。
        /// </summary>
        internal static string Shell_LivePerformanceMode_Text {
            get {
                return ResourceManager.GetString("Shell_LivePerformanceMode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Shell_Main_Content {
            get {
                return ResourceManager.GetString("Shell_Main.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string Shell_ManagementNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动会话 的本地化字符串。
        /// </summary>
        internal static string Shell_ManagementSessions_Content {
            get {
                return ResourceManager.GetString("Shell_ManagementSessions.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 1.0 API 端口 的本地化字符串。
        /// </summary>
        internal static string Shell_Midi1ApiNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_Midi1ApiNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI 设置 的本地化字符串。
        /// </summary>
        internal static string Shell_MidiNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MidiNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows MIDI Services UMP 端点 的本地化字符串。
        /// </summary>
        internal static string Shell_MidiServicesNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MidiServicesNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string Shell_MoreNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_MoreNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理和过滤 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsProcessing_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsProcessing.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传输 的本地化字符串。
        /// </summary>
        internal static string Shell_PluginsTransport_Content {
            get {
                return ResourceManager.GetString("Shell_PluginsTransport.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路由 的本地化字符串。
        /// </summary>
        internal static string Shell_Routes_Content {
            get {
                return ResourceManager.GetString("Shell_Routes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备和配置 的本地化字符串。
        /// </summary>
        internal static string Shell_SetupNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_SetupNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统信息 的本地化字符串。
        /// </summary>
        internal static string Shell_SystemInfo_Content {
            get {
                return ResourceManager.GetString("Shell_SystemInfo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsConsole_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsConsole.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量监控器 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsMonitor_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsMonitor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsNavHeader_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsNavHeader.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SysEx 传输 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsSysEx_Text {
            get {
                return ResourceManager.GetString("Shell_ToolsSysEx.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备测试 的本地化字符串。
        /// </summary>
        internal static string Shell_ToolsTest_Content {
            get {
                return ResourceManager.GetString("Shell_ToolsTest.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疑难解答 的本地化字符串。
        /// </summary>
        internal static string Shell_Troubleshooting_Text {
            get {
                return ResourceManager.GetString("Shell_Troubleshooting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐家优化 的本地化字符串。
        /// </summary>
        internal static string Shell_WindowsSettings_Text {
            get {
                return ResourceManager.GetString("Shell_WindowsSettings.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinMM MIDI 1.0 端口 的本地化字符串。
        /// </summary>
        internal static string Shell_WinMMMidi1ApiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_WinMMMidi1ApiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinRT MIDI 1.0 端口 的本地化字符串。
        /// </summary>
        internal static string Shell_WinRTMidi1ApiDevices_Content {
            get {
                return ResourceManager.GetString("Shell_WinRTMidi1ApiDevices.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string ShellPage_AdministratorIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_AdministratorIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者模式已启用 的本地化字符串。
        /// </summary>
        internal static string ShellPage_DeveloperModeIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_DeveloperModeIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 MIDI 服务 的本地化字符串。
        /// </summary>
        internal static string ShellPage_ServiceUnavailableIndicator_Text {
            get {
                return ResourceManager.GetString("ShellPage_ServiceUnavailableIndicator.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找设置 的本地化字符串。
        /// </summary>
        internal static string ShellPage_SettingsSearchBox_PlaceholderText {
            get {
                return ResourceManager.GetString("ShellPage_SettingsSearchBox.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向所选端点发送系统独占 (SysEx) 二进制 7 位文件（典型的 MIDI 1.0 SysEx 文件）。对于较旧的设备或数据缓冲区非常小的设备，如果将传输延迟增加 10-50 毫秒，效果可能会更好。当通过 SysEx 发送大型音色库或固件升级时尤其如此。 的本地化字符串。
        /// </summary>
        internal static string ToolsSysExPageDescription_Text {
            get {
                return ResourceManager.GetString("ToolsSysExPageDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您可以从 Windows Defender 扫描中排除特定的受信任进程和文件位置。这将显著提高这些位置的读取/写入速度，但您必须小心只放置受信任的内容和插件。 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 Defender 扫描中排除 DAW 进程 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludeDawProcessButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludeDawProcessButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排除 DAW 项目文件夹 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludeDawProjectsFolderButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludeDawProjectsFolderButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排除插件数据文件夹 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_ExcludePluginDataFoldersButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard_ExcludePluginDataFoldersButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defender 设置 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_DefenderSettingsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_DefenderSettingsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用低延迟音频时，将 Windows 电源模式设置为最佳性能有助于提高处理器速度并减少故障。 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源模式 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 Windows 设置 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_PowerModeCard_LaunchButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_PowerModeCard_LaunchButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面聚焦 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_DesktopSpotlightCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_DesktopSpotlightCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game DVR 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_GameDvrCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_GameDvrCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地理位置 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_GeoLocationCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_GeoLocationCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁屏提示 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_LockscreenTipsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_LockscreenTipsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_NewsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_NewsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸牌和休闲游戏 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_SolitaireAndGamesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_SolitaireAndGamesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始菜单中的推荐应用 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StartMenuRecommendedAppsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StartMenuRecommendedAppsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始菜单中的 Web 搜索 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StartMenuWebSearchCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StartMenuWebSearchCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘滞键 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_StickyKeysCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_StickyKeysCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WeatherCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WeatherCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小组件 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WidgetsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WidgetsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 建议 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_WindowsSuggestionsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_WindowsSuggestionsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xbox 应用 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeatures_XboxCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeatures_XboxCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预安装的 Windows 功能对许多用户来说很好，但有时会干扰创作过程。您可以在此处轻松删除或禁用它们。卸载后，无法重新安装。 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeaturesCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeaturesCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预安装的 Windows 功能 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableFeaturesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableFeaturesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这些功能可以轻松打开或关闭，但为了方便起见位于此处。 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableRecoverableFeaturesCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableRecoverableFeaturesCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可配置的 Windows 功能 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_RemoveOrDisableRecoverableFeaturesCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_RemoveOrDisableRecoverableFeaturesCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虽然保持最新状态对安全性、功能和错误修复很重要，但您可以在工作期间暂停 Windows 更新一段时间。 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_Description {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 更新 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_Header {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停更新 X 天 的本地化字符串。
        /// </summary>
        internal static string WindowsSettings_UpdateSettingsCard_PauseUpdatesButton_Content {
            get {
                return ResourceManager.GetString("WindowsSettings_UpdateSettingsCard_PauseUpdatesButton.Content", resourceCulture);
            }
        }
    }
}
