
#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace midi_configuration_api
{
    [MIDI_API_CONTRACT(1)]
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;
    }
}
