// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "IMidiServiceTransportPluginConfig.idl";
import "IMidiServiceMessageProcessingPluginConfig.idl";
import "MidiServiceConfigResponse.idl";
import "MidiServicesSdkRuntimeVersion.idl";

namespace Microsoft.Windows.Devices.Midi2.Service
{
    [default_interface]
    static runtimeclass MidiService
    {
        static Boolean EnsureServiceAvailable();

        //static Boolean IsCompatibleRuntimeInstalled();
        //static MidiServicesSdkRuntimeVersion GetInstalledRuntimeVersion();

        //static Windows.Foundation.Uri GetLatestRuntimeReleaseInstallerUri();
        static Windows.Foundation.Uri GetLatestSettingsAppReleaseInstallerUri();
        static Windows.Foundation.Uri GetLatestConsoleAppReleaseInstallerUri();

        static MidiServiceConfigResponse UpdateTransportPluginConfig(
            IMidiServiceTransportPluginConfig configUpdate);

        static MidiServiceConfigResponse UpdateProcessingPluginConfig(
            IMidiServiceMessageProcessingPluginConfig configUpdate);
    }
}

