// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Windows.Devices.Midi2.Service
{
    enum MidiServiceConfigResponseStatus
    {
        Success =                       0,

        ErrorTargetNotFound =           404,

        ErrorConfigJsonNullOrEmpty =    600,
        ErrorProcessingConfigJson =     601,
        ErrorProcessingResponseJson =   605,

        ErrorNotImplemented =           2600,

        //ErrorOther =                9999,
    };
}