// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT

import "IMidiEndpointMessageProcessingPlugin.idl";
import "MidiStreamConfigurationRequestReceivedEventArgs.idl";
import "MidiFunctionBlock.idl";
import "MidiVirtualEndpointDeviceDefinition.idl";

namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    [default_interface]
    runtimeclass MidiVirtualEndpointDevice : IMidiEndpointMessageProcessingPlugin
    {
        MidiVirtualEndpointDeviceDefinition DeviceDefinition{ get; };

        IMapView<UInt8, MidiFunctionBlock> FunctionBlocks{ get; };
        
        Boolean UpdateFunctionBlock(MidiFunctionBlock block);
        Boolean UpdateEndpointName(String name);

        Boolean SuppressHandledMessages{ get; set; };

        event Windows.Foundation.TypedEventHandler<MidiVirtualEndpointDevice, MidiStreamConfigurationRequestReceivedEventArgs> StreamConfigurationRequestReceived;
    }
}