import "Ump128.idl";

namespace Microsoft.Windows.Midi.Messages.Data
{
  

    [default_interface]
    runtimeclass MidiMixedDataSetHeaderMessage
    {
        UInt8 Group;
        UInt8 MdsId;
        UInt16 ValidBytesIncludingHeaderInThisChunk;
        UInt16 NumberOfChunks;
        UInt16 ChunkIndex;      // starts at 1
        UInt16 ManufacturerId;
        UInt16 DeviceId;
        UInt16 SubId1;
        UInt16 SubId2;

        // TODO constructors and factory methods
    };


}