import "Ump32.idl";
import "Midi1ChannelVoiceMessage.idl";


namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{

    runtimeclass Midi1NoteOnMessage : Midi1ChannelVoiceMessage
    {
        UInt8 NoteNumber;
        UInt8 Velocity;

        Midi1NoteOnMessage();

        [default_overload]
        static Midi1NoteOnMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump32 ump);
        static Midi1NoteOnMessage FromWord(UInt32 word0);
        static Midi1NoteOnMessage FromMidi1Bytes(UInt8 group, UInt8 midi1Byte0, UInt8 midi1Byte1, UInt8 midi1Byte2);
    };

}