// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2.ClientEndpointContracts
{
    interface IMidiEndpointUpdateDialog
    {
        // The settings to use for this plugin. If it's an existing endpoint(s), it'll be provided
        // up-front. If it's a new set of endpoint(s), it will be empty or null at the start
        // After the UI is shown, this property contains the updated/new JSON.
        String SettingsJson{ get; set; };

        // returns true if update is to be applied, false if not
        Boolean Show(String title);
    }
}