// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "IMidiEndpointCreateSettingsPanel.idl";
import "IMidiEndpointCreateDialog.idl";

import "IMidiEndpointUpdateSettingsPanel.idl";
import "IMidiEndpointUpdateDialog.idl";

import "IMidiEndpointPropertiesSettingsPanel.idl";
import "IMidiEndpointPropertiesDialog.idl";

import "IMidiTransportGlobalSettingsPanel.idl";


namespace Microsoft.Devices.Midi2.ClientEndpointContracts
{
    // I wonder if it wouldn't be better to leave out this interface and just do runtime discovery

    interface IMidiCreatableEndpointSdkPlugin
    {
        Boolean SupportsCreate{ get; };      
        IMidiEndpointCreateSettingsPanel GetCreateSettingsPanel();
        IMidiEndpointCreateDialog GetCreateDialog();

        Boolean SupportsUpdate{ get; };
        IMidiEndpointUpdateSettingsPanel GetUpdateSettingsPanel();
        IMidiEndpointUpdateDialog GetUpdateDialog();

        Boolean SupportsProperties{ get; };
        IMidiEndpointPropertiesSettingsPanel GetPropertiesSettingsPanel();
        IMidiEndpointPropertiesDialog GetPropertiesDialog();

        Boolean SupportsGlobalTransportSettings{ get; };
        IMidiTransportGlobalSettingsPanel GetTransportGlobalSettingsPanel();


    }
}
