// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "IMidiEndpointSettingsData.idl";

namespace Microsoft.Devices.Midi2.ClientEndpointContracts
{
    interface IMidiEndpointPropertiesSettingsPanel
    {
        IMidiEndpointSettingsData Settings{ get; set; };

        // Any global settings which apply to all endpoints created for this transport
        Windows.UI.Xaml.FrameworkElement GetSettingsUI();
    }
}