// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


// Interface for settings classes that transport SDK plugins will implement when 
// providing custom connection settings for their transports

#include "midl_defines.h";
MIDI_IDL_IMPORT

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT_1]
    [
        uuid(65736736-35f3-421c-a683-3a034ad0dcc2),
        version(1.0),
    ]
    interface IMidiEndpointConnectionSettings
    {
        String SettingsJson { get; set; };

        Boolean IsDirty{ get; set; };
    }
}