// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessageReceivedEventArgs.idl";

namespace Windows.Devices.Midi2
{
    [
        uuid(dabfaf64-28d6-4122-92ef-5bc6548f2a69),
        version(1.0),
    ]
    interface IMidiInputConnection
    {
        // zero or more filters for this reader. This is the real reason to have multiple readers on an endpoint
        //IVector<IMidiMessageListener> PreFilterListeners{ get; };
        //IVector<IMidiMessageClientFilter> Filters{ get; };
        //MidiMessageClientFilterStrategy FilterStrategy{ get; };


        UInt32 ReceiveBuffer(Windows.Foundation.IMemoryBuffer buffer, UInt32 byteOffsetInBuffer, UInt32 maxBytesToReceive);

        // notification that there are new messages received. Optional.
        event Windows.Foundation.TypedEventHandler<IInspectable, MidiMessageReceivedEventArgs> MessageReceived;
    }
}