// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessageBuffer.idl";

import "IMidiUmp.idl";

namespace Windows.Devices.Midi2
{
    [
        uuid(8b71d1b8-c239-4b88-8142-05ee5118d41e),
        version(1.0),
    ]
    interface IMidiOutputConnection
    {

        // sends any number of messages
        UInt32 SendBuffer(UInt64 timestamp, Windows.Foundation.IMemoryBuffer midiData, UInt32 byteOffset, UInt32 length);

        Boolean SendUmp(IMidiUmp ump);

        Boolean SendWords(UInt64 timestamp, UInt32 word0);
        //void SendWords(UInt64 timestamp, UInt32 word0, UInt32 word1);
        //void SendWords(UInt64 timestamp, UInt32 word0, UInt32 word1, UInt32 word2);
        //void SendWords(UInt64 timestamp, UInt32 word0, UInt32 word1, UInt32 word2, UInt32 word3);


    }
}