// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiMessageBuffer.idl";

import "MidiUmp32.idl";

namespace Windows.Devices.Midi2
{
    [
        uuid(8b71d1b8-c239-4b88-8142-05ee5118d41e),
        version(1.0),
    ]
    interface IMidiOutputConnection
    {

        // sends any number of messages
        UInt32 SendBuffer(Windows.Foundation.IMemoryBuffer midiData, UInt32 byteOffset, UInt32 length);

        // originally this was named "SendMessage" but forgot that clashes with windows.h sendmessage
        void SendUmp(IMidiUmp ump);
    }
}