// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Windows.Devices.Midi2
{
    enum MidiMessageClientFilterStrategy
    {
        Ignore = 0,         // ignore all filters
        OrFilters = 1,      // any filters may pass to accept the message
        AndFilters,         // all attached filters must pass to accept the message
    };
}