// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// This is the moral equivalent of a "port" in MIDI 1.0. MIDI 2.0 UMP Endpoints are
// almost always bidirectional. This is the main entity that applications will use
// after creating a session

import "MidiMessagesReceivedEventArgs.idl";
import "MidiMessageReader.idl";
import "MidiMessageWriter.idl";

namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiEndpointConnection
    {
        //MidiEndpointConnection();

        // Enumeration Assistance ==============================================================================================

        // Get the enumeration device selector for all compatible devices
        static String GetDeviceSelector();
    
        // Id from Windows. This can be used to retrieve the MidiDeviceInformation object with the PnP properties
        String DeviceId{ get; };


        // Message I/O =========================================================================================================

        // Use this to obtain the message reader (one per Endpoint Connection) for processing incoming messages
        // repeat calls to this will return the same instance
        MidiMessageReader GetMessageReader();

        // Use this to obtain the message writer (one per Endpoint Connection) for sending messages
        // repeat calls to this will return the same instance
        MidiMessageWriter GetMessageWriter();


        // notification that there are new messages received. Optional.
        event Windows.Foundation.EventHandler<MidiMessagesReceivedEventArgs> MessagesReceived;

    }
}