// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

//#include "namespace_defs.h"

// NOTE: This class needs to be thread-safe with read/write locks

namespace Windows.Devices.Midi2
{
    unsealed runtimeclass MidiMessageBuffer : Windows.Foundation.IMemoryBuffer
    {

        static MidiMessageBuffer Create(UInt32 sizeInBytes);

        
    };
}