// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiGroup.idl";
import "MidiChannel.idl";

import "MidiUmpMessageTypeEnum.idl";

import "IMidiEndpointMessageListener.idl";

namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiMessageTypeEndpointListener : IMidiEndpointMessageListener
    {
        MidiMessageTypeEndpointListener();

        IVector<MidiUmpMessageType> IncludeMessageTypes{ get; };
    }
}