// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

//#include "namespace_defs.h"

// NOTE: This class needs to be thread-safe with read/write locks

// TODO: Still need to decide if this is needed or if the MemoryBuffer type will suffice.

import "IMidiUmp.idl";


namespace Windows.Devices.Midi2
{
    // this could end up in the SDK instead.

    unsealed runtimeclass MidiMessageBuffer : Windows.Foundation.IMemoryBuffer
    {
        static MidiMessageBuffer Create(UInt32 sizeInBytes);

        // polymorphic. Will return the correct type of UMP
//        MidiUmp GetUmp(UInt32 position);

        // todo: implement an IMidiBufferByteAccess-type of interface in COM to enable more direct manipulation of bytes, words, structs


    };
}