// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// This is the moral equivalent of an input "port" in MIDI 1.0. MIDI 2.0 UMP Endpoints are
// almost always bidirectional.

import "MidiEndpointConnection.idl";
import "IMidiInputConnection.idl";
import "IMidiMessageReceivedEventSource.idl";

namespace Windows.Devices.Midi2
{

    [default_interface]
    runtimeclass MidiInputEndpointConnection : Windows.Devices.Midi2.MidiEndpointConnection, 
                                               Windows.Devices.Midi2.IMidiInputConnection,
                                               Windows.Devices.Midi2.IMidiMessageReceivedEventSource

    {
        // Get the enumeration device selector for all compatible devices
        static String GetDeviceSelectorForInput();



    }
}