// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Windows.Devices.Midi2
{
    // the size in MIDI Words.

    enum MidiUmpSize
    {
        Ump32 = 1,
        Ump64 = 2,
        Ump96 = 3,
        Ump128 = 4,
    };
}