// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiClock
    {
        // gets the current MIDI timestamp
        static UInt64 GetMidiTimestamp();

        // returns the units per second for the timestamp
        static UInt64 GetMidiTimestampFrequency();
    }
}

