// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// this event is just a signal to the client to read from the midimessagereader for the endpointconnection
// This avoids copying data, and provides a lot more flexibility.


//import "IMidiInputConnection.idl";
import "IMidiUmp.idl";

namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiMessagesReceivedEventArgs
    {
        MidiMessagesReceivedEventArgs();

        // TODO

        //IMidiInputConnection Source{ get; };

 //       IMidiUmp Ump{ get; };

    }
}