// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h";
MIDI_IDL_IMPORT

// wraps the UMP type so we still quickly read/write packed data appropriately

import "IMidiUmp.idl";

namespace Windows.Devices.Midi2
{
	[MIDI_API_CONTRACT(1)]
	unsealed runtimeclass MidiUmp64 : IMidiUmp
	{
		MidiUmp64();
		MidiUmp64(UInt64 timestamp, UInt32 word0, UInt32 word1);
		MidiUmp64(UInt64 timestamp, UInt32[] words);

		UInt32 Word0{ get; set; };
		UInt32 Word1{ get; set; };
	};
}
