// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiEndpointConnectOptions
    {
        MidiEndpointConnectOptions();

        // TODO: Probably need options here to disable initial FB and other info queries upon connection?

        Boolean DisableProcessingFunctionBlockInformationMessages { get; set; };
        Boolean DisableProcessingEndpointInformationMessages { get; set; };


        static MidiEndpointConnectOptions Default{ get; };
    }
}