// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// 

namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiMessageBuffer
    {
        MidiMessageBuffer();

        // TODO: Once the user-mode x-proc circular buffer code is checked in, We'll need a high-performance way 
        // to enable accessing the memory mapped buffers from the service but in a way that is compliant with 
        // WinRT (so can't just throw around raw pointers)


        // likely similar to IMemoryBuffer (and may implement that interface for compatibility), but works on 
        // 32 bit MIDI Words and with the existing buffer memory, not new memory


    }
}