// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services Client SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// 

namespace Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiTransports
    {
        String GetTransportProperties(String transportId, String configurationJson);

        void UpdateTransport(String transportId, String configurationJson);
    }
}