
import "oaidl.idl";
import "ocidl.idl";

import "MidiAbstraction.idl";

[
    // Make sure the uuid here is the same as declared in dllmain.h
    uuid(18675309-734b-494c-8c73-d9ae45faa4a7),
    version(1.0),
]
library Midi2LoopbackTransportAbstractionLib
{
    importlib("stdole2.tlb");

    // Make sure this is unique to your class
    [uuid(f7f838a3-b996-4e06-ac00-51625e595dd5), version(1.0)]
        coclass Midi2LoopbackTransportAbstraction
    {
        [default] interface IMidiAbstraction;
    }
};