// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


// represents a MIDI 2.0 Property Exchange Property

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiProperty
    {
        MidiProperty();


        String RawJson{ get; };




    }
}