// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2
{
    // this is the direction as specified in the spec, so it is 
    // from the POV of the function block, not from the OS. IOW, 
    // Input here means the device FB *receives* messages that
    // are sent through Windows
    enum MidiFunctionBlockDirection
    {
        FunctionBlockDirectionInput = 0x1,
        FunctionBlockDirectionOutput = 0x2,
        FunctionBlockDirectionBidirectional = 0x3
    };
}