// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "MidiMessageType.idl";

namespace Microsoft.Devices.Midi2
{
    [default_interface]
    runtimeclass UmpUtilities
    {
        UmpUtilities();


        static MidiMessageType GetMessageTypeFromFirstWord(UInt32 firstWord);

        static Int16 GetUmpLengthInWordsFromFirstWord(UInt32 firstWord);



    }
}