// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    // What a host does when an unknown remote client asks to connect.
    [contract(MidiTransportsNetworkApiContract, 1)]
    enum MidiNetworkRemoteClientPolicy
    {
        // any remote client which is not on the deny list is admitted
        AllowAny = 0,

        // the host holds the invitation until the user approves or denies the client
        RequireApproval = 1,
    };
}
