// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



namespace Windows.Devices.Midi2.Enumeration
{
    [contract(MidiEnumerationApiContract, 1)]
    
    [interface_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointUserSuppliedInfo", UUID_IMidiEndpointUserSuppliedInfo)]
    [constructor_name("Windows.Devices.Midi2.Enumeration.IMidiEndpointUserSuppliedInfoFactory", UUID_IMidiEndpointUserSuppliedInfoFactory)]
    runtimeclass MidiEndpointUserSuppliedInfo
    {
        MidiEndpointUserSuppliedInfo();
        MidiEndpointUserSuppliedInfo(
            String name, 
            String imageFileName, 
            Boolean requiresNoteOffTranslation,
            UInt16 recommendedControlChangeAutomationIntervalMilliseconds,
            Boolean supportsMidiPolyphonicExpression,
            Int64 customMidiOutgoingLatencyTicks,
            Boolean useCustomMidiOutgoingLatencyTicksForScheduling
        );

        [noexcept] Boolean IsReadOnly { get; };

        [noexcept] String Name;
        [noexcept] String Description;

        [noexcept] String ImageFileName;

        [noexcept] Boolean RequiresNoteOffTranslation;
        [noexcept] UInt16 RecommendedControlChangeAutomationIntervalMilliseconds;
        [noexcept] Boolean SupportsMidiPolyphonicExpression;

        [noexcept] Int64 CustomMidiOutgoingLatencyTicks;
        [noexcept] Boolean UseCustomMidiOutgoingLatencyTicksForScheduling;

        // supplied by the transport, not by the user, and reported here so an application can show
        // what compensation is in effect without having to read device properties itself
        [noexcept] Int64 CalculatedMidiOutgoingLatencyTicks;
    };
}
