// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiBluetoothProtocolEnum.idl";
import "IMidiServiceTransportPluginConfig.idl";

namespace Windows.Devices.Midi2.Transports.Bluetooth
{
    [contract(MidiTransportsBluetoothApiContract, 1)]

    // Publishing this PC is the one place a Bluetooth MIDI protocol is chosen rather than
    // reported, because a peripheral has to advertise as one or the other.
    [interface_name("Windows.Devices.Midi2.Transports.Bluetooth.IMidiBluetoothPeripheralConfig", UUID_IMidiBluetoothPeripheralConfig)]
    [constructor_name("Windows.Devices.Midi2.Transports.Bluetooth.IMidiBluetoothPeripheralConfigFactory", UUID_IMidiBluetoothPeripheralConfigFactory)]
    runtimeclass MidiBluetoothPeripheralConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiBluetoothPeripheralConfig();
        MidiBluetoothPeripheralConfig(MidiBluetoothProtocol protocol);

        [noexcept] MidiBluetoothProtocol Protocol;

        // Saving with this false is how a caller stops the peripheral being published on the next
        // service start, since stopping it is otherwise only for this session.
        [noexcept] Boolean IsEnabled;
    }
}
