// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkAdvertisedHostRemovedEventArgs", UUID_IMidiNetworkAdvertisedHostRemovedEventArgs)]
    runtimeclass MidiNetworkAdvertisedHostRemovedEventArgs
    {
        [noexcept] String HostDeviceId { get; };

        // "instance._midi2._udp.local", for logging and for matching against a stored entry.
        [noexcept] String FullName{ get; };
    }
}

