// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiGroup.idl";

namespace Windows.Devices.Midi2.Utilities.SysExTransfer
{
    [contract(MidiSysExTransferUtilityApiContract,1)]
    [interface_name("Windows.Devices.Midi2.Utilities.SysExTransfer.IMidiSystemExclusiveReceivedEventArgs", UUID_IMidiSystemExclusiveReceivedEventArgs)]
    runtimeclass MidiSystemExclusiveReceivedEventArgs
    {
        Windows.Devices.Midi2.MidiGroup Group{ get; };

        // The received bytes, including the F0 and F7 framing, so they may be written directly
        // to a .syx file. A single event may carry more than one complete message.
        Windows.Foundation.Collections.IVectorView<UInt8> Bytes{ get; };

        // True when this block does not contain a matched F0/F7 pair, meaning it is a fragment
        // of a larger message rather than one or more whole messages.
        Boolean IsPartial{ get; };
    };
}
