// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "IMidiServiceTransportPluginConfig.idl";

namespace Windows.Devices.Midi2.Transports.Rtp
{
    [contract(MidiTransportsRtpApiContract, 1)]

    // Send with MidiRtpTransportManager.RemoveRtpHostAsync, and save with
    // MidiServiceTransportPluginConfigManager.SaveUpdate to take the host and its remembered
    // decisions out of the configuration file
    [interface_name("Windows.Devices.Midi2.Transports.Rtp.IMidiRtpHostRemovalConfig", UUID_IMidiRtpHostRemovalConfig)]
    [constructor_name("Windows.Devices.Midi2.Transports.Rtp.IMidiRtpHostRemovalConfigFactory", UUID_IMidiRtpHostRemovalConfigFactory)]
    runtimeclass MidiRtpHostRemovalConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiRtpHostRemovalConfig();
        MidiRtpHostRemovalConfig(Guid hostId);

        [noexcept] Guid HostId{ get; set; };
    }
}
