// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


namespace Windows.Devices.Midi2.Utilities.Sequencing
{
    // Bars and beats are counted from one, the way a player and a score show them, not from zero.
    [contract(MidiSequencingUtilityApiContract,1)]
    struct MidiSequenceBarPosition
    {
        UInt32 Bar;
        UInt32 Beat;
        UInt32 TicksIntoBeat;
    };
}
