// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\..\..\Inc\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";



import "IMidiServiceTransportPluginConfig.idl";

namespace Windows.Devices.Midi2.Transports.Network
{
    [contract(MidiTransportsNetworkApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkRemoteClientApprovalConfig", UUID_IMidiNetworkRemoteClientApprovalConfig)]
    [constructor_name("Windows.Devices.Midi2.Transports.Network.IMidiNetworkRemoteClientApprovalConfigFactory", UUID_IMidiNetworkRemoteClientApprovalConfigFactory)]
    runtimeclass MidiNetworkRemoteClientApprovalConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiNetworkRemoteClientApprovalConfig();

        MidiNetworkRemoteClientApprovalConfig(
            Guid hostId, 
            String remoteClientName,
            String remoteClientProductInstanceId,
            Boolean approve, 
            Boolean restrictScopeToThisRequestOnly);


        [noexcept] Guid HostId{ get; set; };

        [noexcept] String RemoteClientName{ get; set; };
        [noexcept] String RemoteClientProductInstanceId{ get; set; };
        [noexcept] Boolean Approve{ get; set; };
        [noexcept] Boolean ScopeIsThisRequestOnly{ get; set; };

    }
}
