// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// This file needs to be 100% compatible with the C++/CX definitions for 
// WinRT MIDI 1.0. This is here for repointing the older classes to the
// new service and Windows MIDI Services in general. 

#include "winrt_midi1_midl_defines.h"
MIDI_IDL_IMPORT

import "IMidiMessage.idl";

namespace Windows.Devices.Midi
{
    [MIDI1_SHIM_API_CONTRACT(1)]
    [marshaling_behavior(agile)]
    runtimeclass MidiSystemExclusiveMessage : [default] IMidiMessage
    {
        MidiSystemExclusiveMessage(Windows.Storage.Streams.IBuffer rawData);
    }
}