// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// This file needs to be 100% compatible with the C++/CX definitions for 
// WinRT MIDI 1.0. This is here for repointing the older classes to the
// new service and Windows MIDI Services in general. 

#include "winrt_midi1_midl_defines.h"
MIDI_IDL_IMPORT

import "IMidiMessage.idl";

namespace MIDI_ROOT_NAMESPACE_IDL
{
    [MIDI1_SHIM_API_CONTRACT(1)]
    [marshaling_behavior(agile)]
    [interface_name(MIDI_MIDL_INTERFACE_NAME(IMidiPitchBendChangeMessage), 29DF4CB1-2E9F-4FAF-8C2B-9CB82A9079CA)]
    runtimeclass MidiPitchBendChangeMessage : IMidiMessage
    {
        MidiPitchBendChangeMessage(UInt8 channel, UInt16 bend);

        UInt8 Channel{ get; };
        UInt16 Bend{ get; };
    }
}