// TODO: Figure out if we should split this to plug into the existing Windows.Devices.Enumeration 
// and the underlying device enumerator / device tree code. 

// TODO: Refer to the UMP lib

namespace MidiEnumeration
{
    [default_interface]
    runtimeclass MidiDeviceInformation
    {
        string Id;                                  // Id of the device
        string Name;                                // Name of the device as supplied by the user. Defaults to DeviceSuppliedName
        string DeviceSuppliedName;                  // Name of the device as supplied by the device. Cannot be changed
        string TransportType;                       // type of transport: BLE, USB etc. as defined by the transport
        string IconPath;                            // device icon/image as configured by user

        string ManufacturerName;                    // Name of the manufacturer of the device

        IDictionary<string, object> Properties;     // Additional properties like the driver information, etc.


        public static MidiDeviceWatcher CreateWatcher();


        public static FindAll();
        public static FindAllAsync();

        public static FindAll(string transportType);
        public static FindAllAsync(string transportType);
    };

    interface IMidiDeviceEnumerator
    {
        // TODO
    };

    [default_interface]
    runtimeclass MidiDeviceInformationCollection
    {
        // TODO
    };


    [default_interface]
    runtimeclass MidiDeviceWatcher
    {
        // TODO
    };
}