//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Devices.Midi2.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Devices.Midi2.ConsoleApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility application for interacting with Windows MIDI Services from the command line. Requires that Windows MIDI Services is installed and enabled on the PC..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Console.
        /// </summary>
        internal static string AppShortName {
            get {
                return ResourceManager.GetString("AppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows MIDI Services Console.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a report, typically for a support request, or for use when filing a bug.
        /// </summary>
        internal static string CommandDiagnosticsReportDescription {
            get {
                return ResourceManager.GetString("CommandDiagnosticsReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations on a single endpoint, including reporting details, sending messages, monitoring, and more. If you leave out the Instance Id, you will be prompted to select from a list..
        /// </summary>
        internal static string CommandEndpointDescription {
            get {
                return ResourceManager.GetString("CommandEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List out all properties for a given endpoint.
        /// </summary>
        internal static string CommandEndpointPropertiesDescription {
            get {
                return ResourceManager.GetString("CommandEndpointPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate (list) endpoints and transports.
        /// </summary>
        internal static string CommandEnumerateDescription {
            get {
                return ResourceManager.GetString("CommandEnumerateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List MIDI UMP endpoints visible to Windows MIDI Services-aware applications.
        /// </summary>
        internal static string CommandEnumerateEndpointsDescription {
            get {
                return ResourceManager.GetString("CommandEnumerateEndpointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List MIDI 1.0 endpoints as seen in apps using older MIDI APIs.
        /// </summary>
        internal static string CommandEnumerateLegacyEndpointsDescription {
            get {
                return ResourceManager.GetString("CommandEnumerateLegacyEndpointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all MIDI transport plugins installed on this PC..
        /// </summary>
        internal static string CommandEnumerateTransportPluginsDescription {
            get {
                return ResourceManager.GetString("CommandEnumerateTransportPluginsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors a UMP endpoint for incoming messages.
        /// </summary>
        internal static string CommandMonitorEndpointDescription {
            get {
                return ResourceManager.GetString("CommandMonitorEndpointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a single message to a UMP endpoint as a list of up to four 32 bit MIDI words.
        /// </summary>
        internal static string CommandSendMessageDescription {
            get {
                return ResourceManager.GetString("CommandSendMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends a text file of UMP MIDI words to the specified endpoint. See arguments and options for format and delimiters..
        /// </summary>
        internal static string CommandSendMessagesFileDescription {
            get {
                return ResourceManager.GetString("CommandSendMessagesFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform operations on the service, such as checking to see if it is running, pinging the standard ping loopback, etc..
        /// </summary>
        internal static string CommandServiceDescription {
            get {
                return ResourceManager.GetString("CommandServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping the MIDI Windows Service.
        /// </summary>
        internal static string CommandServicePingDescription {
            get {
                return ResourceManager.GetString("CommandServicePingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to see if the Windows Service is running.
        /// </summary>
        internal static string CommandServiceStatusDescription {
            get {
                return ResourceManager.GetString("CommandServiceStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current MIDI clock timestamp value.
        /// </summary>
        internal static string CommandTimeDescription {
            get {
                return ResourceManager.GetString("CommandTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch endpoints for add/remove and PnP property change notifications.
        /// </summary>
        internal static string CommandWatchEndpointsDescription {
            get {
                return ResourceManager.GetString("CommandWatchEndpointsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string CommonTableHeaderIndex {
            get {
                return ResourceManager.GetString("CommonTableHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an endpoint.
        /// </summary>
        internal static string EndpointPickerPleaseSelectEndpoint {
            get {
                return ResourceManager.GetString("EndpointPickerPleaseSelectEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerating endpoints failed. Is the MIDI service running?.
        /// </summary>
        internal static string ErrorEnumEndpointsFailed {
            get {
                return ResourceManager.GetString("ErrorEnumEndpointsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WinRT types could not be activated. Is Windows MIDI Services installed?.
        /// </summary>
        internal static string ErrorGeneralFailReasonWinRTActivation {
            get {
                return ResourceManager.GetString("ErrorGeneralFailReasonWinRTActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping test failed.
        /// </summary>
        internal static string ErrorPingTestFailed {
            get {
                return ResourceManager.GetString("ErrorPingTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping result summary is null.
        /// </summary>
        internal static string ErrorPingTestFailReasonSummaryNull {
            get {
                return ResourceManager.GetString("ErrorPingTestFailReasonSummaryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create endpoint connection. Is the endpoint Id correct? Is the type of endpoint correct?.
        /// </summary>
        internal static string ErrorUnableToCreateEndpointConnection {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateEndpointConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create session..
        /// </summary>
        internal static string ErrorUnableToCreateSession {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open specified endpoint..
        /// </summary>
        internal static string ErrorUnableToOpenEndpoint {
            get {
                return ResourceManager.GetString("ErrorUnableToOpenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string GenericAverage {
            get {
                return ResourceManager.GetString("GenericAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clock ticks.
        /// </summary>
        internal static string GenericClockTicks {
            get {
                return ResourceManager.GetString("GenericClockTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string GenericCount {
            get {
                return ResourceManager.GetString("GenericCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to microseconds.
        /// </summary>
        internal static string GenericMicroseconds {
            get {
                return ResourceManager.GetString("GenericMicroseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string GenericMilliseconds {
            get {
                return ResourceManager.GetString("GenericMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responses.
        /// </summary>
        internal static string GenericResponses {
            get {
                return ResourceManager.GetString("GenericResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string GenericTotal {
            get {
                return ResourceManager.GetString("GenericTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not result in a valid UMP.
        /// </summary>
        internal static string MessageValidationErrorInvalidUmp {
            get {
                return ResourceManager.GetString("MessageValidationErrorInvalidUmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide at least one valid 32-bit MIDI word.
        /// </summary>
        internal static string MessageValidationErrorTooFewWords {
            get {
                return ResourceManager.GetString("MessageValidationErrorTooFewWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide up to four valid 32-bit MIDI words, comprising a single valid UMP..
        /// </summary>
        internal static string MessageValidationErrorTooManyWords {
            get {
                return ResourceManager.GetString("MessageValidationErrorTooManyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string MonitorEndpointResultTableColumnHeaderTimestamp {
            get {
                return ResourceManager.GetString("MonitorEndpointResultTableColumnHeaderTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Words Received.
        /// </summary>
        internal static string MonitorEndpointResultTableColumnHeaderWordsReceived {
            get {
                return ResourceManager.GetString("MonitorEndpointResultTableColumnHeaderWordsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape key pressed. Monitoring terminated..
        /// </summary>
        internal static string MonitorEscapePressedMessage {
            get {
                return ResourceManager.GetString("MonitorEscapePressedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring incoming messages on.
        /// </summary>
        internal static string MonitorMonitoringOnEndpointLabel {
            get {
                return ResourceManager.GetString("MonitorMonitoringOnEndpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press escape to stop monitoring..
        /// </summary>
        internal static string MonitorPressEscapeToStopMonitoringMessage {
            get {
                return ResourceManager.GetString("MonitorPressEscapeToStopMonitoringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string MonitorSessionNameSuffix {
            get {
                return ResourceManager.GetString("MonitorSessionNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to annotate key messages written to the file. Annotations begin with the # sign and are written on the line before the UMP line..
        /// </summary>
        internal static string ParameterCaptureMessagesAnnotate {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesAnnotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to echo the incoming messages to the screen. False to simply show capture progress..
        /// </summary>
        internal static string ParameterCaptureMessagesEcho {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter to separate fields. Valid values include:.
        /// </summary>
        internal static string ParameterCaptureMessagesFieldDelimiter {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesFieldDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format for the fields. Hex prefix is &quot;0x&quot;, suffix is &quot;h&quot;. Decimal values do not have leading zeroes. Valid values include:.
        /// </summary>
        internal static string ParameterCaptureMessagesFieldFormat {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for the messages. Valid values include:.
        /// </summary>
        internal static string ParameterCaptureMessagesFilter {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to include the timestamp as the first field for each message..
        /// </summary>
        internal static string ParameterCaptureMessagesIncludeTimestamps {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesIncludeTimestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the file to write to. The file must not already exist..
        /// </summary>
        internal static string ParameterCaptureMessagesOutputFile {
            get {
                return ResourceManager.GetString("ParameterCaptureMessagesOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint Id (also called a Device Instance Id) of the endpoint as used in Windows.Devices.Enumeration. This includes the MIDI interface GUID at the end of the string. You can find the Endpoint Ids by enumerating endpoints through this app. If you leave off the Id, we&apos;ll re-enumerate them and provide a list for you to pick from..
        /// </summary>
        internal static string ParameterCommonEndpointIdDescription {
            get {
                return ResourceManager.GetString("ParameterCommonEndpointIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction of data flow for the endpoints to list.
        /// </summary>
        internal static string ParameterEnumEndpointsDirection {
            get {
                return ResourceManager.GetString("ParameterEnumEndpointsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the UMP Endpoint Id in the output.
        /// </summary>
        internal static string ParameterEnumEndpointsIncludeEndpointId {
            get {
                return ResourceManager.GetString("ParameterEnumEndpointsIncludeEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the diagnostic loopback endpoints.
        /// </summary>
        internal static string ParameterEnumEndpointsIncludeLoopbackEndpoints {
            get {
                return ResourceManager.GetString("ParameterEnumEndpointsIncludeLoopbackEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include more details for each endpoint.
        /// </summary>
        internal static string ParameterEnumEndpointsVerboseOutput {
            get {
                return ResourceManager.GetString("ParameterEnumEndpointsVerboseOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction of data flow for the endpoints to list.
        /// </summary>
        internal static string ParameterEnumLegacyEndpointsDirection {
            get {
                return ResourceManager.GetString("ParameterEnumLegacyEndpointsDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include the MIDI 1.0 Endpoint Id (the Port Id) in the output.
        /// </summary>
        internal static string ParameterEnumLegacyEndpointsIncludeEndpointId {
            get {
                return ResourceManager.GetString("ParameterEnumLegacyEndpointsIncludeEndpointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction of the endpoint referenced by the Id. If this doesn&apos;t match the endpoint type, the connection will fail..
        /// </summary>
        internal static string ParameterMonitorEndpointDirectionDescription {
            get {
                return ResourceManager.GetString("ParameterMonitorEndpointDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for a single incoming message only.
        /// </summary>
        internal static string ParameterMonitorEndpointSingleMessage {
            get {
                return ResourceManager.GetString("ParameterMonitorEndpointSingleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all messages as they come in.
        /// </summary>
        internal static string ParameterMonitorEndpointVerbose {
            get {
                return ResourceManager.GetString("ParameterMonitorEndpointVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of times to send this message.
        /// </summary>
        internal static string ParameterSendMessageCount {
            get {
                return ResourceManager.GetString("ParameterSendMessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay, in milliseconds, between messages. This is an approximate delay. Specify 0 for no delay..
        /// </summary>
        internal static string ParameterSendMessageDelayBetweenMessages {
            get {
                return ResourceManager.GetString("ParameterSendMessageDelayBetweenMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The direction of the endpoint referenced by the Id. If this doesn&apos;t match the endpoint type, the connection will fail..
        /// </summary>
        internal static string ParameterSendMessageEndpointDirectionDescription {
            get {
                return ResourceManager.GetString("ParameterSendMessageEndpointDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path and filename of the text file to send. This can include lines which begin with # for a comment, or are completely empty for spacing. Remaining lines must be valid delimited (big-endian) hexadecimal UMP words..
        /// </summary>
        internal static string ParameterSendMessagesFileCommandFile {
            get {
                return ResourceManager.GetString("ParameterSendMessagesFileCommandFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter between fields. Set to &quot;Auto&quot; to have this evaluated for each line. Valid values include:.
        /// </summary>
        internal static string ParameterSendMessagesFileFieldDelimiter {
            get {
                return ResourceManager.GetString("ParameterSendMessagesFileFieldDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non-stream messages, replace the second nibble with the specified new group index. Helpful when sending previously-recorded SysEx to a new group..
        /// </summary>
        internal static string ParameterSendMessagesFileReplaceGroup {
            get {
                return ResourceManager.GetString("ParameterSendMessagesFileReplaceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose output as the messages are sent.
        /// </summary>
        internal static string ParameterSendMessagesFileVerbose {
            get {
                return ResourceManager.GetString("ParameterSendMessagesFileVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp offset in microseconds (1/1,000,000 of a second) to use when scheduling this message..
        /// </summary>
        internal static string ParameterSendMessageTimestampOffsetMicroseconds {
            get {
                return ResourceManager.GetString("ParameterSendMessageTimestampOffsetMicroseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data format for the individual words. Valid values include:.
        /// </summary>
        internal static string ParameterSendMessageWordFormat {
            get {
                return ResourceManager.GetString("ParameterSendMessageWordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit MIDI words, typically in hexadecimal 0x00000000 format. Big-endian, same as the MIDI protocol wire format. Use the parameter name in front of each word sent..
        /// </summary>
        internal static string ParameterSendMessageWords {
            get {
                return ResourceManager.GetString("ParameterSendMessageWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of times to ping the MIDI Windows Service.
        /// </summary>
        internal static string ParameterServicePingCount {
            get {
                return ResourceManager.GetString("ParameterServicePingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ping timeout in milliseconds. Does not include the session and connection creation and teardown time..
        /// </summary>
        internal static string ParameterServicePingTimeout {
            get {
                return ResourceManager.GetString("ParameterServicePingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True to show details from each ping request and response..
        /// </summary>
        internal static string ParameterServicePingVerbose {
            get {
                return ResourceManager.GetString("ParameterServicePingVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report additional details about the service.
        /// </summary>
        internal static string ParameterServiceStatusVerbose {
            get {
                return ResourceManager.GetString("ParameterServiceStatusVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string PingResultTableColumnHeaderPing {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client
        ///Receive
        ///Timestamp.
        /// </summary>
        internal static string PingResultTableColumnHeaderReceiveTimestamp {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderReceiveTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client
        ///Round Trip
        ///Microseconds.
        /// </summary>
        internal static string PingResultTableColumnHeaderRoundTripMicroseconds {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderRoundTripMicroseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client
        ///Round Trip
        ///Milliseconds.
        /// </summary>
        internal static string PingResultTableColumnHeaderRoundTripMilliseconds {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderRoundTripMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client
        ///Round Trip
        ///System Ticks.
        /// </summary>
        internal static string PingResultTableColumnHeaderRoundTripTicks {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderRoundTripTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client
        ///Send
        ///Timestamp.
        /// </summary>
        internal static string PingResultTableColumnHeaderSendTimestamp {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderSendTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service
        ///Receive/Send
        ///System Ticks.
        /// </summary>
        internal static string PingResultTableColumnHeaderServiceBreakdown {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderServiceBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service
        ///Receive
        ///Timestamp.
        /// </summary>
        internal static string PingResultTableColumnHeaderServiceTimestamp {
            get {
                return ResourceManager.GetString("PingResultTableColumnHeaderServiceTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string SendMessageResultTableColumnHeaderTimestamp {
            get {
                return ResourceManager.GetString("SendMessageResultTableColumnHeaderTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Words Sent.
        /// </summary>
        internal static string SendMessageResultTableColumnHeaderWordsSent {
            get {
                return ResourceManager.GetString("SendMessageResultTableColumnHeaderWordsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending MIDI message(s) through.
        /// </summary>
        internal static string SendMessageSendingThroughEndpointLabel {
            get {
                return ResourceManager.GetString("SendMessageSendingThroughEndpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string SendMessageSessionNameSuffix {
            get {
                return ResourceManager.GetString("SendMessageSessionNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating session and opening endpoint....
        /// </summary>
        internal static string StatusCreatingSessionAndOpeningEndpoint {
            get {
                return ResourceManager.GetString("StatusCreatingSessionAndOpeningEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Type.
        /// </summary>
        internal static string TableColumnHeaderCommonDetailedMessageType {
            get {
                return ResourceManager.GetString("TableColumnHeaderCommonDetailedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Type.
        /// </summary>
        internal static string TableColumnHeaderCommonMessageType {
            get {
                return ResourceManager.GetString("TableColumnHeaderCommonMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string TableColumnHeaderCommonTimestamp {
            get {
                return ResourceManager.GetString("TableColumnHeaderCommonTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified group index is invalid. Specify a group index between 0 and 15..
        /// </summary>
        internal static string ValidationErrorInvalidGroup {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a count &gt; 0..
        /// </summary>
        internal static string ValidationErrorInvalidMessageCount {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidMessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified ping count is too high. Please provide a value &lt;= 255..
        /// </summary>
        internal static string ValidationErrorPingCountTooHigh {
            get {
                return ResourceManager.GetString("ValidationErrorPingCountTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified ping count is too low. Please provide a value &gt; 0..
        /// </summary>
        internal static string ValidationErrorPingCountTooLow {
            get {
                return ResourceManager.GetString("ValidationErrorPingCountTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified timeout is too low. Please provide a value &gt;= 10ms..
        /// </summary>
        internal static string ValidationErrorPingTimeoutTooLow {
            get {
                return ResourceManager.GetString("ValidationErrorPingTimeoutTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape key pressed. Shutting down watcher..
        /// </summary>
        internal static string WatcherEscapePressedMessage {
            get {
                return ResourceManager.GetString("WatcherEscapePressedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press escape to stop monitoring..
        /// </summary>
        internal static string WatcherPressEscapeToStopWatchingMessage {
            get {
                return ResourceManager.GetString("WatcherPressEscapeToStopWatchingMessage", resourceCulture);
            }
        }
    }
}
