// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Devices.Midi2.Messages
{
    enum Midi2ChannelVoiceMessageStatus
    {
        RegisteredPerNoteController =   0x0,
        AssignablePerNoteController =   0x1,

        RegisteredController =          0x2,
        AssignableController =          0x3,

        RelativeRegisteredController =  0x4,
        RelativeAssignableController =  0x5,

        PerNotePitchBend =              0x6,
        //Unused7 = 0x7,

        NoteOff =                       0x8,
        NoteOn =                        0x9,
        PolyPressure =                  0xA,
        ControlChange =                 0xB,
        ProgramChange =                 0xC,
        ChannelPressure =               0xD,
        PitchBend =                     0xE,
        PerNoteManagement =             0xF,
    };
}