// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "Midi1ChannelVoiceMessageStatusEnum.idl";
import "Midi2ChannelVoiceMessageStatusEnum.idl";


namespace Microsoft.Windows.Devices.Midi2.Messages
{
    static runtimeclass MidiMessageConverter
    {
        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1Message(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 statusByte
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1Message(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 statusByte,
            UInt8 dataByte1
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1Message(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            UInt8 statusByte,
            UInt8 dataByte1,
            UInt8 dataByte2
        );


        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1ChannelPressureMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiChannelPressureMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1NoteOffMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiNoteOffMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1NoteOnMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiNoteOnMessage originalMessage);

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1PitchBendChangeMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiPitchBendChangeMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1PolyphonicKeyPressureMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiPolyphonicKeyPressureMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1ProgramChangeMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiProgramChangeMessage originalMessage
        );


        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1TimeCodeMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiTimeCodeMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1SongPositionPointerMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiSongPositionPointerMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1SongSelectMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiSongSelectMessage originalMessage
        );


        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1TuneRequestMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiTuneRequestMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1TimingClockMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiTimingClockMessage originalMessage
        );


        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1StartMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiStartMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1ContinueMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiContinueMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1StopMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiStopMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1ActiveSensingMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiActiveSensingMessage originalMessage
        );

        static Microsoft.Windows.Devices.Midi2.MidiMessage32 ConvertMidi1SystemResetMessage(
            UInt64 timestamp,
            Microsoft.Windows.Devices.Midi2.MidiGroup group,
            Windows.Devices.Midi.MidiSystemResetMessage originalMessage
        );
    };
}