// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Windows.Devices.Midi2.Messages
{
    enum MidiSystemExclusive8Status
    {
        CompleteMessageInSingleMessagePacket =  0x0,
        StartMessagePacket =                    0x1,
        ContinueMessagePacket =                 0x2,
        EndMessagePacket =                      0x3,
    };
}