// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


namespace Windows.Devices.Midi2.ServiceConfig
{
    [contract(MidiServiceConfigApiContract, 1)]
    [uuid(UUID_IMidiServiceTransportPluginConfig), version(1.0)]
    interface IMidiServiceTransportPluginConfig
    {
        Guid TransportId { get; };

        Windows.Data.Json.JsonObject ConfigJson{ get; };
    }
}