// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"

namespace Windows.Devices.Midi2.ServiceConfig
{
    [contractversion(1)]
    apicontract MidiServiceConfigApiContract { };
}

