
namespace Windows.Devices.Midi2
{
    [default_interface]
    unsealed runtimeclass MidiMasterReferenceClock
    {
        // TODO: This will implement IReferenceClock and so can inherit its features and use cases



    };
}