import "Ump.idl";

namespace Windows.Devices.Midi2.Messages
{

    [default_interface]
    runtimeclass Ump128 : Ump
    {
        UInt32 Word1;
        UInt32 Word2;
        UInt32 Word3;

        Ump128();

        static Ump128 FromWords(UInt32 word0, UInt32 word1, UInt32 word2, UInt32 word3);
    };
}