// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "oaidl.idl";
import "ocidl.idl";

import "MidiAbstraction.idl";

[
    uuid(f9d8d093-27d4-44b8-a458-f057603b4115),
    version(1.0),
]
library Midi2EndpointMetadataListenerTransformLib
{
    importlib("stdole2.tlb");

    [uuid(597b9a96-9724-4091-9a7b-5f646bc4a4a6), version(1.0)]
    coclass Midi2EndpointMetadataListenerTransform
    {
        [default] interface IMidiDataTransform;
    }
};

