// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "oaidl.idl";
import "ocidl.idl";

import "WindowsMidiServices.idl";

#include "midi_group_transform_clsid.h"

[
    uuid(LIBID_RAW_Midi2GroupTransform),
    version(1.0),
]
library Midi2GroupTransformLib
{
    importlib("stdole2.tlb");

    [uuid(CLSID_RAW_Midi2GroupTransform), version(1.0)]
    coclass Midi2GroupTransform
    {
        [default] interface IMidiDataTransform;
    }
};

