// Common structure for ALL device types in MIDI, regardless of transport
namespace Windows.Devices.Enumeration
{
    [default_interface]
    unsealed runtimeclass MidiDeviceInformation
    {
        String Id;
        String Name;

        // User-supplied Name (if provided, this is what the Name property contains)
        // Today, the DeviceInformation.Properties class is an IReadOnlyDictionary so 
        // if we use the same thing, all the possible properties would need to be added 
        // during enumeration, even if the property information is not yet available.
        // Not sure if the objects contained in the dictionary are immutable or if
        // properties can be changed post-enumeration -- which is needed here.
        // 
        // Property Bag Properties:
        // 
        // Properties Set by System, by the Service
        // ========================================================================
        // Transport Information (USB, BLE, RTP, Network MIDI 2, Virtual, etc.)
        // Stream Data Format: Byte Stream (MIDI 1) or UMP
        // 
        // USB Properties set by Driver through the Service
        // Some of these may be displayed to the user in the control panel or in apps
        // and others are needed by developers to be able to target specific
        // devices in your config, update, and librarian apps
        // ========================================================================
        // Display Name
        // Friendly Name
        // Manufacturer Name
        // iSerial if provided
        // Group Terminal Block info?
        // VID (for identification by manufacturer-specific apps)
        // PID (for identification by manufacturer-specific apps)
        // Driver Provider
        // Driver Date
        // Driver Version
        // Inf Name
        // Bus reported device description
        // 
        //
        // Properties set by UMP Endpoint Discovery Messages
        // These are all optional and may be provided by the endpoint at any point
        // in time. Populated by the service, which sends out a notification when
        // any properties change.
        // ========================================================================
        // UMP Version major, minor
        // Number of Function Blocks (0-32)
        // M2 - MIDI 2.0 Protocol Capability
        // M1 - MIDI 1.0 Protocol Capability
        // RXJR - Receive JR Timestamp Capability
        // TXJR - Transmit JR Timestamp Capability
        // Device Identification Device Manufacturer
        // Device Identification Device Family
        // Device Identification Family Model NUmber
        // Device Identification Software Revision
        // Endpoint Name (max 98 bytes, UTF8)
        //
        // Properties set by product instance ID notification messages
        // ========================================================================
        // Product Instance Id (Up to 16 byte string)
        // 
        // 
        // 
        //
        // Properties set by user, optionally, in the current MIDI configuration
        // ========================================================================
        // Device Name
        // Device Icon Path
        // Device Notes
        // 



        // Collection of function block information instances.
        // Included in this class because we may end up transforming Group Terminal Blocks to 
        // Function Blocks. These are mutable over time.




    };
}




