// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    [MIDI_INTERFACE_UUID("2ebcfa13-585a-4376-8fe1-635784fa7fd4",1.0)]
    interface IMidiServiceMessageProcessingPluginConfiguration
    {
        // we configure plugins on a single endpoint
        String EndpointDeviceId { get; };

        // The Id for this plugin type. It is per-type only
        Guid MessageProcessingPluginId { get; };

        // The instance Id. A single endpoint may have multiples of the same plugin type (a generic filter, for example)
        Guid PluginInstanceId{ get; };

        Boolean IsFromConfigurationFile{ get; };   // true if from the config file. Apps shouldn't normally set this to true

        // the actual changes to be made
        Windows.Data.Json.JsonObject SettingsJson { get; };
    }
}