// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

import "MidiFunctionBlocksUpdatedEventArgs.idl";
import "MidiFunctionBlock.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [MIDI_INTERFACE_UUID("8f231346-d933-4a83-bbcf-9dbd77380f1f",1.0)]
    interface IMidiFunctionBlockDevice
    {

    }
}