// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

import "MidiPacketTypeEnum.idl";
import "MidiMessageTypeEnum.idl";

namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    [MIDI_INTERFACE_UUID("2eb5df8a-d751-4997-bf96-ba9a531fd5ff",1.0)]
    interface IMidiUniversalPacket
    {
        MIDI_TIMESTAMP Timestamp;

        MidiMessageType MessageType;
        MidiPacketType PacketType;

        UInt32 PeekFirstWord();


        IVector<UInt32> GetAllWords();
        UInt8 AppendAllMessageWordsToList(IVector<UInt32> targetList);

        UInt8 FillBuffer(UInt32 byteOffset, Windows.Foundation.IMemoryBuffer buffer);
    };
}