// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// Custom event sinks to provide MIDI 1.0 port-like views into the stream for 
// incoming messages

#include "midl_defines.h"
MIDI_IDL_IMPORT

import "MidiBidirectionalEndpointOpenOptions.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [MIDI_INTERFACE_UUID("8ef0557e-1a53-4ab2-ab80-d36f1a16f33b",1.0)]
    interface IMidiBidirectionalEndpointOpenOptionsUser
    {
        MidiBidirectionalEndpointOpenOptions BidirectionalEndpointOpenOptions { get; set; };
    }
}