// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(19)]
    [MIDI_INTERFACE_UUID("b2417dde-ef35-499b-a89b-0a4c32cc699a",1.0)]
    interface IMidiServiceTransportPluginConfiguration
    {
        // the Id for this transport type
        Guid TransportId { get; };
        Boolean IsFromConfigurationFile{ get; };   // true if from the config file. Apps shouldn't normally set this to true

        // the settings json. This will typically contain operations to create/update/delete
        // individual endpoints. The format of this is specific to each transport in the service
        Windows.Data.Json.JsonObject SettingsJson { get; };
    }
}