// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(19)]
    [default_interface]
    runtimeclass MidiServiceLoopbackEndpointCreationResult
    {
        Boolean Success{ get; };

        Guid AssociationId{ get; };

        String EndpointDeviceIdA { get; };
        String EndpointDeviceIdB{ get; };
    }
}