// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    enum MidiUmpMessageType
    {
        UtilityMessage32 = 0x0,
        SystemCommon32 = 0x1,
        Midi1ChannelVoice32 = 0x2,
        DataMessage64 = 0x3,
        Midi2ChannelVoice64 = 0x4,
        DataMessage128 = 0x5,
        FutureReserved632 = 0x6,
        FutureReserved732 = 0x7,
        FutureReserved864 = 0x8,
        FutureReserved964 = 0x9,
        FutureReservedA64 = 0xA,
        FutureReservedB96 = 0xB,
        FutureReservedC96 = 0xC,
        FlexData128 = 0xD,
        FutureReservedE128 = 0xE,
        UmpStream128 = 0xF
    };
}