// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// Group terminal blocks are being phased out in favor of Function Blocks, but
// will still be found in devices. See MIDI implementation guide and 
// documentation to better understand the relationship between Group Terminal
// Blocks and Function Blocks


#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    enum MidiGroupTerminalBlockProtocol
    {
        Unknown = 0x00,
        Midi1Message64 = 0x01,
        Midi1Message64WithJitterReduction = 0x02,
        Midi1Message128 = 0x03,
        Midi1Message128WithJitterReduction = 0x04,
        Midi2 = 0x11,
        Midi2WithJitterReduction = 0x12
    };
}
