// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(19)]
    [default_interface]
    runtimeclass MidiServiceMessageProcessingPluginInfo
    {
        Guid Id{ get; };           // from registry
        //String RegistryKey{ get; };     // from registry
        //Boolean IsEnabled{ get; };      // from registry


        String Name { get; };           // from component information
        String Description{ get; };     // from component information
        String Author{ get; };          // from component information

        // TBD if we change this to an image type or URI instead
        String SmallImagePath{ get; };        // from component information

        String Version{ get; };

        Boolean SupportsMultipleInstancesPerDevice{ get; };

        //String ServicePluginFileName{ get; };   

        Boolean IsSystemManaged{ get; };                    // True if it can't be added/removed. may get this from the registry
        Boolean IsClientConfigurable{ get; };               // true if we should try to instantiate the config assembly

        String ClientConfigurationAssemblyName { get; };    // this needs to come from the component to prevent registry hacks

    }
}