// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace Windows.Devices.Midi2
{
    // NOTE: the values are different for function blocks and group terminal
    // blocks, so we have to different enumerations

    [MIDI_API_CONTRACT(19)]
    enum MidiServiceConfigurationResponseStatus
    {
        Success = 0,

        ErrorTargetNotFound = 404,

        ErrorJsonNullOrEmpty = 600,
        ErrorProcessingJson = 601,

        ErrorNotImplemented = 2600,

        ErrorOther = 9999,
    };
}