// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [default_interface]
    runtimeclass MidiClock
    {
        // gets the current MIDI timestamp
        static MIDI_TIMESTAMP GetMidiTimestamp();

        // returns the units per second for the timestamp
        static UInt64 GetMidiTimestampFrequency();

        // convenience function
        static UInt64 ConvertTimestampToMicroseconds(MIDI_TIMESTAMP timestampValue);

        // TODO: Consider adding a wrapper for GetSystemTimePReciseAsFileTime to enable 
        // synchronizing timestamps to wall clock time, as much as that is possible
    }
}

