// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


#include "midl_defines.h"
MIDI_IDL_IMPORT


import "IMidiEndpointMessageProcessingPlugin.idl";
import "MidiFunctionBlock.idl";
import "MidiProperty.idl";
import "MidiProfile.idl";

//import "MidiEndpointInformation.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [default_interface]
    runtimeclass MidiVirtualDevice : IMidiEndpointMessageProcessingPlugin
    {
        MidiVirtualDevice();

        Boolean IsMidiCIDevice{ get; set; };


        String EndpointName{ get; set; };
        String EndpointProductInstanceId{ get; set; };

        // TODO: Other endpoint properties, including the MIDI SysEx stuff, protocol, UMP version, etc.

        // TODO: MUID table?


        // this can only be set before the connection is opened
        Boolean AreFunctionBlocksStatic{ get; set; };

        // This is a view because all modifications require sending notifications
        // out on the endpoint. So the functions do that.
        IMapView<UInt8, MidiFunctionBlock> FunctionBlocks{ get; };
        
        Boolean AddFunctionBlock(MidiFunctionBlock block);
        void UpdateFunctionBlock(MidiFunctionBlock block);
        void RemoveFunctionBlock(UInt8 functionBlockNumber);

 //       MidiEndpointInformation EndpointInformation{ get; set; };

        // true if you want the stream / function block etc. messages automatically handled
        // and then removed from the stream. False if the endpoint should still raise
        // MessageReceived events for those messages
        Boolean SuppressHandledMessages{ get; set; };


        // TODO: MIDI CI / Profiles etc.
    }
}