// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT

import "MidiEndpointConnection.idl";
import "IMidiEndpointConnectionSettings.idl";
import "MidiSessionSettings.idl";
import "MidiVirtualEndpointDeviceDefinition.idl";

namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    [default_interface]
    runtimeclass MidiSession : Windows.Foundation.IClosable
    {
        Guid Id { get; };
        String Name{ get; };
        MidiSessionSettings Settings{ get; };

        static MidiSession CreateSession(String sessionName);
        static MidiSession CreateSession(String sessionName, MidiSessionSettings settings);

        Boolean IsOpen { get; };

        IMapView<Guid, MidiEndpointConnection> Connections{ get; };

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId
        );

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId,
            Boolean autoReconnect
        );

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId,
            Boolean autoReconnect,
            IMidiEndpointConnectionSettings settings
        );


        MidiEndpointConnection CreateVirtualDeviceAndConnection(
            MidiVirtualEndpointDeviceDefinition deviceDefinition
        );

        void DisconnectEndpointConnection(Guid endpointConnectionId);

        Boolean UpdateName(String newName);
    }
}