// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace MIDI_MIDL_NAMESPACE
{
    // this is the direction as specified in the spec, so it is 
    // from the POV of the function block, not from the OS. IOW, 
    // Input here means the device FB *receives* messages that
    // are sent through Windows
    MIDI_API_CONTRACT_v1
    enum MidiFunctionBlockMidi10
    {
        Not10 = 0x0,
        YesBandwidthUnrestricted = 0x1,
        YesBandwidthRestricted = 0x2,
        Reserved = 0x3
    };
}