// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace MIDI_MIDL_NAMESPACE
{
    // NOTE: the values are different for function blocks and group terminal
    // blocks, so we have to different enumerations

    MIDI_API_CONTRACT_v1
    enum MidiFunctionBlockDirection
    {
        Undefined = 0x0,
        BlockInput = 0x1,
        BlockOutput = 0x2,
        Bidirectional = 0x3
    };
}