// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

// A version of this code will be moved into the service instead of local to the in-proc API

#include "midl_defines.h"
MIDI_IDL_IMPORT

import "MidiGlobalInformationCacheUpdatedEventArgs.idl";
import "IMidiCacheableMetadata.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [default_interface]
    static runtimeclass MidiGlobalCache
    {
        // for this local cache implementation, the expiration is only checked when you attempt to get the data
        // or you check to see if the data is present. When the back-end moves to a service, we may handle that
        // with some sort of watcher if the expiration time is critical to track

        [default_overload]
        static void AddOrUpdateData(String key, String data, Windows.Foundation.DateTime expirationTime);

        [default_overload]
        static void AddOrUpdateData(String key, String data);

        static void AddOrUpdateData(String propertyKey, IMidiCacheableMetadata data, Windows.Foundation.DateTime expirationTime);
        static void AddOrUpdateData(String propertyKey, IMidiCacheableMetadata data);

        static void RemoveData(String key);
        static String GetData(String key);
        static Boolean IsDataPresent(String key);

        static event Windows.Foundation.TypedEventHandler<IInspectable, MidiGlobalInformationCacheUpdatedEventArgs> GlobalInformationUpdated;

    }
}
