// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT


import "MidiFunctionBlock.idl";


namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1
    [default_interface]
    runtimeclass MidiVirtualEndpointDeviceDefinition
    {
        MidiVirtualEndpointDeviceDefinition();

        String EndpointName;
        String EndpointProductInstanceId;

        String TransportSuppliedDescription;

        Boolean SupportsMidi1ProtocolMessages;
        Boolean SupportsMidi2ProtocolMessages;
        Boolean SupportsReceivingJRTimestamps;
        Boolean SupportsSendingJRTimestamps;

        IVector<UInt8> DeviceManufacturerSystemExclusiveId{ get; };
        UInt8 DeviceFamilyLsb;
        UInt8 DeviceFamilyMsb;
        UInt8 DeviceFamilyModelLsb;
        UInt8 DeviceFamilyModelMsb;
        IVector<UInt8> SoftwareRevisionLevel{ get; };

        Boolean AreFunctionBlocksStatic;

        IVector<MidiFunctionBlock> FunctionBlocks{ get; };
    }
}