// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

// this simply checks that the UMP packet type aligns with the number of words
// Beyond that, the API generally does not care what's in the UMP. This enables
// new messages to be defined without breaking the API

import "MidiMessage64.idl";
import "MidiMessage128.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    static runtimeclass MidiCIMessageUtility
    {
        static void Foo();   // TODO: placeholder

    };
}
