// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT


import "MidiFunctionBlockDirectionEnum.idl";
import "MidiFunctionBlockUIHintEnum.idl";
import "MidiGroup.idl";

import "MidiUmp128.idl";

// TODO: Verify this has everything in the spec

import "IMidiCacheableMetadata.idl";
import "MidiFunctionBlockMidi10Enum.idl";

namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(1)]
    [default_interface]
    runtimeclass MidiFunctionBlock : IMidiCacheableMetadata
    {
        MidiFunctionBlock();

        UInt8 Number{ get; };               // function block number: 0-31
        String Name{ get; };

        Boolean IsActive{ get; };

        MidiFunctionBlockDirection Direction{ get; };
        MidiFunctionBlockUIHint UIHint{ get; };

        MidiFunctionBlockMidi10 Midi10Connection{ get; };

        UInt8 FirstGroupIndex{ get; };
        UInt8 NumberOfGroupsSpanned{ get; };

        UInt8 MidiCIMessageVersionFormat{ get; };

        UInt8 MaxSysEx8Streams{ get; };

        void UpdateFromMessages(MidiUmp128[] endpointMessages);

    }
}