// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT


namespace Windows.Devices.Midi2
{
    [MIDI_API_CONTRACT(19)]
    [default_interface]
    runtimeclass MidiClock
    {
        // gets the current MIDI timestamp
        static MIDI_TIMESTAMP Now{ get; };

        // gets the current MIDI timestamp
        static MIDI_TIMESTAMP TimestampConstantSendImmediately{ get; };

        // returns the units per second for the timestamp
        static UInt64 TimestampFrequency{ get; };

        // convenience functions
        //static Double ConvertTimestampToNanoseconds(MIDI_TIMESTAMP timestampValue);   // TODO post-NAMM 2024
        static Double ConvertTimestampToMicroseconds(MIDI_TIMESTAMP timestampValue);
        static Double ConvertTimestampToMilliseconds(MIDI_TIMESTAMP timestampValue);
        static Double ConvertTimestampToSeconds(MIDI_TIMESTAMP timestampValue);   // TODO post-NAMM 2024

        // these can offset to the future or the past, which is why the offset is signed
        static MIDI_TIMESTAMP OffsetTimestampByTicks(MIDI_TIMESTAMP timestampValue, Int64 offsetTicks);
        static MIDI_TIMESTAMP OffsetTimestampByMicroseconds(MIDI_TIMESTAMP timestampValue, Int64 offsetMicroseconds);
        static MIDI_TIMESTAMP OffsetTimestampByMilliseconds(MIDI_TIMESTAMP timestampValue, Int64 offsetMilliseconds);
        static MIDI_TIMESTAMP OffsetTimestampBySeconds(MIDI_TIMESTAMP timestampValue, Int64 offsetSeconds);



        // TODO: Consider adding a wrapper for GetSystemTimePreciseAsFileTime to enable 
        // synchronizing timestamps to wall clock time, as much as that is possible






    }
}

