// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "midl_defines.h"
MIDI_IDL_IMPORT

namespace Windows.Devices.Midi2
{
    // Yes, this is effectively recreating the HRESULT, but 
    // our API standards do not allow creating and exposing
    // custom HRESULTs in public APIs
    [MIDI_API_CONTRACT(1)]
    [flags]
    enum MidiSendMessageResult
    {
        // top level success/failure flag
        
        Succeeded =                         0x80000000,
        Failed =                            0x10000000,

        // success details

        SentImmediately =                   0x00000001,
        Scheduled =                         0x00000002,
        SystemExclusiveParked =             0x00000004,

        // service failure reasons

        BufferFull =                        0x00010000,
        SchedulerQueueFull =                0x00020000,
        EndpointConnectionClosedOrInvalid = 0x00040000,

        // validation failure reasons

        InvalidMessageTypeForWordCount =    0x00100000,
        InvalidMessageOther =               0x00200000,
        DataIndexOutOfRange =               0x00400000,


        Other =                             0x01000000,
    };
}