// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2.Diagnostics
{
    struct MidiServiceMessageProcessingPluginInfo
    {
        Guid Id;

        String Name;
        String Description;
        String Author;

        String SmallImagePath;

        String Version;

        Boolean SupportsMultipleInstancesPerDevice;

        Boolean IsSystemManaged;
        Boolean IsClientConfigurable;

        //String ClientConfigurationAssemblyName;

    };
}