// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2.Diagnostics
{
    [default_interface]
    runtimeclass MidiServiceMessageProcessingPluginInfo
    {
        Guid Id{ get; };

        String Name { get; };
        String Description{ get; };
        String Author{ get; };

        String SmallImagePath{ get; };

        String Version{ get; };

        Boolean SupportsMultipleInstancesPerDevice{ get; };

        Boolean IsSystemManaged{ get; };
        Boolean IsClientConfigurable{ get; };

        String ClientConfigurationAssemblyName { get; };

    }
}