// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

import "MidiServiceTransportPluginInfo.idl";
import "MidiServiceMessageProcessingPluginInfo.idl";
import "MidiServiceSessionInfo.idl";

namespace Microsoft.Devices.Midi2.Diagnostics
{
    [default_interface]
    runtimeclass MidiDiagnostics
    {
        static IVector<MidiServiceTransportPluginInfo> GetInstalledTransportPlugins();
        static IVector<MidiServiceMessageProcessingPluginInfo> GetInstalledMessageProcessingPlugins();

        static IVector<MidiServiceSessionInfo> GetActiveSessions();
    }
}

