// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2.Diagnostics
{
    [default_interface]
    runtimeclass MidiServicePingResponse
    {
        UInt32 SourceId { get; };
        UInt32 Index { get; };

        UInt64 ClientSendMidiTimestamp{ get; };
        UInt64 ServiceReportedMidiTimestamp{ get; };
        UInt64 ClientReceiveMidiTimestamp{ get; };

        UInt64 ClientDeltaTimestamp{ get; };
    }
}
