// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "MidiVirtualDeviceCreationConfig.idl";
import "MidiVirtualDevice.idl";

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [default_interface]
    static runtimeclass MidiVirtualDeviceManager
    {
        static Boolean IsTransportAvailable{ get; };

        static Guid AbstractionId{ get; };

        static MidiVirtualDevice CreateVirtualDevice(
            MidiVirtualDeviceCreationConfig creationConfig);

        //static Boolean RemoveTransientLoopbackEndpoints(
        //    MidiLoopbackEndpointDeletionConfiguration deletionConfiguration);
    }
}