// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    [default_interface]
    runtimeclass MidiVirtualDeviceCreationConfig : Microsoft.Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiVirtualDeviceCreationConfig(
            String name,
            String description,
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo
        );

        MidiVirtualDeviceCreationConfig(
            String name,
            String description, 
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity declaredDeviceIdentity
        );

        MidiVirtualDeviceCreationConfig(
            String name,
            String description,
            String manufacturer,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo declaredEndpointInfo,
            Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity declaredDeviceIdentity,
            Microsoft.Windows.Devices.Midi2.MidiEndpointUserSuppliedInfo userSuppliedInfo
        );


        // maps to transport-supplied values. We don't make the rest of the
        // MidiEndpointTransportSuppliedInfo settings available because some, like 
        // transport id and data format, need to be set service-side. Also, all 
        // app-to-app MIDI devices are multi-client
        String Name;
        String Description;
        String Manufacturer;


        Microsoft.Windows.Devices.Midi2.MidiDeclaredDeviceIdentity DeclaredDeviceIdentity;
        Microsoft.Windows.Devices.Midi2.MidiDeclaredEndpointInfo DeclaredEndpointInfo;
        Microsoft.Windows.Devices.Midi2.MidiEndpointUserSuppliedInfo UserSuppliedInfo;

        IVector<Microsoft.Windows.Devices.Midi2.MidiFunctionBlock> FunctionBlocks{ get; };
    }
}