// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Windows.Devices.Midi2.Endpoints.Virtual
{
    runtimeclass MidiStreamConfigRequestReceivedEventArgs
    {
        UInt64 Timestamp{ get; };

        Microsoft.Windows.Devices.Midi2.MidiProtocol PreferredMidiProtocol{ get; };

        Boolean RequestEndpointTransmitJitterReductionTimestamps{ get; };
        Boolean RequestEndpointReceiveJitterReductionTimestamps{ get; };
    }
}