// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

namespace Microsoft.Devices.Midi2.Endpoints.Virtual
{
    runtimeclass MidiStreamConfigurationRequestReceivedEventArgs
    {
        UInt64 Timestamp{ get; };

        Microsoft.Devices.Midi2.MidiProtocol PreferredMidiProtocol{ get; };

        Boolean RequestEndpointTransmitJitterReductionTimestamps{ get; };
        Boolean RequestEndpointReceiveJitterReductionTimestamps{ get; };
    }
}