//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc


// Application banner

#define IDS_BANNER_TOOL_INFO										50000
#define IDS_BANNER_COPYRIGHT										50001
#define IDS_BANNER_INFO_URL											50002

// Drivers32 registry errors

#define IDS_ERROR_NO_INPROC_SERVER									50100
#define IDS_ERROR_MIDI0_ENTRY_INVALID								50101
#define IDS_ERROR_NO_WDMAUD2_ENTRY									50102
#define IDS_ERROR_NO_WDMAUD2_ENTRY_TYPICAL							50103
#define IDS_ERROR_NO_WDMAUD2_ENTRY_REMEDY							50104
#define IDS_ERROR_COULD_NOT_OPEN_DRIVERS32							50105
#define IDS_ERROR_EXCEPTION_ENUMERATING_REGISTRY					50106

// Windows MIDI Services registry errors

#define IDS_ERROR_NO_ROOT_REGISTRY_KEY								50200
#define IDS_ERROR_MIDISRV_NO_IMAGE_PATH								50201
#define IDS_ERROR_MIDISRV_KEY_INVALID								50202
#define IDS_ERROR_NO_MIDISRV_SERVICES_KEY							50203
#define IDS_ERROR_NO_SDK_INSTALLED_VALUE							50204
#define IDS_ERROR_NO_SDK_ROOT_KEY									50205

// Transport errors

#define IDS_ERROR_NO_TRANSPORT_CLSID								50300
#define IDS_ERROR_CANNOT_ENUMERATE_TRANSPORTS						50301
#define IDS_ERROR_NO_TRANSPORTS_FOUND								50302
#define IDS_ERROR_EXCEPTION_ENUMERATING_TRANSPORTS					50303

// Endpoint enumeration errors

#define IDS_ERROR_CANNOT_ENUMERATE_DEVICES							50400
#define IDS_ERROR_NO_NAMING_TABLE									50401
#define IDS_ERROR_NO_ENDPOINT_PARENT								50402
#define IDS_ERROR_NO_DEVICES_FOUND_1								50403
#define IDS_ERROR_NO_DEVICES_FOUND_2								50404
#define IDS_ERROR_NO_DEVICES_FOUND_3								50405

// MIDI 1.0 enumeration errors

#define IDS_ERROR_EXCEPTION_ENUMERATING_WINRT_MIDI1					50500
#define IDS_ERROR_PORT_NODRIVER										50501
#define IDS_ERROR_PORT_INVALPARAM									50502
#define IDS_ERROR_PORT_BADDEVICEID									50503
#define IDS_ERROR_PORT_NOMEM										50504
#define IDS_ERROR_EXCEPTION_ENUMERATING_WINMM_INPUTS				50505
#define IDS_ERROR_EXCEPTION_ENUMERATING_WINMM_OUTPUTS				50506

// Ping and clock errors

#define IDS_ERROR_PING_FAILED										50600
#define IDS_ERROR_PING_FAILED_NULL_RESULT							50601
#define IDS_ERROR_PING_FAILED_EXCEPTION								50602
#define IDS_ERROR_CLOCK_HRESULT										50603

// System information errors

#define IDS_ERROR_UNIDENTIFIED_ARCHITECTURE							50700
#define IDS_ERROR_CANNOT_QUERY_ARCHITECTURE							50701

// Run outcome

#define IDS_ERROR_EXCEPTION_GATHERING_INFORMATION					50800
#define IDS_ERROR_ABORTING_RUN										50801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
