// this file has been auto-generated by the Windows MIDI Services build process
// the version information here represents the NuGet package version your app was
// built against

#ifndef WINDOWS_MIDI_SERVICES_SDK_RUNTIME_VERSION_INCLUDE
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_VERSION_INCLUDE

#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_IS_PREVIEW                         true
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_SOURCE                             L"GitHub Preview"
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_DATE                               L"2025-09-03"
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_NAME                       L"Preview 14"
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_FULL                       L"1.0.14-preview.14.87"
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_MAJOR                      1
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_MINOR                      0
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_PATCH                      14
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_BUILD_NUMBER               87
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_PREVIEW                            L"preview.14.87"
#define WINDOWS_MIDI_SERVICES_SDK_RUNTIME_BUILD_VERSION_FILE                       L"1.0.14.87"

#endif
