// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "stdafx.h"
#include "MidiNetworkApiTests.h"

#include <vector>
#include <optional>

#include <winrt/Windows.Networking.h>
#include <winrt/Windows.Networking.Sockets.h>

using namespace WEX::Logging;
using namespace WEX::Common;


namespace
{
    // Any host these tests create is named with this prefix so a leaked one is obvious
    // in the configuration file and can be told apart from a real user host.
    constexpr wchar_t TestHostNamePrefix[] = L"MidiApiTest_";

    // Byte counts from the MIDI 2.0 spec, restated rather than included so the test fails if
    // the service ever quietly changes them.
    constexpr uint32_t MaxUmpEndpointNameBytes = 98;
    constexpr uint32_t MaxProductInstanceIdBytes = 42;

    std::wstring RepeatedString(_In_ wchar_t const ch, _In_ size_t const count)
    {
        return std::wstring(count, ch);
    }

    // Skips the rest of the test rather than failing it when the service is not running.
    // A developer box without the service installed should not produce red tests here.
    bool ServiceIsAvailable()
    {
        try
        {
            return MidiNetworkTransportManager::IsTransportAvailable();
        }
        catch (...)
        {
            return false;
        }
    }

    std::wstring MakeUniqueSuffix()
    {
        return winrt::to_string(winrt::to_hstring(foundation::GuidHelper::CreateNewGuid())).empty()
            ? std::wstring{ L"x" }
            : std::wstring{ winrt::to_hstring(foundation::GuidHelper::CreateNewGuid()).c_str() };
    }

    // Asks the system for an ephemeral port and gives it straight back. Nothing else is likely
    // to take it in the meantime, and no network MIDI host holds it, which is what the port
    // collision tests need.
    std::optional<uint16_t> PickLikelyFreePort()
    {
        try
        {
            winrt::Windows::Networking::Sockets::DatagramSocket socket;

            socket.BindEndpointAsync(winrt::Windows::Networking::HostName{ L"127.0.0.1" }, L"").get();

            auto const portText = std::wstring{ socket.Information().LocalPort() };

            socket.Close();

            if (portText.empty())
            {
                return std::nullopt;
            }

            return static_cast<uint16_t>(std::stoul(portText));
        }
        catch (...)
        {
            return std::nullopt;
        }
    }
}

#define SKIP_IF_NO_NETWORK_TRANSPORT() \
    if (!ServiceIsAvailable()) \
    { \
        Log::Result(TestResults::Skipped, L"Network MIDI 2.0 transport is not available on this PC."); \
        return; \
    }


// Every host and every connected client leaves a deactivated software device node behind for its
// UMP endpoint, and for any MIDI 1.0 ports created alongside it, because the service never
// deletes one. These two hooks remove exactly the nodes this test method caused to be created.
bool MidiNetworkApiTests::TestSetup()
{
    m_deviceNodeTracker.Start();

    return true;
}

bool MidiNetworkApiTests::TestCleanup()
{
    m_deviceNodeTracker.RemoveDeviceNodesCreatedSinceStart();

    return true;
}


winrt::guid MidiNetworkApiTests::CreateTestHost(std::wstring const& nameSuffix, bool const advertise)
{
    MidiNetworkHostCreationConfig config;

    // the id is generated by the API at construction, not supplied by the caller
    auto hostId = config.HostId();

    config.Name(winrt::hstring{ TestHostNamePrefix + nameSuffix });
    config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + nameSuffix });

    // The UMP product instance id is capped at 42 bytes by the spec, and the service rejects
    // the whole host definition if it is longer, so this cannot carry the full suffix.
    config.ProductInstanceId(winrt::hstring{ (TestHostNamePrefix + nameSuffix).substr(0, 42) });

    config.UseAutomaticPortAllocation(true);
    config.CreateOnlyUmpEndpoints(true);

    config.Advertise(advertise);

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

    if (response == nullptr || !response.Success())
    {
        Log::Comment(String().Format(
            L"Host creation failed. code=0x%08X message='%s'",
            response == nullptr ? 0 : (uint32_t)response.ErrorCode(),
            response == nullptr ? L"null response" : response.ErrorMessage().c_str()));

        return winrt::guid{};
    }

    return hostId;
}

void MidiNetworkApiTests::RemoveTestHost(winrt::guid const& hostId)
{
    if (hostId == winrt::guid{})
    {
        return;
    }

    try
    {
        MidiNetworkHostRemovalConfig removalConfig(hostId);
        MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();
    }
    catch (...)
    {
        // best effort cleanup only
    }
}

bool MidiNetworkApiTests::HostIsPresent(winrt::guid const& hostId)
{
    // The service applies a configuration update and brings the host up on its own
    // threads, so a host can be a moment behind the call that created it. Poll rather
    // than sampling once.
    const int maxAttempts = 50;     // up to 5 seconds

    for (int attempt = 0; attempt < maxAttempts; attempt++)
    {
        auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

        if (hosts != nullptr)
        {
            for (auto const& host : hosts)
            {
                if (host.HostId() == hostId)
                {
                    return true;
                }
            }
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    return false;
}

// True when the host is gone. Removal is also applied asynchronously.
bool MidiNetworkApiTests::HostIsAbsent(winrt::guid const& hostId)
{
    const int maxAttempts = 50;     // up to 5 seconds

    for (int attempt = 0; attempt < maxAttempts; attempt++)
    {
        auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

        bool found{ false };

        if (hosts != nullptr)
        {
            for (auto const& host : hosts)
            {
                if (host.HostId() == hostId)
                {
                    found = true;
                    break;
                }
            }
        }

        if (!found)
        {
            return true;
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }

    return false;
}

// Fails the test if a newly created host never shows up, and says what to check first.
// The usual cause is a service-side network transport binary older than the host
// lifecycle commands, because the transport lives in Program Files rather than
// System32 and is easy to leave behind when deploying.
void MidiNetworkApiTests::VerifyHostAppeared(winrt::guid const& hostId)
{
    if (!HostIsPresent(hostId))
    {
        Log::Comment(
            L"The host was created without error but never appeared in GetConfiguredHosts. "
            L"Check that 'C:\\Program Files\\Windows MIDI Services\\Service\\Midi2.NetworkMidiTransport.dll' "
            L"is current. Deploy it with build\\replace_just_network_x64.bat from an elevated prompt, "
            L"restart the service, and re-run.");

        VERIFY_FAIL(L"Created host did not appear in GetConfiguredHosts.");
    }
}


void MidiNetworkApiTests::TestTransportIsAvailable()
{
    // Not skipped. This test is the one that reports whether the transport is there.
    auto available = MidiNetworkTransportManager::IsTransportAvailable();

    Log::Comment(String().Format(L"Network transport available: %s", available ? L"true" : L"false"));

    if (!available)
    {
        Log::Result(TestResults::Skipped, L"Network MIDI 2.0 transport is not installed on this PC.");
    }
}

void MidiNetworkApiTests::TestTransportIdIsStable()
{
    auto id1 = MidiNetworkTransportManager::TransportId();
    auto id2 = MidiNetworkTransportManager::TransportId();

    VERIFY_ARE_EQUAL(id1, id2);
    VERIFY_IS_FALSE(id1 == winrt::guid{});
}

void MidiNetworkApiTests::TestRawEnumerateHostsResponse()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    winrt::Windows::Devices::Midi2::ServiceConfig::MidiServiceTransportCommand command(
        MidiNetworkTransportManager::TransportId());

    command.Verb(L"enumerateHosts");

    auto response = winrt::Windows::Devices::Midi2::ServiceConfig::MidiServiceTransportPluginConfigManager::SendCommand(command);

    VERIFY_IS_NOT_NULL(response);

    Log::Comment(String().Format(L"Status: %d", (int)response.Status()));
    Log::Comment(String().Format(L"Error message: '%s'", response.ServiceErrorMessage().c_str()));

    auto responseJson = response.ResponseJson();

    if (responseJson != nullptr)
    {
        Log::Comment(String().Format(L"RAW RESPONSE: %s", responseJson.Stringify().c_str()));
    }
    else
    {
        Log::Comment(L"RAW RESPONSE: <null>");
    }

    // What the SDK actually surfaces from that same data. Entries whose identifier is not a
    // valid guid are skipped by design, but they must not take the rest of the list with them,
    // which is what happened when the parse threw out of the enumeration loop.
    auto parsed = MidiNetworkTransportManager::GetConfiguredHosts();

    uint32_t rawCount{ 0 };
    uint32_t parseableCount{ 0 };

    if (responseJson != nullptr && responseJson.HasKey(L"hosts"))
    {
        auto hostsArray = responseJson.GetNamedArray(L"hosts");

        rawCount = hostsArray.Size();

        for (auto const& entry : hostsArray)
        {
            auto entryObject = entry.GetObject();

            if (entryObject == nullptr)
            {
                continue;
            }

            auto identifier = entryObject.GetNamedString(L"entryIdentifier", L"");

            try
            {
                if (!identifier.empty())
                {
                    winrt::guid parsedId{ identifier };
                    parseableCount++;
                }
            }
            catch (...)
            {
                // not a guid, so the SDK is expected to skip it
            }
        }
    }

    Log::Comment(String().Format(
        L"Raw entries: %d, of which parseable: %d, surfaced by GetConfiguredHosts: %d",
        rawCount, parseableCount, parsed.Size()));

    VERIFY_ARE_EQUAL(parseableCount, parsed.Size());
}

void MidiNetworkApiTests::TestGetConfiguredHostsReturnsCollection()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

    VERIFY_IS_NOT_NULL(hosts);

    Log::Comment(String().Format(L"Configured hosts: %d", hosts.Size()));

    // every entry must be readable without throwing
    for (auto const& host : hosts)
    {
        VERIFY_IS_NOT_NULL(host);

        Log::Comment(String().Format(
            L"  host '%s' started=%s port=%s",
            host.UmpEndpointName().c_str(),
            host.HasStarted() ? L"true" : L"false",
            host.ActualPort().c_str()));
    }
}

void MidiNetworkApiTests::TestGetConfiguredClientsReturnsCollection()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto clients = MidiNetworkTransportManager::GetConfiguredClients();

    VERIFY_IS_NOT_NULL(clients);

    Log::Comment(String().Format(L"Configured clients: %d", clients.Size()));

    for (auto const& client : clients)
    {
        VERIFY_IS_NOT_NULL(client);

        Log::Comment(String().Format(
            L"  client sessionActive=%s remote=%s:%s",
            client.IsSessionActive() ? L"true" : L"false",
            client.ConnectedRemoteAddress().c_str(),
            client.ConnectedRemotePort().c_str()));
    }
}

void MidiNetworkApiTests::TestGetPendingRemoteClientsReturnsCollection()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto pending = MidiNetworkTransportManager::GetPendingRemoteClients();

    // The most important assertion in this file. This returned null before the
    // implementation landed, which crashed anything that tried to iterate it.
    VERIFY_IS_NOT_NULL(pending);

    Log::Comment(String().Format(L"Pending remote clients: %d", pending.Size()));

    for (auto const& client : pending)
    {
        VERIFY_IS_NOT_NULL(client);

        // A pending entry is only actionable if it carries the three values the
        // approve/deny command requires, so those must never come back blank.
        VERIFY_IS_FALSE(client.HostId() == winrt::guid{});
        VERIFY_IS_FALSE(client.UmpEndpointName().empty());
        VERIFY_IS_FALSE(client.ProductInstanceId().empty());

        Log::Comment(String().Format(
            L"  pending '%s' (%s) for host '%s' from %s",
            client.UmpEndpointName().c_str(),
            client.ProductInstanceId().c_str(),
            client.HostUmpEndpointName().c_str(),
            client.RemoteAddress().c_str()));

        // The request time is a real time if it is set at all. Zero means the service
        // had no time recorded, which is allowed, but a garbage year is not.
        auto requestTime = client.RequestTime();

        if (requestTime.time_since_epoch().count() != 0)
        {
            auto asFileTime = winrt::clock::to_file_time(requestTime);

            // 2000-01-01 in FILETIME ticks. Anything earlier means the ISO 8601
            // round trip lost the date.
            VERIFY_IS_GREATER_THAN(asFileTime.value, 125911584000000000ull);
        }
    }
}

void MidiNetworkApiTests::TestGetAdvertisedHostsReturnsCollection()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hosts = MidiNetworkTransportManager::GetAdvertisedHosts();

    VERIFY_IS_NOT_NULL(hosts);

    Log::Comment(String().Format(L"Advertised hosts visible: %d", hosts.Size()));
}

void MidiNetworkApiTests::TestGetPendingRemoteClientsIsRepeatable()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // A settings app polls this on a timer, so the same call repeated has to keep
    // working and keep agreeing with itself when nothing has changed.
    const int iterations = 20;

    uint32_t firstCount{ 0 };

    for (int i = 0; i < iterations; i++)
    {
        auto pending = MidiNetworkTransportManager::GetPendingRemoteClients();

        VERIFY_IS_NOT_NULL(pending);

        if (i == 0)
        {
            firstCount = pending.Size();
        }
        else
        {
            // Nothing is connecting during this test, so the count must be stable.
            VERIFY_ARE_EQUAL(firstCount, pending.Size());
        }
    }

    Log::Comment(String().Format(L"%d polls returned a stable count of %d", iterations, firstCount));
}


void MidiNetworkApiTests::TestHostRemovalConfigRoundTrip()
{
    auto hostId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkHostRemovalConfig config(hostId);

    VERIFY_ARE_EQUAL(hostId, config.HostId());
    VERIFY_ARE_EQUAL(MidiNetworkTransportManager::TransportId(), config.TransportId());

    auto otherId = foundation::GuidHelper::CreateNewGuid();
    config.HostId(otherId);

    VERIFY_ARE_EQUAL(otherId, config.HostId());
}

void MidiNetworkApiTests::TestHostRemovalConfigJsonShape()
{
    auto hostId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkHostRemovalConfig config(hostId);

    auto configJson = config.ConfigJson();

    VERIFY_IS_NOT_NULL(configJson);

    Log::Comment(String().Format(L"Removal config json: %s", configJson.Stringify().c_str()));

    // Walk the wrapper the service expects, one level at a time, so a failure
    // says which level is wrong.
    VERIFY_IS_TRUE(configJson.HasKey(L"endpointTransportPluginSettings"));

    auto pluginSettings = configJson.GetNamedObject(L"endpointTransportPluginSettings");
    VERIFY_IS_NOT_NULL(pluginSettings);

    // The transport id is written in the braced uppercase form the service uses, so the
    // key is matched by parsing it rather than by comparing strings.
    auto expectedTransportId = MidiNetworkTransportManager::TransportId();

    json::JsonObject transportObject{ nullptr };

    for (auto const& pair : pluginSettings)
    {
        if (winrt::guid(pair.Key()) == expectedTransportId)
        {
            transportObject = pair.Value().GetObject();
            break;
        }
    }

    VERIFY_IS_NOT_NULL(transportObject);
    VERIFY_IS_TRUE(transportObject.HasKey(L"remove"));

    auto removeObject = transportObject.GetNamedObject(L"remove");
    VERIFY_IS_NOT_NULL(removeObject);
    VERIFY_IS_TRUE(removeObject.HasKey(L"hosts"));

    auto hostsObject = removeObject.GetNamedObject(L"hosts");
    VERIFY_IS_NOT_NULL(hostsObject);

    // the host being removed is named by its id
    bool foundHostKey{ false };

    for (auto const& pair : hostsObject)
    {
        if (winrt::guid(pair.Key()) == hostId)
        {
            foundHostKey = true;
            break;
        }
    }

    VERIFY_IS_TRUE(foundHostKey);
}

void MidiNetworkApiTests::TestApprovalConfigRoundTrip()
{
    auto hostId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkRemoteClientApprovalConfig config(
        hostId,
        L"Some Remote Endpoint",
        L"SomeProductInstanceId",
        true,
        false);

    VERIFY_ARE_EQUAL(hostId, config.HostId());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"Some Remote Endpoint" }, config.RemoteClientName());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"SomeProductInstanceId" }, config.RemoteClientProductInstanceId());
    VERIFY_IS_TRUE(config.Approve());
    VERIFY_IS_FALSE(config.ScopeIsThisRequestOnly());

    VERIFY_ARE_EQUAL(MidiNetworkTransportManager::TransportId(), config.TransportId());

    // settable as well as gettable
    config.Approve(false);
    config.ScopeIsThisRequestOnly(true);

    VERIFY_IS_FALSE(config.Approve());
    VERIFY_IS_TRUE(config.ScopeIsThisRequestOnly());
}

void MidiNetworkApiTests::TestApprovalConfigJsonIsNotNull()
{
    MidiNetworkRemoteClientApprovalConfig config(
        foundation::GuidHelper::CreateNewGuid(),
        L"Name",
        L"Id",
        true,
        false);

    // An approval is sent as a command, so there is no configuration payload, but the
    // property must still return an object rather than null.
    VERIFY_IS_NOT_NULL(config.ConfigJson());
}

void MidiNetworkApiTests::TestDisconnectConfigJsonIsNotNull()
{
    MidiNetworkClientDisconnectConfig config(foundation::GuidHelper::CreateNewGuid());

    VERIFY_IS_NOT_NULL(config.ConfigJson());
}


void MidiNetworkApiTests::TestCreateThenRemoveHost()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hostId = CreateTestHost(MakeUniqueSuffix());

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    // remove it even if an assert below halts the method
    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    MidiNetworkHostRemovalConfig removalConfig(hostId);

    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(removalResponse);

    if (!removalResponse.Success())
    {
        Log::Comment(String().Format(L"Removal error: %s", removalResponse.ErrorMessage().c_str()));
    }

    VERIFY_IS_TRUE(removalResponse.Success());

    // the response should identify what it acted on
    VERIFY_ARE_EQUAL(hostId, removalResponse.HostId());

    // and the host must actually be gone
    VERIFY_IS_TRUE(HostIsAbsent(hostId));

    cleanup.release();
}

// Creation used to return as soon as the definition was queued, leaving the caller to poll.
// A successful await must now mean the host is live.
void MidiNetworkApiTests::TestCreateHostAsyncReturnsOnlyOnceHostHasStarted()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hostId = CreateTestHost(MakeUniqueSuffix());

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    // deliberately no polling here: one sample, taken the moment creation returned
    auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

    VERIFY_IS_NOT_NULL(hosts);

    bool found{ false };

    for (auto const& host : hosts)
    {
        if (host.HostId() == hostId)
        {
            found = true;

            VERIFY_IS_TRUE(host.HasStarted());

            break;
        }
    }

    VERIFY_IS_TRUE(found);
}

void MidiNetworkApiTests::TestCreateStopStartThenRemoveHost()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hostId = CreateTestHost(MakeUniqueSuffix());

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    auto stopResponse = MidiNetworkTransportManager::StopNetworkHostAsync(hostId).get();
    VERIFY_IS_NOT_NULL(stopResponse);
    VERIFY_IS_TRUE(stopResponse.Success());

    auto startResponse = MidiNetworkTransportManager::StartNetworkHostAsync(hostId).get();
    VERIFY_IS_NOT_NULL(startResponse);
    VERIFY_IS_TRUE(startResponse.Success());

    // removing a running host has to work, not just a stopped one
    MidiNetworkHostRemovalConfig removalConfig(hostId);
    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(removalResponse);
    VERIFY_IS_TRUE(removalResponse.Success());
    VERIFY_IS_TRUE(HostIsAbsent(hostId));

    cleanup.release();
}

void MidiNetworkApiTests::TestRemoveNonexistentHostFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // a host id the service has never seen
    MidiNetworkHostRemovalConfig removalConfig(foundation::GuidHelper::CreateNewGuid());

    auto response = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    // a failure has to say something, otherwise the caller has nothing to show a user
    VERIFY_IS_FALSE(response.ErrorMessage().empty());

    Log::Comment(String().Format(L"Expected failure message: %s", response.ErrorMessage().c_str()));
}

void MidiNetworkApiTests::TestCreateThenImmediatelyRemoveDoesNotLeak()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto const hostsBefore = MidiNetworkTransportManager::GetConfiguredHosts().Size();

    // No wait between the two calls, so removal lands while the service may still be building
    // the host. Repeated, because the window is small and timing dependent.
    const int iterations = 15;

    std::vector<winrt::guid> createdIds;

    for (int i = 0; i < iterations; i++)
    {
        auto suffix = MakeUniqueSuffix();

        MidiNetworkHostCreationConfig config;

        auto hostId = config.HostId();

        config.Name(winrt::hstring{ TestHostNamePrefix + suffix });
        config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + suffix });
        config.ProductInstanceId(winrt::hstring{ (TestHostNamePrefix + suffix).substr(0, 42) });
        config.UseAutomaticPortAllocation(true);
        config.CreateOnlyUmpEndpoints(true);
        config.Advertise(false);

        auto creationResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

        VERIFY_IS_NOT_NULL(creationResponse);
        VERIFY_IS_TRUE(creationResponse.Success());

        createdIds.push_back(hostId);

        MidiNetworkHostRemovalConfig removalConfig(hostId);

        auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

        VERIFY_IS_NOT_NULL(removalResponse);

        // Removing an entry which has been accepted but not yet built is still a removal, so
        // this must not come back as "host not found".
        VERIFY_IS_TRUE(removalResponse.Success());
    }

    // Let anything still in flight inside the service finish before counting.
    std::this_thread::sleep_for(std::chrono::seconds(3));

    for (auto const& id : createdIds)
    {
        VERIFY_IS_TRUE(HostIsAbsent(id));
    }

    auto const hostsAfter = MidiNetworkTransportManager::GetConfiguredHosts().Size();

    Log::Comment(String().Format(
        L"%d create/remove cycles. Hosts before %d, after %d.",
        iterations, hostsBefore, hostsAfter));

    VERIFY_ARE_EQUAL(hostsBefore, hostsAfter);
}


void MidiNetworkApiTests::TestApproveUnknownRemoteClientFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkRemoteClientApprovalConfig config(
        foundation::GuidHelper::CreateNewGuid(),      // host that does not exist
        L"NoSuchRemoteEndpoint",
        L"NoSuchProductInstanceId",
        true,                                          // approve
        false);

    auto response = MidiNetworkTransportManager::ApproveOrDenyRemoteClientConnectRequestAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_IS_FALSE(response.ErrorMessage().empty());

    // the response must echo back what was asked for, so a caller polling several
    // decisions at once can tell them apart
    VERIFY_ARE_EQUAL(config.HostId(), response.HostId());
    VERIFY_ARE_EQUAL(config.RemoteClientName(), response.RemoteClientName());
    VERIFY_ARE_EQUAL(config.RemoteClientProductInstanceId(), response.RemoteClientProductInstanceId());

    Log::Comment(String().Format(L"Expected failure message: %s", response.ErrorMessage().c_str()));
}

void MidiNetworkApiTests::TestDenyUnknownRemoteClientFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkRemoteClientApprovalConfig config(
        foundation::GuidHelper::CreateNewGuid(),
        L"NoSuchRemoteEndpoint",
        L"NoSuchProductInstanceId",
        false,                                         // deny
        true);                                         // this request only

    auto response = MidiNetworkTransportManager::ApproveOrDenyRemoteClientConnectRequestAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_IS_FALSE(response.ErrorMessage().empty());

    Log::Comment(String().Format(L"Expected failure message: %s", response.ErrorMessage().c_str()));
}

void MidiNetworkApiTests::TestApprovalWithEmptyIdentityFailsWithoutCallingService()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // The service requires all four arguments and rejects the command outright if any
    // is missing, so the API stops this before it goes anywhere.
    MidiNetworkRemoteClientApprovalConfig config(
        foundation::GuidHelper::CreateNewGuid(),
        L"",                                           // no name
        L"",                                           // no product instance id
        true,
        false);

    auto response = MidiNetworkTransportManager::ApproveOrDenyRemoteClientConnectRequestAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_IS_FALSE(response.ErrorMessage().empty());

    Log::Comment(String().Format(L"Expected validation message: %s", response.ErrorMessage().c_str()));
}


// ============================================================================
// Fuzzing / hostile input
// ============================================================================

void MidiNetworkApiTests::TestFuzzNullConfigsAreRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Every entry point which takes a configuration object has to survive a null one. These
    // are all declared noexcept, so an unhandled throw here would take the process down
    // rather than surface as a failed call.

    auto creationResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(nullptr).get();
    VERIFY_IS_NOT_NULL(creationResponse);
    VERIFY_IS_FALSE(creationResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::InvalidArgument, creationResponse.ErrorCode());

    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(nullptr).get();
    VERIFY_IS_NOT_NULL(removalResponse);
    VERIFY_IS_FALSE(removalResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkHostRemovalErrorCode::InvalidArgument, removalResponse.ErrorCode());

    auto connectResponse = MidiNetworkTransportManager::ConnectNetworkClientAsync(nullptr).get();
    VERIFY_IS_NOT_NULL(connectResponse);
    VERIFY_IS_FALSE(connectResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkClientConnectErrorCode::InvalidArgument, connectResponse.ErrorCode());

    auto disconnectResponse = MidiNetworkTransportManager::DisconnectNetworkClientAsync(nullptr).get();
    VERIFY_IS_NOT_NULL(disconnectResponse);
    VERIFY_IS_FALSE(disconnectResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkClientDisconnectErrorCode::InvalidArgument, disconnectResponse.ErrorCode());

    auto approvalResponse = MidiNetworkTransportManager::ApproveOrDenyRemoteClientConnectRequestAsync(nullptr).get();
    VERIFY_IS_NOT_NULL(approvalResponse);
    VERIFY_IS_FALSE(approvalResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkRemoteClientApprovalErrorCode::InvalidArgument, approvalResponse.ErrorCode());
}

void MidiNetworkApiTests::TestFuzzEmptyHostCreationFieldsAreRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // A host with no name at all. The service needs a UMP endpoint name to build the
    // endpoint and to advertise, so this cannot be allowed through.
    MidiNetworkHostCreationConfig config;

    config.Name(L"");
    config.ServiceInstanceName(L"");
    config.ProductInstanceId(L"");
    config.UseAutomaticPortAllocation(true);
    config.Advertise(false);

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_IS_FALSE(response.ErrorMessage().empty());

    Log::Comment(String().Format(
        L"Empty fields rejected with 0x%08X: %s",
        (uint32_t)response.ErrorCode(),
        response.ErrorMessage().c_str()));
}

void MidiNetworkApiTests::TestFuzzOversizeEndpointNameIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkHostCreationConfig config;

    auto hostId = config.HostId();

    config.Name(winrt::hstring{ RepeatedString(L'N', MaxUmpEndpointNameBytes + 50) });
    config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() });
    config.ProductInstanceId(L"TestProductInstance");
    config.UseAutomaticPortAllocation(true);
    config.Advertise(false);

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

    VERIFY_IS_NOT_NULL(response);

    // The name limit used to be enforced only when the host was being started, which meant
    // creation reported success and the host then silently never appeared.
    VERIFY_IS_FALSE(response.Success());
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::EndpointNameTooLong, response.ErrorCode());

    VERIFY_IS_TRUE(HostIsAbsent(hostId));
}

void MidiNetworkApiTests::TestFuzzOversizeProductInstanceIdIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkHostCreationConfig config;

    auto hostId = config.HostId();

    config.Name(L"Oversize Product Instance Id Test");
    config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() });
    config.ProductInstanceId(winrt::hstring{ RepeatedString(L'P', MaxProductInstanceIdBytes + 20) });
    config.UseAutomaticPortAllocation(true);
    config.Advertise(false);

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::ProductInstanceIdTooLong, response.ErrorCode());

    VERIFY_IS_TRUE(HostIsAbsent(hostId));
}

void MidiNetworkApiTests::TestFuzzHugeStringsAreRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Far past anything the protocol or the configuration file could carry. The point is
    // that this is refused rather than allocated, serialized and sent.
    MidiNetworkHostCreationConfig config;

    auto hostId = config.HostId();

    config.Name(winrt::hstring{ RepeatedString(L'A', 64 * 1024) });
    config.ServiceInstanceName(winrt::hstring{ RepeatedString(L'B', 64 * 1024) });
    config.ProductInstanceId(winrt::hstring{ RepeatedString(L'C', 64 * 1024) });
    config.ManuallyAssignedPort(winrt::hstring{ RepeatedString(L'9', 4096) });
    config.UseAutomaticPortAllocation(false);
    config.Advertise(false);

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    VERIFY_IS_TRUE(HostIsAbsent(hostId));

    Log::Comment(String().Format(L"Huge strings rejected with 0x%08X", (uint32_t)response.ErrorCode()));
}

void MidiNetworkApiTests::TestFuzzHostileCharactersDoNotCrash()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Quotes and backslashes break naive json building, braces look like guids, control
    // characters and surrogate pairs break naive string handling, and path separators and
    // '#' are meaningful in device interface ids.
    const std::wstring hostileNames[] =
    {
        L"\"quoted\"",
        L"back\\slash",
        L"{not-a-guid}",
        L"new\r\nline",
        L"tab\there",
        L"null\u0001control",
        L"emoji \U0001F3B9 surrogate",
        L"semi;colon#hash\\?query",
        L"../../relative/path",
        L"%s %d %n format",
        L"<xml attr='x'/>",
    };

    for (auto const& name : hostileNames)
    {
        MidiNetworkHostCreationConfig config;

        auto hostId = config.HostId();

        config.Name(winrt::hstring{ name });
        config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() });
        config.ProductInstanceId(L"HostileCharTest");
        config.UseAutomaticPortAllocation(true);
        config.Advertise(false);

        // Whether the service accepts or rejects any given string is its business. What
        // matters is that the call returns a response and the host does not linger.
        auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

        VERIFY_IS_NOT_NULL(response);

        if (response.Success())
        {
            // Removing before the creator thread has promoted the pending definition can race
            // with it, so wait for the host to exist before taking it away.
            if (HostIsPresent(hostId))
            {
                RemoveTestHost(hostId);

                VERIFY_IS_TRUE(HostIsAbsent(hostId));
            }
            else
            {
                Log::Comment(String().Format(L"Host for name '%s' was accepted but never appeared.", name.c_str()));

                RemoveTestHost(hostId);
            }
        }
    }

    // and the transport is still healthy afterwards
    VERIFY_IS_NOT_NULL(MidiNetworkTransportManager::GetConfiguredHosts());
    VERIFY_IS_NOT_NULL(MidiNetworkTransportManager::GetPendingRemoteClients());
}

void MidiNetworkApiTests::TestFuzzUnknownGuidsFailCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Guids the service has never seen, including the empty one, on every verb which
    // takes an entry identifier.
    const winrt::guid unknownIds[] =
    {
        winrt::guid{},
        foundation::GuidHelper::CreateNewGuid(),
        winrt::guid{ L"FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF" },
    };

    for (auto const& id : unknownIds)
    {
        auto startResponse = MidiNetworkTransportManager::StartNetworkHostAsync(id).get();
        VERIFY_IS_NOT_NULL(startResponse);
        VERIFY_IS_FALSE(startResponse.Success());

        auto stopResponse = MidiNetworkTransportManager::StopNetworkHostAsync(id).get();
        VERIFY_IS_NOT_NULL(stopResponse);
        VERIFY_IS_FALSE(stopResponse.Success());

        MidiNetworkHostRemovalConfig removalConfig(id);
        auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();
        VERIFY_IS_NOT_NULL(removalResponse);
        VERIFY_IS_FALSE(removalResponse.Success());

        MidiNetworkClientDisconnectConfig disconnectConfig(id);
        auto disconnectResponse = MidiNetworkTransportManager::DisconnectNetworkClientAsync(disconnectConfig).get();
        VERIFY_IS_NOT_NULL(disconnectResponse);
        VERIFY_IS_FALSE(disconnectResponse.Success());
    }
}

void MidiNetworkApiTests::TestFuzzInvalidPortsAreRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Port is a string on the wire, so it can be anything at all.
    const std::wstring badPorts[] =
    {
        L"",
        L"0",
        L"-1",
        L"65536",
        L"99999999999999999999",
        L"not-a-port",
        L"80abc",
        L" 443 ",
    };

    for (auto const& port : badPorts)
    {
        auto clientId = foundation::GuidHelper::CreateNewGuid();

        MidiNetworkClientMatchCriteria criteria;
        criteria.DirectHostNameOrIPAddress(L"127.0.0.1");

        MidiNetworkClientConnectConfig config;
        config.ClientId(clientId);
        config.UmpEndpointName(L"Invalid Port Test");
        config.MatchCriteria(criteria);

        auto response = MidiNetworkTransportManager::ConnectNetworkClientAsync(config).get();

        VERIFY_IS_NOT_NULL(response);

        // DirectPort is a UInt16 in the API, so the out-of-range string cases cannot even be
        // expressed. What is reachable is port zero, which must still be refused.
        Log::Comment(String().Format(
            L"port '%s' -> success=%s code=0x%08X",
            port.c_str(),
            response.Success() ? L"true" : L"false",
            (uint32_t)response.ErrorCode()));

        if (response.Success())
        {
            MidiNetworkClientDisconnectConfig disconnectConfig(clientId);
            MidiNetworkTransportManager::DisconnectNetworkClientAsync(disconnectConfig).get();
        }
    }
}

void MidiNetworkApiTests::TestFuzzRepeatedBadCallsAreStable()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // A settings app with a bug, or something malicious, could hammer these. The service
    // must not accumulate state, and the API must keep answering.
    const int iterations = 100;

    for (int i = 0; i < iterations; i++)
    {
        auto id = foundation::GuidHelper::CreateNewGuid();

        MidiNetworkHostRemovalConfig removalConfig(id);
        auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();
        VERIFY_IS_FALSE(removalResponse.Success());

        MidiNetworkRemoteClientApprovalConfig approvalConfig(id, L"nobody", L"nothing", true, false);
        auto approvalResponse = MidiNetworkTransportManager::ApproveOrDenyRemoteClientConnectRequestAsync(approvalConfig).get();
        VERIFY_IS_FALSE(approvalResponse.Success());
    }

    // the transport is still answering normally
    auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();
    VERIFY_IS_NOT_NULL(hosts);

    auto pending = MidiNetworkTransportManager::GetPendingRemoteClients();
    VERIFY_IS_NOT_NULL(pending);

    Log::Comment(String().Format(L"%d hostile round trips completed, %d hosts still configured", iterations, hosts.Size()));
}


// ============================================================================
// Feature coverage
// ============================================================================

void MidiNetworkApiTests::TestAdvertisedHostWatcherLifecycle()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto watcher = MidiNetworkAdvertisedHostWatcher::Create();

    VERIFY_IS_NOT_NULL(watcher);

    // events must be subscribable and revocable even if nothing ever fires
    auto addedToken = watcher.Added([](auto&&, auto&&) {});
    auto removedToken = watcher.Removed([](auto&&, auto&&) {});
    auto updatedToken = watcher.Updated([](auto&&, auto&&) {});
    auto enumerationCompletedToken = watcher.EnumerationCompleted([](auto&&, auto&&) {});
    auto stoppedToken = watcher.Stopped([](auto&&, auto&&) {});

    VERIFY_IS_NOT_NULL(watcher.EnumeratedHosts());

    watcher.Start();

    // mDNS discovery is not instant and there may be nothing on the network at all, so this
    // only checks that the watcher reaches a sane state rather than that it finds anything.
    std::this_thread::sleep_for(std::chrono::seconds(2));

    Log::Comment(String().Format(L"Watcher started: %d, hosts seen: %d",
        watcher.IsStarted() ? 1 : 0,
        watcher.EnumeratedHosts().Size()));

    VERIFY_IS_TRUE(watcher.IsStarted());

    watcher.Stop();

    VERIFY_IS_FALSE(watcher.IsStarted());

    watcher.Added(addedToken);
    watcher.Removed(removedToken);
    watcher.Updated(updatedToken);
    watcher.EnumerationCompleted(enumerationCompletedToken);
    watcher.Stopped(stoppedToken);
}

void MidiNetworkApiTests::TestAdvertisedHostWatcherDoubleStartStopIsSafe()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto watcher = MidiNetworkAdvertisedHostWatcher::Create();
    VERIFY_IS_NOT_NULL(watcher);

    // Repeated calls in either direction have to be harmless, and these are all noexcept, so an
    // unguarded throw would terminate the process rather than fail the test.
    watcher.Stop();
    watcher.Start();
    watcher.Start();
    watcher.Stop();
    watcher.Stop();

    Log::Comment(String().Format(L"Watcher survived repeated start/stop, started %d", watcher.IsStarted() ? 1 : 0));

    VERIFY_IS_FALSE(watcher.IsStarted());
}

// https://github.com/microsoft/MIDI/issues/1149. Creating a host raises Added; removing it has
// to raise Removed. The transport tests prove the service stops answering mDNS queries and
// multicasts a goodbye with TTL 0 for the PTR, SRV and TXT records, so a failure here is in the
// watcher or the platform discovery layer beneath it, not in the advertisement.
void MidiNetworkApiTests::TestAdvertisedHostWatcherRaisesAddedAndRemovedForARealHost()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto watcher = MidiNetworkAdvertisedHostWatcher::Create();

    VERIFY_IS_NOT_NULL(watcher);

    wil::unique_event addedSignal;
    wil::unique_event removedSignal;

    addedSignal.create(wil::EventOptions::ManualReset);
    removedSignal.create(wil::EventOptions::ManualReset);

    // The suffix is what makes this host's device id unique, and the id is how the two events
    // are tied to this test rather than to whatever else is on the network.
    auto const suffix = MakeUniqueSuffix();
    auto const expectedInstanceFragment = std::wstring{ TestHostNamePrefix } + suffix;

    std::mutex idLock;
    std::wstring addedDeviceId;

    auto addedToken = watcher.Added([&](auto&&, MidiNetworkAdvertisedHostAddedEventArgs const& args)
        {
            auto const id = std::wstring{ args.AddedHost().DeviceId() };

            if (id.find(expectedInstanceFragment) != std::wstring::npos)
            {
                {
                    auto lock = std::scoped_lock{ idLock };
                    addedDeviceId = id;
                }

                addedSignal.SetEvent();
            }
        });

    auto removedToken = watcher.Removed([&](auto&&, MidiNetworkAdvertisedHostRemovedEventArgs const& args)
        {
            auto const id = std::wstring{ args.HostDeviceId() };

            if (id.find(expectedInstanceFragment) != std::wstring::npos)
            {
                removedSignal.SetEvent();
            }
        });

    auto revoke = wil::scope_exit([&]()
        {
            watcher.Added(addedToken);
            watcher.Removed(removedToken);
            watcher.Stop();
        });

    watcher.Start();

    // Started before the host exists, so the arrival is a genuine Added rather than part of
    // the initial enumeration.
    std::this_thread::sleep_for(std::chrono::seconds(3));

    auto hostId = CreateTestHost(suffix, true);

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    VERIFY_IS_TRUE(
        addedSignal.wait(30000),
        L"The watcher raised Added for a newly advertised host");

    {
        auto lock = std::scoped_lock{ idLock };
        Log::Comment(String().Format(L"Added device id: %s", addedDeviceId.c_str()));
    }

    MidiNetworkHostRemovalConfig removalConfig(hostId);

    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(removalResponse);
    VERIFY_IS_TRUE(removalResponse.Success());

    cleanup.release();

    VERIFY_IS_TRUE(
        removedSignal.wait(60000),
        L"The watcher raised Removed once the host stopped advertising");
}


namespace
{
    std::wstring DescribeInspectable(winrt::Windows::Foundation::IInspectable const& value)
    {
        if (value == nullptr) return L"<null>";

        if (auto v = value.try_as<winrt::hstring>())              return L"\"" + std::wstring{ *v } + L"\"";
        if (auto v = value.try_as<bool>())                        return *v ? L"true" : L"false";
        if (auto v = value.try_as<uint8_t>())                     return std::to_wstring(*v);
        if (auto v = value.try_as<uint16_t>())                    return std::to_wstring(*v);
        if (auto v = value.try_as<uint32_t>())                    return std::to_wstring(*v);
        if (auto v = value.try_as<int32_t>())                     return std::to_wstring(*v);
        if (auto v = value.try_as<uint64_t>())                    return std::to_wstring(*v);
        if (auto v = value.try_as<winrt::guid>())                 return std::wstring{ winrt::to_hstring(*v) };

        if (auto v = value.try_as<winrt::Windows::Foundation::IReferenceArray<winrt::hstring>>())
        {
            std::wstring joined{ L"[" };

            for (auto const& item : v.Value())
            {
                joined += L"'" + std::wstring{ item } + L"' ";
            }

            return joined + L"]";
        }

        return L"<unhandled type>";
    }
}

// Not a real test. Kept because reproducing 1149 needs a watcher that requests more properties
// than the SDK's, and rebuilding that by hand each time is slow.
void MidiNetworkApiTests::TestDiagDnssdWatcherPropertiesAcrossHostRemoval()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    namespace enumeration = winrt::Windows::Devices::Enumeration;

    // Everything plausibly carrying a liveness signal. All are valid canonical names; an
    // invalid one makes CreateWatcher throw.
    auto props = winrt::single_threaded_vector<winrt::hstring>(
        {
            L"System.Devices.Dnssd.InstanceName",
            L"System.Devices.Dnssd.HostName",
            L"System.Devices.Dnssd.PortNumber",
            L"System.Devices.Dnssd.TextAttributes",
            L"System.Devices.Dnssd.Ttl",
            L"System.Devices.InterfaceEnabled",
            L"System.Devices.Aep.IsPresent",
            L"System.Devices.Aep.IsConnected",
            L"System.Devices.AepService.ParentAepIsPaired",
        });

    // The AQS is no longer part of the SDK surface, because discovery no longer goes through
    // Windows.Devices.Enumeration. It is restated here because this test is about that layer.
    auto watcher = enumeration::DeviceInformation::CreateWatcher(
        L"System.Devices.AepService.ProtocolId:={4526e8c1-8aac-4153-9b16-55e86ada0e54} AND "
        L"System.Devices.Dnssd.ServiceName:=\"_midi2._udp\" AND "
        L"System.Devices.Dnssd.Domain:=\"local\"",
        props,
        enumeration::DeviceInformationKind::AssociationEndpointService);

    auto const suffix = MakeUniqueSuffix();
    auto const fragment = std::wstring{ TestHostNamePrefix } + suffix;

    auto addedToken = watcher.Added([&](auto&&, enumeration::DeviceInformation const& info)
        {
            if (std::wstring{ info.Id() }.find(fragment) == std::wstring::npos) return;

            Log::Comment(String().Format(L"[ADDED] %s", info.Id().c_str()));

            for (auto const& kv : info.Properties())
            {
                Log::Comment(String().Format(L"        %s = %s",
                    kv.Key().c_str(), DescribeInspectable(kv.Value()).c_str()));
            }
        });

    auto updatedToken = watcher.Updated([&](auto&&, enumeration::DeviceInformationUpdate const& update)
        {
            if (std::wstring{ update.Id() }.find(fragment) == std::wstring::npos) return;

            Log::Comment(String().Format(L"[UPDATED] %d changed propert(ies)", update.Properties().Size()));

            for (auto const& kv : update.Properties())
            {
                Log::Comment(String().Format(L"        %s = %s",
                    kv.Key().c_str(), DescribeInspectable(kv.Value()).c_str()));
            }
        });

    auto removedToken = watcher.Removed([&](auto&&, enumeration::DeviceInformationUpdate const& update)
        {
            if (std::wstring{ update.Id() }.find(fragment) == std::wstring::npos) return;

            Log::Comment(String().Format(L"[REMOVED] %s", update.Id().c_str()));
        });

    auto revoke = wil::scope_exit([&]()
        {
            watcher.Added(addedToken);
            watcher.Updated(updatedToken);
            watcher.Removed(removedToken);
        });

    watcher.Start();

    std::this_thread::sleep_for(std::chrono::seconds(3));

    auto hostId = CreateTestHost(suffix, true);

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    Log::Comment(L"=== host is live, observing for 30s ===");
    std::this_thread::sleep_for(std::chrono::seconds(30));

    Log::Comment(L"=== removing host ===");

    MidiNetworkHostRemovalConfig removalConfig(hostId);
    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(removalResponse);
    VERIFY_IS_TRUE(removalResponse.Success());

    cleanup.release();

    Log::Comment(L"=== host removed, observing for 120s ===");
    std::this_thread::sleep_for(std::chrono::seconds(120));

    Log::Comment(L"=== done ===");

    watcher.Stop();
}


#include "midi_dnssd_browser.h"
#include "midi_network_port_picker.h"

// The shared browser is what both the SDK watcher and the service transport sit on, so this is
// the lowest level at which 1149 can be pinned down.
void MidiNetworkApiTests::TestDnssdBrowserReportsHostAddedAndRemoved()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto const suffix = MakeUniqueSuffix();
    auto const expectedInstance = std::wstring{ TestHostNamePrefix } + suffix;

    WindowsMidiServicesInternal::MidiDnssdBrowser browser;

    wil::unique_event addedSignal;
    wil::unique_event removedSignal;

    addedSignal.create(wil::EventOptions::ManualReset);
    removedSignal.create(wil::EventOptions::ManualReset);

    std::mutex captureLock;
    WindowsMidiServicesInternal::MidiDnssdService capturedAdd;
    std::wstring capturedRemovedDeviceId;
    int addedCount{ 0 };
    int updatedCount{ 0 };

    auto matches = [&expectedInstance](std::wstring const& name)
        {
            return name.find(expectedInstance) != std::wstring::npos;
        };

    auto hr = browser.Start(
        L"_midi2._udp.local",
        [&](WindowsMidiServicesInternal::MidiDnssdService const& service)
        {
            if (!matches(service.FullName)) return;

            {
                auto guard = std::scoped_lock{ captureLock };
                capturedAdd = service;
                addedCount++;
            }

            addedSignal.SetEvent();
        },
        [&](WindowsMidiServicesInternal::MidiDnssdService const& service, uint32_t const changedFields)
        {
            if (!matches(service.FullName)) return;

            auto guard = std::scoped_lock{ captureLock };
            updatedCount++;

            // An update is only ever raised for a real change, so it must name at least one.
            VERIFY_ARE_NOT_EQUAL(
                static_cast<uint32_t>(WindowsMidiServicesInternal::MidiDnssdChangedNone),
                changedFields);
        },
        [&](std::wstring const& fullName, std::wstring const& deviceId)
        {
            if (!matches(fullName)) return;

            {
                auto guard = std::scoped_lock{ captureLock };
                capturedRemovedDeviceId = deviceId;
            }

            removedSignal.SetEvent();
        });

    VERIFY_SUCCEEDED(hr);
    VERIFY_IS_TRUE(browser.IsRunning());

    auto stopBrowser = wil::scope_exit([&]() { browser.Stop(); });

    std::this_thread::sleep_for(std::chrono::seconds(2));

    auto hostId = CreateTestHost(suffix, true);

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    VERIFY_IS_TRUE(addedSignal.wait(30000), L"The browser reported the new host");

    {
        auto guard = std::scoped_lock{ captureLock };

        Log::Comment(String().Format(L"Added: full name '%s'", capturedAdd.FullName.c_str()));
        Log::Comment(String().Format(L"       instance  '%s'", capturedAdd.ServiceInstanceName.c_str()));
        Log::Comment(String().Format(L"       type '%s' domain '%s'", capturedAdd.ServiceType.c_str(), capturedAdd.Domain.c_str()));
        Log::Comment(String().Format(L"       host '%s' port %d", capturedAdd.HostName.c_str(), capturedAdd.Port));
        Log::Comment(String().Format(L"       device id '%s'", capturedAdd.DeviceId().c_str()));
        Log::Comment(String().Format(L"       UMP endpoint name '%s'", capturedAdd.UmpEndpointName().c_str()));
        Log::Comment(String().Format(L"       product instance id '%s'", capturedAdd.ProductInstanceId().c_str()));

        for (auto const& address : capturedAdd.IPv4Addresses)
        {
            Log::Comment(String().Format(L"       IPv4 %s", address.c_str()));
        }

        for (auto const& address : capturedAdd.IPv6Addresses)
        {
            Log::Comment(String().Format(L"       IPv6 %s", address.c_str()));
        }

        // Everything a caller needs to connect has to be present on the Added report itself.
        VERIFY_ARE_EQUAL(expectedInstance, capturedAdd.ServiceInstanceName);
        VERIFY_ARE_EQUAL(std::wstring{ L"_midi2._udp" }, capturedAdd.ServiceType);
        VERIFY_ARE_EQUAL(std::wstring{ L"local" }, capturedAdd.Domain);
        VERIFY_IS_FALSE(capturedAdd.HostName.empty());
        VERIFY_IS_GREATER_THAN(capturedAdd.Port, static_cast<uint16_t>(0));
        VERIFY_IS_FALSE(capturedAdd.IPv4Addresses.empty(), L"At least one address was resolved");
        VERIFY_ARE_EQUAL(expectedInstance, capturedAdd.UmpEndpointName());

        // Existing configuration files store this exact form as the client match id.
        VERIFY_ARE_EQUAL(
            std::wstring{ L"DnsSd#" } + expectedInstance + L"._midi2._udp.local#0",
            capturedAdd.DeviceId());

        // Re-announcements repeat records constantly. Added must not fire again for them.
        VERIFY_ARE_EQUAL(1, addedCount, L"Added fired exactly once despite re-announcements");
    }

    VERIFY_IS_TRUE(browser.EnumeratedServices().size() > 0);

    MidiNetworkHostRemovalConfig removalConfig(hostId);
    auto removalResponse = MidiNetworkTransportManager::RemoveNetworkHostAsync(removalConfig).get();

    VERIFY_IS_NOT_NULL(removalResponse);
    VERIFY_IS_TRUE(removalResponse.Success());

    cleanup.release();

    VERIFY_IS_TRUE(removedSignal.wait(30000), L"The browser reported the host going away");

    {
        auto guard = std::scoped_lock{ captureLock };

        // The removal has to carry the same id the addition did, or a caller cannot correlate.
        VERIFY_ARE_EQUAL(capturedAdd.DeviceId(), capturedRemovedDeviceId);

        Log::Comment(String().Format(L"Updated fired %d time(s) while the host was live", updatedCount));
    }
}

void MidiNetworkApiTests::TestDnssdServiceChangedFieldsNameEachChange()
{
    using namespace WindowsMidiServicesInternal;

    MidiDnssdService baseline{ };
    baseline.FullName = L"thing._midi2._udp.local";
    baseline.HostName = L"thing.local";
    baseline.Port = 5004;
    baseline.IPv4Addresses = { L"192.168.1.10" };
    baseline.IPv6Addresses = { L"fe80::1" };
    baseline.TextAttributes = { { L"UMPEndpointName", L"Thing" } };

    VERIFY_ARE_EQUAL(
        static_cast<uint32_t>(MidiDnssdChangedNone),
        baseline.ChangedFieldsSince(baseline),
        L"An identical re-announcement reports no change");

    {
        auto s = baseline; s.HostName = L"other.local";
        VERIFY_ARE_EQUAL(static_cast<uint32_t>(MidiDnssdChangedHostName), s.ChangedFieldsSince(baseline));
    }

    {
        auto s = baseline; s.Port = 5006;
        VERIFY_ARE_EQUAL(static_cast<uint32_t>(MidiDnssdChangedPort), s.ChangedFieldsSince(baseline));
    }

    {
        auto s = baseline; s.IPv4Addresses = { L"192.168.1.11" };
        VERIFY_ARE_EQUAL(static_cast<uint32_t>(MidiDnssdChangedIPv4Addresses), s.ChangedFieldsSince(baseline));
    }

    {
        auto s = baseline; s.IPv6Addresses.push_back(L"fe80::2");
        VERIFY_ARE_EQUAL(static_cast<uint32_t>(MidiDnssdChangedIPv6Addresses), s.ChangedFieldsSince(baseline));
    }

    {
        auto s = baseline; s.TextAttributes[L"ProductInstanceId"] = L"ABC";
        VERIFY_ARE_EQUAL(static_cast<uint32_t>(MidiDnssdChangedTextAttributes), s.ChangedFieldsSince(baseline));
    }

    // Several at once have to come back combined, not just the first one found.
    {
        auto s = baseline;
        s.Port = 5008;
        s.HostName = L"moved.local";
        s.IPv4Addresses.clear();

        VERIFY_ARE_EQUAL(
            static_cast<uint32_t>(MidiDnssdChangedHostName | MidiDnssdChangedPort | MidiDnssdChangedIPv4Addresses),
            s.ChangedFieldsSince(baseline),
            L"Simultaneous changes are all reported");
    }

    // The DeviceId is the caller's correlation key and must not move for a content change.
    {
        auto s = baseline; s.Port = 9999;

        VERIFY_ARE_EQUAL(baseline.DeviceId(), s.DeviceId());
    }
}

void MidiNetworkApiTests::TestGeneratedHostPortIsUsableAndInRange()
{
    using namespace WindowsMidiServicesInternal;

    uint16_t port{ 0 };

    VERIFY_IS_TRUE(TryGenerateAvailableHostPort(port));

    Log::Comment(String().Format(L"Generated port %d", port));

    VERIFY_IS_GREATER_THAN_OR_EQUAL(port, MidiNetworkGeneratedPortRangeLow);
    VERIFY_IS_LESS_THAN_OR_EQUAL(port, MidiNetworkGeneratedPortRangeHigh);

    // Below the Windows dynamic range, or the OS would hand it to some other process and the
    // whole point of keeping the port is lost.
    VERIFY_IS_LESS_THAN(port, static_cast<uint16_t>(49152));

    VERIFY_IS_TRUE(IsUdpPortAvailable(port), L"A freshly generated port is free");

    // Repeated calls must not keep handing out the same number.
    bool sawDifferent{ false };

    for (int i = 0; i < 10 && !sawDifferent; i++)
    {
        uint16_t another{ 0 };

        VERIFY_IS_TRUE(TryGenerateAvailableHostPort(another));

        sawDifferent = (another != port);
    }

    VERIFY_IS_TRUE(sawDifferent, L"Generated ports are randomised");
}

// The case a naive picker gets wrong. A port held by the MIDI service, which runs as
// LocalSystem, reports WSAEACCES to a normal user process rather than WSAEADDRINUSE.
void MidiNetworkApiTests::TestPortPickerRejectsAPortTheServiceAlreadyHolds()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

    VERIFY_IS_NOT_NULL(hosts);

    std::vector<uint16_t> livePorts;

    for (auto const& host : hosts)
    {
        if (!host.HasStarted()) continue;

        auto const text = std::wstring{ host.ActualPort() };

        if (text.empty()) continue;

        livePorts.push_back(static_cast<uint16_t>(std::stoul(text)));
    }

    if (livePorts.empty())
    {
        Log::Result(TestResults::Skipped, L"No started host on this PC to test against.");

        return;
    }

    for (auto const port : livePorts)
    {
        Log::Comment(String().Format(L"Live host port %d", port));

        VERIFY_IS_FALSE(
            WindowsMidiServicesInternal::IsUdpPortAvailable(port),
            L"A port the service is already bound to is not offered as available");
    }
}

void MidiNetworkApiTests::TestUnusedServiceInstanceNameIsReturnedUnchanged()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto const unused = winrt::hstring{ std::wstring{ L"midi-name-check-" } + std::to_wstring(GetTickCount64()) };

    VERIFY_IS_TRUE(
        MidiNetworkHostCreationConfig::IsServiceInstanceNameAvailable(unused),
        L"A name nobody holds is available");

    // No decoration when none is needed, or every host would end up called something-02.
    VERIFY_ARE_EQUAL(
        unused,
        MidiNetworkHostCreationConfig::MakeUniqueServiceInstanceName(unused));
}

void MidiNetworkApiTests::TestServiceInstanceNameInUseIsDetectedAndAnAlternativeOffered()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto const suffix = MakeUniqueSuffix();

    auto hostId = CreateTestHost(suffix);

    VERIFY_IS_FALSE(hostId == winrt::guid{});

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    auto const taken = winrt::hstring{ std::wstring{ TestHostNamePrefix } + suffix };

    Log::Comment(String().Format(L"Name held by the new host: %s", taken.c_str()));

    // A stopped or non advertising host still holds its name, so this has to see the configured
    // host rather than only what is on the wire.
    VERIFY_IS_FALSE(
        MidiNetworkHostCreationConfig::IsServiceInstanceNameAvailable(taken),
        L"A name a configured host already holds is not available");

    auto const alternative = MidiNetworkHostCreationConfig::MakeUniqueServiceInstanceName(taken);

    Log::Comment(String().Format(L"Offered alternative: %s", alternative.c_str()));

    VERIFY_ARE_NOT_EQUAL(taken, alternative);

    VERIFY_IS_TRUE(
        std::wstring{ alternative }.find(L"-02") != std::wstring::npos,
        L"The first alternative is the original with -02 appended");

    // The whole point of offering it is that it can actually be used.
    VERIFY_IS_TRUE(
        MidiNetworkHostCreationConfig::IsServiceInstanceNameAvailable(alternative),
        L"The offered alternative is itself free");
}

void MidiNetworkApiTests::TestClientMatchCriteriaRoundTrip()
{
    MidiNetworkClientMatchCriteria criteria;

    criteria.DeviceId(L"SomeDeviceId");
    criteria.DirectHostNameOrIPAddress(L"192.168.1.50");
    criteria.DirectPort(5673);

    VERIFY_ARE_EQUAL(winrt::hstring{ L"SomeDeviceId" }, criteria.DeviceId());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"192.168.1.50" }, criteria.DirectHostNameOrIPAddress());
    VERIFY_ARE_EQUAL((uint16_t)5673, criteria.DirectPort());

    // must not throw or return null even when only partly populated
    auto json = criteria.GetConfigJson();

    Log::Comment(String().Format(L"Match criteria json: %s", json.c_str()));
}

void MidiNetworkApiTests::TestClientConnectConfigRoundTrip()
{
    auto clientId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkClientMatchCriteria criteria;
    criteria.DirectHostNameOrIPAddress(L"127.0.0.1");
    criteria.DirectPort(5004);

    MidiNetworkClientConnectConfig config;

    config.ClientId(clientId);
    config.Comment(L"a comment");
    config.UmpEndpointName(L"Round Trip Endpoint");
    config.CreateOnlyUmpEndpoints(true);
    config.MatchCriteria(criteria);

    VERIFY_ARE_EQUAL(clientId, config.ClientId());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"a comment" }, config.Comment());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"Round Trip Endpoint" }, config.UmpEndpointName());
    VERIFY_IS_TRUE(config.CreateOnlyUmpEndpoints());
    VERIFY_IS_NOT_NULL(config.MatchCriteria());
    VERIFY_ARE_EQUAL((uint16_t)5004, config.MatchCriteria().DirectPort());

    VERIFY_ARE_EQUAL(MidiNetworkTransportManager::TransportId(), config.TransportId());
    VERIFY_IS_NOT_NULL(config.ConfigJson());
}

void MidiNetworkApiTests::TestDisconnectUnknownClientFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkClientDisconnectConfig config(foundation::GuidHelper::CreateNewGuid());

    auto response = MidiNetworkTransportManager::DisconnectNetworkClientAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    Log::Comment(String().Format(
        L"Disconnect of unknown client failed with 0x%08X: %s",
        (uint32_t)response.ErrorCode(),
        response.ErrorMessage().c_str()));
}


// ------------------------------------------------------------------------------
// Connecting by device id
// ------------------------------------------------------------------------------

namespace
{
    // The configured client entry for an id, from the service, or nothing. Polled because the
    // service registers the definition on its own threads.
    MidiNetworkConfiguredClient FindConfiguredClient(_In_ winrt::guid const& clientId)
    {
        for (int attempt = 0; attempt < 40; attempt++)
        {
            auto clients = MidiNetworkTransportManager::GetConfiguredClients();

            if (clients != nullptr)
            {
                for (auto const& client : clients)
                {
                    if (client != nullptr && client.ClientId() == clientId)
                    {
                        return client;
                    }
                }
            }

            std::this_thread::sleep_for(std::chrono::milliseconds(250));
        }

        return nullptr;
    }

    bool ConfiguredClientIsGone(_In_ winrt::guid const& clientId)
    {
        for (int attempt = 0; attempt < 40; attempt++)
        {
            auto clients = MidiNetworkTransportManager::GetConfiguredClients();

            bool found{ false };

            if (clients != nullptr)
            {
                for (auto const& client : clients)
                {
                    if (client != nullptr && client.ClientId() == clientId)
                    {
                        found = true;
                        break;
                    }
                }
            }

            if (!found)
            {
                return true;
            }

            std::this_thread::sleep_for(std::chrono::milliseconds(250));
        }

        return false;
    }

    // Best effort, so a failed assert cannot leave an entry in the service.
    void RemoveTestClient(_In_ winrt::guid const& clientId)
    {
        try
        {
            MidiNetworkClientDisconnectConfig config(clientId);
            MidiNetworkTransportManager::DisconnectNetworkClientAsync(config).get();
        }
        catch (...)
        {
        }
    }
}

void MidiNetworkApiTests::TestConnectByDeviceIdCreatesAnMdnsMatchedEntry()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // A device id which resolves to nothing, so no connection is attempted. What matters is
    // that the entry the service records is a device id match rather than an address, because
    // only that survives the remote moving to a new address or port.
    auto clientId = foundation::GuidHelper::CreateNewGuid();
    auto deviceId = winrt::hstring{ std::wstring{ L"MidiApiTest_NoSuchDevice_" } + MakeUniqueSuffix() };

    MidiNetworkClientMatchCriteria criteria;
    criteria.DeviceId(deviceId);

    MidiNetworkClientConnectConfig config;
    config.ClientId(clientId);
    config.UmpEndpointName(L"MidiApiTest Device Id Match");
    config.MatchCriteria(criteria);

    auto response = MidiNetworkTransportManager::ConnectNetworkClientAsync(config).get();

    VERIFY_IS_NOT_NULL(response);

    if (response != nullptr)
    {
        Log::Comment(String().Format(
            L"Connect by device id: success=%d code=0x%08X message='%s'",
            response.Success() ? 1 : 0,
            (uint32_t)response.ErrorCode(),
            response.ErrorMessage().c_str()));
    }

    VERIFY_IS_TRUE(response.Success(), L"A device id is enough to connect with");

    if (!response.Success())
    {
        return;
    }

    auto entry = FindConfiguredClient(clientId);

    VERIFY_IS_NOT_NULL(entry);

    if (entry != nullptr)
    {
        VERIFY_ARE_EQUAL(deviceId, entry.MatchDeviceId(), L"The entry matches on the device id it was given");
        VERIFY_IS_FALSE(entry.IsDirectConnection(), L"A device id match is not a direct connection");
    }

    RemoveTestClient(clientId);
}

void MidiNetworkApiTests::TestConnectWithNoMatchCriteriaValuesFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Criteria which name nothing at all. Previously this reached the service as a direct
    // connect with an empty address, which is a much less useful error.
    MidiNetworkClientMatchCriteria criteria;

    MidiNetworkClientConnectConfig config;
    config.ClientId(foundation::GuidHelper::CreateNewGuid());
    config.UmpEndpointName(L"MidiApiTest Empty Criteria");
    config.MatchCriteria(criteria);

    auto response = MidiNetworkTransportManager::ConnectNetworkClientAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    VERIFY_ARE_EQUAL(
        MidiNetworkClientConnectErrorCode::InvalidOrMissingMatchCriteria,
        response.ErrorCode(),
        L"Criteria with neither a device id nor an address are rejected as such");
}

void MidiNetworkApiTests::TestConnectByDeviceIdEntryCanBeDisconnected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto clientId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkClientMatchCriteria criteria;
    criteria.DeviceId(winrt::hstring{ std::wstring{ L"MidiApiTest_NoSuchDevice_" } + MakeUniqueSuffix() });

    MidiNetworkClientConnectConfig config;
    config.ClientId(clientId);
    config.UmpEndpointName(L"MidiApiTest Device Id Removal");
    config.MatchCriteria(criteria);

    auto connectResponse = MidiNetworkTransportManager::ConnectNetworkClientAsync(config).get();
    VERIFY_IS_TRUE(connectResponse != nullptr && connectResponse.Success());

    VERIFY_IS_NOT_NULL(FindConfiguredClient(clientId));

    // This entry never became a live client, and removing one used to report "client not found"
    // and leave it in the list for good.
    MidiNetworkClientDisconnectConfig disconnectConfig(clientId);

    auto disconnectResponse = MidiNetworkTransportManager::DisconnectNetworkClientAsync(disconnectConfig).get();

    VERIFY_IS_NOT_NULL(disconnectResponse);
    VERIFY_IS_TRUE(disconnectResponse.Success(), L"An entry which never connected can still be removed");

    VERIFY_IS_TRUE(ConfiguredClientIsGone(clientId), L"The entry is no longer reported");
}

void MidiNetworkApiTests::TestDisconnectRemovesTheConfiguredClientEntry()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // Loopback port 1, so nothing answers and the entry stays a definition.
    auto clientId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkClientMatchCriteria criteria;
    criteria.DirectHostNameOrIPAddress(L"127.0.0.1");
    criteria.DirectPort(1);

    MidiNetworkClientConnectConfig config;
    config.ClientId(clientId);
    config.UmpEndpointName(L"MidiApiTest Direct Removal");
    config.MatchCriteria(criteria);

    auto connectResponse = MidiNetworkTransportManager::ConnectNetworkClientAsync(config).get();
    VERIFY_IS_TRUE(connectResponse != nullptr && connectResponse.Success());

    VERIFY_IS_NOT_NULL(FindConfiguredClient(clientId));

    MidiNetworkClientDisconnectConfig disconnectConfig(clientId);

    auto disconnectResponse = MidiNetworkTransportManager::DisconnectNetworkClientAsync(disconnectConfig).get();
    VERIFY_IS_TRUE(disconnectResponse != nullptr && disconnectResponse.Success());

    VERIFY_IS_TRUE(
        ConfiguredClientIsGone(clientId),
        L"A disconnected entry is removed rather than left reporting as unavailable");
}


// ------------------------------------------------------------------------------
// Disconnecting a remote client from one of our hosts
// ------------------------------------------------------------------------------

void MidiNetworkApiTests::TestRemoteClientDisconnectConfigRoundTrip()
{
    auto hostId = foundation::GuidHelper::CreateNewGuid();

    MidiNetworkRemoteClientDisconnectConfig config(hostId, L"Some Remote", L"SOMEREMOTE01");

    VERIFY_ARE_EQUAL(hostId, config.HostId());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"Some Remote" }, config.RemoteClientName());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"SOMEREMOTE01" }, config.RemoteClientProductInstanceId());

    VERIFY_ARE_EQUAL(MidiNetworkTransportManager::TransportId(), config.TransportId());

    // Nothing is written to the configuration file for a disconnect, but the generic transport
    // plugin surface must still hand back an object rather than null.
    VERIFY_IS_NOT_NULL(config.ConfigJson());

    MidiNetworkRemoteClientDisconnectConfig settable;

    settable.HostId(hostId);
    settable.RemoteClientName(L"Renamed");
    settable.RemoteClientProductInstanceId(L"RENAMED01");

    VERIFY_ARE_EQUAL(winrt::hstring{ L"Renamed" }, settable.RemoteClientName());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"RENAMED01" }, settable.RemoteClientProductInstanceId());
}

void MidiNetworkApiTests::TestDisconnectRemoteClientWithEmptyIdentityFailsWithoutCallingService()
{
    // A remote client is named by the pair. Half of it could match the wrong device, so this is
    // rejected client-side rather than being sent on.
    MidiNetworkRemoteClientDisconnectConfig config(foundation::GuidHelper::CreateNewGuid(), L"", L"");

    auto response = MidiNetworkTransportManager::DisconnectRemoteClientAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    VERIFY_ARE_EQUAL(
        MidiNetworkRemoteClientDisconnectErrorCode::InvalidOrMissingRemoteClientIdentity,
        response.ErrorCode());
}

void MidiNetworkApiTests::TestDisconnectUnknownRemoteClientFailsCleanly()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    MidiNetworkRemoteClientDisconnectConfig config(
        foundation::GuidHelper::CreateNewGuid(),
        L"Nobody Is Connected Under This Name",
        L"NOBODY01");

    auto response = MidiNetworkTransportManager::DisconnectRemoteClientAsync(config).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());

    Log::Comment(String().Format(
        L"Disconnect of unknown remote client failed with 0x%08X: %s",
        (uint32_t)response.ErrorCode(),
        response.ErrorMessage().c_str()));
}

void MidiNetworkApiTests::TestDisconnectRemoteClientWithNullConfigFailsCleanly()
{
    // The whole surface is noexcept, so a null here must fail rather than terminate.
    auto response = MidiNetworkTransportManager::DisconnectRemoteClientAsync(nullptr).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success());
    VERIFY_ARE_EQUAL(MidiNetworkRemoteClientDisconnectErrorCode::InvalidArgument, response.ErrorCode());
}

void MidiNetworkApiTests::TestDefaultHostConfigCreatesUmpEndpointsOnly()
{
    auto config = MidiNetworkHostCreationConfig::CreateDefault();

    VERIFY_IS_NOT_NULL(config);

    if (config == nullptr) return;

    // UMP endpoints only. The comment above this line in the implementation used to claim the
    // opposite, which is exactly the sort of thing a caller copies.
    VERIFY_IS_TRUE(
        config.CreateOnlyUmpEndpoints(),
        L"The default host creates UMP endpoints only; a caller wanting MIDI 1.0 ports clears this.");
}

void MidiNetworkApiTests::TestConnectConfigCustomEndpointNameRoundTrip()
{
    MidiNetworkClientConnectConfig config;

    VERIFY_IS_TRUE(config.CustomEndpointName().empty(), L"No custom name by default");

    config.CustomEndpointName(L"Studio Rack Top");

    VERIFY_ARE_EQUAL(winrt::hstring{ L"Studio Rack Top" }, config.CustomEndpointName());

    // Endpoint names are capped by the MIDI 2.0 specification, and this shares that cap.
    config.CustomEndpointName(winrt::hstring{ RepeatedString(L'N', MaxUmpEndpointNameBytes * 2) });

    VERIFY_IS_LESS_THAN_OR_EQUAL(
        (uint32_t)winrt::to_string(config.CustomEndpointName()).length(),
        MaxUmpEndpointNameBytes,
        L"An oversize custom name is truncated rather than passed on");
}

// The DNS-SD instance label behind DeviceId is a name, not an identity: a responder renames a
// colliding label and a firmware update can change it outright. Without the device's own identity
// alongside it, a reconnect after any of that would silently never match.
void MidiNetworkApiTests::TestMatchCriteriaJsonCarriesDeviceIdentity()
{
    MidiNetworkClientMatchCriteria criteria;
    criteria.DeviceId(L"DnsSd#contoso-synth._midi2._udp.local#0");
    criteria.ProductInstanceId(L"CONTOSO-PID-12345");
    criteria.UmpEndpointName(L"Contoso Synth");

    auto const text = std::wstring{ criteria.GetConfigJson() };

    Log::Comment(String().Format(L"Match criteria json: %s", text.c_str()));

    VERIFY_IS_TRUE(
        text.find(L"CONTOSO-PID-12345") != std::wstring::npos,
        L"The product instance id reaches the configuration file");

    VERIFY_IS_TRUE(
        text.find(L"Contoso Synth") != std::wstring::npos,
        L"The advertised endpoint name reaches the configuration file");
}


void MidiNetworkApiTests::TestMatchCriteriaIdentityIsWrittenAlongsideDeviceId()
{
    MidiNetworkClientMatchCriteria criteria;
    criteria.DeviceId(L"DnsSd#contoso-synth._midi2._udp.local#0");
    criteria.ProductInstanceId(L"CONTOSO-PID-12345");

    auto const text = std::wstring{ criteria.GetConfigJson() };

    // Not an either/or: the id is the fast path and the identity is the fallback, so losing
    // either one to an if/else would defeat the point.
    VERIFY_IS_TRUE(
        text.find(L"contoso-synth._midi2._udp.local") != std::wstring::npos,
        L"The device id is still written when an identity is supplied");

    VERIFY_IS_TRUE(
        text.find(L"CONTOSO-PID-12345") != std::wstring::npos,
        L"The identity is written even though a device id was supplied");
}


void MidiNetworkApiTests::TestConnectConfigJsonCarriesTheCustomEndpointName()
{    MidiNetworkClientMatchCriteria criteria;
    criteria.DirectHostNameOrIPAddress(L"127.0.0.1");
    criteria.DirectPort(5004);

    MidiNetworkClientConnectConfig config;
    config.ClientId(foundation::GuidHelper::CreateNewGuid());
    config.UmpEndpointName(L"Local Name");
    config.CustomEndpointName(L"Name In Windows");
    config.MatchCriteria(criteria);

    auto json = config.ConfigJson();

    VERIFY_IS_NOT_NULL(json);

    // The name has to reach the configuration file, or it would be forgotten on restart.
    auto text = json.Stringify();

    Log::Comment(String().Format(L"Connect config json: %s", text.c_str()));

    VERIFY_IS_TRUE(
        std::wstring{ text }.find(L"Name In Windows") != std::wstring::npos,
        L"The custom endpoint name is written into the configuration entry");
}

void MidiNetworkApiTests::TestHostCreationConfigRemoteClientPolicyRoundTrip()
{
    MidiNetworkHostCreationConfig config;

    // The default has to stay permissive, or existing configurations change behavior.
    VERIFY_ARE_EQUAL(MidiNetworkRemoteClientPolicy::AllowAny, config.RemoteClientPolicy());

    config.RemoteClientPolicy(MidiNetworkRemoteClientPolicy::RequireApproval);

    VERIFY_ARE_EQUAL(MidiNetworkRemoteClientPolicy::RequireApproval, config.RemoteClientPolicy());

    auto text = config.ConfigJson().Stringify();

    Log::Comment(String().Format(L"Host config json: %s", text.c_str()));

    VERIFY_IS_TRUE(
        std::wstring{ text }.find(L"requireApproval") != std::wstring::npos,
        L"The approval policy reaches the configuration entry");
}

void MidiNetworkApiTests::TestHostCreationConfigManualPortRoundTrip()
{
    MidiNetworkHostCreationConfig config;

    config.UseAutomaticPortAllocation(false);
    config.ManuallyAssignedPort(L"5008");

    VERIFY_IS_FALSE(config.UseAutomaticPortAllocation());
    VERIFY_ARE_EQUAL(winrt::hstring{ L"5008" }, config.ManuallyAssignedPort());

    auto text = config.ConfigJson().Stringify();

    VERIFY_IS_TRUE(
        std::wstring{ text }.find(L"5008") != std::wstring::npos,
        L"A manually assigned port reaches the configuration entry");
}

void MidiNetworkApiTests::TestHostCreationConfigAuthenticationTypeRoundTrip()
{
    MidiNetworkHostCreationConfig config;

    // Authentication is not implemented yet, and the service refuses a host configured for it.
    // The property still has to round-trip, because that refusal is what has to keep working.
    VERIFY_ARE_EQUAL(MidiNetworkAuthenticationType::NoAuthentication, config.AuthenticationType());

    config.AuthenticationType(MidiNetworkAuthenticationType::UserAuthentication);

    VERIFY_ARE_EQUAL(MidiNetworkAuthenticationType::UserAuthentication, config.AuthenticationType());
}

void MidiNetworkApiTests::TestTransportManagerDnsSdConstantsAreUsable()
{
    VERIFY_IS_FALSE(MidiNetworkTransportManager::MidiNetworkUdpDnsServiceType().empty());
    VERIFY_IS_FALSE(MidiNetworkTransportManager::MidiNetworkUdpDnsDomain().empty());
    VERIFY_IS_FALSE(MidiNetworkTransportManager::MidiNetworkUdpDnsSdQueryName().empty());

    Log::Comment(String().Format(
        L"service type '%s', domain '%s', query name '%s'",
        MidiNetworkTransportManager::MidiNetworkUdpDnsServiceType().c_str(),
        MidiNetworkTransportManager::MidiNetworkUdpDnsDomain().c_str(),
        MidiNetworkTransportManager::MidiNetworkUdpDnsSdQueryName().c_str()));

    // Spec section 4.4 and RFC 6763: the advertisement lives under _midi2._udp
    VERIFY_IS_TRUE(
        std::wstring{ MidiNetworkTransportManager::MidiNetworkUdpDnsServiceType() }.find(L"_udp") != std::wstring::npos,
        L"The DNS-SD service type names the UDP protocol");

    // This is passed straight to DnsServiceBrowse, so it has to be the full query name.
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"_midi2._udp.local" },
        MidiNetworkTransportManager::MidiNetworkUdpDnsSdQueryName());
}

void MidiNetworkApiTests::TestDuplicateServiceInstanceNameIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // The service instance name becomes the DNS-SD instance and the virtual parent device id,
    // so a second host cannot share it.
    auto sharedName = winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() };

    MidiNetworkHostCreationConfig firstConfig;
    MidiNetworkHostCreationConfig secondConfig;

    auto firstId = firstConfig.HostId();
    auto secondId = secondConfig.HostId();

    // two independently constructed configs must never collide
    VERIFY_ARE_NOT_EQUAL(firstId, secondId);

    auto cleanup = wil::scope_exit([&]
        {
            RemoveTestHost(firstId);
            RemoveTestHost(secondId);
        });

    firstConfig.Name(L"Duplicate Name Test A");
    firstConfig.ServiceInstanceName(sharedName);
    firstConfig.ProductInstanceId(L"DuplicateTestA");
    firstConfig.UseAutomaticPortAllocation(true);
    firstConfig.Advertise(false);

    auto firstResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(firstConfig).get();

    VERIFY_IS_NOT_NULL(firstResponse);
    VERIFY_IS_TRUE(firstResponse.Success());

    VerifyHostAppeared(firstId);

    secondConfig.Name(L"Duplicate Name Test B");
    secondConfig.ServiceInstanceName(sharedName);
    secondConfig.ProductInstanceId(L"DuplicateTestB");
    secondConfig.UseAutomaticPortAllocation(true);
    secondConfig.Advertise(false);

    auto secondResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(secondConfig).get();

    VERIFY_IS_NOT_NULL(secondResponse);
    VERIFY_IS_FALSE(secondResponse.Success());
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::ServiceInstanceNameInUse, secondResponse.ErrorCode());

    VERIFY_IS_TRUE(HostIsAbsent(secondId));

    Log::Comment(String().Format(L"Duplicate rejected: %s", secondResponse.ErrorMessage().c_str()));
}


// Two hosts on one port would mean two sockets fighting over the same inbound datagrams. The
// second bind is what actually fails, at start time, so the collision is caught up front.
void MidiNetworkApiTests::TestDuplicateManualPortIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto port = PickLikelyFreePort();

    VERIFY_IS_TRUE(port.has_value(), L"A free port could be found to test with");

    auto const sharedPort = winrt::hstring{ std::to_wstring(port.value()) };

    MidiNetworkHostCreationConfig firstConfig;
    MidiNetworkHostCreationConfig secondConfig;

    auto firstId = firstConfig.HostId();
    auto secondId = secondConfig.HostId();

    auto cleanup = wil::scope_exit([&]
        {
            RemoveTestHost(firstId);
            RemoveTestHost(secondId);
        });

    auto const firstSuffix = MakeUniqueSuffix();

    firstConfig.Name(L"Duplicate Port Test A");
    firstConfig.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + firstSuffix });
    firstConfig.ProductInstanceId(L"DuplicatePortA");
    firstConfig.UseAutomaticPortAllocation(false);
    firstConfig.ManuallyAssignedPort(sharedPort);
    firstConfig.Advertise(false);

    auto firstResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(firstConfig).get();

    VERIFY_IS_NOT_NULL(firstResponse);
    VERIFY_IS_TRUE(firstResponse.Success(), L"The first host claimed the port");

    VerifyHostAppeared(firstId);

    auto const secondSuffix = MakeUniqueSuffix();

    secondConfig.Name(L"Duplicate Port Test B");
    secondConfig.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + secondSuffix });
    secondConfig.ProductInstanceId(L"DuplicatePortB");
    secondConfig.UseAutomaticPortAllocation(false);
    secondConfig.ManuallyAssignedPort(sharedPort);
    secondConfig.Advertise(false);

    auto secondResponse = MidiNetworkTransportManager::CreateNetworkHostAsync(secondConfig).get();

    VERIFY_IS_NOT_NULL(secondResponse);
    VERIFY_IS_FALSE(secondResponse.Success(), L"A second host asking for the same port is rejected");
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::NetworkPortInUse, secondResponse.ErrorCode());

    VERIFY_IS_TRUE(HostIsAbsent(secondId));

    Log::Comment(String().Format(L"Duplicate port rejected: %s", secondResponse.ErrorMessage().c_str()));
}


// The automatic case is the easy one to miss: the first entry says "automatic", so comparing
// requested ports finds nothing, yet its socket is bound to a real number.
void MidiNetworkApiTests::TestManualPortMatchingAnAutomaticPortIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    auto automaticHostId = CreateTestHost(MakeUniqueSuffix());

    MidiNetworkHostCreationConfig manualConfig;

    auto manualHostId = manualConfig.HostId();

    auto cleanup = wil::scope_exit([&]
        {
            RemoveTestHost(automaticHostId);
            RemoveTestHost(manualHostId);
        });

    VerifyHostAppeared(automaticHostId);

    // Whatever the system handed the automatic host.
    winrt::hstring assignedPort{ };

    for (int attempt = 0; attempt < 50 && assignedPort.empty(); attempt++)
    {
        auto hosts = MidiNetworkTransportManager::GetConfiguredHosts();

        if (hosts != nullptr)
        {
            for (auto const& host : hosts)
            {
                if (host.HostId() == automaticHostId)
                {
                    assignedPort = host.ActualPort();
                    break;
                }
            }
        }

        if (assignedPort.empty())
        {
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
        }
    }

    VERIFY_IS_FALSE(assignedPort.empty(), L"The automatic host reported the port it was given");

    Log::Comment(String().Format(L"Automatic host was given port %s", assignedPort.c_str()));

    manualConfig.Name(L"Automatic Port Collision Test");
    manualConfig.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() });
    manualConfig.ProductInstanceId(L"AutoPortCollision");
    manualConfig.UseAutomaticPortAllocation(false);
    manualConfig.ManuallyAssignedPort(assignedPort);
    manualConfig.Advertise(false);

    auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(manualConfig).get();

    VERIFY_IS_NOT_NULL(response);
    VERIFY_IS_FALSE(response.Success(), L"A manual port duplicating an automatically assigned one is rejected");
    VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::NetworkPortInUse, response.ErrorCode());

    VERIFY_IS_TRUE(HostIsAbsent(manualHostId));
}


void MidiNetworkApiTests::TestOutOfRangeManualPortIsRejected()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // 65535 is the highest there is, and a port has to be a number at all.
    for (auto const& portText : { winrt::hstring{ L"65536" }, winrt::hstring{ L"not a port" } })
    {
        MidiNetworkHostCreationConfig config;

        auto hostId = config.HostId();

        auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

        config.Name(L"Out Of Range Port Test");
        config.ServiceInstanceName(winrt::hstring{ TestHostNamePrefix + MakeUniqueSuffix() });
        config.ProductInstanceId(L"OutOfRangePort");
        config.UseAutomaticPortAllocation(false);
        config.ManuallyAssignedPort(portText);
        config.Advertise(false);

        auto response = MidiNetworkTransportManager::CreateNetworkHostAsync(config).get();

        VERIFY_IS_NOT_NULL(response);

        VERIFY_IS_FALSE(
            response.Success(),
            String().Format(L"A port of '%s' is rejected", portText.c_str()));

        VERIFY_ARE_EQUAL(MidiNetworkHostCreationErrorCode::InvalidNetworkPort, response.ErrorCode());

        VERIFY_IS_TRUE(HostIsAbsent(hostId));
    }
}


// ============================================================================
// Generated host ids
// ============================================================================

void MidiNetworkApiTests::TestHostCreationConfigGeneratesUniqueIds()
{
    // No service needed. The id is generated in the API, so a caller can read it back
    // immediately and use it to remove the host later.
    const int count = 50;

    std::vector<winrt::guid> seen;

    for (int i = 0; i < count; i++)
    {
        MidiNetworkHostCreationConfig config;

        auto id = config.HostId();

        VERIFY_ARE_NOT_EQUAL(winrt::guid{}, id);

        for (auto const& existing : seen)
        {
            VERIFY_ARE_NOT_EQUAL(existing, id);
        }

        seen.push_back(id);
    }

    VERIFY_ARE_EQUAL((size_t)count, seen.size());
}

void MidiNetworkApiTests::TestGeneratedHostIdSurvivesRoundTripToService()
{
    SKIP_IF_NO_NETWORK_TRANSPORT();

    // The id the API generated must be the one the service stores and hands back, otherwise
    // the caller has no way to find the host it just created.
    auto hostId = CreateTestHost(MakeUniqueSuffix());

    VERIFY_ARE_NOT_EQUAL(winrt::guid{}, hostId);

    auto cleanup = wil::scope_exit([&] { RemoveTestHost(hostId); });

    VerifyHostAppeared(hostId);

    bool found{ false };

    for (auto const& host : MidiNetworkTransportManager::GetConfiguredHosts())
    {
        if (host.HostId() == hostId)
        {
            found = true;
            break;
        }
    }

    VERIFY_IS_TRUE(found);

    // and it is still the same id on a second read, so nothing is regenerating it
    bool foundAgain{ false };

    for (auto const& host : MidiNetworkTransportManager::GetConfiguredHosts())
    {
        if (host.HostId() == hostId)
        {
            foundAgain = true;
            break;
        }
    }

    VERIFY_IS_TRUE(foundAgain);
}


// ============================================================================
// Service instance name compliance
// ============================================================================

void MidiNetworkApiTests::TestEnsureCompliantServiceInstanceNameStripsPeriods()
{
    // A period would split this into two DNS labels, so it cannot survive. Periods are removed
    // rather than substituted, so nothing the caller did not type appears in the result.
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"contososynth1" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"contoso.synth.1"));

    // including the case where someone passes the fully qualified name by mistake
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"bomebox-8q6d2z-1_midi2_udplocal" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"bomebox-8q6d2z-1._midi2._udp.local"));
}

void MidiNetworkApiTests::TestEnsureCompliantServiceInstanceNameKeepsSpacesAndUnicode()
{
    // RFC 6763 treats the instance name as user-visible text, so these are all legal.
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"Pete's Studio Rig" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"Pete's Studio Rig"));

    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"Sala de M\u00fasica" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"Sala de M\u00fasica"));

    // leading and trailing whitespace is not meaningful and gets trimmed
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"Studio A" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"   Studio A   "));
}

void MidiNetworkApiTests::TestEnsureCompliantServiceInstanceNameStripsControlCharacters()
{
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"Studio A" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"Stu\r\ndio\t A"));

    // an input made entirely of illegal characters leaves nothing behind, and the caller
    // is expected to treat an empty result as "pick something else"
    VERIFY_ARE_EQUAL(
        winrt::hstring{ L"" },
        MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(L"..."));
}

void MidiNetworkApiTests::TestEnsureCompliantServiceInstanceNameLimitsToLabelByteCount()
{
    const size_t maxBytes = 63;

    auto longAscii = MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(
        winrt::hstring{ RepeatedString(L'A', 200) });

    VERIFY_ARE_EQUAL(maxBytes, (size_t)longAscii.size());

    // The limit is bytes once encoded, not characters, so multi-byte text has to come back
    // shorter in characters than the ASCII case rather than the same length.
    std::wstring multiByte;
    for (int i = 0; i < 200; i++)
    {
        multiByte += L"\u00e9";        // two bytes each in UTF-8
    }

    auto longUnicode = MidiNetworkHostCreationConfig::EnsureCompliantServiceInstanceName(winrt::hstring{ multiByte });

    VERIFY_IS_LESS_THAN((size_t)longUnicode.size(), maxBytes);
    VERIFY_IS_GREATER_THAN((size_t)longUnicode.size(), (size_t)0);

    // and it must never split a character in half
    for (auto const ch : std::wstring{ longUnicode.c_str() })
    {
        VERIFY_ARE_EQUAL(L'\u00e9', ch);
    }
}

void MidiNetworkApiTests::TestDefaultConfigServiceInstanceNameHasNoSuffix()
{
    auto config = MidiNetworkHostCreationConfig::CreateDefault();

    VERIFY_IS_NOT_NULL(config);

    auto name = config.ServiceInstanceName();

    Log::Comment(String().Format(L"Default service instance name: '%s'", name.c_str()));

    VERIFY_IS_FALSE(name.empty());

    // The transport appends "." + the service type when it builds the PTR record, so storing
    // the suffix here would produce a doubled name on the wire.
    std::wstring nameStr{ name.c_str() };

    VERIFY_IS_TRUE(nameStr.find(L'.') == std::wstring::npos);

    VERIFY_ARE_NOT_EQUAL(winrt::guid{}, config.HostId());
}
