// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================


import "MidiSetup.idl";

namespace Microsoft.Devices.Midi2.Setups
{
    [default_interface]
    runtimeclass MidiSetupsManager
    {
        MidiSetupsManager();

        MidiSetup Current{ get; };
        void SwitchTo(MidiSetup setup);

        void AddNew(MidiSetup setup);
        void Save(MidiSetup setup);

        void Delete(String setupId);
    }
}
