#pragma once
#include "Microsoft.Windows.Midi.Messages.Data.MidiSystemExclusive7BitMessage.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Windows::Midi::Messages::Data::implementation
{
    struct MidiSystemExclusive7BitMessage : MidiSystemExclusive7BitMessageT<MidiSystemExclusive7BitMessage>
    {
        MidiSystemExclusive7BitMessage() = default;

        static winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessage FromUmp(winrt::Microsoft::Windows::Midi::Messages::Ump64 const& ump);
        static winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessage FromWords(uint32_t word0, uint32_t word1);
        static winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessage FromFields(uint8_t group, winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessageStatus const& status, uint8_t byteCount, array_view<uint8_t const> bytes);
        uint8_t Group();
        void Group(uint8_t value);
        winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessageStatus Status();
        void Status(winrt::Microsoft::Windows::Midi::Messages::Data::MidiSystemExclusive7BitMessageStatus const& value);
        uint8_t PacketByteCount();
        void PacketByteCount(uint8_t value);
        com_array<uint8_t> Bytes();
        void Bytes(array_view<uint8_t const> value);
    };
}
namespace winrt::Microsoft::Windows::Midi::Messages::Data::factory_implementation
{
    struct MidiSystemExclusive7BitMessage : MidiSystemExclusive7BitMessageT<MidiSystemExclusive7BitMessage, implementation::MidiSystemExclusive7BitMessage>
    {
    };
}
