import "Ump64.idl";

namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{
    enum Midi2NoteOnOffAttributeType
    {
        NoAttributeData = 0x00,
        ManufacturerSpecific = 0x01,
        ProfileSpecific = 0x02,
        PitchSevenDotNine = 0x03
    };


    [default_interface]
    unsealed runtimeclass Midi2ChannelVoiceMessage
    {
        UInt8 Group;
        UInt8 Opcode;
        UInt8 Channel;

        [default_overload]
        static Microsoft.Windows.Midi.Messages.Ump64 ToUmp();
        static void ToUmp(out Microsoft.Windows.Midi.Messages.Ump64 ump);
    };


}