import "Ump64.idl";
import "Midi2ChannelVoiceMessage.idl";


namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{


    [default_interface]
    runtimeclass Midi2NoteOffMessage : Midi2ChannelVoiceMessage
    {
        UInt8 NoteNumber;
        Midi2NoteOnOffAttributeType AttributeType;
        UInt16 Velocity;
        UInt16 AttributeData;

        Midi2NoteOffMessage();

        static Midi2NoteOffMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump64 ump);
        static Midi2NoteOffMessage FromWords(UInt32 word0, UInt32 word1);
        static Midi2NoteOffMessage FromFields(UInt8 group, UInt8 channel, Midi2NoteOnOffAttributeType attributeType, UInt16 velocity, UInt16 attributeData);
    };



}