namespace Microsoft.Windows.Midi.Helpers
{

    [default_interface]
    runtimeclass MidiSystemExclusiveHelper
    {

        static UInt16 Convert7BitManufacturerIdTo16Bit(UInt8 byte1);
        static UInt16 Convert21BitManufacturerIdTo16Bit(UInt8 byte1, UInt8 byte2, UInt8 byte3);


        // TODO: Class to take a large number of bytes in some sort of buffer or stream and send them
        // may also want to a file object and send it with some options

        [default_overload]
        static Boolean SendSystemExclusive7Bit(UInt8 todo);
        static Boolean SendSystemExclusive7BitFile(UInt8 todo);

        [default_overload]
        static Boolean SendSystemExclusive8Bit(UInt8 todo);
        static Boolean SendSystemExclusive8BitFile(UInt8 todo);

    };
}

