
import "Ump64.idl";
import "MidiSystemExclusive7BitMessageStatus.idl";


namespace Microsoft.Windows.Midi.Messages.Data
{

    [default_interface]
    runtimeclass MidiSystemExclusive7BitMessage
    {
        UInt8 Group;
        MidiSystemExclusive7BitMessageStatus Status;
        UInt8 PacketByteCount;
        UInt8[] Bytes;        // 6 bytes. TBD if we want to use an array here, or just have 6 fields  

        MidiSystemExclusive7BitMessage();

        static MidiSystemExclusive7BitMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump64 ump);
        static MidiSystemExclusive7BitMessage FromWords(UInt32 word0, UInt32 word1);
        static MidiSystemExclusive7BitMessage FromFields(UInt8 group, MidiSystemExclusive7BitMessageStatus status, UInt8 byteCount, UInt8[] bytes);
    };

}