namespace Microsoft.Windows.Midi.Helpers
{

    [default_interface]
    runtimeclass MidiMixedDataSetHelper
    {
        // TODO: This class could take a large number of bytes
        // or a stream (like a file) and some metadata, and from
        // that, build and send the MixedDataSet chunks, headers and payloads.

    };
}
