import "UmpType.idl";

namespace Microsoft.Windows.Midi.Messages
{

    [default_interface]
    unsealed runtimeclass Ump
    {
        Ump();

        UInt32 Word0; // special case. A Uwp is always at least 1 word, and we need this for parsing

        UmpType GetPacketType();

    };


}
