import "Ump.idl";

namespace Microsoft.Windows.Midi.Messages
{

    [default_interface]
    runtimeclass Ump96 : Ump
    {
        UInt32 Word1;
        UInt32 Word2;

        Ump96();

        static Ump96 FromWords(UInt32 word0, UInt32 word1, UInt32 word2);
    };


}