//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc


// Application banner

#define IDS_BANNER_TOOL_INFO										50000
#define IDS_BANNER_DESCRIPTION										50001

// Registry scan status

#define IDS_STATUS_CHECKING_KEY										50100
#define IDS_STATUS_NO_VALUES_TO_DELETE								50101

// Entries which are left alone

#define IDS_FOUND_CORRECT_MIDI_VALUE								50200
#define IDS_FOUND_CORRECT_MIDI1_VALUE								50201
#define IDS_FOUND_MIDI_MAPPER										50202
#define IDS_FOUND_KORG_BLE_DRIVER									50203
#define IDS_FOUND_COOLSOFT_MIDI_MAPPER								50204
#define IDS_FOUND_COOLSOFT_VIRTUAL_MIDI_SYNTH						50205
#define IDS_FOUND_OTHER_VALUE										50206

// Entries which need fixing

#define IDS_FOUND_INCORRECT_VALUE									50300
#define IDS_FOUND_INCORRECT_VALUE_TYPE								50301

// Proposed changes and confirmation

#define IDS_PROMPT_CHANGES_REQUIRED									50400
#define IDS_PROMPT_CLOSE_OTHER_APPS									50401
#define IDS_LABEL_PROPOSED_CHANGES_64_BIT							50402
#define IDS_LABEL_PROPOSED_CHANGES_32_BIT							50403
#define IDS_PROPOSED_DELETE_VALUE									50404
#define IDS_PROPOSED_UPDATE_MIDI_VALUE								50405
#define IDS_PROPOSED_UPDATE_MIDI1_VALUE								50406
#define IDS_PROPOSED_UPDATE_TRANSFER_COMPLETE						50407
#define IDS_PROMPT_YES_NO_KEYS										50408

// Applying changes

#define IDS_STATUS_MAKING_CHANGES_64_BIT							50500
#define IDS_STATUS_MAKING_CHANGES_32_BIT							50501
#define IDS_STATUS_DELETED_VALUE									50502
#define IDS_STATUS_UPDATED_MIDI_VALUE								50503
#define IDS_STATUS_UPDATED_MIDI1_VALUE								50504
#define IDS_STATUS_CHANGES_MADE_REBOOT								50505
#define IDS_STATUS_NO_CHANGES_MADE									50506
#define IDS_STATUS_NO_INCORRECT_VALUES								50507

// Errors

#define IDS_ERROR_UNABLE_TO_INITIALIZE_COM							50600
#define IDS_ERROR_NOT_ADMINISTRATOR									50601
#define IDS_ERROR_DELETING_VALUE									50602
#define IDS_ERROR_UNABLE_TO_WRITE_MIDI_VALUE						50603
#define IDS_ERROR_UNABLE_TO_WRITE_MIDI1_VALUE						50604


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
