// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";


import "MidiBasicLoopbackEndpointDefinition.idl";


namespace Windows.Devices.Midi2.Endpoints.BasicLoopback
{
    [contract(MidiEndpointsBasicLoopbackApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Endpoints.BasicLoopback.IMidiBasicLoopbackRemovalConfig", UUID_IMidiBasicLoopbackRemovalConfig)]
    runtimeclass MidiBasicLoopbackRemovalConfig : Windows.Devices.Midi2.ServiceConfig.IMidiServiceTransportPluginConfig
    {
        MidiBasicLoopbackRemovalConfig(Guid associationId);

        Guid AssociationId;
    }
}