// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App SDK and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

// error codes shared with service
#include "..\..\..\Transport\BasicLoopbackMidiTransport\basic_loopback_transport_error_codes.h"

namespace Windows.Devices.Midi2.Endpoints.BasicLoopback
{
    [contract(MidiEndpointsBasicLoopbackApiContract, 1)]
    enum MidiBasicLoopbackEndpointCreationResultErrorCode
    {
        UnknownOrUnspecified =      BASIC_LOOPBACK_ERROR_CODE_UNKNOWN_ERROR,
        UnrecognizedCommand =       BASIC_LOOPBACK_ERROR_CODE_UNRECOGNIZED_COMMAND,

        InvalidJson =               BASIC_LOOPBACK_ERROR_CODE_INVALID_JSON,

        EndpointCreationFailed =    BASIC_LOOPBACK_ERROR_CODE_ENDPOINT_CREATION_FAILED,

        DuplicateUniqueId =         BASIC_LOOPBACK_ERROR_CODE_DUPLICATE_UNIQUE_ID,
        MissingUniqueId =           BASIC_LOOPBACK_ERROR_CODE_MISSING_UNIQUE_ID,
        MissingEndpointName =       BASIC_LOOPBACK_ERROR_CODE_MISSING_ENDPOINT_NAME,
        MissingAssociationId =      BASIC_LOOPBACK_ERROR_CODE_MISSING_ASSOCIATION_ID,
        EndpointNotFound =          BASIC_LOOPBACK_ERROR_CODE_ENDPOINT_NOT_FOUND,

        // checked by SDK not service
        NameInUse =                 0x00002010,
        ClientApiException =        0x00002011,
    };
}