#include "pch.h"
#include "Microsoft.Windows.Midi.Messages.ChannelVoice.Midi2RelativeAssignableControllerMessage.h"
#include "Microsoft.Windows.Midi.Messages.ChannelVoice.Midi2RelativeAssignableControllerMessage.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Windows::Midi::Messages::ChannelVoice::implementation
{
    winrt::Microsoft::Windows::Midi::Messages::ChannelVoice::Midi2RelativeAssignableControllerMessage Midi2RelativeAssignableControllerMessage::FromUmp(winrt::Microsoft::Windows::Midi::Messages::Ump64 const& ump)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Windows::Midi::Messages::ChannelVoice::Midi2RelativeAssignableControllerMessage Midi2RelativeAssignableControllerMessage::FromWords(uint32_t word0, uint32_t word1)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Windows::Midi::Messages::ChannelVoice::Midi2RelativeAssignableControllerMessage Midi2RelativeAssignableControllerMessage::FromFields(uint8_t group, uint8_t channel, uint8_t bank, uint8_t index, uint32_t data)
    {
        throw hresult_not_implemented();
    }
    uint8_t Midi2RelativeAssignableControllerMessage::Bank()
    {
        throw hresult_not_implemented();
    }
    void Midi2RelativeAssignableControllerMessage::Bank(uint8_t value)
    {
        throw hresult_not_implemented();
    }
    uint8_t Midi2RelativeAssignableControllerMessage::Index()
    {
        throw hresult_not_implemented();
    }
    void Midi2RelativeAssignableControllerMessage::Index(uint8_t value)
    {
        throw hresult_not_implemented();
    }
    uint32_t Midi2RelativeAssignableControllerMessage::Data()
    {
        throw hresult_not_implemented();
    }
    void Midi2RelativeAssignableControllerMessage::Data(uint32_t value)
    {
        throw hresult_not_implemented();
    }
}
