#pragma once
#include "Microsoft.Windows.Midi.Helpers.MidiSystemExclusiveHelper.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Windows::Midi::Helpers::implementation
{
    struct MidiSystemExclusiveHelper : MidiSystemExclusiveHelperT<MidiSystemExclusiveHelper>
    {
        MidiSystemExclusiveHelper() = default;

        static uint16_t Convert7BitManufacturerIdTo16Bit(uint8_t byte1);
        static uint16_t Convert21BitManufacturerIdTo16Bit(uint8_t byte1, uint8_t byte2, uint8_t byte3);
        static bool SendSystemExclusive7Bit(uint8_t todo);
        static bool SendSystemExclusive7BitFile(uint8_t todo);
        static bool SendSystemExclusive8Bit(uint8_t todo);
        static bool SendSystemExclusive8BitFile(uint8_t todo);
    };
}
namespace winrt::Microsoft::Windows::Midi::Helpers::factory_implementation
{
    struct MidiSystemExclusiveHelper : MidiSystemExclusiveHelperT<MidiSystemExclusiveHelper, implementation::MidiSystemExclusiveHelper>
    {
    };
}
