import "MidiSessionCreateOptions.idl";
import "MidiDevice.idl";
import "MidiEndpoint.idl";
import "MidiMessageReceivedEventArgs.idl";
import "MidiDeviceInformation.idl";
import "MidiEndpointInformation.idl";
import "Ump.idl";


namespace Microsoft.Windows.Midi
{

    [default_interface]
    runtimeclass MidiSession
    {
        Guid Id {get;};
        String Name {get;};
        Windows.Foundation.DateTime CreateTime{get;};

        // TODO: List/hash of open endpoints/devices in this session



        static MidiSession Create(String name, String appName, MidiSessionCreateOptions options);
        static MidiSession Create(String name, String appName);

        void Close();

        // device and endpoint functions

        // when you open an endpoint from the session, its incoming messages
        // get received to the session
        // if you open the endpoint from the endpoint itself, the messages
        // get received at that endpoint object.
        // this supports both a flat model and the WinRT MIDI style model
        [default_overload]
        Microsoft.Windows.Midi.Devices.MidiEndpoint OpenEndpoint(Microsoft.Windows.Midi.Enumeration.MidiEndpointInformation information);
        Microsoft.Windows.Midi.Devices.MidiEndpoint OpenEndpoint(Guid deviceId, Guid endpointId);

        event Windows.Foundation.EventHandler<Microsoft.Windows.Midi.MidiMessageReceivedEventArgs> MessageReceived;


        // message sending
        [default_overload]
        void SendUmp(Microsoft.Windows.Midi.Enumeration.MidiEndpointInformation information, Microsoft.Windows.Midi.Messages.Ump message);
        void SendUmp(Guid deviceId, Guid endpointId, Microsoft.Windows.Midi.Messages.Ump message);

        // TODO: Send a buffer/array of UMPs


        [default_overload]
        void SendUmpWithJRTimestamp(Microsoft.Windows.Midi.Enumeration.MidiEndpointInformation information, MidiJitterReductionTimestampMessage timestamp, Microsoft.Windows.Midi.Messages.Ump message);
        void SendUmpWithJRTimestamp(Guid deviceId, Guid endpointId, MidiJitterReductionTimestampMessage timestamp, Microsoft.Windows.Midi.Messages.Ump message);

        // TODO: Send a buffer/array of UMPs












        // makes a server call, so prefer not to have in a property
        Boolean UpdateName(String newName);


    };
}