import "Ump128.idl";
import "MidiSystemExclusive8BitMessageStatus.idl";

namespace Microsoft.Windows.Midi.Messages.Data
{

    [default_interface]
    runtimeclass Midi2SystemExclusive8BitMessage
    {
        UInt8 Group;
        MidiSystemExclusive8BitMessageStatus Status;
        UInt8 PacketByteCountIncludingStreamId;
        UInt8 StreamId;
        UInt8[] Bytes;        // 13 bytes. TBD if we want to use an array here, or just have 13 fields  

        // TODO constructors and factory methods
    };

}