import "Ump64.idl";
import "Midi2ChannelVoiceMessage.idl";


namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{
    [default_interface]
    runtimeclass Midi2PitchBendMessage : Midi2ChannelVoiceMessage
    {
        UInt32 Data;

        Midi2PitchBendMessage();

        static Midi2PitchBendMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump64 ump);
        static Midi2PitchBendMessage FromWords(UInt32 word0, UInt32 word1);
        static Midi2PitchBendMessage FromFields(UInt8 group, UInt8 channel, UInt32 data);

    };

}