import "Ump64.idl";
import "Midi2ChannelVoiceMessage.idl";


namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{

    [default_interface]
    runtimeclass Midi2RegisteredControllerMessage : Midi2ChannelVoiceMessage
    {
        UInt8 Bank;     // RPN MSB
        UInt8 Index;    // RPN LSB
        UInt32 Data;

        Midi2RegisteredControllerMessage();

        static Midi2RegisteredControllerMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump64 ump);
        static Midi2RegisteredControllerMessage FromWords(UInt32 word0, UInt32 word1);
        static Midi2RegisteredControllerMessage FromFields(UInt8 group, UInt8 channel, UInt8 bank, UInt8 index, UInt32 data);
    };


}