import "Ump64.idl";
import "Midi2ChannelVoiceMessage.idl";


namespace Microsoft.Windows.Midi.Messages.ChannelVoice
{

    [default_interface]
    runtimeclass Midi2AssignablePerNoteControllerMessage : Midi2ChannelVoiceMessage
    {
        UInt8 NoteNumber;
        UInt8 Index;
        UInt32 Data;

        Midi2AssignablePerNoteControllerMessage();

        static Midi2AssignablePerNoteControllerMessage FromUmp(Microsoft.Windows.Midi.Messages.Ump64 ump);
        static Midi2AssignablePerNoteControllerMessage FromWords(UInt32 word0, UInt32 word1);
        static Midi2AssignablePerNoteControllerMessage FromFields(UInt8 group, UInt8 channel, UInt8 noteNumber, UInt8 index, UInt32 data);
    };


}