namespace Microsoft.Windows.Midi.Enumeration
{

    [default_interface]
    runtimeclass MidiTransportInformation
    {
        Guid Id {get;};

        String Name{get;};
        String Description{get;};

        String PluginName {get;};
        String IconFileName{get;};

    };
}

