
namespace Microsoft.Windows.Midi.Messages.Data
{
    enum MidiSystemExclusive7BitMessageStatus
    {
        CompleteInOneUmp = 0x0,
        SystemExclusiveStartUmp = 0x1,
        SystemExclusiveContinueUmp = 0x2,
        SystemExclusiveEndUmp = 0x3
    };


}