import "Ump128.idl";

namespace Microsoft.Windows.Midi.Messages.Data
{

    [default_interface]
    runtimeclass MidiMixedDataSetPayloadMessage
    {
        UInt8 Group;
        UInt8 MdsId;
        UInt8[] Bytes;        // 14 bytes. TBD if we want to use an array here, or something else  

        // TODO constructors and factory methods
    };



}