// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services WinRT API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "..\shared\midi_sdk_idl_defs.h"
import "MidiApiContracts.idl";

import "MidiLoopbackEndpointEntry.idl";

namespace Windows.Devices.Midi2.Endpoints.Loopback
{
    [contract(MidiEndpointsLoopbackApiContract, 1)]
    [interface_name("Windows.Devices.Midi2.Endpoints.Loopback.IMidiLoopbackEntry", UUID_IMidiLoopbackEntry)]
    runtimeclass MidiLoopbackEntry
    {
        Guid AssociationId{ get; };

        MidiLoopbackEndpointEntry EndpointA{ get; };
        MidiLoopbackEndpointEntry EndpointB{ get; };

        Boolean IsMuted{ get; };
    };
}