// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

namespace Microsoft.Devices.Midi2
{
    MIDI_API_CONTRACT_v1
    [MIDI_INTERFACE_UUID("65736736-35f3-421c-a683-3a034ad0dcc2",1.0)]
    interface IMidiEndpointConnectionSettings
    {
        String SettingsJson { get; };
    }
}