// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiPacketTypeEnum.idl";
import "MidiMessageTypeEnum.idl";

namespace Microsoft.Devices.Midi2
{
    [uuid("2eb5df8a-d751-4997-bf96-ba9a531fd5ff"), version(1.0)]
    interface IMidiUniversalPacket
    {
        UInt64 Timestamp;

        MidiMessageType MessageType;
        MidiPacketType PacketType{ get; };

        UInt32 PeekFirstWord();


        IVector<UInt32> GetAllWords();
        UInt8 AppendAllMessageWordsToList(IVector<UInt32> targetList);

        UInt8 FillBuffer(UInt32 byteOffset, Windows.Foundation.IMemoryBuffer buffer);
    };
}