// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Devices.Midi2
{
    [flags]
    enum MidiEndpointDeviceInformationFilters
    {
        IncludeClientUmpNative =            0x00000001,
        IncludeClientByteStreamNative =     0x00000002,

        IncludeVirtualDeviceResponder =     0x00000100,

        IncludeDiagnosticLoopback =         0x00010000,
        IncludeDiagnosticPing =             0x00020000,


        AllTypicalEndpoints = IncludeClientUmpNative | IncludeClientByteStreamNative,
    };
}