// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

namespace MIDI_MIDL_NAMESPACE
{
    MIDI_API_CONTRACT_v1

    struct MidiDeclaredDeviceIdentity
    {
        // can't declare fixed-size arrays in MIDL 3.0
    
        UInt8 SystemExclusiveIdLsb;
        UInt8 SystemExclusiveIdSecondMsb;
        UInt8 SystemExclusiveIdMsb;

        UInt8 DeviceFamilyLsb;
        UInt8 DeviceFamilyMsb;

        UInt8 DeviceFamilyModelNumberLsb;
        UInt8 DeviceFamilyModelNumberMsb;

        UInt8 SoftwareRevisionLevelLsb;
        UInt8 SoftwareRevisionLevelSecondLsb;
        UInt8 SoftwareRevisionLevelSecondMsb;
        UInt8 SoftwareRevisionLevelMsb;
};
}