// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

import "MidiGroupTerminalBlockDirectionEnum.idl";
import "MidiGroupTerminalBlockProtocolEnum.idl";
import "MidiGroup.idl";

import "MidiFunctionBlock.idl";

namespace Microsoft.Devices.Midi2
{
    MIDI_API_CONTRACT_v1
    [default_interface]
    runtimeclass MidiGroupTerminalBlock
    {
        UInt8 Number{ get; };

        String Name{ get; };

        MidiGroupTerminalBlockDirection Direction { get; };
        MidiGroupTerminalBlockProtocol Protocol { get; };

        UInt8 FirstGroupIndex{ get; };
        UInt8 GroupCount{ get; };

        Boolean IncludesGroup(MidiGroup group);

        UInt16 MaxDeviceInputBandwidthIn4KBitsPerSecondUnits{ get; };
        UInt16 MaxDeviceOutputBandwidthIn4KBitsPerSecondUnits{ get; };

        UInt32 CalculatedMaxDeviceInputBandwidthBitsPerSecond{ get; };
        UInt32 CalculatedMaxDeviceOutputBandwidthBitsPerSecond{ get; };

        MidiFunctionBlock AsEquivalentFunctionBlock();
    }
}