// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "MidiEndpointConnection.idl";
import "IMidiEndpointConnectionSettings.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiSession : Windows.Foundation.IClosable
    {
        Guid SessionId { get; };
        String Name{ get; };

        static MidiSession Create(String sessionName);

        Boolean IsOpen { get; };

        IMapView<Guid, MidiEndpointConnection> Connections{ get; };

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId
        );

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId,
            Boolean autoReconnect
        );

        MidiEndpointConnection CreateEndpointConnection(
            String endpointDeviceId,
            Boolean autoReconnect,
            IMidiEndpointConnectionSettings settings
        );

        void DisconnectEndpointConnection(Guid endpointConnectionId);

        Boolean UpdateName(String newName);
    }
}