// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Devices.Midi2
{
    enum MidiFunctionBlockRepresentsMidi10Connection
    {
        Not10 = 0x0,
        YesBandwidthUnrestricted = 0x1,
        YesBandwidthRestricted = 0x2,
        Reserved = 0x3
    };
}