// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

import "IMidiUniversalPacket.idl";

namespace Microsoft.Windows.Devices.Midi2
{
    [default_interface]
    unsealed runtimeclass MidiMessage64 : IMidiUniversalPacket,
                                          Windows.Foundation.IStringable
    {
        MidiMessage64();
        MidiMessage64(UInt64 timestamp, UInt32 word0, UInt32 word1);
        MidiMessage64(UInt64 timestamp, UInt32[] words);

        UInt32 Word0;
        UInt32 Word1;
    };
}
