// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================

namespace Microsoft.Windows.Devices.Midi2
{
    [default_interface]
    runtimeclass MidiChannel
    {
        //MidiChannel();
        MidiChannel(UInt8 index);

        static String ShortLabel{ get; };
        static String LongLabel{ get; };

        UInt8 Index;
        UInt8 DisplayValue{ get; };

        static Boolean IsValidIndex(UInt8 index);
    }
}