// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

namespace Microsoft.Devices.Midi2
{
    MIDI_API_CONTRACT_v1
    enum Midi1ChannelVoiceMessageStatus
    {
        NoteOff = 0x8,
        NoteOn = 0x9,
        PolyPressure = 0xA,
        ControlChange = 0xB,
        ProgramChange = 0xC,
        ChannelPressure = 0xD,
        PitchBend = 0xE,
    };
}