// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://github.com/microsoft/MIDI/
// ============================================================================

#include "namespace_defines.h"
#include "midl_defines.h"

MIDI_IDL_IMPORT

namespace Microsoft.Devices.Midi2
{
    MIDI_API_CONTRACT_v1
    enum MidiSystemExclusive8Status
    {
        CompleteMessageInSingleMessagePacket =  0x0,
        StartMessagePacket =                    0x1,
        ContinueMessagePacket =                 0x2,
        EndMessagePacket =                      0x3,
    };
}