// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License
// ============================================================================
// This is part of the Windows MIDI Services App API and should be used
// in your Windows application via an official binary distribution.
// Further information: https://aka.ms/midi
// ============================================================================


import "oaidl.idl";
import "ocidl.idl";
import "unknwn.idl";

import "WindowsMidiServices.idl";


[
    uuid(51F2C928-D846-45E9-BFA8-058BC804FF3E),
    version(1.0),
]
library Midi2VirtualPatchBayTransportLib
{
    importlib("stdole2.tlb");

    [uuid(B7C8E2D2-EE3B-4044-B9CF-6F29528AB46D), version(1.0)]
    coclass Midi2VirtualPatchBayTransport
    {
        [default] interface IMidiTransport;
    }
};

