name: Build service and plugins

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v3
    - name: Build Service x86
      run: msbuild /src/api/midi2.sln /t:Build /p:Configuration=Release /p:Platform=x86
    - name: Build Service x64
      run: msbuild /src/api/midi2.sln /t:Build /p:Configuration=Release /p:Platform=x64
    - name: Build Service Arm64EC
      run: msbuild /src/api/midi2.sln /t:Build /p:Configuration=Release /p:Platform=Arm64EC
