name: Build service, plugins, and App SDK

on:
  push:
    branches: [ "main" ]
    #paths:
    #- 'src\api\**'
  #pull_request:
   # branches: [ "main" ]
    #paths:
    #- 'src\api\**'

env:
  MIDI2_SOLUTION: '${{ github.workspace }}\src\api\Midi2.sln'
  SDK_SOLUTION: '${{ github.workspace }}\src\api\Midi2-AppSDK.sln'
  #SOLUTION_DIR: '${{ github.workspace }}\src\api'
  SOLUTION_DIR: 'd:/a/MIDI/MIDI/src/api'
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        service-build-platform: [x86, x64, Arm64EC]
    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        submodules: true

    - name: Checkout vcpkg
      run: git submodule update --init --recursive
        
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup vcpkg - KSA Transport
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        runVcpkgInstall: true
        runVcpkgFormatString: '[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.SOLUTION_DIR]/Transport/KSAggregateTransport/`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        vcpkgJsonGlob: '${{ env.SOLUTION_DIR }}/Transport/KSAggregateTransport/vcpkg.json'
        vcpkgConfigurationJsonGlob: '${{ env.SOLUTION_DIR }}/Transport/KSAggregateTransport/vcpkg-configuration.json'

    - name: Setup vcpkg - ByteStreamToUMP Transform
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        runVcpkgInstall: true
        runVcpkgFormatString: '[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.SOLUTION_DIR]/Transform/ByteStreamToUMP/`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        vcpkgJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/ByteStreamToUMP/vcpkg.json'
        vcpkgConfigurationJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/ByteStreamToUMP/vcpkg-configuration.json'

    - name: Setup vcpkg - UmpProtocolDownscaler Transform
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        runVcpkgInstall: true
        runVcpkgFormatString: '[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.SOLUTION_DIR]/Transform/UmpProtocolDownscaler/`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        vcpkgJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/UmpProtocolDownscaler/vcpkg.json'
        vcpkgConfigurationJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/UmpProtocolDownscaler/vcpkg-configuration.json'

    - name: Setup vcpkg - UMPToByteStream Transform
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        runVcpkgInstall: true
        runVcpkgFormatString: '[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.SOLUTION_DIR]/Transform/UMPToByteStream/`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]'
        vcpkgJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/UMPToByteStream/vcpkg.json'
        vcpkgConfigurationJsonGlob: '${{ env.SOLUTION_DIR }}/Transform/UMPToByteStream/vcpkg-configuration.json'

     
    - name: Setup NuGet
      uses: NuGet/setup-nuget@12c57947e9458a5b976961b08ea0706a17dd71ae # v3.0.0
      
    - name: Restore Service NuGet packages for Midi2 Solution
      run: nuget restore ${{ env.MIDI2_SOLUTION }}

    - name: Build Service
      run: msbuild ${{ env.MIDI2_SOLUTION }} /t:Build /p:Configuration=Release /p:Platform=${{ matrix.service-build-platform }}
