
namespace Windows.Devices.Midi
{
    // for processing a single message. We may need to provide
    // an interface which supports processing multiple messages
    // or a stream, or supports transforming the number of
    // messages so that it is more or less than what was passed
    // in. Those may require just passing in a stream reference
    // instead, which has some threading implications

    interface IMidiPlugin
    {
        String Name{ get; };            // Name of this plugin
        String Provider{ get; };        // Provider (company, individual, etc.) of the plugin
        String Version{ get; };         // Version string

        String IconFileName{ get; };            // File name (not full path) of icon for this plugin
    };
}