import "MidiMessage.idl";
import "Midi1ChannelVoiceMessage.idl";

namespace Windows.Devices.Midi
{
    runtimeclass Midi1PitchBendMessage : Midi1ChannelVoiceMessage
    {
        UInt8 DataLsb{ get; };
        UInt8 DataMsb{ get; };

        // does the bit shifting for you
        UInt16 CombinedBendData{ get; };
    };
}

