import "MidiMessage.idl";
import "Midi1ChannelVoiceMessage.idl";

namespace Windows.Devices.Midi
{
    runtimeclass Midi1ControlChangeMessage : Midi1ChannelVoiceMessage
    {
        UInt8 Index{ get; };
        UInt8 Data{ get; };
    };
}



