import "MidiMessage.idl";
import "Midi2ChannelVoiceMessage.idl";

namespace Windows.Devices.Midi
{
    runtimeclass Midi2PolyPressureMessage : Midi2ChannelVoiceMessage
    {
        UInt8 NoteNumber{ get; };
        UInt32 Data{ get; };
    };
}

