
namespace Windows.Devices.Midi
{
	// This should be named MIdiMessageReceivedEventArgs but that already exists in 
	// Windows.Devices.Midi in the Windows SDK
	[default_interface]
	runtimeclass Midi2MessageReceivedEventArgs
	{
		String SourceEndpointId {get; };

		//Ump Packet{ get; };
	};
}