import "MidiMessage.idl";
import "Midi2ChannelVoiceMessage.idl";

namespace Windows.Devices.Midi
{
    runtimeclass Midi2ProgramChangeMessage : Midi2ChannelVoiceMessage
    {
        Boolean BankValid{ get; };

        UInt8 Program{ get; };

        UInt8 BankMsb{ get; };
        UInt8 BankLsb{ get; };

        // does the bit shifting for you
        UInt16 CombinedBank{ get; };
    };

}

