import "MidiSessionLogLevel.idl";

namespace Windows.Devices.Midi
{

    [default_interface]
    runtimeclass MidiSessionCreateSettings
    {
        MidiSessionLogLevel LogLevel{ get; set; };
    };

}
