import "MidiMessage.idl";
import "Midi1ChannelVoiceMessage.idl";

namespace Windows.Devices.Midi
{
	runtimeclass Midi1ProgramChangeMessage : Midi1ChannelVoiceMessage
	{
		UInt8 Program{ get; };
	};
}



