import "MidiMessage.idl";
import "Midi2UtilityMessage.idl";

namespace Windows.Devices.Midi
{
	runtimeclass Midi2JitterReductionTimestampMessage : Midi2UtilityMessage
	{
		UInt16 SenderClockTimestamp { get; };
	};

}


