namespace Windows.Devices.Midi
{
    struct Ump32
    {
        UInt32 Word1;
    };

    struct Ump64
    {
        UInt32 Word1;
        UInt32 Word2;
    };

    struct Ump96
    {
        UInt32 Word1;
        UInt32 Word2;
        UInt32 Word3;
    };

    struct Ump128
    {
        UInt32 Word1;
        UInt32 Word2;
        UInt32 Word3;
        UInt32 Word4;
    };


}